### ISSUE TITLE
test_run_kfold_cross_validation_with_list_input fails on Fedora 23

### ISSUE THREAD

**Issue by tdaede** [Netflix/vmaf#1]
<pre>
FAIL: test_run_kfold_cross_validation_with_list_input (cross_validation_test.FeatureCrossValidationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/thomas/sandbox/vmaf/python/test/cross_validation_test.py", line 92, in test_run_kfold_cross_validation_with_list_input
    self.assertAlmostEquals(output['aggr_stats']['SRCC'], 0.90636761259756715, places=4)
AssertionError: 0.90647090523758211 != 0.9063676125975672 within 4 places
</pre>

The value is off just a little too much for places=4. How much variance is expected here?

**Comment by zli-nflx** [comment]
Hi Tdaede, there could be several possibilities: 1) If the numpy/scipy/sklearn are not up-to-date, there could be numeric differences. You can follow the Prerequiste/Troubleshooting section for this. 2) I also found that there could be numeric difference across platforms. I have not tried on Fedora. I could definitely look into a Fedora to see if the result makes sense or not. Is this the only failed test case?

**Comment by haiqianw** [comment]
Hi Zhi,

I am Haiqiang Wang from USC. Currently I work with Ioannis on the project.

I pulled it from Git yesterday. All the prerequisite (numpy, scipy,
sklearn) were installed with correct version, but I encountered the same
FAIL as Thomas, it is the only failure that happened. My platform is Mac
pro El Capitan 10.11.

Best,
Haiqiang

**Comment by tdaede** [comment]
I realized that Fedora 23's versions of all the packages were out of date from those listed. I made a virtualenv and installed the versions listed, but still got the exact same result.

Maybe it's a difference in BLAS implementation or something? I'm using atlas 3.10.2.

**Comment by zli-nflx** [comment]
Hi Haiqiang, just want to make sure you were directly building in Mac OS, not on a Fedora VM, right?

**Comment by haiqianw** [comment]
Yes, directly in Mac OS.

**Comment by zli-nflx** [comment]
@tdaede: I was able to reproduce your issue on Fedora 23 (I noticed the atlas version was atlas-3.10.2-6.fc23.x86_64 when installing numpy). After upgrading numpy/scipy/sklearn/matplotlib/pandas (pip install --upgrade xxx), the issue went away.

@haiqianw: I tried it on El Capitan, but was unable to reproduce it.

I suspect it is still issue of package out of date. When you check the package version, please try to use:

python -c 'import numpy as pkg; print pkg.__version__; print pkg.__file__'
python -c 'import scipy as pkg; print pkg.__version__; print pkg.__file__'
python -c 'import matplotlib as pkg; print pkg.__version__; print pkg.__file__'
python -c 'import pandas as pkg; print pkg.__version__; print pkg.__file__'
python -c 'import sklearn as pkg; print pkg.__version__; print pkg.__file__'

instead of 'pip freeze'. Sometimes they can give you different results.

**Comment by haiqianw** [comment]
When I run
python -c 'import numpy as pkg; print pkg.version; print pkg.file'
it gives:
===============================================
<module 'numpy.version' from '/Users/Haiqiang/anaconda/lib/python2.7/site-packages/numpy/version.pyc'>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'file'
===============================================
If I check the package version following README
===============================================
1.10.4
/Users/Haiqiang/anaconda/lib/python2.7/site-packages/numpy/__init__.pyc
0.17.0
/Users/Haiqiang/anaconda/lib/python2.7/site-packages/scipy/__init__.pyc
1.5.1
/Users/Haiqiang/anaconda/lib/python2.7/site-packages/matplotlib/__init__.pyc
0.18.0
/Users/Haiqiang/anaconda/lib/python2.7/site-packages/pandas/__init__.pyc
0.17.1
/Users/Haiqiang/anaconda/lib/python2.7/site-packages/sklearn/__init__.pyc
===============================================
The only difference with README is about pandas, which required >=0.17.1

**Comment by zli-nflx** [comment]
@haiqianw: from your output, I realize that you are using the anaconda installation. It's an known issue to me that some test cases will fail under anaconda (it seems to be an artifact with their bake). I would recommend not to use anaconda but simply use pip.

**Comment by tdaede** [comment]
In a Fedora 23 VM with blas and lapack but no atlas, all unit tests pass. So it seems like this is due to one of the dependencies using atlas instead. I'll walk through each one and see if I can find the offending package.

**Comment by zli-nflx** [comment]
Thanks! Let me know if you find anything and I'll put some notes in the troubleshoot section.
