### ISSUE TITLE
About the Video Database

### ISSUE THREAD

**Issue by xbfhuawei** [Netflix/vmaf#10]
Hi Li，
    I want to kown how to get the Video Database. Can I download the Video Database through Network？ Thx

**Comment by xbfhuawei** [comment]
More ,We found that the complexity of algorithm is very high so that it hardly can me used in our transcoding project. We fount that VMAF, together with other metrics, have been integrated into your encoding pipeline to improve on our automated QC.How it be?

**Comment by zli-nflx** [comment]
Please note that the C code hasn't been performance-optimized. Any contribution on the code optimization (e.g. threading, SIMD) will be welcome.
