### ISSUE TITLE
Chroma values are not included in VMAF calculation?

### ISSUE THREAD

**Issue by shhhhh79** [Netflix/vmaf#100]
I prepared a reference image and a modified image which has the same luma as the reference but very distorted chroma.
These two give exactly the same results when I run VMAF.
Am I doing something wrong or chroma is excluded for VMAF calculation?

Thank you.

**Comment by li-zhi** [comment]
Indeed, current VMAF version is based on luma component only. We are
considering extending to chroma in future versions.

**Comment by shhhhh79** [comment]
Thank you for the answer!

I have a question.
If I run VMAF for chroma values as if they were luma, then the calculated VMAF will be still valid?
I guess not because luma and chroma have different characteristics and VMAF is somehow trained for luma..

**Comment by li-zhi** [comment]
I would guess that the prediction is order-accurate, but not its absolute value.
