### ISSUE TITLE
No NEG model for 4K?

### ISSUE THREAD

**Issue by wabiloo** [Netflix/vmaf#1001]
Is there any particular reason why there is not NEG version of the 4K model?
I cannot find any information about it in the usual places

**Comment by nilfm** [comment]
Hi, sorry I missed this question. The model you are referring to was uploaded in December 2022 [here](https://github.com/Netflix/vmaf/blob/master/model/vmaf_4k_v0.6.1neg.json), so indeed it was not present at the time of opening this issue.

**Comment by nilfm** [comment]
Closing this issue but feel free to reopen with further questions.
