### ISSUE TITLE
Why SDR luma range is set between 0.01nit to 300nit?

### ISSUE THREAD

**Issue by codenobug1** [Netflix/vmaf#1015]
Hi, I found the parameter of bt1886 eotf is set to 300 and 0.01. In the recommendation from ITU the white point should be 100nit and the black should be 0.1? If there are some special purposes for setting the luma range of SDR to 0.01nit to 300nit?

**Comment by krasuluk** [comment]
Hi, good question! The parameters in the recommendation were determined based on the characteristics of the (mostly CRT) screens at the time. The parameters that are used here better reflect the capabilities of the currently available SDR displays.

**Comment by codenobug1** [comment]
Thanks for your reply!
