### ISSUE TITLE
CAMBI heatmaps output

### ISSUE THREAD

**Issue by bassemelmeligy** [Netflix/vmaf#1016]
Hi, In the v2.3.1 release note it's mentioned "CAMBI: option to output heatmaps."
I couldn't find the related cli command, any clue what the command might look like?

**Comment by kylophone** [comment]
> Hi, In the v2.3.1 release note it's mentioned "CAMBI: option to output heatmaps." I couldn't find the related cli command, any clue what the command might look like?

`--feature cambi=heatmaps_path=/path/to/heatmaps/`

**Comment by bassemelmeligy** [comment]
Super, thanks alot!
