### ISSUE TITLE
get different scores when change the order of reference video and distorted video?

### ISSUE THREAD

**Issue by jj199603** [Netflix/vmaf#1018]
I use vamf+ffmpeg to test video quality. However, I get different scores for the same videos only after change the order of the reference video and the distorted video. If is reasonable?

**Comment by slhck** [comment]
That is expected. You should only test a distorted video against the reference. Changing the order does not make much sense.

**Comment by jj199603** [comment]
> 

I'm sorry. I mean that the VMAF computation seems to be not symmetric with relation to ref input and distorted input like https://stackoverflow.com/questions/67598772/right-way-to-use-vmaf-with-ffmpeg
For example we can get different vmaf scores using the following two commands:
1-ffmpeg  -i ref.mp4 -i distorted.mp4 -filter xxxxx -model xxxxx
2-ffmpeg  -i distorted.mp4 -i ref.mp4 -filter xxxxx -model xxxxx

**Comment by krasuluk** [comment]
As mentioned above, this behavior is expected. The internal features in VMAF are not symmetrical, as they don't purely calculate the difference between two videos but also factor in other aspects such as possible enhancement etc.
