### ISSUE TITLE
Is there any connection between NFLX_dataset_public.py & NFLX_dataset_public_raw.py?

### ISSUE THREAD

**Issue by gitgjogh** [Netflix/vmaf#102]
Hi zhi,

Is there any connection between `NFLX_dataset_public.py` & `NFLX_dataset_public_raw.py under` `resource/dataset`?

Is `NFLX_dataset_public.py` derived from `NFLX_dataset_public_raw.py`? If yes, which function or module can do these?

**Comment by li-zhi** [comment]
Yes, NFLX_dataset_public is derived from NFLX_dataset_public_raw. The former has the DMOS scores for each distorted video, while the latter has the per-subject, raw opinion scores. mos.subjective_model.SubjectiveModel.to_aggregated_dataset_file can do the conversion. You can search the function name to_aggregated_dataset_file in the repo to find sample usages.

**Comment by gitgjogh** [comment]
Hi Zhi,
Thanks for you quick reply. I took a look at the codes and found some sample usages inside `subjective_model_test.py`. Now my question is how to reporduce `NFLX_dataset_public.py`?

I tried to reproduce `NFLX_dataset_public_raw.py` like this:
>        subjective_model = DmosModel.from_dataset_file("NFLX_dataset_public_raw.py")
>        result = subjective_model.run_modeling(normalize_final=True, transform_final={'p1':25.46, 'p0':73.41769})
>        subjective_model.to_aggregated_dataset_file("NFLX_dataset_public.py")
The result is not so closed. 

As I'm trying to apply `VMAF` on mobile videos. We may collect DMOS datas from mobile device in the future. So I am curious about how to aggregate the raw data.

**Comment by li-zhi** [comment]
Use the following:
```
subjective_model = DmosModel.from_dataset_file("NFLX_dataset_public_raw.py")
result = subjective_model.run_modeling(normalize_final=False, transform_final={'p1': 20.0, 'p0': 0.0})
subjective_model.to_aggregated_dataset_file("NFLX_dataset_public.py")
```
Here normalize_final means applying a z-scoring to the output; transform_final follows normalize_final, and it applies a polynomial transform (in this case, f(x) = 20 * x + 0).

The NFLX_dataset_public.py generated is equivalent, but the order of entries are different.

**Comment by gitgjogh** [comment]
Got it! Thanks very much.

**Comment by ciwei123** [comment]
@li-zhi @gitgjogh I use the code 
"
subjective_model = DmosModel.from_dataset_file("NFLX_dataset_public_raw.py")
result = subjective_model.run_modeling(normalize_final=False, transform_final={'p1': 20.0, 'p0': 0.0})
subjective_model.to_aggregated_dataset_file("NFLX_dataset_public.py")
"
but I get the NFLX_dataset_public.py which is not closed to the provided in resource/dataset/NFLX_dataset_public.py.Could you share me the convertion script? Thank you very much!!

**Comment by li-zhi** [comment]
I could not remember how it was created. If you plot the scatter between NFLX_dataset_public and the result you obtained, what do you get? Does it fall onto a straight line?
