### ISSUE TITLE
local explain of vmaf

### ISSUE THREAD

**Issue by Lelouch422** [Netflix/vmaf#1025]
hi @li-zhi , Does local explain can be accessed in the latest vmaf version?

**Comment by li-zhi** [comment]
@Lelouch422 yes, it is available through the VMAF Python library. Here is one example of how to use it: https://github.com/Netflix/vmaf/blob/master/python/test/local_explainer_test.py#L243

**Comment by Lelouch422** [comment]
Thanks a lot!
