### ISSUE TITLE
VMAF comparisons at very low quality range

### ISSUE THREAD

**Issue by nandakd** [Netflix/vmaf#103]
Hello,

Here are some results that VMAF produces (at the very low bitrate, low quality range) that we're trying to understand. 
Here's what we did:
a) Take high quality 1080p source, downsample to 400x224, encode at low bitrate, decode and upsample to 1080p and compare with 1080p source (1080p comparison) - VMAF 13.135
b) Downsample high quality 1080p source to 400x224, encode at low bitrate, decode and compare to 400x224 source (224p comparison) - VMAF 54.12

Intuitively, we know a) will be lower than b) because viewing the 224p encoded clip on a 224p screen will look much better than viewing it on a 1080p screen. However if you look at a) results, there are many frames with vmaf =0 (even though elementary metrics are reasonable and closely remember neighboring frames). Do you know why? 

Attached are the two files. There are no process errors, we tested this at multiple resolutions, and VMAF results are acceptable when the encode resolutions and VMAF-test resolutions are closer together (such as 720p and 1080p). 

[VMAF-400x224.txt](https://github.com/Netflix/vmaf/files/1217133/VMAF-400x224.txt)
[VMAF-1080p.txt](https://github.com/Netflix/vmaf/files/1217134/VMAF-1080p.txt)

**Comment by li-zhi** [comment]
@nandakd For the difference between VMAF results at 400x224 vs 1080p, refer to the first question on the FAQ page. As regarding why there are many zeros, by default VMAF scores impose a hard clip on [0, 100]. You can optionally turn that clip off if you run wrapper/vmafossexec (the model file to use should be model/vmaf_v0.6.1.pkl).

**Comment by nandakd** [comment]
Thanks - I've referred to both Issue #74 and the FAQ.  According to our discussion around Issue #74, what was done in a) above was the right thing to do, since the current VMAF model was trained using all 1080p comparisons. 
My question was - what is the real meaning of frame VMAF scores tending to zero (clipped or not clipped)? The frames I mentioned are not very different from neighbouring frames visually, and the elementary metrics are also similar. This is a reasonable test-case, since Netflix's own public datasets contain 1080p content downsampled to 224p (and then upsampled to 1080p). Are these VMAF measurements valid at all?

**Comment by nandakd** [comment]
Hi, any updates on this issue?

**Comment by li-zhi** [comment]
@nandakd: if I understand your question correctly, you are asking the interpretation of zero/near-zero VMAF scores for some video frames, which looks similar to their neighboring frames that have higher scores. I have two questions:
1) are these frames static? and are the neighboring frames high-motion? The temporal information is a factor that will affect the VMAF score calculated, but may not easily observed on single frames.
2) Is it possible to share these videos to develop some visual intuition, so that if it is a bug, we can improve upon it.

**Comment by nandakd** [comment]
Zhi,
Sorry for the confusion - resolving this issue. I realised the aspect ratios had been messed up during the downscaling/upscaling process. Even though all the resolutions were messed up, only the very small ones (224p) were giving obviously corrupted scores, such as zero VMAF, with the 720p and 1080p videos giving fairly plausible, but still incorrect scores. Thanks!
