### ISSUE TITLE
VMAF on Android devices

### ISSUE THREAD

**Issue by AdrianPdevel** [Netflix/vmaf#1031]
I have been trying VMAF and it's working great so far, thanks for this tool!
I was wondering whether VMAF can be ported to android phones somehow.
I tried [FFmpeg Media Encoder](https://play.google.com/store/apps/details?id=com.silentlexx.ffmpeggui), [FFmpeg](https://play.google.com/store/apps/details?id=com.crossplat.ffmpegmobile), [mobile-ffmpeg](https://github.com/tanersener/mobile-ffmpeg) but none of them supports VMAF.
Is there a technical reason for this (e.g., only working on x86 systems) or simply nobody decided to actively work on this so far?
If possible, what would it take to port VMAF to Android?
Could it run in real time, analyzing the screen of a modern phone (e.g., Samsung S22), or would the computation be too heavy?

**Comment by nilfm** [comment]
Closing this thread as part of a clean-up.
