### ISSUE TITLE
ffmpeg command doesn't print SSIM score

### ISSUE THREAD

**Issue by arianaa30** [Netflix/vmaf#1037]
I'm trying to use this command to compute VMAF as well as SSIM. But it prints only VMAF score, but not SSIM score. Why is that?

`.\ffmpeg.exe -i .\myvideo.mp4 -i .\original.mp4 -lavfi "libvmaf=model_path=model/vmaf_v0.6.1.json:phone_model=0:n_subsample=10:log_path=111.json:n_threads=8:ssim=1" -f null -`
...
`[libvmaf @ 000001efd3deee40] VMAF score: 89.999172`

How can I print SSIM score along with VMAF score here? (I want it print in the console)

**Comment by li-zhi** [comment]
Try look into the 111.json file. It should have SSIM.

**Comment by arianaa30** [comment]
The json has it, but I want it printed out.

- Sent from my phone. Pls excuse typos & brevity.

**Comment by arianaa30** [comment]
And why the vmaf score in the json (mean value) is different from the one
printed out?

**Comment by li-zhi** [comment]
You can do:
.\ffmpeg.exe -i .\myvideo.mp4 -i .\original.mp4 -lavfi "libvmaf=model_path=model/vmaf_v0.6.1.json:phone_model=0:n_subsample=10:log_path=/dev/stdout:n_threads=8:ssim=1" -f null -

What is the score difference? mind provide instruction to reproduce the issue?

**Comment by li-zhi** [comment]
Very interesting. Could you share the media files and the cmd you used so
that we could reproduce the issue?

**Comment by arianaa30** [comment]
```
.\ffmpeg.exe -i .\android1.mp4 -i .\android2.mp4 -map 0:v -map 1:v -lavfi "[0:v][1:v]libvmaf=log_fmt=json:model_path=model/vmaf_v0.6.1.json:phone_model=0:n_subsample=10:log_path=25.json:n_threads=8:ssim=1:psnr=1" -f null -
```
For any 2 videos I used, I was witnessing it. So not specific to any videos.

**Comment by slhck** [comment]
The console only ever prints the final VMAF score, nothing else.

If you want to see the full log, write it to a file, with the `log_path=/path/to/file.json` option. If you read out that log, and have `ssim=1`, it should contain SSIM scores for every frame.

> And this is what I see in JSON

The JSON file should have many more entries than what you have shown. Can you show the full JSON file?

**Comment by 1480c1** [comment]
> could not open file: /dev/stdout
> libvmaf ERROR could not write output: /dev/stdout

As a note, if you wanted to replicate the original command, but on Windows, you can replace `/dev/stdout` with `con` as
```ps
.\ffmpeg.exe -i 'D:\1.mp4' -i 'D:\2.mp4' -lavfi "libvmaf=log_path=con:n_threads=8:ssim=1" -f null -
```

and that will print out to your console, just not to stdout, so you cannot capture it using `>` if you wanted to

**Comment by arianaa30** [comment]
Printing is fine to a file for now. But one question I had was, why the avg VMAF score printed is different from the JSON value in the file!!

**Comment by nilfm** [comment]
Closing for now, please feel free to reopen with more details to reproduce
