### ISSUE TITLE
Short mathamatical pseudo-code for VMAF prediction

### ISSUE THREAD

**Issue by kedartatwawadi** [Netflix/vmaf#1047]
Thanks for the great tool. I was trying to understand and re-create VMAF score prediction in a standalone environment.
To that effect, I wanted to know if it would be possible to provide a short description/pseudocode of the VMAF score computation from the atomic features)

I am aware that the core algorithm is a nu-SVR based implementation, but there seem to be some transformations/normalization etc. It would be great to know what exactly we are doing, and how they relate to the parameters in the [model/vmaf_v0.6.1](https://github.com/Netflix/vmaf/blob/21886c045a09105f0a8abd7711a98a946826928a/model/vmaf_v0.6.1.json) file for example.

Thanks!

**Comment by venomone** [comment]
@kedartatwawadi 

ffmpeg -i "/tmp/VODProcessing/original.mp4" -ss 00:00:00 -to 00:00:20 -c:v libx264 -crf 0 -c:a copy "/tmp/VODProcessing/reference.mp4" -y
ffmpeg -i "/tmp/VODProcessing/reference.mp4" -ss 00:00:00 -to 00:00:20 -c:v libx264 -crf 36 -c:a copy "/tmp/VODProcessing/distorted.mp4" -y

do comparison

ffmpeg -i /tmp/VODProcessing/distorted.mp4 -i /tmp/VODProcessing/reference.mp4 -lavfi "[0:v]scale=3840:2160:flags=bicubic[distorted];[1:v]scale=3840:2160:flags=bicubic[reference];[distorted][reference]libvmaf=model=path=/strics/Strics/vmaf_models/vmaf_4k_v0.6.1.json" -f null -

Now rerun the cmd for the reference material with a diffrent crf, lets say 30 (this might take some time):

ffmpeg -i "/tmp/VODProcessing/reference.m4v" -ss 00:00:00 -to 00:00:20 -c:v libx264 -crf 30 -c:a copy "/tmp/VODProcessing/distorted.mp4" -y

rerun the comparison again (same command as the first):

ffmpeg -i /tmp/VODProcessing/distorted.mp4 -i /tmp/VODProcessing/reference.mp4 -lavfi "[0:v]scale=3840:2160:flags=bicubic[distorted];[1:v]scale=3840:2160:flags=bicubic[reference];[distorted][reference]libvmaf=model=path=/strics/Strics/vmaf_models/vmaf_4k_v0.6.1.json" -f null -

doing this for a various crf ranges, you will end up with something like this:

vmaf scorings (target 99.75 (+/- 0.05) ):

mode / reference crf / distorted crf
crf 0/36 = 95.454410
crf 0/34 = 96.357551
crf 0/32 = 97.156582
crf 0/30 = 97.676059
crf 0/28 = 98.287124
crf 0/26 = 98.670041
crf 0/24 = 99.084506
crf 0/22 = 99.392410
crf 0/20 = 99.640319
crf 0/19 = 99.743600
crf 0/18 = 99.840459 


So crf value of 19 seems the optimal way to go if your target is 99.75% of the original visible quality.

Hope that helped
