### ISSUE TITLE
Dimension requirement to calculate ms_ssim

### ISSUE THREAD

**Issue by JohnhqWang** [Netflix/vmaf#105]
I tried to run VMAF on cropped video segments with dimension 128x72, which is 1/5 of 640x360. It seems that ms_ssim has specific requirement on the picture size.

`Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yj/vmaf/python/src/vmaf/tools/misc.py", line 262, in func_wrapper
    executor = func(args)
  File "/home/yj/vmaf/python/src/vmaf/core/executor.py", line 119, in _run
    result = self._run_on_asset(asset)
  File "/home/yj/vmaf/python/src/vmaf/core/executor.py", line 291, in _run_on_asset
    self._generate_result(asset)
  File "/home/yj/vmaf/python/src/vmaf/core/quality_runner.py", line 468, in _generate_result
    run_process(vmafossexec_cmd, shell=True)
  File "/home/yj/vmaf/python/src/vmaf/tools/misc.py", line 378, in run_process
    assert ret == 0, 'Process returned {ret}, cmd: {cmd}'.format(ret=ret, cmd=cmd)
AssertionError: Process returned 255, cmd: /home/yj/vmaf/wrapper/vmafossexec yuv420p 128 72 /home/yj/haiqiang/YUV/640x360/videoSRC001_640x360_30/videoSRC001_640x360_30_qp_00/videoSRC001_128x72_30_qp_00_crop_785.yuv /home/yj/haiqiang/YUV/640x360/videoSRC001_640x360_30/videoSRC001_640x360_30_qp_08/videoSRC001_128x72_30_qp_08_crop_785.yuv 
/home/yj/vmaf/model/vmaf_v0.6.1.pkl --log /home/yj/vmaf/workspace/workdir/bc7b20b3-2209-45ad-9eb9-06f87f03a7e8/VMAFOSSEXEC_VF0.2.4b-0.6.1_1cd71b5996385fc000c8e2b5abc0decabecfeed2 --log-fmt xml --psnr --ssim --ms-ssim
Error: compute_ms_ssim failed.` 

Is there anyone familiar with it? Is it W or H > 256 or something else?

**Comment by yuhjay** [comment]
VMAF is based on collected subjective scores. If image size is too small, the final score could be biased. MSSIM is based on on psychological models, so the requirement is reasonable.

從我的 iPhone 傳送

**Comment by JohnhqWang** [comment]
Hi Joe @yuhjay, thanks for the explanation. The purpose here is to evaluate local quality of spatial-temporal segments and fuse local scores afterwards.
