### ISSUE TITLE
How to use VMAF for non 1080p videos

### ISSUE THREAD

**Issue by sridhard** [Netflix/vmaf#1054]
Hi,

In VMAF docs it is clear how to use VMAF when the reference video is 1080p. 

In our cases the reference videos are not always 1080p. 

Case-1: Reference video is 720p and we transcode to 480p. In this case we are upsampling the distorted video to 720p and then comparing the quality. We are doing this because in ffmpeg command section of vmaf docs, the distorted video is upscaled to 720p. But in VMAF docs it is suggested to upscale both reference and distorted to 1080p. Which is correct here? should be upscale distorted video to 720p or upscale both reference and distorted to 1080p? which one give better results

Case-2: Some cases we have a reference video greater than 1080p like 2k video. In this case we want to transcode the video to 1080p. In this case should we downscale the reference video to 1080p? or what is the correct method?

**Comment by li-zhi** [comment]
Hi,

Case-1: if the reference is 720p, encode is 480p and you upscale the encode to 720p: this is legitimate, with the interpretation that the normalized viewing distance (viewing distance / display height) is 4.5H (I assume you use VMAF v0.6.1 model here). Recall that the v0.6.1 model is a [60 pixel/degree model](https://github.com/Netflix/vmaf/blob/master/resource/doc/faq.md#q-when-computing-vmaf-on-low-resolution-videos-480-pixel-height-for-example-why-the-scores-look-so-high-even-when-there-are-visible-artifacts).

Case-2: if you downscale the reference to 1080p, the score should be interepreted as measured at 3H; if you upscale the encode to 4K, the score should be interpreted as measured at 1.5H.

**Comment by sridhard** [comment]
Thanks for quick reply.

How can we interpret the VMAF scores in these different conditions?

**Comment by sridhard** [comment]
ok. thanks
