### ISSUE TITLE
how to train vamf phone-model?

### ISSUE THREAD

**Issue by NewRegin** [Netflix/vmaf#106]
As we know, Netflix use the Double Stimulus Impairment Scale (DSIS) method(as specified in recommendation ITU-R BT.500–13) in standardized subjective testing on the TV model.
So question 1:
on the phone model, what's the method, DSIS or other? 
Question 2:
What is the difference between the experimental environment and before? 
Question 3:
Do you use a variety of mobile phone brands in the phone-experiments, for example, iphone, samsung and etc?

**Comment by li-zhi** [comment]
@NewRegin:
1. The model was ACR when phone mobile was trained. In fact, we tried both DSIS and ACR in the past, and the resulting model were quite consistent with each other.
2.3. The subjective test was conducted in a way that subjects views video on a Samsung S5, with a viewing distance natural to the viewers. The experiment was conducted in a lab environment, with set up according to ITU-R BT.500.

**Comment by NewRegin** [comment]
thanks @li-zhi

**Comment by liuxj901103** [comment]
Hi, I have the same confusion.Have you got the anwser?
