### ISSUE TITLE
Cannot enable ssim or ms_ssim feature through ffmpeg

### ISSUE THREAD

**Issue by slhck** [Netflix/vmaf#1075]
I'm not sure if that's by-design, but I can enable all features through the ffmpeg filter except for `ssim` and `ms_ssim`.

This is using FFmpeg 5.1 under macOS with the Homebrew version that bundles libvmaf 2.3.1.

```
ffmpeg -nostdin -nostats -y -threads 0 -r 25.0 -i test/ref-1280x720.mkv -r 25.0 -i test/dist-854x480.mkv -filter_complex '[1][0]scale2ref=flags=bicubic[dist][ref];[dist]settb=1/AVTB,setpts=PTS-STARTPTS[distpts];[ref]settb=1/AVTB,setpts=PTS-STARTPTS[refpts];[distpts][refpts]libvmaf='"'"'model=path=/opt/homebrew/opt/libvmaf/share/libvmaf/model/vmaf_v0.6.1.json\:enable_transform=true\:enable_conf_interval=true:log_path=/var/folders/3h/9h8lqbnx0p372m8qh7fpd1dh0000gn/T/v1bstr5c-vmaf.txt:log_fmt=json:n_threads=0:n_subsample=1:feature=name=ms_ssim'"'"'' -an -f null /dev/null
```

Fails with:

> [Parsed_libvmaf_5 @ 0x14af06180] problem during vmaf_use_feature: ms_ssim

Same for `ssim`:

```
ffmpeg -nostdin -nostats -y -threads 0 -r 25.0 -i test/ref-1280x720.mkv -r 25.0 -i test/dist-854x480.mkv -filter_complex '[1][0]scale2ref=flags=bicubic[dist][ref];[dist]settb=1/AVTB,setpts=PTS-STARTPTS[distpts];[ref]settb=1/AVTB,setpts=PTS-STARTPTS[refpts];[distpts][refpts]libvmaf='"'"'model=path=/opt/homebrew/opt/libvmaf/share/libvmaf/model/vmaf_v0.6.1.json\:enable_transform=true\:enable_conf_interval=true:log_path=/var/folders/3h/9h8lqbnx0p372m8qh7fpd1dh0000gn/T/g6aqqbz4-vmaf.txt:log_fmt=json:n_threads=0:n_subsample=1:feature=name=ssim'"'"'' -an -f null /dev/null
```

Fails with:

> [Parsed_libvmaf_5 @ 0x13d605020] problem during vmaf_use_feature: ssim

The "problem during" statement is not very informative.

I *can* run all other features, e.g. `ciede`, `cambi`, `psnr`, `psnr_hvs`, …

**Comment by kylophone** [comment]
The ffmpeg filter documentation is wrong, I will send a patch to fix. These feature extractors are actually called `float_ms_ssim` and `float_ssim`.

**Comment by slhck** [comment]
`float_ssim` and `float_ms_ssim` works, thanks!

I have some other suggestions for the docs there, but I'll provide a separate patch to `ffmpeg-devel` then.

**Comment by clemg** [comment]
Where is the patch fix? On my side, the docs [still have the wrong name](https://ffmpeg.org/ffmpeg-all.html#libvmaf)

**Comment by clemg** [comment]
if not, maybe I can send a patch?
