### ISSUE TITLE
VMAF 2.3.0 : the score output by the terminal is inconsistent with the score in the output file

### ISSUE THREAD

**Issue by Rolyyu** [Netflix/vmaf#1084]
When the parameter contains --subsample, the vmaf score output by the terminal is inconsistent with the score in the output file

❯ ./vmaf \
    --reference ref.yuv \
    --distorted dis.yuv \
    --width 1920 --height 1080 --pixel_format 420 --bitdepth 8 \
    --model version=vmaf_v0.6.1 \
    --threads 4 \
    --subsample 10 \
    --json --output output.json
VMAF version 5c1c9bfa
75 frames ⠉⠙ 34.85 FPS
vmaf_v0.6.1: 94.423696

These data are extracted from the attached file. If you calculate the mean of each frame score, it is consistent with the terminal output. **However, the vmaf mean in the output file is abnormal.**

>         "vmaf": 79.544828
>         "vmaf": 100.000000
>         "vmaf": 99.517673
>         "vmaf": 100.000000
>         "vmaf": 91.859050
>         "vmaf": 95.592886
>         "vmaf": 91.290891
>         "vmaf": 97.584242
>
>     "vmaf": {
>       "min": 79.544828,
>       "max": 79.544828,
>       "mean": 79.544828,
>       "harmonic_mean": 79.544828
>     }

[output.txt](https://github.com/Netflix/vmaf/files/9372190/output.txt)

**Comment by nilfm** [comment]
Thanks @Rolyyu for bringing this issue to our attention, it was a bug in the way parameters were passed to the output_json and output_xml functions when subsampling was present. This was fixed by #1135 so I'm closing it, feel free to reopen if there are more problems.
