### ISSUE TITLE
Windows Build - no built in models and documentation inconsitencies

### ISSUE THREAD

**Issue by gregor40** [Netflix/vmaf#1085]
I have managed to build VMAF on Windows 11 using Msys.

1) In your documentation here:
https://github.com/Netflix/vmaf/blob/master/resource/doc/windows.md
it would be worth mentioning, that Msys comes with several bashes. In order to successfully compile vmaf "MSYS2 MinGW x86" had to be used in place of "MSYS2 MSYS".

2) In order to use vmaf command line tool from the Windows environment the user has either to modify environment variables to point to mingw ddls' or to copy 
```
libgcc_s_seh-1.dll  
libstdc++-6.dll
libwinpthread-1.dll
```
to the directory with the vmaf.exe 

3) The most pressing issue is that though in meson_options.txt I have the default setting of
```
option('built_in_models',
    type: 'boolean',
    value: true,
    description: 'Compile default vmaf models into the library')
```

the vmaf.exe command line tool seems to compile without the built-in models. It requires -m parameter and when providing the model name with:

```
>vmaf -r input.y4m -d input.y4m -o vmaf.json --json --threads 24 --model version=vmaf_v0.6.1
VMAF version 2.3.1
←[35mlibvmaf←[0m ←[33mWARNING←[0m no such built-in model: "vmaf_v0.6.1"
←[35mlibvmaf←[0m ←[33mWARNING←[0m no such built-in model collection: "vmaf_v0.6.1"
problem loading model: vmaf_v0.6.1
```

The solution is to provide path to the model json file. 

```
>vmaf -r input.y4m -d out.y4m -o vmaf.json --json --threads 24 --model path="vmaf_v0.6.1.json"
VMAF version 2.3.1
7572 frames ÔáŹÔáü 94.69 FPS←[K
vmaf_v0.6.1.json: 97.206295
```

I don't think that is an expected behavior taking into consideration the documentation provided.

**Comment by kylophone** [comment]
If you don't have `xxd` installed, the models will not be compiled into libvmaf.

https://github.com/Netflix/vmaf/issues/989
