### ISSUE TITLE
Discrepancy in VMAF score

### ISSUE THREAD

**Issue by pgmaheshwaran** [Netflix/vmaf#1089]
Noticed the VMAF score difference based on the reference file Bit rate mode (variable / constant ).

Same distorted file processed using the reference file with variable bitrate, resulted in VMAF score 
VMAF score = ~**89.87194**
ffmpeg -i https://d3amo7ft92zgpl.cloudfront.net/referrence-video/1_1080p.mp4 -i https://d3amo7ft92zgpl.cloudfront.net/inital-profile-output/1_1080highp.mp4 -filter_complex libvmaf -f null - 
VMAF score = ~**89.66711**
ffmpeg -i https://d3amo7ft92zgpl.cloudfront.net/referrence-video/1_1080p.mp4 -i https://d3amo7ft92zgpl.cloudfront.net/Bitmovin-output/Zee-Static-Renditions-Black_Widows_1080p_6500000.mp4 -filter_complex libvmaf -f null - 

Same distorted file processed using the reference file with constant bitrate, 
VMAF score = ~**92.12123**
ffmpeg -i https://d3amo7ft92zgpl.cloudfront.net/referrence_ffmpeg/1080p.mp4 -i https://d3amo7ft92zgpl.cloudfront.net/inital-profile-output/1_1080highp.mp4 -filter_complex libvmaf -f null - 
VMAF score = ~**92.9191**
ffmpeg -i https://d3amo7ft92zgpl.cloudfront.net/referrence_ffmpeg/1080p.mp4 -i https://d3amo7ft92zgpl.cloudfront.net/Bitmovin-output/Zee-Static-Renditions-Black_Widows_1080p_6500000.mp4 -filter_complex libvmaf -f null - 

In case I see the actual source and with bicubic upscaling to know the VMAF score; it return different VMAF score
VMAF score = ~**85.3292**
ffmpeg -r 24 -i  https://d3amo7ft92zgpl.cloudfront.net/zee-vq-source.mp4 -r 24 -i  https://d3amo7ft92zgpl.cloudfront.net/inital-profile-output/1_1080highp.mp4 -lavfi "[0:v]setpts=PTS-STARTPTS[reference];[1:v]scale=3840:2160:flags=bicubic,setpts=PTS-STARTPTS[distorted]; [distorted][reference]libvmaf=log_fmt=xml:log_path=/dev/stdout:model_path=/home/ubuntu/ffmpeg_sources/vmaf-2.3.1/model/vmaf_v0.6.1.json:n_threads=4" -f null -

VMAF score = ~**84.872585**
ffmpeg -r 24 -i  https://d3amo7ft92zgpl.cloudfront.net/zee-vq-source.mp4 -r 24 -i  https://d3amo7ft92zgpl.cloudfront.net/Bitmovin-output/Zee-Static-Renditions-Black_Widows_1080p_6500000.mp4 -lavfi "[0:v]setpts=PTS-STARTPTS[reference];[1:v]scale=3840:2160:flags=bicubic,setpts=PTS-STARTPTS[distorted]; [distorted][reference]libvmaf=log_fmt=xml:log_path=/dev/stdout:model_path=/home/ubuntu/ffmpeg_sources/vmaf-2.3.1/model/vmaf_v0.6.1.json:n_threads=4" -f null -

Question?.
1. Why do we find the difference in this case?. Same set of distorted file  with multiple reference we see contrast results. (please check the above details)
2. What is the most ideal way to create reference file , say I have my distorted file processed using QVBR - should we need to process the reference with QVBR or Constant Rate mode or it shouldn't matter ?. Please advise.

Using VMAF version : v2.1.1

Regards,
Maheshwaran.G

**Comment by nilfm** [comment]
Hi, sorry for the delayed response. I'm not sure I understand the question. It seems like you have 3 reference files:
* `https://d3amo7ft92zgpl.cloudfront.net/referrence-video/1_1080p.mp4`
* `https://d3amo7ft92zgpl.cloudfront.net/referrence_ffmpeg/1080p.mp4`
* `https://d3amo7ft92zgpl.cloudfront.net/zee-vq-source.mp4`

and two distorted files:
* `https://d3amo7ft92zgpl.cloudfront.net/inital-profile-output/1_1080highp.mp4`
* `https://d3amo7ft92zgpl.cloudfront.net/Bitmovin-output/Zee-Static-Renditions-Black_Widows_1080p_6500000.mp4 `

and you have run VMAF on all 6 combinations of reference/distorted inputs. Now on to your questions,

1. Is there a reason why you would expect the scores to stay the same when using different sets of inputs? VMAF is a full-reference metric, meaning it takes into account both the reference and distorted video. If you change one of them, the score is (most likely) going to change.
2. Usually, the reference file would be unprocessed, or minimally processed. The reference should be as close to a "perfect" version of the video as possible. Typically, you would start with a reference, encode or process it to obtain a distorted version, and then use VMAF to compare the two.

Does this answer your questions?
