### ISSUE TITLE
CAMBI--python demo

### ISSUE THREAD

**Issue by DAVID-Hown** [Netflix/vmaf#1090]
Hi, I am going to use CAMBI to do some tests, for now I am using the following command 

libvmaf/build/tools/vmaf \
--reference src01_hrc01_576x324.yuv \
--distorted src01_hrc01_576x324.yuv \
--width 576 --height 324 --pixel_format 420 --bitdepth 8 \
--no_prediction --feature cambi --output /dev/stdout,

When I read this document, I also found a Python script. Do you have a Python interface? I tried to organize the Python code to write a test demo, but I found that the script cambi_test.py was an automated test script, so it was difficult for me to organize it. To ask where Cambi actually extracts features in a Python script, I couldn't tune in to get the feature extraction information I wanted including the prediction information

**Comment by nilfm** [comment]
Thanks for reporting this, I believe you are looking for something similar to [run_vmaf.py](https://github.com/Netflix/vmaf/blob/master/python/vmaf/script/run_vmaf.py) or [run_psnr.py](https://github.com/Netflix/vmaf/blob/master/python/vmaf/script/run_psnr.py) for CAMBI, is that correct? I think this would be a welcome addition. @christosbampis any thoughts about this? I could put together a script to make it easier to use CAMBI through python.

**Comment by li-zhi** [comment]
The run_vmaf and run_psnr scripts are a bit outdated and need to be
modernized. The libvmaf/build/tools/vmaf is the first choice. If you want
to stick to Python code, use the class `CambiQualityRunner`. I also have a
convenience library called vmaf-notebook with some examples of how to call
these classes: https://github.com/li-zhi/vmaf-notebook
