### ISSUE TITLE
Calculate VMAF score while encoding a video with FFmpeg

### ISSUE THREAD

**Issue by arianaa30** [Netflix/vmaf#1091]
I have an `ffmpeg` version built with VMAF library. I can use it to calculate the VMAF scores of a distorted video against a reference video using commands like this:

    `ffmpeg -i distorted.mp4 -i original.mp4 -filter_complex "[0:v]scale=640:480:flags=bicubic[main];[main][1:v]libvmaf=model_path=model/vmaf_v0.6.1.json:log_path=log.json" -f null -`

Now, I remember there was a way to get VMAF scores while performing regular ffmpeg encoding. How can I do that at the same time? 

I want to encode a video like this, while also calulate the VMAF of the output file:

    `ffmpeg -i original.mp4 -crf 27 -s 640x480 out.mp4`

**Comment by slhck** [comment]
Take the first command and append your encoding options to generate an output file. Use `-map "1:v"` to only encode the original input (i.e., input with index 1):

```bash
ffmpeg \
  -i distorted.mp4 \
  -i original \
  -filter_complex "
    [0:v]scale=640:480:flags=bicubic[main];
    [main][1:v]libvmaf=model_path=model/vmaf_v0.6.1.json:log_path=log.json
  " \
  -map "1:v" \
  -crf 27 \
  -s 640x480 \
  out.mp4
```

**Comment by arianaa30** [comment]
Thanks. OK then I should just run two sets of commands...twice latency.

**Comment by slhck** [comment]
See here for an example of what I meant with piping frames: https://stackoverflow.com/a/45730491/435093

This also uses a FR metric (PSNR), so it may work for VMAF.
