### ISSUE TITLE
Required meson version is higher then indicated

### ISSUE THREAD

**Issue by ChristianFeldmann** [Netflix/vmaf#1092]
In the docs it is indicated that meson 0.47 is ok to build where in fact 0.56 is required:

```
test/meson.build:41: WARNING: Project targets '>= 0.47.0' but uses feature introduced in '0.56.0': meson.project_source_root.
```

The change was introduced here https://github.com/Netflix/vmaf/pull/1072 by @gizahNL

**Comment by eli-schwartz** [comment]
If it's desirable to continue supporting very old versions of Meson, then `meson.source_root()` can be used. It's a bad, deprecated name that functions identically, but it is not deprecated until 0.56.0, since that's the first version that has a replacement.

**Comment by ChristianFeldmann** [comment]
There is probably some if way to support old and new versions here. But the current master branch needs 0.56 to compile.

**Comment by gizahNL** [comment]
> If it's desirable to continue supporting very old versions of Meson, then `meson.source_root()` can be used. It's a bad, deprecated name that functions identically, but it is not deprecated until 0.56.0, since that's the first version that has a replacement.

iirc meson.source_root() actually will point to the root of the top project, and would still break if libvmaf was used as a meson subproject. Usage in this case is only relevant to tests though, so would imho be less relevant to sub projects.

**Comment by eli-schwartz** [comment]
... that would be my late at night brain at work. :(

For the subproject source root, a common tactic for backwards compat is to save meson.current_source_dir() to a variable in the top-level meson.build file.

**Comment by kylophone** [comment]
I think it's OK to bump the minimum required meson version. `>= 0.56.1` would probably work.

**Comment by kylophone** [comment]
#1094 is merged, closing this.

**Comment by ChristianFeldmann** [comment]
@kylophone added a PR for the docs.
