### ISSUE TITLE
Bug in FFmpeg integration for 10 bit VMAF

### ISSUE THREAD

**Issue by ChristianFeldmann** [Netflix/vmaf#1093]
I was debugging some VMAF calculation in ffmpeg when I stumbled on this bug in the latest master commit (9450f759748d02d1d284d2e4afd741cb0fe0c04a). Its in libavfilter/vf_libvmaf.c::109. The function copy_picture_data does only work correctly for 8 bit input. For 10 bit input, only half of the width of the input picture is copied. But for 10 bit inputs, 2 bytes per pixel must be copied. Git blame tells me this was written by @kylophone . Please see this patch:

```
diff --git a/libavfilter/vf_libvmaf.c b/libavfilter/vf_libvmaf.c
index eee1c280ef..8d5ba4e2d5 100644
--- a/libavfilter/vf_libvmaf.c
+++ b/libavfilter/vf_libvmaf.c
@@ -108,6 +108,7 @@ static enum VmafPixelFormat pix_fmt_map(enum AVPixelFormat av_pix_fmt)
 
 static int copy_picture_data(AVFrame *src, VmafPicture *dst, unsigned bpc)
 {
+    const int bytes_per_value = bpc > 8 ? 2 : 1;
     int err = vmaf_picture_alloc(dst, pix_fmt_map(src->format), bpc,
                                  src->width, src->height);
     if (err)
@@ -117,7 +118,7 @@ static int copy_picture_data(AVFrame *src, VmafPicture *dst, unsigned bpc)
         uint8_t *src_data = src->data[i];
         uint8_t *dst_data = dst->data[i];
         for (unsigned j = 0; j < dst->h[i]; j++) {
-            memcpy(dst_data, src_data, sizeof(*dst_data) * dst->w[i]);
+            memcpy(dst_data, src_data, bytes_per_value * dst->w[i]);
             src_data += src->linesize[i];
             dst_data += dst->stride[i];
         }
-- 
```

I am not sure if this is the right place to post this since this is not the ffmpeg repo but I guess you also wrote that code and can help to get a fix merged. I also posted this to the ffmpeg mailing list: http://ffmpeg.org/pipermail/ffmpeg-devel/2022-September/301429.html

**Comment by kylophone** [comment]
Thanks, I will reply on the mailing list.
