### ISSUE TITLE
When using vmaf.exe or libvmaf, what are the rules for the writing order of "reference video" and "discarded video"?

### ISSUE THREAD

**Issue by henanzheng** [Netflix/vmaf#1100]
After the order is reversed, the results of wmaf will also be different, so who is the first and who is the last to write correctly? I also read the instructions, but I'm still not sure:
![20220928180013](https://user-images.githubusercontent.com/111262981/192752840-cb8dbf4d-b260-48e2-b0df-870fbf6b9d1e.png)
Thanks for your advice!

**Comment by christosbampis** [comment]
The order for libvmaf is always distorted first and then reference. The order that you use in -i affects whether the alias for the video channel ([0:v] and [1:v]) would correspond to the reference or the distorted.

So you could do either

-i ref.mp4 -i dis.mp4 -lavfi "[0:v]setpts=PTS-STARTPTS[reference][1:v]setpts=PTS-STARTPTS[distorted]" or
-i dis.mp4 -i ref.mp4 -lavfi "[0:v]setpts=PTS-STARTPTS[distorted][1:v]setpts=PTS-STARTPTS[reference]"

As long as you pass the aliases correctly to libvmaf (first reference and second distorted), it should be good.

**Comment by henanzheng** [comment]
Thank you. Helped me solve this long confused problem.
