### ISSUE TITLE
Low VMAF score of the first frame

### ISSUE THREAD

**Issue by yuhjay** [Netflix/vmaf#1105]
When we ran VMAF against test sequences, we found VMAF reports lower score. When we compare two identical videos, the first frames could be less than 100. We verified the executable has the same issue.
The test clips are here: https://drive.google.com/drive/folders/15Tz3GUbHdjHde2zD05_vioJ2hjnUgpzE?usp=sharing
./vmaf-master/libvmaf/build/tools/vmafossexec yuv420p 1080 1920 ./test.y4m ./test.y4m ./vmaf-master/model/vmaf_v0.6.1neg.json --log ./test.json

**Comment by kylophone** [comment]
I had a quick look at your logs, and things look normal. When comparing `./test.y4m` to itself, you should not expect to get exactly 100, see the FAQ which I've linked below. To verify you do not have frame mismatch, run `vmaf` with `--feature psnr=enable_mse=true` and confirm MSE is 0.

https://github.com/Netflix/vmaf/blob/master/resource/doc/faq.md#q-when-i-compare-a-video-with-itself-as-reference-i-expect-to-get-a-perfect-score-of-vmaf-100-but-what-i-see-is-a-score-like-987-is-there-a-bug

**Comment by yuhjay** [comment]
Thanks for the explanation.

**Comment by gsimko** [comment]
I believe there's something wrong about the first frame. It always has lower than expected value (even though the first frames are the same), and with ffmpeg even if I just pass in a single frame (using -frames:v 1) vmaf reports two frames, where the first frame has the low unexpected score.
