### ISSUE TITLE
Evaluate scores "on-demand"

### ISSUE THREAD

**Issue by arnisgustins** [Netflix/vmaf#1106]
Hi.
If I understand correctly, the only way to evaluate vmaf score using C API is by:
1. read in all frames with `vmaf_read_pictures()`
2. finish reading with NULL values and `vmaf_read_pictures()`
3. Access scores with `vmaf_score_at_index()` or `vmaf_score_pooled()`.

This means that I can get the scores only at the end of the process, right?

I have a bit of different use case where I would like to get scores "on-demand" for each frame. After I read the frame, I need to get the score before I send in the next frame. And I don't mind if this way the evaluation might be slower. Also I don't care about the "motion" feature.

What I have tried this far is to use `vmaf_score_at_index()` after reading each frame before flushing the buffers with NULL frame. But VMAF complains that the score doesn't exist at given index when calling it right after reading the frame.

Another way that works is to read frame, flush with NULL, get score. But then I have to re-initialise vmaf context, which is very inefficient to do for each frame. Maybe there exists a better way that I am not aware of? Thanks.

**Comment by kylophone** [comment]
Yes, you can read as you go. Since VMAF has a temporal feature (motion), your read will need a 1-frame delay, once you send frame N, you should be able to calculate the score of frame N-1.

**Comment by arnisgustins** [comment]
Yeah, that works, thanks.
Only one thing to keep in mind is to set the thread count to 1. Otherwise some of the N-1 indexes will still show error.
But that makes sense if you do frame-level parallelisation, there is no point in evaluating 1 frame on more than 1 threads.
