### ISSUE TITLE
notyuv dataset process throws ffmpeg: "moov atom not found" on a seemingly valid file

### ISSUE THREAD

**Issue by rubenamtz-msft** [Netflix/vmaf#1111]
I am trying to retrain on mp4 dis and ref videos. The error is random in some cases it throws the error and in some others it doesn't, the issue can't be entirely replicated. Found this on SO: https://superuser.com/questions/1712123/ffmpeg-moov-atom-not-found-on-a-seemingly-valid-file

Trace:
Process Process-138:1:
Traceback (most recent call last):
  File "/home/azureuser/vmaf/python/vmaf/__init__.py", line 39, in run_process
    subprocess.check_output(cmd, stderr=subprocess.STDOUT, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/anaconda/envs/azureml_py38/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/usr/bin/ffmpeg  -i /home/azureuser/cloudfiles/data/datastore/mlvideoprem/data/CLIC2022/encoded_30fps_1080p_augmented_old/originals_rotate_-10/209921b14cef20d62002e2b0c21ad692226135b52fee7eead315039ca51c470c.mp4 -an -vsync 0 -pix_fmt yuv420p  -vf scale=1920x1080 -f rawvideo -sws_flags bicubic -y -nostdin /home/azureuser/vmaf/workspace/workdir/7f4d3ee5-721c-4603-bb63-4c11226dbd55/ref_clic_test_split_2_final_aug_5_136_209921b14cef20d62002e2b0c21ad692226135b52fee7eead315039ca51c470c_notyuv_vs_209921b14cef20d62002e2b0c21ad692226135b52fee7eead315039ca51c470c_notyuv_q_1920x1080' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/anaconda/envs/azureml_py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/azureuser/vmaf/python/vmaf/core/executor.py", line 524, in _open_ref_workfile
    _open_workfile_method(self, asset, path, workfile_path, yuv_type, workfile_yuv_type, resampling_type, width_height,
  File "/home/azureuser/vmaf/python/vmaf/core/executor.py", line 585, in _open_workfile
    run_process(ffmpeg_cmd, shell=True, env=VmafExternalConfig.ffmpeg_env())
  File "/home/azureuser/vmaf/python/vmaf/__init__.py", line 41, in run_process
    raise AssertionError(f'Process returned {e.returncode}, cmd: {cmd}, msg: {str(e.output)}')
AssertionError: Process returned 1, cmd: /usr/bin/ffmpeg  -i /home/azureuser/cloudfiles/data/datastore/mlvideoprem/data/CLIC2022/encoded_30fps_1080p_augmented_old/originals_rotate_-10/209921b14cef20d62002e2b0c21ad692226135b52fee7eead315039ca51c470c.mp4 -an -vsync 0 -pix_fmt yuv420p  -vf scale=1920x1080 -f rawvideo -sws_flags bicubic -y -nostdin /home/azureuser/vmaf/workspace/workdir/7f4d3ee5-721c-4603-bb63-4c11226dbd55/ref_clic_test_split_2_final_aug_5_136_209921b14cef20d62002e2b0c21ad692226135b52fee7eead315039ca51c470c_notyuv_vs_209921b14cef20d62002e2b0c21ad692226135b52fee7eead315039ca51c470c_notyuv_q_1920x1080, msg: b'ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers\n  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)\n  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 31.100 / 56. 31.100\n  libavcodec     58. 54.100 / 58. 54.100\n  libavformat    58. 29.100 / 58. 29.100\n  libavdevice    58.  8.100 / 58.  8.100\n  libavfilter     7. 57.100 /  7. 57.100\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  5.100 /  5.  5.100\n  libswresample   3.  5.100 /  3.  5.100\n  libpostproc    55.  5.100 / 55.  5.100\n[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55e7142f0700] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!\n[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55e7142f0700] moov atom not found\n/home/azureuser/cloudfiles/data/datastore/mlvideoprem/data/CLIC2022/encoded_30fps_1080p_augmented_old/originals_rotate_-10/209921b14cef20d62002e2b0c21ad692226135b52fee7eead315039ca51c470c.mp4: Invalid data found when processing input\n'

I tried to validate if this was related to parallelization but didn't have enough time to go through all the videos., for the ones I tested it I didn't get an error with parallelize = False.

**Comment by li-zhi** [comment]
I wonder if you just re-run `/usr/bin/ffmpeg -i /home/azureuser/cloudfiles/data/datastore/mlvideoprem/data/CLIC2022/encoded_30fps_1080p_augmented_old/originals_rotate-10/209921b14cef20d62002e2b0c21ad692226135b52fee7eead315039ca51c470c.mp4 -an -vsync 0 -pix_fmt yuv420p -vf scale=1920x1080 -f rawvideo -sws_flags bicubic -y -nostdin /home/azureuser/vmaf/workspace/workdir/7f4d3ee5-721c-4603-bb63-4c11226dbd55/ref_clic_test_split_2_final_aug_5_136_209921b14cef20d62002e2b0c21ad692226135b52fee7eead315039ca51c470c_notyuv_vs_209921b14cef20d62002e2b0c21ad692226135b52fee7eead315039ca51c470c_notyuv_q_1920x1080`, what would happen?

**Comment by rubenamtz-msft** [comment]
I found out there was a frame difference between the two videos, thanks for pointing this out @li-zhi
