### ISSUE TITLE
Is there an effort to cover the graphics effects ?

### ISSUE THREAD

**Issue by pure-water** [Netflix/vmaf#1112]
As the title

**Comment by slhck** [comment]
Could you please clarify what you mean by “cover the graphics effects”? Can you give an example?

(You can always retrain the model using your own dataset, e.g. as [attempted for gaming](https://github.com/Netflix/vmaf/issues/320)).

**Comment by pure-water** [comment]
Yes, that is what I mean since VMAF is intended for video stream .  What about the rendering contents as game etc... In theroy we can train own dataset but indivual is lack of systematic efforts such as netflix's scoring system I assume

**Comment by nilfm** [comment]
At this moment we don't have plans for a gaming-specific VMAF model. I'll be closing this thread to avoid duplicating this conversation but leaving #320 open for discussion of user-generated gaming models.
