### ISSUE TITLE
Frame metric field changes in v2.3.1

### ISSUE THREAD

**Issue by jurisbu** [Netflix/vmaf#1126]
Hi dear VMAF team,

It looks like in version v2.3.1 field names for frame metrics were changed.
```
psnr -> psnr_y
ms_ssim -> float_ms_ssim
ssim -> float_ssim
etc.
```

Do you plan to change these frequently in minor/bugfix versions? Is it possible to somehow do it in non-breaking way? Or maybe there are other suggested ways of how to "ingest" VQ metrics in a forward-compatible manner?

Thanks!

**Comment by kylophone** [comment]
Breakage is not intentional, do you have before/after command lines that you've used to generate this? We have feature name aliases [here](https://github.com/Netflix/vmaf/blob/master/libvmaf/src/feature/alias.c#L101-L118) that should have taken care of this.

**Comment by jurisbu** [comment]
@kylophone  I was not aware of feature name aliases. In any case my `ffmpeg` commandline was:

```
ffmpeg -i compressed.mp4 -i src.mp4 -lavfi libvmaf=n_subsample=1ms_ssim=1:psnr=1:log_fmt=json -f null -
```

The commandline was not modified. What changed for me was the ffmpeg version as provided by https://johnvansickle.com/ffmpeg/. Previous version that I used was ffmpeg v5.0.1 that was build with libvmaf v2.3.0 and now the latest ffmpeg v5.1.1 with libvmaf v2.3.1.

Are you saying that I should be able to change ffmpeg commandline to use feature aliases and have same results with both libvmaf 2.3.0 and 2.3.1? (fingers crossed)

**Comment by jurisbu** [comment]
So, I suppose this is dead end ...
