### ISSUE TITLE
using YUV format or MP4 format in the experiment？

### ISSUE THREAD

**Issue by NewRegin** [Netflix/vmaf#113]
Hello！I know the vmaf support the yuv format and ffmpeg-vmaf support the mp4 and other formats，but In the training process，I mean In the training of vmaf-TV model and the vmaf-phone model，what's the format of videos? Can I use the dmos scores of some mp4 videos to retrain the vamf model?

**Comment by li-zhi** [comment]
Yes this is possible. Just create a dataset file with yuv_fmt being 'notyuv'. In the field 'quality_width' and 'quality_height', specify the resolution at which you want VMAF to be calculated at. An example can be found at https://github.com/Netflix/vmaf/blob/master/python/test/resource/test_image_dataset_notyuv.py.

**Comment by NewRegin** [comment]
sometimes, the resolution is dynamic, for example:

```

dataset_name = 'example_image'

yuv_fmt = 'notyuv'


from vmaf.config import VmafConfig

ref_videos = [
    {'content_id': 0,'quality_width': 1080, 'quality_height': 1920,  'path': VmafConfig.test_resource_path('icpf', 'frame00000001.icpf')},

    {'content_id': 1, 'quality_width': 540, 'quality_height': 960, 'path': VmafConfig.test_resource_path('icpf', 'frame00000002.icpf')},
]

dis_videos = [
    {'content_id': 0, 'asset_id': 0, 'quality_width': 1080, 'quality_height': 1920, 'dmos': 100, 'path': VmafConfig.test_resource_path('icpf', 'frame00000000.icpf')}, # ref
    {'content_id': 0, 'asset_id': 1, 'quality_width': 1080, 'quality_height': 1920, 'dmos': 50,  'path': VmafConfig.test_resource_path('icpf', 'frame00000001.icpf')},

    {'content_id': 1, 'asset_id': 2, 'quality_width': 540, 'quality_height': 960, 'dmos': 100,  'path': VmafConfig.test_resource_path('icpf', 'frame00000002.icpf')}, # ref
    {'content_id': 1, 'asset_id': 3, 'quality_width': 540, 'quality_height': 960, 'dmos': 80,  'path': VmafConfig.test_resource_path('icpf', 'frame00000003.icpf')},
]
```

is this OK?

**Comment by li-zhi** [comment]
The quality_width and quality_height are actually different from the source video's width and height. They are the resolution that the videos are scaled to before VMAF calculation is performed. For the videos of MP4 format, since the width and height are coded in their header (unlike YUV), you don't actually have to specify them.

Furthermore, if you want to control the scaling method, add a line like `resampling_type = 'bicubic'` (if you don't add, the default is bilinear).

**Comment by NewRegin** [comment]
thanks, zhi!
