### ISSUE TITLE
Results in MSU Video Quality Metrics Benchmark

### ISSUE THREAD

**Issue by msm1rnov** [Netflix/vmaf#1133]
Hello! We have recently launched and evaluated this algorithm on the dataset of our video quality metrics benchmark. The dataset distortions refer to compression artifacts on professional and user-generated content. Method took 1th place on [the global leaderboard](https://videoprocessing.ai/benchmarks/video-quality-metrics_both.html) and 1th place on [the full-reference-only leaderboard](https://videoprocessing.ai/benchmarks/video-quality-metrics_frm.html) in the terms of SROCC. You can see more detailed results here. If you have any other video quality metric (either full-reference or no-reference) that you want to see in our benchmark, we kindly invite you to participate. You can submit it to the benchmark, following the submission steps, described [here](https://videoprocessing.ai/benchmarks/video-quality-metrics.html#submit).

**Comment by igv** [comment]
I'd like to see PSNR-HVS (preferably with these changes: [1](https://github.com/Netflix/vmaf/pull/925/commits/a2743de7920194aefea60d467076f18383dd3f15), [2](https://github.com/Netflix/vmaf/pull/925/commits/b91a31fec4d30253196f06344bc735064419de2a), [3](https://github.com/Netflix/vmaf/pull/925/commits/c127c9cb69ec1b6ad2344b0eee7e4ea174d9f385), [4](https://github.com/Netflix/vmaf/pull/925#issuecomment-962555994)), [VIFp](https://github.com/Netflix/vmaf/issues/826#issuecomment-781923811) and SSIM with MAD (mean absolute deviation) pooling, it's better compatible with SSIM than mean pooling.
