### ISSUE TITLE
VMAF output to pipe/stream

### ISSUE THREAD

**Issue by Batuzz** [Netflix/vmaf#1134]
Hello, I know I can save VMAF output to a file using the `log_path` FFMPEG parameter or `--output/-o` in VMAF directly. On the other hand, I think that output to stream eg. pipe output would be super useful in terms of optimizing the VMAF calculation workflow. I could use the output stream directly in the video processing flow, instead of reading the file that just has been saved.

Do you have any solution for that? Looking inside the code of VMAF, it seems I could not achieve such behavior right now.

Do you have any strong opinion on that, eg. why it should not be implemented this way? Otherwise, are you OK with me making a pull request for that feature request?

**Comment by kylophone** [comment]
If you try `--quiet --output /dev/stdout`, what you're asking for should work. You can redirect the stream, filter with pipe, ...
