### ISSUE TITLE
How to choose correct vmaf score when scale up 720p to 1080p (source video) ?

### ISSUE THREAD

**Issue by kocoten1992** [Netflix/vmaf#1139]
Hi, I'm very new to vmaf, my apology.

I've a source video (happened to be 1080p), I've encode source video to 1080p and 720p video.

Compare between distorted 1080p and source video is pretty strange forward. But my understanding is that, if I want to compare vmaf between 720p and source video, I need to scale 720p video up, but isn't doing so will lower vmaf score?

So how could I pick the appropriate vmaf score for 720p ? I read FAQ and Netflix blog, but there is no mention of that https://netflixtechblog.com/vmaf-the-journey-continues-44b51ee9ed12

If I may, could I ask what is the relation between compare vmaf between 1080p and 720p? What is the recommended vmaf score for 720p that you guy use? for 480p, 360p, 240 as well?

For example, in VP9 guideline, there is a section what is the recommended CRF between 1080p and 720p and so on, https://developers.google.com/media/vp9/settings/vod.

I feel like that what we are missing here..

**Comment by slhck** [comment]
Does this answer your questions? https://github.com/Netflix/vmaf/issues/891

Basically you have an interdependence of assumed viewing distance and resolution. If you want to measure encoding quality only, you should probably compare a downscaled 720p version of the source against your encode. (Because anyway that's what an encoder will do, too.)

**Comment by kocoten1992** [comment]
Thank you very much @slhck ! I'll answer more clear here for future reader.

Based on answer https://github.com/Netflix/vmaf/issues/891#issuecomment-897835120, the correct way to do in this case is downscale source video to 720p first (remember to use `-crf 0` to retain all quality), and then compare distorted 720p against that.
