### ISSUE TITLE
Warning "svg.image_noscale is deprecated"

### ISSUE THREAD

**Issue by slhck** [Netflix/vmaf#114]
Running the latest version of VMAF under macOS 10.12 with Homebrew-installed Python 2.7.13 and `matplotlib` version 2.0.2, I am getting the following when running this command:

```
./run_vmaf yuv420p 576 324 python/test/resource/yuv/src01_hrc00_576x324.yuv python/test/resource/yuv/src01_hrc01_576x324.yuv --out-fmt json
```

Output starts with:

```
/usr/local/lib/python2.7/site-packages/matplotlib/rcsetup.py:589: UserWarning: svg.image_noscale is deprecated. Set image.interpolation to 'none' instead.
  warnings.warn("svg.image_noscale is deprecated. Set "
```

I don't know what exactly causes this ~error~ warning – any ideas?

**Comment by li-zhi** [comment]
Shouldn't impact any output since run_vmaf doesn't produce any graphics..

**Comment by slhck** [comment]
I assumed it would not cause any wrong output, but it still seems weird to get that warning, especially when no graphics are being produced.

**Comment by li-zhi** [comment]
The only case when a graph is generated is by enabling the option `--local-explain`. This is an hidden option that tries to provide some insights on the relative weights of different features in the final result. Could you try that and see if you can get a plot?

**Comment by slhck** [comment]
Using the Docker version I cannot reproduce this anymore, maybe it's a particular version of a package that caused it.
