### ISSUE TITLE
Dockerfile requires download of tex-common?

### ISSUE THREAD

**Issue by slhck** [Netflix/vmaf#115]
Installing the Docker variant, I see that these packages, among others, are downloaded:

```
tex-common tex-gyre texlive-base texlive-binaries texlive-extra-utils
  texlive-font-utils texlive-fonts-extra texlive-fonts-extra-doc
  texlive-fonts-recommended texlive-fonts-recommended-doc
  texlive-generic-recommended texlive-latex-base texlive-latex-base-doc
  texlive-latex-extra texlive-latex-extra-doc texlive-latex-recommended
  texlive-latex-recommended-doc texlive-pictures texlive-pictures-doc
  texlive-pstricks texlive-pstricks-doc
```

What causes these to be downloaded and installed? It takes quite a long time just to set up those dependencies.

Full log here: https://pastebin.com/raw/zQMLkFsR

**Comment by li-zhi** [comment]
@leandromoreira

**Comment by leandromoreira** [comment]
@slhck I followed the steps on the [prerequisite-installation](https://github.com/Netflix/vmaf#prerequisite-installation) and I was adding some packages as I was facing some issues. 

But if you can shrink its size it'll be awesome!!! Maybe now we're able to make a smaller docker image.

**Comment by slhck** [comment]
My idea would be to only install the essential packages needed for running VMAF. I have yet to check why TeX would be needed here.

I'll create a new Dockerfile based on a smaller base image, too, like `alpine`, and send a PR.

**Comment by slhck** [comment]
Just to mention that the basic `vmaf` image takes 3.45GB, plus 122MB from the `ubuntu` container.

**Comment by leandromoreira** [comment]
@slhck I know, it'll be great if we could decrease its size.

**Comment by slhck** [comment]
I'm not sure why `pkg-config gfortran libhdf5-dev libfreetype6-dev liblapack-dev` are needed and listed in the README. The following dependencies do the trick for me with the base Ubuntu Docker image:

`apt-get install build-essential git python python-setuptools python-dev python-tk`

Then, all I need to do is:

`pip install numpy scipy matplotlib notebook pandas sympy nose scikit-learn h5py`
