### ISSUE TITLE
First frame always has lower score than expected

### ISSUE THREAD

**Issue by gsimko** [Netflix/vmaf#1159]
https://github.com/Netflix/vmaf/issues/1105 was closed but I think the bug is still present.

I believe there's something wrong about the first frame. It always has lower than expected value, and with ffmpeg even if I just pass in a single frame (using -frames:v 1) vmaf reports two frames, where the first frame has the low unexpected score.

**Comment by nilfm** [comment]
Hi, would you mind providing a command line and inputs to reproduce this?

**Comment by gsimko** [comment]
Sorry but it's been such a long time ago I can't do that anymore.
