### ISSUE TITLE
ffmpeg2vmaf should use bicubic upscaling not bilinear for more consistent results

### ISSUE THREAD

**Issue by chadnickbok** [Netflix/vmaf#116]
I ran into a strange issue testing vmaf results across resolutions - basically ffmpeg2vmaf doesn't like 540p content. I assume this is due to the exact multiple-of-two scaling the bilinear filter does, but essentially any content I encode at 540p get a worse vmaf score than 522p.

Switching ffmpeg2vmaf over from bilinear to bicubic scaling in `python/src/vmaf/core/asset.py` reduces this issue (and greatly improves overall VMAF scores!)

My suggestion is to make bicubic scaling the default option, as it has both higher resulting vmaf scores (usually) and more consistency across resolutions.

**Comment by li-zhi** [comment]
Great point. I will put in a fix. -Zhi
