### ISSUE TITLE
Question：Can the (MS) SSIM values of different components (for example MS-SSIM_Y、MS-SSIM_U、MS-SSIM_V) be calculated by this program?

### ISSUE THREAD

**Issue by ajian-hit** [Netflix/vmaf#1173]

**Comment by nilfm** [comment]
`libvmaf` does not support this at the moment, all the (MS-)SSIM calculations are done only on the luma layer. You can always preprocess your video to extract any channel you want and run the metrics on it, for example using ffmpeg's [extractplanes](https://ffmpeg.org/ffmpeg-filters.html#extractplanes) filter.

**Comment by ajianx** [comment]
您好！您的邮件我已收到，我会尽快阅读并予以回复……      祝好！                                                                   —杨冬建

**Comment by ajianx** [comment]
您好！您的邮件我已收到，我会尽快阅读并予以回复……      祝好！                                                                   —杨冬建
