### ISSUE TITLE
How to compute ms_ssim with libvmaf in ffmpeg without computing vmaf score?

### ISSUE THREAD

**Issue by WuDi329** [Netflix/vmaf#1179]
I would like to compute a ms_ssim score using ffmpeg. I would like to use libvmaf, but libvmaf always computes the vmaf score in parallel.
if I want to compute a ms_ssim score, I can use the libvmaf like so
`ffmpeg -i output.mp4 -i source.mp4 -lavfi "float_ms_ssim" -f null -`

This gives the ms_ssim score, but computes in parallel the vmaf score (which is very slow, in opposition to the ms_ssim which is very fast).
![image](https://user-images.githubusercontent.com/55496466/229993558-48e4fe58-15c0-4df0-b50d-b6a036ea6f37.png)

Is there a way to compute the ms_ssim score without calculating the vmaf score?

**Comment by kylophone** [comment]
The `vmaf` command line tool has a "--no_prediction" parameter to avoid loading the default model. We'd need to something similar in the ffmpeg filter since the model is also loaded by default if unset [here](https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/vf_libvmaf.c#L79).

**Comment by WuDi329** [comment]
> The `vmaf` command line tool has a `--no_prediction` parameter to avoid loading the default model. We'd need to something similar in the ffmpeg filter since the model is also loaded by default if unset [here](https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/vf_libvmaf.c#L79).

tks!

**Comment by KiritoGuugk** [comment]
> The `vmaf` command line tool has a `--no_prediction` parameter to avoid loading the default model. We'd need to something similar in the ffmpeg filter since the model is also loaded by default if unset [here](https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/vf_libvmaf.c#L79).

Can you provide the full ffmpeg command? Cause I am a newbie and try add `no_prediction` parameter after `libvmaf=` but failed
