### ISSUE TITLE
vmaf with cuda in ffmpeg?

### ISSUE THREAD

**Issue by thet0ast3r** [Netflix/vmaf#1184]
Hi,

I have been trying to getting libvmaf to work with ffmpeg; but using cuda for feature extraction. 

I installed vmaf from the latest commit, ran the tests. All came back ok, also the cuda tests.

Then i compiled ffmpeg with some minimal encoding & decoding capabilities & --enable-libvmaf. 

When i then attempt to use the vmaf filter in ffmpeg on a video, it appears to not be using any gpu, and only one cpu thread. I can work around this by using threads=8 for example, but when i try to pass gpumask:0, ffmpeg, i get an error:

`Error applying option 'gpumask' to filter 'libvmaf': Option not found`

Am I making any obvious mistake here, or is it just not possible with ffmpeg at the moment? 

Thanks,
Tobias

**Comment by thet0ast3r** [comment]
also:
using ubuntu 22.04, cuda toolkit 12.1, ffmpeg 6.0

**Comment by kylophone** [comment]
The FFmpeg filter does not support CUDA yet, support for that is coming. I will be sending a patch to FFmpeg soon, more details here: https://github.com/Netflix/vmaf/pull/1185.

**Comment by gedoensmax** [comment]
Extending Kyle's answer as the patch has been submitted: http://ffmpeg.org/pipermail/ffmpeg-devel/2023-August/313073.html

**Comment by nilfm** [comment]
Further extending Kyle's answer - the patch is now in upstream ffmpeg: https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/7f685d0f493bbfa44cf1b3b65f9347291e23872b?hp=b23eaf968e375f2d38865d90a788221caead3324

Closing for now, please reopen if you have any issues with the filter.
