### ISSUE TITLE
[Question] Does vmaf support chroma channel?

### ISSUE THREAD

**Issue by Lelouch422** [Netflix/vmaf#1190]
Hi, I have a question: 
The output of vmaf value seems only for luma channel, does it support to calculate the value of chroma channel, just like psnrY/psnrU/psnrV?
how to use command-line or ffmpeg to get the chroma result, thanks!

**Comment by Lelouch422** [comment]
@li-zhi @kylophone , thanks!

**Comment by krasuluk** [comment]
@Lelouch422 Currently, the VMAF algorithm is only defined for the luma channel. Due to the perceptual nature of the features, running it on the chroma channel would lead to inaccurate results, as the perceptual mechanisms for luminance and chrominance differ significantly.

**Comment by Lelouch422** [comment]
@krasuluk Thanks for your prompt reply!
