### ISSUE TITLE
ninja build fails when i enable_cuda

### ISSUE THREAD

**Issue by Mlypse** [Netflix/vmaf#1191]
Hi,
The default method can be compiled successfully, but when I use cuda to compile and accelerate, ninja build fails.

The first compilation error seems to be this  
 ../src/feature/cuda/integer_motion_cuda.c:283:118: error: 'CU_EVENT_WAIT_DEFAULT' undeclared (first use in this function); did you mean 'CU_EVENT_DEFAULT'?

How to repro:
git clone https://github.com/Netflix/vmaf.git
git checkout master
python3 -m pip install virtualenv
python3 -m virtualenv .venv
source .venv/bin/activate
pip install meson
sudo apt install nasm ninja-build doxygen xxd
export PATH=/usr/local/cuda/bin:$PATH
meson -Denable_cuda=true build --buildtype release
ninja -vC build

I use cuda-11.0, other information：
(.venv) (base) oppoer@task-20230630152022-44593:/home/notebook/code/personal/vmaf/libvmaf$ cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by fchord** [comment]
[vmaf_master_cuda_build_err.log](https://github.com/Netflix/vmaf/files/11915245/vmaf_master_cuda_build_err.log)

**Comment by yaellivne2** [comment]
I see the same error

**Comment by Mlypse** [comment]
I measured fps for 2K (600 frames) by ffmpeg_lavfi_libvmaf vmaf_cpu and vmaf_gpu , the results are as follows:

ffmpeg_lavfi_libvmaf: 23fps
vmaf_cpu: 9fps
vmaf_gpu: 198fps

I have two doubts:
1. Is ffmpeg faster than vmaf_cpu because of IO optimization?
2. Is the fps of vmaf_gpu accurate? It shows 198fps, but it takes 12 seconds to actually test 600 frames

**Comment by gedoensmax** [comment]
That sounds off I agree. What section of the process are you timing ? I would assume a higher spin up and also spin down time of the process with CUDA enabled. There are still things to optimize that, but I was under the impression that's probably fine as one usually wants to run this for longer videos?
