### ISSUE TITLE
different from the example

### ISSUE THREAD

**Issue by Wangld5** [Netflix/vmaf#1198]
I use the example to test whether I successfully install the vmaf. However, I get the different result from the example:
![image](https://github.com/Netflix/vmaf/assets/30035015/bf41fb23-810b-49e1-b520-5d0c5ae8e51b)
![image](https://github.com/Netflix/vmaf/assets/30035015/453b512e-1c6e-4e0d-a24e-f5e2b83a0be3)
I do not know whether it is normal.

**Comment by nilfm** [comment]
Hi, are you referring to the example in the README [here](https://github.com/Netflix/vmaf/tree/f9f8e96bcbe6dfaedb6c56a7c222bb027977c14c/libvmaf/tools)?

I'm seeing the same score in both screenshots, so the differences are:
* the version, which comes from the commit ID that you built VMAF on. In this case, you used [this recent commit](https://github.com/Netflix/vmaf/commit/49e809c7456267132770a1640716c6562bb3eac8).
* the FPS, which depends on your system

Unless I'm missing something else, the differences you are seeing are normal.

**Comment by Wangld5** [comment]
Thank you for your reply

**Comment by nilfm** [comment]
No problem, closing this issue but if you have a follow-up question feel free to re-open it.
