### ISSUE TITLE
vmaf can be applied to evaluate the single video?

### ISSUE THREAD

**Issue by sicily373** [Netflix/vmaf#1202]
As demonstrated in the demo , the vamf applied to evaluate the base video and the test video, the command `python ./vmaf/script/run_vmaf.py yuv420p 576 324 base_video.yuv test_video.yuv --out-fmt json`. there are two necessary parameters, base_video.yuv and test_video.yuv. 
However, if i want to evaluate the single video after editing and splicing, can i use the vmaf? if yes, how should i use it?

**Comment by nilfm** [comment]
VMAF is a full-reference metric, so it requires both the reference and distorted video for quality evaluation. From what you're describing, you are looking for a no-reference metric. You can read more about this classification [here](https://en.wikipedia.org/wiki/Video_quality#Classification_of_objective_video_quality_models).

For example, CAMBI (which is a metric provided by libvmaf in this repo) is no-reference, but it is specialized to detect banding artifacts, rather than a general quality assessment.

**Comment by sicily373** [comment]
> VMAF is a full-reference metric, so it requires both the reference and distorted video for quality evaluation. From what you're describing, you are looking for a no-reference metric. You can read more about this classification [here](https://en.wikipedia.org/wiki/Video_quality#Classification_of_objective_video_quality_models).
> 
> For example, CAMBI (which is a metric provided by libvmaf in this repo) is no-reference, but it is specialized to detect banding artifacts, rather than a general quality assessment.

thanks for your reply

**Comment by sicily373** [comment]
> VMAF is a full-reference metric, so it requires both the reference and distorted video for quality evaluation. From what you're describing, you are looking for a no-reference metric. You can read more about this classification [here](https://en.wikipedia.org/wiki/Video_quality#Classification_of_objective_video_quality_models).
> 
> For example, CAMBI (which is a metric provided by libvmaf in this repo) is no-reference, but it is specialized to detect banding artifacts, rather than a general quality assessment.

Thanks for your reply. And i have a new question: how should i compute the CAMBI score of a video (or a image)?

**Comment by nilfm** [comment]
You can refer to [this guide](https://github.com/Netflix/vmaf/blob/master/resource/doc/cambi.md#how-to-run-cambi) to run CAMBI using the VMAF command line tool. You still need to pass two inputs, but just pass the same input as reference and distorted, as only the distorted one is used in CAMBI.

**Comment by nilfm** [comment]
Closing this, feel free to reopen if you have further questions.
