### ISSUE TITLE
Common encoder bug/feature leading to inaccuracy for even n_subsample values

### ISSUE THREAD

**Issue by veikk0** [Netflix/vmaf#1214]
Thought I'd bring this up here, even though it's not an issue with VMAF itself, since it's likely to affect VMAF users who make use of the subsampling feature.

An issue [was reported](https://github.com/xiph/rav1e/issues/2468) in rav1e where the encoder retains a significantly differing amount of grain/detail every other frame. [shssoichiro](https://github.com/shssoichiro) did some digging and [came to the conclusion](https://github.com/xiph/rav1e/issues/2468#issuecomment-1086533406) that this is a natural effect of using frame pyramids and that all encoders are prone to it. So far I've also reproduced this with x264, x265, libaom, and SVT-AV1 using the ducks_take_off_1080p50_60f.y4m test clip from the objective-2-slow dataset. I was unable to reproduce this using h264_vaapi and hevc_vaapi on a Radeon RX 6600, so hardware encoders may or may not be affected.

How this relates to VMAF is that libvmaf offers the `n_subsample` option to speed up calculation by only computing scores every N frames. When an even value of `n_subsample` is used with an input file exhibiting the aforementioned issue, only the frames with a higher amount of detail are evaluated, leading to a variance from the ground truth VMAF score. This variance can be pretty significant and varies by encoder and often with the encoder preset. With rav1e's speed 9, `n_subsample=2` lead to a VMAF score of 96.716700, when the ground truth was 93.087603. That's an error of +3.62. With SVT-AV1's preset 12 + tune 0, the error was +2.71.

Now, this might not be as much of an issue when calculating the average VMAF of longer videos. Due to a variance in content, the error might be averaged out. But in some of my tests with a 60-second video, there was still an error of +0.39 with `n_subsample=2`, whereas using a value of 3 or 5 had an error of about +0.02 at most.

Where I can see this being an issue is VMAF-guided shot-based encoding and other applications where the content being evaluated is shorter clips. In such cases, this may lead to quality dips from one scene to the next.

I haven't done thorough testing, since the issue being present can vary a lot based on content, the encoder and settings used, and possibly the kind of VMAF quality being targeted (since more/less detail will be present). But perhaps this is a common enough of an encoder quirk that recommending against the use of even subsampling values would be a good idea?

Attached are some sample encodes of ducks_take_off_1080p50_60f done with various encoders for easier reproducibility, followed by the error introduced by using `n_subsample=2`.

* [x264-fast](https://github.com/Netflix/vmaf/assets/7808922/fa7c2245-1e2f-4739-b7ac-9652c6c14bc3) (error of 2.00)
* [x265-slow](https://github.com/Netflix/vmaf/assets/7808922/44055a14-c49e-4290-b30f-006aeab604db) (error of 1.70)
* [SVT-AV1 preset 12](https://github.com/Netflix/vmaf/assets/7808922/7cdb2dbe-0d8c-4f2a-93c1-d7f05314369e) (error of 2.71)
* [SVT-AV1 preset 5](https://github.com/Netflix/vmaf/assets/7808922/5dc53324-dcfd-464f-b653-80c574c93f15) (error of 1.81)
* [libaom cpu-used 4](https://github.com/Netflix/vmaf/assets/7808922/79306ddd-0d8b-40f7-909a-6ef715914c0c) (error of 1.21)
* [libaom cpu-used 6](https://github.com/Netflix/vmaf/assets/7808922/a0fcb794-6474-4114-bdd3-1f0cc490d119) (error of -0.69, here the score is actually lower than the ground truth)
* [rav1e speed9 with 4 tiles](https://user-images.githubusercontent.com/7808922/231004205-8c7db926-cbd0-43c2-8e23-e3a8dc1a9881.mp4) (error of 3.62)

**Comment by kylophone** [comment]
This is a very good observation and callout. I think we should be adding a pointer to this analysis in the `n_subsample` documentation.

**Comment by nilfm99** [comment]
#1324 added a link to this analysis in `libvmaf.h`.
