### ISSUE TITLE
pkg-config file should not hardcode which C++ runtime to use

### ISSUE THREAD

**Issue by dwbuiten** [Netflix/vmaf#122]
Currently, `libvmaf.pc` hardcodes the use of libstdc++, which is simply untrue on many systems and toolchains, which may be using e.g. `libc++` or some other C++ runtime.

**Comment by li-zhi** [comment]
@ashk43712 would you take a look?

**Comment by li-zhi** [comment]
@rbultje would you take a look?

**Comment by rbultje** [comment]
I'm not really very familiar with pkg-config so I don't really know how to fix it...

**Comment by kylophone** [comment]
Closing this old issue, I believe meson does the right thing now.
