### ISSUE TITLE
For the first frame, its features integer_motion and integer_motion2 are always 0

### ISSUE THREAD

**Issue by wbaiting** [Netflix/vmaf#1229]
I found that for the first frame, its features integer_motion and integer_motion2 are always 0. I'm guessing if this is why the VMAF value of the first frame is less than 100 when we compare two identical videos.

**Comment by nilfm** [comment]
You are right that for the first frame those features are always 0. However, VMAF does not guarantee that VMAF(x, x) == 100, see the relevant FAQ [here](https://github.com/Netflix/vmaf/blob/master/resource/doc/faq.md#q-when-i-compare-a-video-with-itself-as-reference-i-expect-to-get-a-perfect-score-of-vmaf-100-but-what-i-see-is-a-score-like-987-is-there-a-bug).

Note that motion is only computed on the reference video, and therefore it doesn't matter if the reference and distorted video are identical for this feature. Most videos will have enough motion that VMAF will be 100 past the first frame, and this is probably the behavior that you are seeing, but you can easily construct an input where VMAF is not 100 on any frame, such as `/dev/zero`.

**Comment by nilfm** [comment]
Closing this, please reopen if you have further questions.
