### ISSUE TITLE
Question about supporting Python 3

### ISSUE THREAD

**Issue by c-bata** [Netflix/vmaf#128]
Hi! Thanks for developing this interesting library.

I know this library supported Python 3.6 ([see here](https://github.com/Netflix/vmaf/blob/master/python/setup.py#L33-L36)), and I could successfully install vmaf library on Python 3.6 and I could try to calculate PSNR via [ffmpeg libvmaf filter](https://ffmpeg.org/ffmpeg-filters.html#libvmaf).
But following scripts written for Python 2:
https://github.com/Netflix/vmaf/blob/master/python/script/

And also the script on README uses a print statement.
https://github.com/Netflix/vmaf/compare/master...c-bata:replace-print-statement-with-function?expand=1

So I have a plan to fix these scripts to support Python 3. I want to know that you are positive to support Python 3.

**Comment by li-zhi** [comment]
@c-bata Thanks for this. We are also planning to iterative the repo to make it support publishing in Python 2 and 3 (publishing is not ready yet). In the mean time, please feel free to submit PR to make the code more general. +@zsimic

**Comment by c-bata** [comment]
I see. thanks.
