### ISSUE TITLE
unittest errors and warnings

### ISSUE THREAD

**Issue by CSMGAO** [Netflix/vmaf#130]
when I run ./unittest, some errors and warnings occur.  Should I be concerned about these Warning/Errors? Thanks!

They are shown as follows:

UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.18 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
UserWarning)
/vmaf/vmaf-master/python/src/vmaf/core/perf_metric.py:297: RuntimeWarning: invalid value encountered in double_scalars  z = (mos_a - mos_b) / np.sqrt(var_a/n_a + var_b/n_b)

======================================================================
FAIL: test_run_vmaf_runner_pool_perc10 (quality_runner_test.QualityRunnerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/CORP/min.gao/vmaf/vmaf-master/python/test/quality_runner_test.py", line 933, in test_run_vmaf_runner_pool_perc10
    self.assertAlmostEqual(results[0]['VMAF_score'], 72.753572476835515, places=4)
AssertionError: 72.753852967634373 != 72.75357247683552 within 4 places

======================================================================
FAIL: test_run_vmafossexec_runner_enable_avx_precise (quality_runner_test.QualityRunnerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/CORP/min.gao/vmaf/vmaf-master/python/test/quality_runner_test.py", line 1375, in test_run_vmafossexec_runner_enable_avx_precise
    self.assertAlmostEqual(results[0]['VMAFOSSEXEC_score'], 76.699266666666674, places=5)
AssertionError: 76.699306249999992 != 76.69926666666667 within 5 places

**Comment by CSMGAO** [comment]
When the reference video is the same as the distorted video, why the VMAF score is 98.908912 not 100. 
Here is my cmd line: 
./run_vmaf yuv420p 1280 720 /YuvSeq/src.yuv /YuvSeq/src.yuv --out-fmt text

**Comment by li-zhi** [comment]
It is likely due to different versions of numpy/sklearn. Since the numerical error is small, I think you can safely ignore them.

About the question why you don't get a perfect score when using the same video as reference, an explanation is provided to the FAQ page at: https://github.com/Netflix/vmaf/blob/master/FAQ.md. Basically the ML-based approach doesn't guarantee that you have a perfect score, but you should get a score close enough.
