### ISSUE TITLE
Python .egg files are deprecated and should be replaced by Wheel format (python)

### ISSUE THREAD

**Issue by SingingBush** [Netflix/vmaf#1307]
In the python dir:

```
./setup.py build
./setup.py install
pip install .
```

```
DEPRECATION: Loading egg at /home/user/vmaf/.venv/lib64/python3.12/site-packages/vmaf-2.0.0-py3.12-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
```

_please note_: it's worth also pointing out that I had checked out the 3.0.0 tag but the setup.py has resulted in 2.0.0 being in the egg file name. This is because the python build gets the version from `python/vmaf/__init__.py` while the lib has it defined in `libvmaf/meson.build` so it's easy for them to fall out of sync. I've created #1309 for this.

**Comment by nilfm99** [comment]
With the current master, I can run `pip install .` directly and it'll build a wheel, both on mac and linux. It does require a recent version of pip, 23.3.2 worked for me. Are you still having this issue? (we'll treat #1309 separately)

**Comment by SingingBush** [comment]
I'm on pip 23.2.1. I've pulled the latest changes and can confirm that I now see the change in build output

```
Building wheels for collected packages: vmaf
  Building wheel for vmaf (pyproject.toml) ... done
  Created wheel for vmaf: filename=vmaf-2.0.0-cp312-cp312-linux_x86_64.whl
```

and doing `pip list | grep vmaf` shows I have vmaf 2.0.0 installed. thanks
