### ISSUE TITLE
Python version in GitHub actions should be updated

### ISSUE THREAD

**Issue by SingingBush** [Netflix/vmaf#1308]
it's currently using 3.8, please update to the latest stable release (currently 3.12). This will also require addressing #1306 and #1307

**Comment by nilfm99** [comment]
We have found that our dependency `libsvm-official` didn't publish wheels for python3.12, so we're staying at 3.11 for now. We will be making more changes to the CI code soon to adapt to arm64 architectures which github actions will be offering soon.

Thanks for opening this issue. Closing this thread, please reopen if you have other suggestions.
