### ISSUE TITLE
Segfault running ffmpeg+libvmaf on Alpine Linux

### ISSUE THREAD

**Issue by mshang** [Netflix/vmaf#131]
I get a segfault when running the libvmaf filter in ffmpeg on Alpine Linux. The problem can be demonstrated by building the following Dockerfile:

```
FROM alpine

RUN apk add --no-cache build-base unzip curl coreutils nasm git

RUN git clone --depth 1 https://github.com/Netflix/vmaf.git vmaf \
        && cd vmaf \
        && make \
        && make install

RUN curl -s http://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 | tar jxf - -C . \
        && cd ffmpeg \
        && ./configure --enable-libvmaf --enable-version3 \
        && make -j32 \
        && make install

RUN curl https://thumbs.gfycat.com/RichPepperyFerret-mobile.mp4 > rpf.mp4 \
        && ffmpeg -i rpf.mp4 rpf2.mp4 \
        && ffmpeg -i rpf.mp4 -i rpf2.mp4 -filter_complex libvmaf -f null -
```

Output (last 2 lines):

```
Segmentation fault (core dumped)
The command '/bin/sh -c curl https://thumbs.gfycat.com/RichPepperyFerret-mobile.mp4 > rpf.mp4         && ffmpeg -i rpf.mp4 rpf2.mp4   && ffmpeg -i rpf.mp4 -i rpf2.mp4 -filter_complex libvmaf -f null -' returned a non-zero code: 139
```

Could this problem occur because Alpine Linux uses musl instead of glibc?

**Comment by ReaddyEddy** [comment]
Yes

**Comment by mshang** [comment]
Looks like it comes down to a difference in pthreads implementation between glibc and musl. The line that segfaults is in `libavfilter/vf_libvmaf.c` in the ffmpeg codebase:

    pthread_join(s->vmaf_thread, NULL);

If I add a conditional so that this line is only called if `vmaf_thread` has been initialized, then it works.

**Comment by mshang** [comment]
So really, this is a bug in the ffmpeg code that connects to vmaf, not in vmaf itself, so feel free to close this issue if it's not helpful. However, I'm not submitting a bug to ffmpeg because I don't want to register for their bug tracker.
