### ISSUE TITLE
Is GPU required to build cuda-enabled version?

### ISSUE THREAD

**Issue by adityapatadia** [Netflix/vmaf#1318]
According to this doc: https://github.com/Netflix/vmaf/blob/master/resource/doc/docker.md#docker-with-cuda-support , CUDA driver etc is required. My question is whether a GPU is required to build cuda enabled libvmaf with ffmpeg or it would build on normal CPU and CI pipeline like bitbucket or github?

**Comment by kylophone** [comment]
I think technically this could be cross-compiled, but for now the most supported way to build is with the Dockerfile and CUDA driver. I would prefer us to eventually get to a point where what you are describing is possible.
