### ISSUE TITLE
Run in Batch gives slightly different results than single runs

### ISSUE THREAD

**Issue by ecomte** [Netflix/vmaf#136]
We ran the same videos in batch as we did one-by-one. Extremely similar results, but an average of 0.30 difference in the aggregate scores. What could be causing this, and is this a bigger issue or something I should be worried about?

**Comment by li-zhi** [comment]
I wouldn’t expect this to happen. What were the command lines used?

**Comment by ecomte** [comment]
My apologies. We found that we were using yuv's that were converted from mp4 compared to yuv's that were converted from mpg. That explains why scores were very similar but differed by a little.
