### ISSUE TITLE
How to specify multiple features with FFMPEG and VMAF?

### ISSUE THREAD

**Issue by ltrudeau-twoorioles** [Netflix/vmaf#1365]
I would like to output VMAF, SSIM and PSNR in the same .json file using FFMPEG. I tried this:

```
ffmpeg -i SolLevante_SDR_UHD_24fps.mov -i SolLevante_SDR_UHD_24fps.mov -vframes 10 -lavfi libvmaf=log_path=test.json:log_fmt='json':feature='name=psnr':feature='name=float_ssim' -f null -
```

I get float_ssim but not psnr

I also tried 

```
ffmpeg -i SolLevante_SDR_UHD_24fps.mov -i SolLevante_SDR_UHD_24fps.mov -vframes 10 -lavfi libvmaf=log_path=test.json:log_fmt='json':feature='name=psnr:float_ssim' -f null -
```

I get psnr but not float_ssim. 

Any ideas on what I'm doing wrong?

**Comment by XuShiSheng** [comment]
你好！邮件已收到，我会尽快回复你--许思焱

**Comment by nilfm99** [comment]
Hi @ltrudeau-twoorioles, could you specify which ffmpeg version you are using? I have tried the ffmpeg 7.0 release, and following the example [here](https://ffmpeg.org/ffmpeg-filters.html#Examples-92), I was able to get both `psnr` and `float_ssim`. Here is my command:
```
ffmpeg -i ref5.y4m -i dis5.y4m -lavfi libvmaf='log_path=test.json:log_fmt=json:feature=name=psnr|name=float_ssim' -f null -
```

Hope this helps. Please let me know if this doesn't work for you, along with the ffmpeg version, and we will investigate further.
