### ISSUE TITLE
frame sampling

### ISSUE THREAD

**Issue by mshang** [Netflix/vmaf#140]
In order to reduce the runtime of vmaf, there could be option to sample frames when calculating elementary metrics. For example, calculate elementary metrics on only one of every three frames. This is not equivalent to sampling frames as a preprocessing step before feeding into vmaf because doing so would result in higher motion scores, which would throw off the results.

**Comment by chadnickbok** [comment]
This is a great feature I'd love to see.

Additionally, it would be awesome if there was a way to run vmaf in parallel across multiple frame pairs, to make use of multiple cores and speed up vmaf time.
