### ISSUE TITLE
how can i get same frame from a source ref doc to dis doc. 

### ISSUE THREAD

**Issue by balsei** [Netflix/vmaf#141]
how can i get same frames  between source ref video and  dis video. 

for example : i have a ref video  and  a dis video . but they have different frames, how can i get same frames between them and then run vmaf to get result.
tks~

**Comment by li-zhi** [comment]
Not sure if I fully get the question, but I think you need to pre-process them (like using FFmpeg) to make the frames aligned before passing them to VMAF.
