### ISSUE TITLE
Unittest failures and errors

### ISSUE THREAD

**Issue by KanoB** [Netflix/vmaf#142]
Hello

I was able to compile on Centos7 virtual machine, after having all prerequisites installed.
But when runing the unittest I'm getting 2 failures, 21 errors and 1 skipped. I would appreciate you help on how can fix this to have a proper VMAF installation. 
Attached are the output of the unitest modules that fail.
- cross_validation_test.py	RAN 11: errors 11
- local_explainer_test.py		RAN 3: errors 1
- noref_feature_extractor_test.py	RAN 5: failures 2, errors 3
- train_test_model_test.py	RAN 12, errors 6

[local_explainer_test errors.txt](https://github.com/Netflix/vmaf/files/1624670/local_explainer_test.errors.txt)
[noref_feature_extractor_test errors.txt](https://github.com/Netflix/vmaf/files/1624671/noref_feature_extractor_test.errors.txt)
[train_test_model_test errors.txt](https://github.com/Netflix/vmaf/files/1624672/train_test_model_test.errors.txt)
[cross_validation_test errors.txt](https://github.com/Netflix/vmaf/files/1624673/cross_validation_test.errors.txt)

These are the python modules used
numpy 1.14.0
/usr/lib64/python2.7/site-packages/numpy/__init__.pyc
scipy 1.0.0
/usr/lib64/python2.7/site-packages/scipy/__init__.pyc
matplotlib 2.1.1
/usr/lib64/python2.7/site-packages/matplotlib/__init__.pyc
pandas 0.22.0
/usr/lib64/python2.7/site-packages/pandas/__init__.pyc
sklearn 0.19.1
/usr/lib64/python2.7/site-packages/sklearn/__init__.pyc
/usr/lib64/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
h5py 2.7.1
/usr/lib64/python2.7/site-packages/h5py/__init__.pyc

**Comment by li-zhi** [comment]
Looks like your numpy may have screwed up. Have you tried to reinstall the packages (or do everything again in a virtual env)?
