### ISSUE TITLE
Memory leak in Win64 ffmpeg with vmaf

### ISSUE THREAD

**Issue by LigH-de** [Netflix/vmaf#143]
The [media-autobuild_suite](https://github.com/jb-alvarado/media-autobuild_suite/) (brief: MABS) supports building ffmpeg in a regularly updates MSYS2/MinGW environment now also with vmaf for the Win64 target platform (a Win32 build failed due to "invalid EMMS intrinsics", is that intended, may that change?).

Another video developer asked me to confirm a memory leak he found, and indeed, once I managed to get ffmpeg built with libvmaf enabled, while comparing two similar videos I noticed a continuously increasing memory consumption.

I hope you can discover whether the reason is within this library or in the ffmpeg interface instead.

![ffmpeg-vmaf-leak](https://user-images.githubusercontent.com/5917225/34908830-6cda9a08-f88e-11e7-92a3-5e057a5c6408.png)

**Comment by LigH-de** [comment]
Also reported as [ffmpeg trac ticket 6967](https://trac.ffmpeg.org/ticket/6967) by the mentioned other developer.

**Comment by enctac** [comment]
This is probably a problem with ffmpeg.
 I sent a patch.

    ​http://ffmpeg.org/pipermail/ffmpeg-devel/2018-March/227312.html
    ​https://patchwork.ffmpeg.org/patch/8158/

This patch seems to work well.
But I am a beginner in programming.
I don't know the framework of ffmpeg well.
Please check it.

**Comment by kylophone** [comment]
@entac, I'll take a look at your patch. Thanks!

**Comment by kylophone** [comment]
Pushed to FFmpeg master.

**Comment by enctac** [comment]
Thanks!
