### ISSUE TITLE
Null results from libvmaf? 

### ISSUE THREAD

**Issue by chrisdavis03** [Netflix/vmaf#145]
I have compiled ffmpeg with libvmaf enabled on MSYS2/MinGW and I am getting null values in most cases. This was compiled with the latest builds. 

ffmpeg -i [reference] -i [distorted] -lavfi libvmaf="model_path=vmaf_model//vmaf_v0.6.1.pkl" -f null -

ProRes422HQ 1080p 23.98 reference yuv422p10le & distorted files - "VMAF score:nan"
    - distorted image was scaled down and rescaled to 1080p as a test. 
 
ProRes422HQ 1080p 23.98 reference yuv422p10le & 1080p h264 5Mbps max yuv420p mp4 - "VMAF score:nan"
    
ProRes422HQ 1080p 23.98 yuv422p10le reference & ProRes422HQ 1080p 23.98 yuv422p10le (same file as reference) - "VMAF score: 99.970710"

ProRes422HQ 1080i 50i yuv422p10le reference & XDCAMHD 1080i 50i yuv422p MXF : vmaf score: 98.147501

So I am not sure why I am getting this result on some files and not others. Especially when two different files in the same format are producing null results. 

I have tried this with "enable_transform=1" and without.  I am having trouble finding what this feature even does but I tried it anyway! Is anyone else seeing this issue or know what I could do to resolve it?

**Comment by li-zhi** [comment]
@chrisdavis03 could you ask the same question in the FFmpeg-devel forum?

**Comment by li-zhi** [comment]
Re: enable_transform

Refer to the code here:
https://github.com/Netflix/vmaf/blob/master/wrapper/src/vmaf.cpp#L481

Basically it does a post processing (e.g. a 2nd-order polynomial point operation) on the predicted score. In some cases (e.g. phone viewing), you want to correct the score a bit to reflect the viewing condition.
