### ISSUE TITLE
ImportError: No module named vmaf.config

### ISSUE THREAD

**Issue by LitovchenkoM** [Netflix/vmaf#147]
Hello.
Tell me please what to do with this error? I followed the instructions, but something went wrong.

![config](https://user-images.githubusercontent.com/23329623/35453560-439eadfe-02fd-11e8-8e7b-aad85293ee31.png)

**Comment by li-zhi** [comment]
This should do with PYTHONPATH. Have you set it up correctly?

**Comment by LitovchenkoM** [comment]
Oh, I forgot. 
When I wrote this - export PYTHONPATH="$(pwd)/python/src:$PYTHONPATH"  - in gitbash it hangs. 
Is this expression for PYTHONPATH correct for Windows? I`m not expert in github...

**Comment by li-zhi** [comment]
Try this one:
https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-7
