### ISSUE TITLE
FAIL: test_to_xml (result_test.ResultFormattingTest)

### ISSUE THREAD

**Issue by enricovittorini** [Netflix/vmaf#148]
VMAV 1.3.1
Ubuntu_17.10-VM-64bit

======================================================================
FAIL: test_to_xml (result_test.ResultFormattingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/osboxes/Desktop/vmaf-1.3.1/python/test/result_test.py", line 160, in test_to_xml
    """.strip())
AssertionError: u'<?xml version="1.0" ?>\n<result executorId="SSIM_V1.0">\n  <asset identifier="test_0_0_checkerboard_1920_1080_10_3_0_0_1920x1080_vs_checkerboard_1920_1080_10_3_1_0_1920x1080_q_1920x1080"/>\n  <frames>\n    <frame SSIM_feature_ssim_c_score="0.997404" SSIM_feature_ssim_l_score="0.999983" SSIM_feature_ssim_s_score="0.935802" SSIM_score="0.933353" frameNum="0"/>\n    <frame SSIM_feature_ssim_c_score="0.997404" SSIM_feature_ssim_l_score="0.999983" SSIM_feature_ssim_s_score="0.935802" SSIM_score="0.933353" frameNum="1"/>\n    <frame SSIM_feature_ssim_c_score="0.997404" SSIM_feature_ssim_l_score="0.999983" SSIM_feature_ssim_s_score="0.935803" SSIM_score="0.933354" frameNum="2"/>\n  </frames>\n  <aggregate SSIM_feature_ssim_c_score="0.997404" SSIM_feature_ssim_l_score="0.999983" SSIM_feature_ssim_s_score="0.9358023333333333" SSIM_score="0.9333533333333334" method="mean"/>\n</result>' != '<?xml version="1.0" ?>\n<result executorId="SSIM_V1.0">\n  <asset identifier="test_0_0_checkerboard_1920_1080_10_3_0_0_1920x1080_vs_checkerboard_1920_1080_10_3_1_0_1920x1080_q_1920x1080"/>\n  <frames>\n    <frame SSIM_feature_ssim_c_score="0.997404" SSIM_feature_ssim_l_score="0.999983" SSIM_feature_ssim_s_score="0.935802" SSIM_score="0.933353" frameNum="0"/>\n    <frame SSIM_feature_ssim_c_score="0.997404" SSIM_feature_ssim_l_score="0.999983" SSIM_feature_ssim_s_score="0.935802" SSIM_score="0.933353" frameNum="1"/>\n    <frame SSIM_feature_ssim_c_score="0.997404" SSIM_feature_ssim_l_score="0.999983" SSIM_feature_ssim_s_score="0.935803" SSIM_score="0.933354" frameNum="2"/>\n  </frames>\n  <aggregate SSIM_feature_ssim_c_score="0.997404" SSIM_feature_ssim_l_score="0.999983" SSIM_feature_ssim_s_score="0.935802333333" SSIM_score="0.933353333333" method="mean"/>\n</result>'

----------------------------------------------------------------------
Ran 263 tests in 511.817s

**Comment by li-zhi** [comment]
@enricovittorini this should be a minor issue. Instead of release 1.3.1, you could use the master branch, in which I have disabled this test.
