### ISSUE TITLE
How to pre-process   destorbed  videos of different frames using FFmpeg 

### ISSUE THREAD

**Issue by balsei** [Netflix/vmaf#149]
eg:pre-process them (like using FFmpeg) to make the frames aligned before passing them to VMAF.

Can introduce some method ?Thank you~

**Comment by christosbampis** [comment]
You can use libvmaf with ffmpeg to process your videos accordingly. Since this is an old issue, I will be closing it. If you have any further issues, please open a new issue with more details on what you are trying to do.
