### ISSUE TITLE
Wrong motion scores reported

### ISSUE THREAD

**Issue by v-pooja** [Netflix/vmaf#152]
I printed the individual motion scores for the example you had given in Readme. ( command : ./vmaf motion yuv420p ../python/test/resource/yuv/src01_hrc00_576x324.yuv ../python/test/resource/yuv/src01_hrc01_576x324.yuv 576 324)
This was the result (shown for first 10 frames)-  
motion: 0 0.000000
motion: 1 4.580837
motion: 2 4.215693
motion: 3 4.070274
motion: 4 3.825236
motion: 5 3.936408
motion: 6 3.635143
motion: 7 4.002877
motion: 8 3.347719
motion: 9 3.817092
motion: 10 3.691148 .....

Now i checked it to verify motion scores with the original output using the command ./run_vmaf yuv420p 576 324 python/test/resource/yuv/src01_hrc00_576x324.yuv python/test/resource/yuv/src01_hrc01_576x324.yuv  --out-fmt json

Here are the results(for the first 10 frames) : 
{
    "executorId": "VMAF_VF0.2.4b-0.6.1", 
    "asset": {
        "identifier": "cmd_5162564171574674_5162564171574674_src01_hrc00_576x324_576x324_vs_src01_hrc01_576x324_576x324_q_576x324"
    }, 
    "frames": [
        {
            "frameNum": 0, 
            "VMAF_feature_adm2_score": 0.96217136750415433, 
            "VMAF_feature_motion2_score": 0.0, 
            "VMAF_feature_vif_scale0_score": 0.50539279105546853, 
            "VMAF_feature_vif_scale1_score": 0.87815481223619163, 
            "VMAF_feature_vif_scale2_score": 0.93758933934495536, 
            "VMAF_feature_vif_scale3_score": 0.96435757157377588, 
            "VMAF_score": 83.868094441269534
        }, 
        {
            "frameNum": 1, 
            "VMAF_feature_adm2_score": 0.94984256440915871, 
            "VMAF_feature_motion2_score": 4.2156929999999999, 
            "VMAF_feature_vif_scale0_score": 0.41109143031796108, 
            "VMAF_feature_vif_scale1_score": 0.81194315704755016, 
            "VMAF_feature_vif_scale2_score": 0.89403688508931733, 
            "VMAF_feature_vif_scale3_score": 0.93713965434015145, 
            "VMAF_score": 82.661645604045333
        }, 
        {
            "frameNum": 2, 
            "VMAF_feature_adm2_score": 0.94353526097589935, 
            "VMAF_feature_motion2_score": 4.0702740000000004, 
            "VMAF_feature_vif_scale0_score": 0.38139805364622886, 
            "VMAF_feature_vif_scale1_score": 0.79762022606001626, 
            "VMAF_feature_vif_scale2_score": 0.88870967833757231, 
            "VMAF_feature_vif_scale3_score": 0.93669068408836953, 
            "VMAF_score": 81.053474938221726
        }, 
        {
            "frameNum": 3, 
            "VMAF_feature_adm2_score": 0.94804535684600044, 
            "VMAF_feature_motion2_score": 3.8252359999999999, 
            "VMAF_feature_vif_scale0_score": 0.39027256681617334, 
            "VMAF_feature_vif_scale1_score": 0.80091553635668877, 
            "VMAF_feature_vif_scale2_score": 0.89109915962321273, 
            "VMAF_feature_vif_scale3_score": 0.9387249283492719, 
            "VMAF_score": 81.935266587112977
        }, 
        {
            "frameNum": 4, 
            "VMAF_feature_adm2_score": 0.93777915463878947, 
            "VMAF_feature_motion2_score": 3.8252359999999999, 
            "VMAF_feature_vif_scale0_score": 0.34953544718938345, 
            "VMAF_feature_vif_scale1_score": 0.76088856753769141, 
            "VMAF_feature_vif_scale2_score": 0.86223057718736063, 
            "VMAF_feature_vif_scale3_score": 0.91933023995641794, 
            "VMAF_score": 77.519625564355977
        }, 
        {
            "frameNum": 5, 
            "VMAF_feature_adm2_score": 0.9352739334116692, 
            "VMAF_feature_motion2_score": 3.6351429999999998, 
            "VMAF_feature_vif_scale0_score": 0.34836843148453278, 
            "VMAF_feature_vif_scale1_score": 0.76045022443533217, 
            "VMAF_feature_vif_scale2_score": 0.85970706906993999, 
            "VMAF_feature_vif_scale3_score": 0.91611922436136772, 
            "VMAF_score": 76.470637944753008
        }, 
        {
            "frameNum": 6, 
            "VMAF_feature_adm2_score": 0.94398982564574452, 
            "VMAF_feature_motion2_score": 3.6351429999999998, 
            "VMAF_feature_vif_scale0_score": 0.3724388208457256, 
            "VMAF_feature_vif_scale1_score": 0.77569389856476201, 
            "VMAF_feature_vif_scale2_score": 0.86861841836794385, 
            "VMAF_feature_vif_scale3_score": 0.91981974868085559, 
            "VMAF_score": 78.732638267982978
        }, 
        {
            "frameNum": 7, 
            "VMAF_feature_adm2_score": 0.93043198747626321, 
            "VMAF_feature_motion2_score": 3.3477190000000001, 
            "VMAF_feature_vif_scale0_score": 0.33949764196054527, 
            "VMAF_feature_vif_scale1_score": 0.74340590247747418, 
            "VMAF_feature_vif_scale2_score": 0.84626437680253419, 
            "VMAF_feature_vif_scale3_score": 0.9063596647197808, 
            "VMAF_score": 74.075814073566008
        }, 
        {
            "frameNum": 8, 
            "VMAF_feature_adm2_score": 0.93347698150126657, 
            "VMAF_feature_motion2_score": 3.3477190000000001, 
            "VMAF_feature_vif_scale0_score": 0.33596599364692359, 
            "VMAF_feature_vif_scale1_score": 0.74814301398466221, 
            "VMAF_feature_vif_scale2_score": 0.85100837297744292, 
            "VMAF_feature_vif_scale3_score": 0.91084336194088278, 
            "VMAF_score": 75.186199558065624
        }, 
        {
            "frameNum": 9, 
            "VMAF_feature_adm2_score": 0.93405914122956568, 
            "VMAF_feature_motion2_score": 3.6911480000000001, 
            "VMAF_feature_vif_scale0_score": 0.35646738953349449, 
            "VMAF_feature_vif_scale1_score": 0.7607033696055121, 
            "VMAF_feature_vif_scale2_score": 0.85849939949690501, 
            "VMAF_feature_vif_scale3_score": 0.91364089520370273, 
            "VMAF_score": 76.025751918284939
        },  ...... }

If we see closely the frameNum 1 is taking the motion score of frame 2 and frameNum 3 and frameNum 4 are giving same values which is clearly wrong. I had tried this out with other video sets as well. Still I find that motion scores are being reported in wrong way in final output set whereas it is being reported correctly in feature vmaf executable.
Why are the motion values wrongly reported in the output? Thank you.

**Comment by li-zhi** [comment]
The motion score extracted by the ./vmaf motion command is the raw score
calculated by the c executable. The final one used in the SVM fusion is
called motion2, which is the aggregated score over every two adjacent
motion scores (by taking the min of the two). The reason why motion2 is
used is to deal with spikiness at scene boundaries.

I hope this helps.

**Comment by v-pooja** [comment]
Thanks.
