### ISSUE TITLE
How to calculate the vmaf score between videos with variable frame rate?

### ISSUE THREAD

**Issue by mengxuewei** [Netflix/vmaf#155]
There are three videos, Video1 is the source video with variable frame rate. Video2 and Video3 are encoded videos from Video1. Video2 is constant frame rate and Video3 is variable frame rate. I want to know which one of Video2 and Video3 is better. So I use vmaf. But there is something wrong when compare with variable frame rate. How can I fix it?

**Comment by cosmin** [comment]
@mengxuewei you won't be able to compare videos of different frame rates together since VMAF performs frame by frame comparisons. You might be able to use ffmpeg to change both the source and the target to the same constant frame rate and then compare those.

**Comment by engineerudays** [comment]
@cosmin i have a case where-in i want to Deploy VMAF to benchmark my Transcodes. And my Transcoder actually generates 25fps output irrespective of the input frame rate. Thats what the application needs. Now changing framerate of all my transcodes is too costly for me, plus the process may add more distortion. Whats the best solution i have for this?

**Comment by cosmin** [comment]
So you should in theory be able to use the FPS filter in ffmpeg to change the original fps to 25 prior to comparison. Try something like 

```
ffmpeg -i encoded.mp4 -i source.mp4 -filter_complex '[1] fps=fps=25 [s_at_25];[0] [s_at_25] libvmaf' -f null -
```

**Comment by engineerudays** [comment]
> So you should in theory be able to use the FPS filter in ffmpeg to change the original fps to 25 prior to comparison. Try something like
> 
> ```
> ffmpeg -i encoded.mp4 -i source.mp4 -filter_complex '[1] fps=fps=25 [s_at_25];[0] [s_at_25] libvmaf' -f null -
> ```

I'm checking if it helps. Will let you know.

Meanwhile, i'm curious to know - how does the industry use VMAF exactly? I'm sure this is not a unique situation. Most of the real-world transcoded would involve changes to frame-rate. Do people really do additional processing to run VMAF (or any other metric) for quality verification? Is that not a additional overhead just for the sake of benchmarking?

Any pointers on this would help. Meanwhile, i will get back to you regarding your suggested solution. Thanks again. Cheers !!

**Comment by slhck** [comment]
I wouldn't consider that a big overhead. Also, if your ingested files have the correct frame rate, changing it is not really necessary.
