### ISSUE TITLE
Missing tag for API change

### ISSUE THREAD

**Issue by KevinJW** [Netflix/vmaf#158]
Hi,

I was trying to build libvmaf for use withing ffmpeg and I note that there is no official tag for the API change, is it safe to assume that ba5356cb41cf3b19ca0bb108bd8e86e9da402f94 is the 'stable' commit for that ?

Thanks

Kevin

**Comment by li-zhi** [comment]
@KevinJW Are you referring to the version bump in libvmaf.pc requested by @rbultje? 0.6.2 is still the latest version for the API, if that answers your question.

**Comment by KevinJW** [comment]
I mean a git tag is missing, not the API version, I'm assuming that the commit mentioned above is the matching one for the API change. Without that I'd have to run from HEAD - which I don't like doing, I'd prefer some stable value that I can using in my build process.

FWIW, My use case is for building into FFmpeg, which was also broken but has now been patched in ffmpeg. So now it builds.

Thanks

Kevin

**Comment by li-zhi** [comment]
You are absolutely right. We made the API change some time ago but haven't been diligent enough to create a new tag (and release). I'll make a new release today. Thanks!

**Comment by KevinJW** [comment]
No problems, it just took me a while to make sure I found a commit that made sense (only to find ffmpeg then crashed!).

Kevin
