### ISSUE TITLE
Same resolution, different bitrate VMAF still the same

### ISSUE THREAD

**Issue by Asusio** [Netflix/vmaf#160]
Hello,

I'm trying to use VMAF on Linux Ubuntu 16.04 with a 5 second video. I have this video in 1080p 60fps in different bitrate. When I'm trying to use VMAF to compare these videos to the original video which is a 4K 60fps 10Mbit/s. The mean score is approximattely always the same.

To use VMAF I first convert the video in a raw format, with this command:
`ffmpeg -i Video.mp4 -c:v rawvideo -pix_fmt yuv420p raw-Video.yuv`

And after I use this command to have a text file:
`./run_vmaf yuv420p 2160 1440 'home/alexis/Desktop/raw-RefVideo.yuv' 'home/alexis/Desktop/raw-DistVideo.yuv' >> /home/alexis/Desktop/output_codec_resolution_fps-bitrate.txt`

Can you explain me why I always have the same result even if the video is different?

Thank you by advance,
Best regards,
Alexis

Here are the following outputs:
[output_x264_1080p60-4Mbps.txt](https://github.com/Netflix/vmaf/files/1980451/output_x264_1080p60-4Mbps.txt)
[output_x264_1080p60-7Mbps.txt](https://github.com/Netflix/vmaf/files/1980452/output_x264_1080p60-7Mbps.txt)
[output_x264_1080p60-9Mbps.txt](https://github.com/Netflix/vmaf/files/1980453/output_x264_1080p60-9Mbps.txt)
[output_x264_1080p60-14Mbps.txt](https://github.com/Netflix/vmaf/files/1980454/output_x264_1080p60-14Mbps.txt)
[output_x264_1080p60-19Mbps.txt](https://github.com/Netflix/vmaf/files/1980455/output_x264_1080p60-19Mbps.txt)
[output_x265_1080p60-7Mbps.txt](https://github.com/Netflix/vmaf/files/1980456/output_x265_1080p60-7Mbps.txt)
[output_x265_1080p60-9Mbps.txt](https://github.com/Netflix/vmaf/files/1980457/output_x265_1080p60-9Mbps.txt)
[output_x265_1080p60-14Mbps.txt](https://github.com/Netflix/vmaf/files/1980458/output_x265_1080p60-14Mbps.txt)
[output_x265_1080p60-19Mbps.txt](https://github.com/Netflix/vmaf/files/1980459/output_x265_1080p60-19Mbps.txt)
[output_x264_1080p60-0.5Mbps.txt](https://github.com/Netflix/vmaf/files/1980460/output_x264_1080p60-0.5Mbps.txt)
[output_x264_1080p60-0.8Mbps.txt](https://github.com/Netflix/vmaf/files/1980461/output_x264_1080p60-0.8Mbps.txt)
[output_x264_1080p60-1Mbps.txt](https://github.com/Netflix/vmaf/files/1980462/output_x264_1080p60-1Mbps.txt)
[output_x264_1080p60-2Mbps.txt](https://github.com/Netflix/vmaf/files/1980463/output_x264_1080p60-2Mbps.txt)
[output_x264_1080p60-3Mbps.txt](https://github.com/Netflix/vmaf/files/1980464/output_x264_1080p60-3Mbps.txt)

**Comment by li-zhi** [comment]
It's a bit hard to figure out what's going on. It seems like all the files are having close but not identical numerical results. I assume the 19Mbps one has high bitrate and should have VMAF close to 100, but you are getting a very low number. I suspect there is something wrong with the preprocessing, e.g. frame misalignment.

One way to try is before running ./run_vmaf, try ./run_psnr with the same setting to see if the PSNR numbers make sense.

**Comment by Asusio** [comment]
Thank you for your answer.
First I did a mistake in my command, the resolution for the reference video is 4000*2250 so the result are differents but the problem is still the same.
I have tried with ./run_psnr and the same command but the result is approximately the same as VMAF.

Here are the result for 0.5Mbit/s and 19 Mbit/s with both command
`./run_vmaf yuv420p 4000 2250 'home/alexis/Desktop/raw-RefVideo.yuv' 'home/alexis/Desktop/raw-DistVideo.yuv' >> /home/alexis/Desktop/output_codec_resolution_fps-bitrate.txt`
`./run_psnr yuv420p 4000 2250 'home/alexis/Desktop/raw-RefVideo.yuv' 'home/alexis/Desktop/raw-DistVideo.yuv' >> /home/alexis/Desktop/output_codec_resolution_fps-bitrate.txt`

[output_x264_1080p60-0.5.txt](https://github.com/Netflix/vmaf/files/1982780/output_x264_1080p60-0.5.txt)
[output_x264_1080p60-19.txt](https://github.com/Netflix/vmaf/files/1982781/output_x264_1080p60-19.txt)

**Comment by li-zhi** [comment]
If run_psnr still give you similar result then I think the issue is somewhere else rather than VMAF. Could you post your run_psnr result?

**Comment by Asusio** [comment]
It's in the same file
(I'll delete the VMAF)

[output_x264_1080p60-0.5.txt](https://github.com/Netflix/vmaf/files/1984075/output_x264_1080p60-0.5.txt)
[output_x264_1080p60-19.txt](https://github.com/Netflix/vmaf/files/1984076/output_x264_1080p60-19.txt)

**Comment by li-zhi** [comment]
PSNR of 10 means the source and distorted videos are out of sync. You may want to debug your decoding pipeline.

**Comment by Asusio** [comment]
Ok thank you, when I'm using the 1080p60 at 19Mbps as a reference and distorted video I have ~99 with VMAF.
So the problem comes from my reference video.

**Comment by Asusio** [comment]
Ok thank you, when I'm using the 1080p60 at 19Mbps as a reference and distorted video I have ~99 with VMAF.
So the problem comes from my reference video.
