### ISSUE TITLE
macOS dependencies no longer valid

### ISSUE THREAD

**Issue by maxlazarov** [Netflix/vmaf#161]
As of this March, Homebrew's `python` package installs Python 3, so the instructions in [the readme](../blob/master/README.md#macos) are no longer valid. Relevant Homebrew post: https://brew.sh/2018/01/19/homebrew-1.5.0/

**Comment by slhck** [comment]
I have to check, but does VMAF not work with Python 3?

One could also update the instructions to use the latest Python 2.7 shipped by Homebrew, but that does not seem like a good long-term solution.

**Comment by slhck** [comment]
@li-zhi you may assign this issue to me; I'll work on updating the instructions.

**Comment by li-zhi** [comment]
@slhck Please go ahead. Thanks for the help!
