### ISSUE TITLE
AssertionError!

### ISSUE THREAD

**Issue by ffleader1** [Netflix/vmaf#163]
I tried to run ./run_vmaf but it gave me this error. Please help.

![image](https://user-images.githubusercontent.com/15016720/39964965-1de351c6-56ba-11e8-9c9c-8adf0e50811d.png)

**Comment by ffleader1** [comment]
It seems that the high resolution caused the problem. My vid was 3840x2160. Dropped a 1080p video in and it runs fine.

**Comment by DonTequila** [comment]
@li-zhi In a separate fork I had added ffmpeg support to the C code of vmafossexec wrapper by using popen. It's only supported on Linux, though. Is this still interesting for the public repo?

**Comment by li-zhi** [comment]
@DonTequila for the ffmpeg support we have both the `ffmpeg2vmaf` tool and `libvmaf` as a filter for ffmpeg. I think that's enough. I'll soon port your multithread support to other tools as well.
