### ISSUE TITLE
Question: citations

### ISSUE THREAD

**Issue by Enchufa2** [Netflix/vmaf#173]
Is there any preferred reference to cite VMAF in research articles?

**Comment by li-zhi** [comment]
I am working on a revamp of the documentation. Stay tuned. In the mean time, the tech blog post is the preferred reference: https://medium.com/netflix-techblog/toward-a-practical-perceptual-video-quality-metric-653f208b9652

**Comment by li-zhi** [comment]
I've added a references page to a list of VMAF-related blogs/papers/presentations at:
https://github.com/Netflix/vmaf/blob/master/resource/doc/references.md

**Comment by christosbampis** [comment]
For your information the references section has also been updated, including the latest VMAF techblog here: https://medium.com/netflix-techblog/vmaf-the-journey-continues-44b51ee9ed12.

**Comment by Enchufa2** [comment]
FYI, we used this metric in the following work: https://doi.org/10.1109/TMC.2018.2876000. And it was a great improvement over the SSIM index. :)
