### ISSUE TITLE
Inconsistency in the PSNR and VMAF calculation with vmafossexec wrapper

### ISSUE THREAD

**Issue by stoyanovgeorge** [Netflix/vmaf#174]
I have compiled today VMAF from source and run the PSNR, SSIM, MS-SSIM and VMAF measurements 
 against two yuv files. 
The command I am using is the following: 
```
./vmafossexec yuv420p 1280 720 reference.yuv distorted.yuv ../model/vmaf_v0.6.1.pkl --log ~/vmaf_yuv.json --log-fmt json --psnr --ssim --ms-ssim
```
And my output is: 
```
Exec FPS: 29.430188
VMAF score = 92.506758
```

I have also calculated the average of all the parameters using a simple python script and the average values are as follows: 
```
ADM2: 0.9872
Motion2: 0.0398
VIF Scale0: 0.6674
VIF Scale1: 0.9512
VIF Scale2: 0.9756
VIF Scale3: 0.9849
VMAF: 92.5068
PSNR: 40.4673dB
SSIM: 0.993
MS-SSIM: 0.9927
```
I have run the same command but this time using the same files this times packed in a nut container and but they are also in rawvideo and when performed the vmafossexec on the .nut files my output is: 
```
Exec FPS: 29.882048
VMAF score = 99.378772
```
and my averages are: 
```
ADM2: 0.99
Motion2: 12.0651
VIF Scale0: 0.6955
VIF Scale1: 0.9564
VIF Scale2: 0.9785
VIF Scale3: 0.9873
VMAF: 99.3788
PSNR: 41.621dB
SSIM: 0.9937
MS-SSIM: 0.9935
```
So this is quite of a difference. On top of that the motion2 score while using yuv is 0.0398, which doesn't make sense, the video sequences are quite dynamic and I am expecting this value to be higher than 10, as stated in the README.md file. If I run PSNR evaluation of these files using ffmpeg 4.0 for the nut and the yuv both PSNRs are the same, which should be exactly the case since they are both in raw video. You can also see that the PSNR average calculated by ffmpeg is 1-2dB lower compared to the PSNR calculated by vmafossexec.  
```
YUV FFMPEG - [Parsed_psnr_0 @ 0x5566f7234dc0] PSNR y:38.657160 u:45.210472 v:43.918902 average:39.888372 min:21.705079 max:50.428166
NUT FFMPEG - [Parsed_psnr_0 @ 0x555c1d2901c0] PSNR y:38.657160 u:45.210472 v:43.918902 average:39.888372 min:21.705079 max:50.428166
```
I have uploaded the log files, please note that those coming from VMAF are actually json files, but I have renamed them in order to be able to upload them here. 
The ffmpeg command I am using for calculating the PSNR are: 
`ffmpeg -i distorted.nut -i reference.nut -lavfi psnr=ffmpeg_nut.log -f null -`
`ffmpeg -s 1280x720 -i distorted.yuv -s 1280x720 -i reference.yuv -lavfi psnr=ffmpeg_yuv.log -f null -
`
[ffmpeg_nut.log](https://github.com/Netflix/vmaf/files/2115342/ffmpeg_nut.log)
[ffmpeg_yuv.log](https://github.com/Netflix/vmaf/files/2115343/ffmpeg_yuv.log)
[vmaf_yuv.log](https://github.com/Netflix/vmaf/files/2115348/vmaf_yuv.log)
[vmaf_nut.log](https://github.com/Netflix/vmaf/files/2115350/vmaf_nut.log)

I am also wondering why in VDK 1.3.5 the VMAF was version 0.6.3 and in VDK 1.3.6 it is 0.6.1, is there a reason why this is like this? I have also tried to use ffmpeg 4.0 for calculating the VMAF but it crashes with unknown format and segfault error, even though I have compiled ffmpeg with libvmaf support. I was tipped off that this is because you have changed the API syntax and I should revert back to 1.3.4. I can provide the log files or open another issue if you want regarding this problem.

**Comment by li-zhi** [comment]
Hi, 
`vmafossexec` only takes raw YUV without container header. So you can't input the NUT files to `vmafossexec`. However, there is a tool at the root called `ffmpeg2vmaf` that can take the NUT file as input. The motion2 number looks suspicious and need some further digging. PSNR needs some further digging too. Try the `run_psnr` tool under the root, which takes the raw YUV file.

Re the VMAF version: since the package has been growing and there were confusion on what this VMAF number should be in the VERSION file, it is decided to stick to the convention that this VMAF version should only be related to the version of the default model for the `VmafQualityRunner`. Whenever there is a numerical change to the VMAF result, this number is going to be updated. For anything else, we are going to use the VDK version number. For `libvmaf`, whenever there is an interface change, the version number at https://github.com/Netflix/vmaf/blob/master/wrapper/libvmaf.pc is going to be updated to the latest VDK number.

**Comment by stoyanovgeorge** [comment]
Yesterday I have also tried to calculate the result with `ffmpeg2vmaf` and the result was the same for both the .nut and .yuv file, but the calculation took considerably more time, since it the ffmpeg doesn't use all cores. The motion2 score is still very low though 0.0464 . 

ffmpeg2vmaf results for NUT file: 
```
ADM2: 0.9828
Motion2: 0.0464
VIF Scale0: 0.6618
VIF Scale1: 0.9437
VIF Scale2: 0.9708
VIF Scale3: 0.9815
VMAF: 91.0795
```

vmafossexec results for the YUV file: 
```
ADM2: 0.9828
Motion2: 0.0464
VIF Scale0: 0.6618
VIF Scale1: 0.9437
VIF Scale2: 0.9708
VIF Scale3: 0.9815
VMAF: 91.0795
PSNR: 40.7593dB
SSIM: 0.9919
MS-SSIM: 0.9919
```
I have run the `run_psnr` as you have suggested and my results are:
NUT file PSNR:
```
"aggregate": {
        "PSNR_score": 41.62100803647153,
        "method": "mean"
    }
```
 YUV file PSNR
```
    "aggregate": {
        "PSNR_score": 40.4673438657821,
        "method": "mean"
    }
```
so it appears it is a problem of the PSNR evaluation script, but this problem seems to affect also the SSIM and MS-SSIM calculations to a lesser extent since there the difference is not that big. I can provide the json log files if you want. 

It would also be great if you can implement log definition for your other tools like `ffmpeg2vmaf` and `./run_vmaf` and `./run_psnr`.

**Comment by stoyanovgeorge** [comment]
I have just noticed that right now I am also unable to compile ffmpeg both 4.0 and the most recent git head with libvmaf support. I am getting the following error: 
```
libavfilter/vf_libvmaf.c: In function ‘compute_vmaf_score’:
libavfilter/vf_libvmaf.c:165:16: error: too few arguments to function ‘compute_vmaf’
     s->error = compute_vmaf(&s->vmaf_score, format, s->width, s->height,
                ^
In file included from libavfilter/vf_libvmaf.c:28:0:
/usr/local/include/libvmaf.h:26:5: note: declared here
 int compute_vmaf(double* vmaf_score, char* fmt, int width, int height, int (*read_frame)(float *ref_data, float *main_data, float *temp_data, int stride_byte, void *user_data),
     ^
ffbuild/common.mak:60: recipe for target 'libavfilter/vf_libvmaf.o' failed
make: *** [libavfilter/vf_libvmaf.o] Error 1
```
And this happened after I have updated VMAF from VDK 1.35 to 1.3.6 yesterday.

**Comment by stoyanovgeorge** [comment]
I have just downgraded the VMAF version to VDK 1.3.4 and now I am able to compile ffmpeg both v.4 and the latest nightly with libvmaf support and it outputs the same result for both the nut and yuv files. which is exactly the same result if I am using ./vmafossexec on yuv files. So I presume ffmpeg is not compatible from VDK v.1.3.5 onwards.

**Comment by GyanD** [comment]
Yes, compute_vmaf ( ) was changed and the ffmpeg filter hasn't been updated.

**Comment by stoyanovgeorge** [comment]
So I have made an experiment and VDK 1.3.5 is causing segmentation fault on both ffmpeg v.4.0 and the latest nightly while 1.3.6 and probably 1.3.7 is preventing compilation of ffmpeg with VMAF support both v.4.0 and latest nightly.

**Comment by li-zhi** [comment]
From what have been reported, the set below seems to be the right result:

ADM2: 0.9828
Motion2: 0.0464
VIF Scale0: 0.6618
VIF Scale1: 0.9437
VIF Scale2: 0.9708
VIF Scale3: 0.9815
VMAF: 91.0795
PSNR: 40.7593dB
SSIM: 0.9919
MS-SSIM: 0.9919

**Comment by stoyanovgeorge** [comment]
@li-zhi yes, but the motion vector score seems to be incorrect and then why the PSNR and SSIM calculated by ffmpeg are lower? Isn't it supposed to report the same results? This is also creating inconsistency with ffmpeg, since if you are using the libvmaf to calculate the PSNR and SSIM the results are different compared to when you are using the dedicated PSNR and SSIM filters in ffmpeg.

**Comment by li-zhi** [comment]
@stoyanovgeorge the `vmafossexec`, `run_vmaf` and `run_psnr` only take in raw YUV videos, which is not the NUT format. Not sure about the motion score unless the video is available for testing.

**Comment by stoyanovgeorge** [comment]
@li-zhi I understood that but 
1. The PSNR and SSIM scores when analyzing YUV content are higher compared to the PSNR and SSIM scores of the same YUV files analyzed with FFMPEG. 
2. the libvmaf support for ffmpeg is broken from VDK 1.3.5 onwards, 1.3.5 you are able to compile ffmpeg with libvmaf support but when trying to use it it gives a segmentation fault and ffmpeg doesn't compile with VDK 1.3.6 and 1.3.7, according to the ffmpeg developers this is because you have changed the API and potentially the ABI in 1.3.5.

**Comment by li-zhi** [comment]
@stoyanovgeorge on 1.:
I tried two commands:
```
./run_psnr yuv420p 576 324 python/test/resource/yuv/src01_hrc00_576x324.yuv python/test/resource/yuv/src01_hrc01_576x324.yuv
ffmpeg -f rawvideo -pix_fmt yuv420p -s 576x324 -i python/test/resource/yuv/src01_hrc00_576x324.yuv -f rawvideo -pix_fmt yuv420p -s 576x324 -i python/test/resource/yuv/src01_hrc01_576x324.yuv -lavfi psnr=ffmpeg_yuv.log -f null -
```
They do give different results for Y-PSNR: 30.755064 vs. 30.66. My speculation is that this is to do with how the per-frame PSNR values get aggregated into the final value. In `run_psnr`, the per-frame PSNR value is calculated, and their mean value is reported. In some alternative implementation (I am not sure if it is the case for `ffmpeg`), the per-frame MSE is calculated, and their mean is then calculated, and finally the mean MSE is converted to the final PSNR. One needs to verify how `ffmpeg` does it.

**Comment by cosmin** [comment]
FYI @stoyanovgeorge as of 8/7 the latest ffmpeg snapshot can be compiled against the latest libvmaf release, and it works great.

**Comment by Ilya87** [comment]
The problem is still here:
resent master ffmpeg ssim (the last frame of sequence from log file):
Y:0.985924 U:0.991896 V:0.990721 All:0.987719 (19.107536)
the latest master VMAF vmafossexec (the last frame of sequence from log file):
<frame frameNum="1190" adm2="0.981982" motion2="1.37553" ssim="0.985279" vif_scale0="0.721532" vif_scale1="0.971456" vif_scale2="0.98693" vif_scale3="0.992511" vmaf="94.0413" />

There is no 0.985279 value in ffmpeg measurements.

**Comment by richardpl** [comment]
FFmpeg ssim is different from libvmaf ssim.

**Comment by li-zhi** [comment]
@richardpl Please see [here](https://github.com/Netflix/vmaf/blob/master/FAQ.md#q-why-the-included-ssim-tool-produces-numerical-results-off-compared-to-other-tools) for explanation.

**Comment by richardpl** [comment]
@li-zhi I know that, and I do not consider that vmaf or ffmpeg bug.
