### ISSUE TITLE
Invalid type when compiling FFMPEG using VMAF header

### ISSUE THREAD

**Issue by kparkins** [Netflix/vmaf#178]
vmaf/wrapper/src/libvmaf.h

#ifdef __cplusplus
extern "C" {
#endif

int compute_vmaf(double* vmaf_score, char* fmt, int width, int height, int (*read_frame)(float *ref_data, float *main_data, float *temp_data, int stride_byte, void *user_data),void *user_data, char *model_path, char *log_path, char *log_fmt, int disable_clip, int disable_avx, int enable_transform, int phone_model, int do_psnr,int do_ssim, int do_ms_ssim, char *pool_method, int n_thread, int n_subsample, **bool conf_interval**);

#ifdef __cplusplus
}
#endif

When configuring FFMpeg with libvmaf an error is generated when config checks the VMAF header file. 

END /var/folders/55/w2y0k2k52v3dz88ls2lml57h0000gp/T//ffconf.GMcvFrhD/test.c
gcc -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I$(SRC_PATH)/compat/dispatch_semaphore -DPIC -std=c11 -Werror=partial-availability -fomit-frame-pointer -fPIC -pthread -I/usr/local/include -L/usr/local/lib -c -o /var/folders/55/w2y0k2k52v3dz88ls2lml57h0000gp/T//ffconf.GMcvFrhD/test.o /var/folders/55/w2y0k2k52v3dz88ls2lml57h0000gp/T//ffconf.GMcvFrhD/test.c
clang: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]
In file included from /var/folders/55/w2y0k2k52v3dz88ls2lml57h0000gp/T//ffconf.GMcvFrhD/test.c:1:
**/usr/local/include/libvmaf.h:26:408: error: unknown type name 'bool'**
int compute_vmaf(double* vmaf_score, char* fmt, int width, int height, int (*read_frame)(float *ref_data, float *main_data, float *temp_data, int stride_byte, void *user_data),void *user_data, char *model_path, char *log_path, char *log_fmt, int disable_clip, int disable_avx, int enable_transform, int phone_model, int do_psnr,int do_ssim, int do_ms_ssim, char *pool_method, int n_thread, int n_subsample, bool conf_interval);
                                                                                                                                                                                           ^
1 error generated.

bool is not a builtin type in C. the last parameter in "compute_vmaf" is of type bool. 
This was introduced here: 1b0f6efb832b0575ca1a852aa3cb29330f43ae97

**Comment by kparkins** [comment]
This is probably not really in scope for this repo however, VMAF > 1.3.4 still does not compile with FFmpeg even with the proposed fixes. This is due to the fact that extra parameters were added to the compute_vmaf function and the arguments have not been added to the corresponding files in libavfilter within FFmpeg. 

int compute_vmaf(double* vmaf_score, char* fmt, int width, int height, int (*read_frame)(float *ref_data, float *main_data, float *temp_data, int stride_byte, void *user_data),void *user_data, char *model_path, char *log_path, char *log_fmt, int disable_clip, int disable_avx, int enable_transform, int phone_model, int do_psnr,int do_ssim, int do_ms_ssim, char *pool_method, **int n_thread, int n_subsample, bool conf_interval)**

https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/vf_libvmaf.c line 168. Also, the context doesn't have the extra parameters. Just a heads up.

**Comment by li-zhi** [comment]
Understood. This requires the effort from the ffmpeg side to update the code. 

@rbultje could you help pass the message?

**Comment by rbultje** [comment]
Already known: http://trac.ffmpeg.org/ticket/7264
