### ISSUE TITLE
Library link issue: wrong  read_frame() was called when run in ffmpeg

### ISSUE THREAD

**Issue by ray-x** [Netflix/vmaf#185]
There are a few read_frame() functions
one provided by common/frame.c
int read_frame(float *ref_data, float *dis_data, float *temp_data, int stride_byte, void *s)

Also, in combo_threadfunc, it should use the read_frame provided by ffmpeg read_frame_10bit or read_frame_8bit

The trick thing is in 
combo.c:177   ret = read_frame(ref_buf, dis_buf, temp_buf, stride, user_data);
It should call ffmpeg read_frame_10bit() or read_frame_8bit() passed in with function pointer. But in master version it will call read_frame() from frame.c
this could be fixed by write 
ret = (thread_data->read_frame)(ref_buf, dis_buf, temp_buf, stride, user_data);
So it is with line 233:
ret = (thread_data->read_frame)(next_ref_buf, next_dis_buf, temp_buf, stride, user_data);

**Comment by kylophone** [comment]
Should be fixed in v1.3.9. Thanks for the report!

**Comment by kylophone** [comment]
see also: http://ffmpeg.org/pipermail/ffmpeg-devel/2018-August/233012.html
