### ISSUE TITLE
ffmpeg(master) arguments do not match libvmaf compute_vmaf()

### ISSUE THREAD

**Issue by ray-x** [Netflix/vmaf#186]
There is a tick in ffmpeg
https://trac.ffmpeg.org/ticket/7248

But giving that vmaf is actively working on new features. It maybe better to add default values in the compute_vmaf arguments list (especially for the new arguments).
ffmpeg master:
    s->error = compute_vmaf(&s->vmaf_score, format, s->width, s->height,
                            read_frame, s, s->model_path, s->log_path,
                            s->log_fmt, 0, 0, s->enable_transform,
                            s->phone_model, s->psnr, s->ssim,
                            s->ms_ssim, s->pool);
compute_vmaf in libvmaf.h
int compute_vmaf(double* vmaf_score, char* fmt, int width, int height, int (*read_frame)(float *ref_data, float *main_data, float *temp_data, int stride_byte, void *user_data),
				 void *user_data, char *model_path, char *log_path, char *log_fmt, int disable_clip, int disable_avx, int enable_transform, int phone_model, int do_psnr,
				 int do_ssim, int do_ms_ssim, char *pool_method, _int n_thread, int n_subsample, int enable_conf_interval_);

The italic part is recently added arguments.

**Comment by kylophone** [comment]
http://ffmpeg.org/pipermail/ffmpeg-devel/2018-August/233012.html
