### ISSUE TITLE
Installation on Ubuntu is not successful,after entering Geographic area as US nothig is happening

### ISSUE THREAD

**Issue by MSucharitha** [Netflix/vmaf#199]
Please help me in installation.

**Comment by ChanceLeachman** [comment]
Hi, I've found the Dockerfile not working too. My workaround was to add this above where python-tk is installed:

ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

You can replace Los_Angeles with your time zone.

**Comment by ChanceLeachman** [comment]
Additionally, I found that I needed to replace RUN cd dir commands with WORKDIR dir.

**Comment by li-zhi** [comment]
@ChanceLeachman would you like to submit a fix?

**Comment by ChanceLeachman** [comment]
Sure! Will try to submit a pull request later today.

**Comment by cosmin** [comment]
This appears to be fixed in latest master, and the issue can probably be closed.
