### ISSUE TITLE
Is there any option to log the vmaf score of every individual frame ?

### ISSUE THREAD

**Issue by svijay05** [Netflix/vmaf#203]

**Comment by christosbampis** [comment]
I believe that the per-frame scores can be found in the xml/json output if you follow this link: https://github.com/Netflix/vmaf/blob/master/resource/doc/VMAF_Python_library.md (search for basic usage)

**Comment by christosbampis** [comment]
Are you looking for an output containing only per-frame VMAF scores? Because in the attached json file, there are the per-frame key value pairs for VMAF predictions, so you can easily extract those from this JSON file.

**Comment by svijay05** [comment]
3 min test video with 30 frames per second has ~5400 frames, but the generated output includes only the score of the first 13 frames. That's what I meant.

**Comment by christosbampis** [comment]
It seems to me that the number of frames is not correct. What is the command that you are using to generate this json file?

**Comment by christosbampis** [comment]
This command line seems ok to me, can you confirm that the input videos are YUV420p and 1920x1080?

**Comment by svijay05** [comment]
Thanks for your time  @christosbampis, VMAF works perfectly, was an issue with the  YUV encoding.

**Comment by zhuxiaol** [comment]
Why my VMAF_score is 0?

{rame: 0/0
    "executorId": "VMAF_VF0.2.4c-0.6.1",
    "asset": {
        "identifier": "cmd_9658997764371198_9658997764371198_13_real_teapot_376x224_376x224_vs_13_arcore_teapot_376x224_q_376x224"
    },
    "frames": [
        {
            "frameNum": 0,
            "VMAF_feature_adm2_score": 0.541459791730362,
            "VMAF_feature_motion2_score": 0.0,
            "VMAF_feature_vif_scale0_score": 0.16038680879058081,
            "VMAF_feature_vif_scale1_score": 0.28488235071996626,
            "VMAF_feature_vif_scale2_score": 0.3145256747290411,
            "VMAF_feature_vif_scale3_score": 0.33458374222480275,
            "VMAF_score": 0.0
        }
    ],
    "aggregate": {
        "VMAF_feature_adm2_score": 0.541459791730362,
        "VMAF_feature_motion2_score": 0.0,
        "VMAF_feature_vif_scale0_score": 0.16038680879058081,
        "VMAF_feature_vif_scale1_score": 0.28488235071996626,
        "VMAF_feature_vif_scale2_score": 0.3145256747290411,
        "VMAF_feature_vif_scale3_score": 0.33458374222480275,
        "VMAF_score": 0.0,
        "method": "mean"
    }
}
