### ISSUE TITLE
AQ in x264 hurts VMAF score

### ISSUE THREAD

**Issue by rbultje** [Netflix/vmaf#21]
I encoded all "4K" clips (provided by netflix) from xiph (http://media.xiph.org/video/derf/) after converting them to 360p 8bit 30fps. I used default 1-pass CRF settings at --preset=veryslow and the following additional settings:

[nothing]
--tune=psnr
--aq-mode=0
--no-psy
--psy-rd=0.0
--aq-mode=0 --no-psy

Then I scored the VMAF score and used a slightly modified version of Google's visual-metrics.py tool to calculate bitrate improvement (https://chromium.googlesource.com/webm/contributor-guide/+/master/scripts/).

The interesting thing in the results was that --tune=psnr _improved_ the VMAF score by about 5%. That shouldn't happen. --tune=psnr basically does two things: it sets --no-psy (which is nearly identical to --psy-rd=0.0, i.e. it tunes energy retention in the rate distortion loop) and it disables adaptive quant (--aq-mode=0). Results for --aq-mode=0 --no-psy and --tune=psnr are identical, which demonstrates this point. Additionally, results for --psy-rd=0.0 and --no-psy are nearly identical.

When looking at the results for only --no-psy/--psy-rd=0.0 or --aq-mode=0, I see very big differences, though. --aq-mode=0 _increases_ VMAF score by about 9% (bitrate improvement), whereas --no-psy/--psy-rd=0.0 _decrease_ VMAF score by about 9%. In other words, AQ hurts VMAF but psy-rd helps VMAF. This is strange. AQ is supposed to help visual quality, right?

Image with results from libvpx' contributors-guide script (baseline is x264 --tune=psnr; "vis" means I didn't use --tune=psnr, i.e. visual tuning; aq0 means I used --aq-mode=0; nopsy means I used --no-psy; psyrd0 means I used --psy-rd=0.0):
<img width="1389" alt="screen shot 2016-09-08 at 3 54 12 pm" src="https://cloud.githubusercontent.com/assets/283893/18364500/8abf6e6c-75dc-11e6-879f-748147e283f6.png">

I've done (unrelated) experiments in my own VP9 encoder (http://www.twoorioles.com/eve-vp9-video-encoder) and have seen similar issues, where AQ (e.g. based on better quality for dark/low-contrast portions of frames) hurts VMAF scores by quite a bit, which I found surprising. I haven't done a lot of analysis on this issue yet and am planning to do more, but figured a bug report might be worth it, maybe you guys have more insight in this and can help me get started trying to address this. I've also done experiments where I used the same code to assign different baseline quantizers based on whole-frame dark/low-contrast scores, and that helped VMAF score as expected. This makes me wonder if certain settings (like contrast, motion, or other things) are per-frame instead of per-block/section values in VMAF, which would mean AQ based on these attributes doesn't increase VMAF score even though it improves visual quality (IMO). (I know, you probably want samples for this, I'll try to make something that's scientifically sound.)

**Comment by li-zhi** [comment]
Hi Ronald,

One thing I am wondering about is, what does the underlying VIF and ADM say when you turn on/off AQ mode? Essentially, VMAF is a meta-metric that aggregates the decisions made by these elementary metrics. If it is that one of the underlying metric says AQ mode doesn't help with quality, we could further dig into that metric.

But to offer another data point. I overheard that the AQ mode in x264 was based on the premise that AQ mode improves SSIM. But we internally tried SSIM on VMAF's training set, and it didn't perform well, and that's why SSIM hasn't been included as one of the elementary features for VMAF.

Zhi

**Comment by rbultje** [comment]
Hi Zhi,

I'll try to do the ADM/IVF individual metrics in my next response. But first, I'd like to address the more fundamental point of whether AQ should help. Let me try to do that scientifically.

I took the first frame of FoodMarket2 @ 360p (scaled with ffmpeg). Then I created a low-contrast version of this frame using the colorchannelmixer filter (ffmpeg -i ~/Movies/nflx360p/FoodMarket2.ffv1.mkv -vframes 1 -vf 'colorchannelmixer=rr=0.5:gg=0.5:bb=0.5' -pix_fmt yuv420p out.yuv). It's basically a dark version of the original frame at 50% contrast. Then, I encoded both frames (the 100% contrast and the 50% contrast, keyframe only since it's one frame) using my encoder at quantizer in the range of 0-250 with a stepsize of 10 and measured the VMAF score against the 50% or 100% original, respectively.

Then, I created two experiments. In the first, I would average (since at this point, that's what "Aggregate" would do for a 2-frame sequence, right?) the VMAF score of one 100% contrast frame and one 50% contrast frame at quantizer Q for the 100% frame, and quantizer Q+offset for the 50% frame, where offset is in the range of -40 to 40 with a stepsize of 10. I also added the respective IVF file sizes. Then I plotted the resulting filesize vs. VMAF graph, which basically allows me to see which offset results in the best cumulative VMAF score.

The plot looks like this:

![2frames](https://cloud.githubusercontent.com/assets/283893/18957352/b694ebe2-862c-11e6-8507-f428c8a2e806.png)

Then, I used ffmpeg to create a side-by-side compilation of the two output files and measured the VMAF score for that side-by-side compilation of the 100% and 50% contrast frames. Doing otherwise the same experiment as above, I see this:

![sidebyside](https://cloud.githubusercontent.com/assets/283893/18957417/f7310bcc-862c-11e6-8a6e-4a9797c91279.png)

The interesting thing here is that if you do the 2-frame experiment, the ideal delta quantizer index appears to be around -30, i.e. the 50% contrast frame should have a lower quantizer than the 100% contrast frame to get the optimal VMAF score per file size, i.e. the 50% contrast frame should have higher quality, which matches my expectation. However, in the side-by-side experiment, the optimal delta quantizer index is essentially zero, i.e. it wants the 100% contrast frame half and the 50% contrast frame half to have the same quality. This does not match my expectation. It seems to me most other variables are the same. I hope this adds some evidence to the notion that VMAF does not appear to react to quality variations within a frame in the same way than it does to quality variations between frames. This might explain (partially?) why for some encoders (including x264, I believe also libvpx), configurations for AQ (or segmentation) that would be expected to help the perceptual experience do not improve the VMAF score.

If you think that this experiment is a somewhat scientific way of trying to disect this without getting into the question of whether the encoder is doing the right thing regarding AQ/segmentation setup, I'll try to repeat this experiment measuring the individual metrics (e.g. ADM, IVF) instead of the combined VMAF score.

Thanks for your comments, btw!

**Comment by rbultje** [comment]
I ran the same experiments using adm2 as a metric, and results are identical. Ivf0 gives the same result also, but it has to be said that the difference in ivf0 score between the different lines is much smaller than the difference between adm2 lines or vmaf lines for varying deltaq-index values.

**Comment by li-zhi** [comment]
Hi Ronald,

Your methodology sounds reasonable to me. I would like to spend some time to reproduce your results and exploring a few variations, such as whether the same observation holds across different pooling mechanisms, video contents and codecs. I'll let you know how things turn out to be.

**Comment by rbultje** [comment]
Hi Zhi, that sounds reasonable, thanks.

**Comment by li-zhi** [comment]
Hi Ronald,

I have a theory that might explain the difference you saw between the 2-frame and side-by-side setup. If it is convenient for you to do a quick test, would you mind trying again the experiments using the attached model files (you also need to pull the latest master. Also the command line interface run_vmaf etc. have changed a little bit)?
[nflxall_vmaftrying.zip](https://github.com/Netflix/vmaf/files/505053/nflxall_vmaftrying.zip)

**Comment by rbultje** [comment]
Hi Zhi, I just tried testing your model, and I think I'm doing something wrong. Here's what I get with the 1.1.6 release:

```
bash-4.3$ wrapper/vmafossexec yuv420p 640 360 /tmp/ref.yuv /tmp/dis.yuv resource/model/nflxall_vmafv4.pkl
Start calculating VMAF score...
Exec FPS: 10.847892
VMAF score = 95.539375
```

And here's what I get with your model:

```
bash-4.3$ wrapper/vmafossexec yuv420p 640 360 /tmp/ref.yuv /tmp/dis.yuv ~/Downloads/nflxall_vmaftrying.pkl
Start calculating VMAF score...
Unknown feature name: 'VMAF_feature_adm3_score'.
Error: Unknown feature name
Usage: wrapper/vmafossexec fmt width height ref_path dis_path model_path [--log log_path] [--log-fmt log_fmt] [--disable-clip] [--psnr] [--ssim] [--ms-ssim]
fmt:
	yuv420p
	yuv422p
	yuv444p
	yuv420p10le
	yuv422p10le
	yuv444p10le

log_fmt:
	xml (default)
	json
```

This is git hash d13611cd859ba267ca0e6f36cb19e55483fc04b2. What should I do to use your model?

Thanks,
Ronald

**Comment by rbultje** [comment]
Hi Zhi,

OK, I quickly tested your modified model, and it looks like the results didn't really change very much to what they were before, i.e. I'm still seeing the issue where side-by-side gives an optimal delta-qidx of near-zero, whereas the 2-frame version gives an optimal delta-qidx of -30 or so. I can provide graphs if that helps.

Thanks,
Ronald

**Comment by li-zhi** [comment]
Hi Ronald,

The fixes in the new release wasn't meant to address this issue. I was
overloaded by other things over the past two weeks. And I promise to start
investigating this once I have time.

Best,
Zhi
