### ISSUE TITLE
Incorrect PSNR (and so it is vmaf ) values in yuv422p10le format

### ISSUE THREAD

**Issue by ray-x** [Netflix/vmaf#211]
It was run in ffmpeg (master build)
Commands: 
ffmpeg  -f rawvideo  -pix_fmt yuv422p10le  -video_size 1920x1080 -i video1.yuv  -f rawvideo  -pix_fmt yuv422p10le  -video_size 1920x1080   -I video2.yuv   -lavfi libvmaf="psnr=1:log_fmt="json":log_path=comp.json" -vframes 1 -y -f null -

The psnr value is 18.0 which is very bad. But if run in ffmpeg directly with 
ffmpeg  -f rawvideo  -pix_fmt yuv422p10le  -video_size 1920x1080 -i video1.yuv  -f rawvideo  -pix_fmt yuv422p10le  -video_size 1920x1080   -I video2.yuv   -lavfi  psnr -vframes 1 -y -f null -
The psnr value is 30.5

I found that in vf_libvmaf.c ,  function  read_frame_##bits##bit (aka.  read_frame_10bit)   is reading and storing 10 bits data and did not truncate to 8bits. When the  frame data passed down to psnr.c/psnr_tools.c. function psnr_constants is always assume that data is 8bit (peak 255 instead of 1023)

It is true that libvmaf readframe will convert 10bit to 8bit. But vf_libvmaf did not do that. 
I am wondering
1) Who should change the codes, vmaf or ffmepg
2) More importantly, can VMAF handle 10bit data in its model and give correct result? I am currently working on videos mostly of 8bit and 10bit. Truncate both to 8bit and compare the video quality seems to be unfair for 10bit video.

**Comment by anotherdirtbag** [comment]
this is months old, but I'll report what seems like a related issue. Using a version of vmaf and ffmpeg that are only 2 days old.
from a source h264 yuv420p video i ran 
`ffmpeg -i input.mkv -map 0:v -c:v libx265 -preset fast -pix_fmt yuv420p10le -crf 21 output_10bit.mp4`
then 
`ffmpeg -i output_10bit.mp4 -i input.mkv -lavfi libvmaf="pool=harmonic mean:n_threads=11" -f null -`
which returns a VMAF score of 81.
then I ran
```
ffmpeg -i output_10bit.mp4 -map 0:v -c:v libx265 -preset ultrafast -pix_fmt yuv420p -crf 0 output_8bit.mp4
ffmpeg -i output_8bit.mp4 -i input.mkv -lavfi libvmaf="pool=harmonic mean:n_threads=11" -f null -
```
which returns a VMAF score of 92.
additionally, if I create output_8bit.mp4 using crf 21 directly from the source video, I get a VMAF of 91.2.

**Comment by richardpl** [comment]
This was bug in libvmaf filter in FFmpeg and have been fixed in master.

**Comment by kylophone** [comment]
> This was bug in libvmaf filter in FFmpeg and have been fixed in master.

Thank you.
