### ISSUE TITLE
vmaf json output has nan in value field

### ISSUE THREAD

**Issue by ray-x** [Netflix/vmaf#215]
From http://json.org
NaN is not valid json value.  "A value can be a string in double quotes, or a number, or true or false or null, or an object or an array. These structures can be nested."
But my vmaf output has following key/value:
    {
      "frameNum":49,
      "metrics":{
        "adm2":0.88962,
        "motion2":24.67111,
        "psnr":25.72294,
        "ssim":0.75942,
        "vif_scale0":0.19775,
        "vif_scale1":0.33302,
        "vif_scale2":0.39012,
        "vif_scale3":nan,
        "vmaf":nan
      }
    }

I think we might use null instead of NaN in above case.

**Comment by li-zhi** [comment]
This is unexpected. Did you run `run_vmaf` or `vmafossexec`? The former one calls Python's native `json.dumps()` method. The latter one calls a third-party library called `ptools` to out JSON.

**Comment by ray-x** [comment]
It was run through command line/lavfi filter of ffmpeg:
ffmpeg -r 30  -ss 00:00:0.466667  -i "CQ_1080p30.mov" -ss 00:00:0.000000  -r 30 -i "CQ_1080p30.mp4" -lavfi libvmaf="psnr=1:ssim=1:log_fmt="json":log_path=CQ_1080p30.json" -y -f null -

**Comment by li-zhi** [comment]
ffmpeg with libvmaf uses the same code path as vmafossexec. The `ptools` library needs to be updated to resolve it. I am marking this issue as `help wanted`.

**Comment by arnisgustins** [comment]
Hi.
Not sure how relevant the "nan" issue is here, but I have found something similar.

```
{
  "version": "e14eeb7b",
  "frames": [
    {
      "frameNum": 0,
      "metrics": {
        "integer_adm2_egl_1": 0.999988,
        "integer_adm_scale0_egl_1": 1.000005,
        "integer_adm_scale1_egl_1": 0.999992,
        "integer_adm_scale2_egl_1": 0.999987,
        "integer_adm_scale3_egl_1": 0.999983,
        "integer_motion2_force_0": 0.000000,
        "integer_motion_force_0": 0.000000,
        "integer_vif_scale0_egl_1": 0.999997,
        "integer_vif_scale1_egl_1": 0.999997,
        "integer_vif_scale2_egl_1": 0.999998,
        "integer_vif_scale3_egl_1": 0.999998,
        "psnr_y": 60.000000,
        "psnr_cb": 49.978972,
        "psnr_cr": 48.494506,
        "psnr_hvs_y": inf,
        "psnr_hvs_cb": 45.972853,
        "psnr_hvs_cr": 43.848467,
        "psnr_hvs": 51.771740,
        "float_ssim": 1.000000,
        "vmaf": 97.425103
      }
```

Here you can see that PSNR_HVS returns "inf" value for "Y", which is not a valid JSON value.
The value itself is expected, but the JSON representation is invalid. I am not sure how to actually represent Infinity in JSON, maybe the range should be cropped just like with PSNR?

**Comment by kylophone** [comment]
Hmm, I wonder if we should use a string. `"psnr_hvs": "inf"`

**Comment by arnisgustins** [comment]
That would work for me. At least the output will be json parsable.

**Comment by slhck** [comment]
I think using a string is the best fallback option. It'd force people parsing this as a number to deal with the error that appears when you try to cast it.

**Comment by anilms** [comment]
One solution could be to use 'Infinity' instead of 'inf'
To reproduce this issue:
```
wget https://media.xiph.org/video/derf/y4m/akiyo_cif.y4m
./build/tools/vmaf -r akiyo_cif.y4m -d akiyo_cif.y4m --aom_ctc v1.0 -q --json -o out.json
```
out.json will have values like:
```
    "psnr_hvs": {
      "min": inf,
      "max": inf,
      "mean": inf,
      "harmonic_mean": inf
    },
```
This produces an error while using json.load()
Temporary hack by replacing inf with Infinity:
```
    "psnr_hvs": {
      "min": Infinity,
      "max": Infinity,
      "mean": Infinity,
      "harmonic_mean": Infinity
    },
```
This can be parsed by json.load()
Also, Infinity will be read by json parser as 'inf' in python.

**Comment by slhck** [comment]
While this would work — and actually seems to be [supported by most parsers](http://seriot.ch/json/parsing.html), at least not breaking them — it's also non-standard, and I'd propose not to use any non-standard extensions.
