### ISSUE TITLE
VMAF score of zero

### ISSUE THREAD

**Issue by RonLu** [Netflix/vmaf#217]
Hi,

I'm using ffmpeg with libvmaf to compute the vmaf score of transcoded video. But for some videos, I got a vmaf score of zero. I have checked the frames of the two videos, didn't find any significant difference. It's strange i always got a score of zero. Could you give some help on this? Thanks.

here is the vmaf json file:
[comp3.txt](https://github.com/Netflix/vmaf/files/2328032/comp3.txt)
(this psnr score looks ok, but all vmaf score of each frame is 0.0)

here is the ffmpeg log:
../utils/ffmpeg -i 1_144-1080.mp4 -i ref-3.mp4 -lavfi libvmaf="psnr=1:log_fmt="json":log_path=comp3.json" -f null -
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '1_144-1080.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 00:00:08.96, start: 0.000000, bitrate: 3610 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 3608 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'ref-3.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
  Duration: 00:00:08.96, start: 0.040000, bitrate: 5117 kb/s
    Stream #1:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 5116 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 (h264) -> libvmaf:main
  Stream #1:0 (h264) -> libvmaf:reference
  libvmaf -> Stream #0:0 (wrapped_avframe)
Press [q] to stop, [?] for help
Start calculating VMAF score...
Output #0, null, to 'pipe:':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
    Stream #0:0: Video: wrapped_avframe, yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc (default)
    Metadata:
      encoder         : Lavc58.18.100 wrapped_avframe
frame=  224 fps=2.9 q=-0.0 Lsize=N/A time=00:00:08.96 bitrate=N/A speed=0.115x
video:117kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Exec FPS: 2.853339
VMAF score = 0.000000
[libvmaf @ 0x58ddb40] VMAF score: 0.000000

**Comment by li-zhi** [comment]
Hi, I looked at the json file you attached. The PSNR score is also low: around 25 dB. Does the total frame number of 224 match your expectation?

**Comment by RonLu** [comment]
Yes, the video duration is 8.96s and fps is 25, so total frame number of 224 is expected. 
The PSNR score is low is because the transcoded video is of 114p and 100k bitrate so its quality comparing to the original video is quite bad. However I don't expect VMAF score should be 0 for this case?

**Comment by RonLu** [comment]
The 114p should be 144p. A typo.
And if I transcode the ref-3.mp4 to a video of 144p but 340k bitrate, I got a VMAF score of 1.046575.
It seems for 144p videos, no matter what bitrate I give, the VMAF is always close to zero. Is this the expected behavior of VMAF?

**Comment by li-zhi** [comment]
The low score is expected. The resolution 144p is very low compared to the original source resolution. The low score mainly reflects the scaling artifact that impairs subjective quality.
