### ISSUE TITLE
SSIM calculation off compared to other tools

### ISSUE THREAD

**Issue by figgis** [Netflix/vmaf#22]
Hi,

I did a quick comparison of the SSIM calculations using

vmaf_psnr: feature/psnr
vmaf_ssim: feature/ssim, using the `ssim: \d+` value
ycbcr_{psnr,ssim}: https://github.com/figgis/yuv-tools
ffmpeg:  ffmpeg -s SIZE -i REC -s SIZE -i DISTORTED -lavfi "ssim="stats_file=stats_ssim.log";[0:v][1:v]"psnr="stats_psnr.log" -f null -

| vmaf_psnr   | vmaf_ssim   | ycbcr_psnr   | ycbcr_ssim   | ffmpeg_psnr   | ffmpeg_ssim   |
|:------------|:------------|:-------------|:-------------|:--------------|:--------------|
| 30,7214     | 0,9294      | 30,7214      | 0,8742       | 30,72         | 0,8733        |
| 30,6442     | 0,9295      | 30,6442      | 0,8729       | 30,64         | 0,8728        |
| 30,6154     | 0,9296      | 30,6154      | 0,8731       | 30,62         | 0,8729        |
| 30,6253     | 0,9296      | 30,6253      | 0,8731       | 30,63         | 0,8731        |
| 30,6286     | 0,9292      | 30,6286      | 0,8727       | 30,63         | 0,8728        |
| 30,6150     | 0,9292      | 30,6150      | 0,8724       | 30,61         | 0,8721        |
| 30,6014     | 0,9292      | 30,6014      | 0,8723       | 30,60         | 0,8720        |
| 30,5964     | 0,9294      | 30,5964      | 0,8724       | 30,60         | 0,8724        |
| 30,5650     | 0,9294      | 30,5650      | 0,8726       | 30,57         | 0,8724        |
| 30,5405     | 0,9297      | 30,5405      | 0,8724       | 30,54         | 0,8725        |

As you can see the SSIM values differs quite alot compared to other tools (I tried some more versions of ssim that I had available and the vmaf version differs compared to them as well).

Do you have an explanation for this?

**Comment by li-zhi** [comment]
Can you share the test videos you used? I only validated the implementation against the original matlab implementation of SSIM.

**Comment by figgis** [comment]
The reference is BQMall_832x480_60.yuv a, well known sequence from the HEVC standardization. I'll try to share the distorted using dropbox later tonight (encoded using hevc reference encoder with qp=38)

**Comment by figgis** [comment]
Sorry for the delay!
[ref.zip](https://github.com/Netflix/vmaf/files/474163/ref.zip)
[dis.zip](https://github.com/Netflix/vmaf/files/474182/dis.zip)

**Comment by figgis** [comment]
wronmg button :-)

**Comment by li-zhi** [comment]
@figgis The ssim implementation in vmaf package includes an empirical downsampling process, as described at the Suggested Usage section of https://ece.uwaterloo.ca/~z70wang/research/ssim/. The other implementations you described above, I believe, does not have this step. This should account for the numerical differences.
