### ISSUE TITLE
How to reject subjective score?

### ISSUE THREAD

**Issue by liuxj901103** [Netflix/vmaf#222]
Hi, I have got some raw subjective scores by my subjective tests , but some of the scores were nosiy. With the algorithm of subjective rejection(SR_DMOS), I could not reject any observer. Also I Tried MLE, which could get Subject bias, Subject inconsistency, Content ambiguity,Outliers. I could not figuer out what was the meaning of the above parameters.  I still don't know how to recover quality scores from noisy scores. Thanks! @pablete @jspears @moustaki @zkwentz @fabiokung

**Comment by slhck** [comment]
> but some of the scores were nosiy

How do you know that some of your scores were noisy?

> I could not figuer out what was the meaning of the above parameters

You can find an explanation [in the paper](https://github.com/Netflix/sureal/blob/master/resource/doc/dcc17v3.pdf):

> - Subject bias. The notion of quality is highly subjective and test subjects are entitled to rate the videos in their own opinions. For example, more picky viewers tend to be biased toward lower scores, and vice versa. Also, not every subject has “golden eyes” – their sensitivity to impairments varies.
> - Subject inconsistency. Subjective testing is a laborious process, and not every viewer can maintain attentiveness throughout. Some tend to rate more consistently than others.
> - Content ambiguity. Some contents tend to be more difficult to be rated than others. For example, water surface with ripples in the dark is more ambiguous than a bright blue sky.
> - Outliers. Last but not least, some raw scores are simply outliers – viewers may just not pay attention. Software issues may also render scores meaningless

> I still don't know how to recover quality scores from noisy scores

Running the sureal software should do exactly that.

If you want to be strict about subject rejection, you could also simply look at the correlations between individual ratings and mean opinion scores and remove all subjects under a given  threshold.

**Comment by liuxj901103** [comment]
Thank you for your quick reply. 
I have checked the datas from my subjective tests. And I think some  observers may not take it seriously. So some scores are obviously wrong.For example, they scored all the videos with different distortion 5 point or 1 point.
I have read the paper, and I got the result with Running the sureal software.
![figure_1](https://user-images.githubusercontent.com/40554507/44972303-42278000-af8b-11e8-9fa3-60e8cba85e71.png)
![figure_2](https://user-images.githubusercontent.com/40554507/44972314-4fdd0580-af8b-11e8-9083-54e2ce6f9e79.png)
![figure_3](https://user-images.githubusercontent.com/40554507/44972319-553a5000-af8b-11e8-9adb-f9abcf89454b.png)
![figure_4](https://user-images.githubusercontent.com/40554507/44972322-58cdd700-af8b-11e8-9689-238108db1196.png)
I just wonder if I can reject some observers with the result above?

**Comment by li-zhi** [comment]
@liuxj901103 from the raw data plot it does look like some subjects are outliers, like the second last and the third last ones. Unfortunately running SR_DMOS doesn't explicitly print out which subjects get rejected, although they do (sorry for the bad interface). It happens here:
https://github.com/Netflix/sureal/blob/master/python/src/sureal/subjective_model.py#L171

I recommend that you add a line below to print out which subjects get rejected. You are also welcome to submit a pull request.

For MLE, there is no explicit subject rejection. A subject being an outlier is manifested by the fact that the subject inconsistency is high. If a subject constantly gives high scores / low scores, the subject bias is also high / low.

**Comment by liuxj901103** [comment]
I have printed out the result of rejected subjects. But it was empty. 
Thanks anyway. I am suposed to make a futher exploration.

**Comment by li-zhi** [comment]
If you try on this dataset: https://github.com/Netflix/sureal/blob/master/resource/dataset/NFLX_dataset_public_raw_last4outliers.py
You should definitely find subjects rejected. Use it as a sanity check.
