### ISSUE TITLE
Is there any available model file for vmafossexec example

### ISSUE THREAD

**Issue by neil0615** [Netflix/vmaf#228]
I try to use vmafossexec.exe to test the test yuv file "src01_hrc00_576x324.yuv" with "src01_hrc01_576x324.yuv".
 Comparing to the demo _run_vmaf_ , I find there is an extra parameter [model_path] and set model_path = /vmaf/model/*model(e.g. vmaf_v0.6.1.pkl.model),but get an error message"Caught logic_error: array: attempting to access element:18446744073709551613 in array of length:0" 
I want to know is there any available model file for testing the example yuv

**Comment by li-zhi** [comment]
[model_path] is optional, and you can leave it out. If you do include it,
make sure to only use vmaf_v0.6.1.pkl.
