### ISSUE TITLE
Docker instructions fail: no matching manifest for windows/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by sandersaares** [Netflix/vmaf#232]
I am following docs in https://github.com/Netflix/vmaf/blob/master/resource/doc/docker.md

The first command `docker build -t vmaf .` results in the following:

```
PS C:\source\vmaf> docker build -t vmaf .
Sending build context to Docker daemon    425MB
Step 1/14 : FROM ubuntu
latest: Pulling from library/ubuntu
latest: Pulling from library/ubuntu
no matching manifest for windows/amd64 in the manifest list entries
```

**Comment by li-zhi** [comment]
We haven't tried the Dockerfile under windows. Perhaps something needs to be modified?

**Comment by nilfm** [comment]
Closing this issue as part of a clean-up as it has been open for a long time and is probably not relevant now. Please feel free to reopen if needed.
