### ISSUE TITLE
Store video

### ISSUE THREAD

**Issue by vivianyeoh** [Netflix/vmaf#235]
Hi,

Can I know how do you save your video? Do you get the video from capture card and store it in yuv directly or you have the mp4 and you just need to convert it to yuv?

**Comment by slhck** [comment]
Your question is not really understandable. Which video specifically are you talking about?

Input to VMAF is generally YUV; if you want to use VMAF with MP4 files, convert them to YUV, or use the ffmpeg `vmaf` filter.

**Comment by vivianyeoh** [comment]
The video to use in dataset. Do you capture it with capture card and use third party to store it or you convert existing mp4 into yuv?

**Comment by slhck** [comment]
Which dataset do you mean?

If you are creating your own dataset from a bunch of, say, H.264-encoded videos that are stored in .MP4, then you could use ffmpeg to convert them to YUV, e.g.:

    ffmpeg -i input.mp4 -c:v rawvideo -pix_fmt yuv420p output.yuv

**Comment by vivianyeoh** [comment]
The dataset to train the model. Have you ever try to store directly to yuv with capture card like magewell pro capture card before?

**Comment by slhck** [comment]
It depends on where you get your material from. Of course you can use a capture card to create the distorted YUV files. But you still need the original source.
