### ISSUE TITLE
What does enable_transform do?

### ISSUE THREAD

**Issue by slhck** [Netflix/vmaf#237]
In the FFmpeg help it says:

> enable_transform: Enables transform for computing vmaf

What transform is that? What is being transformed and how? When would one enable this option?

Would be great if this could be added to the documentation, here and for FFmpeg.

**Comment by li-zhi** [comment]
This option can enable/disable the `score_transform` applied to the final predicted VMAF score, if you have specified `score_transform` option in the input parameter file passed to run_vmaf_training.py. For example: https://github.com/Netflix/vmaf/blob/master/resource/param/vmaf_v6.py. We have been using this option to enable/disable the phone model option, since it is essentially a point operator transformation from the regular VMAF model.

**Comment by slhck** [comment]
Thanks for the explanation. So this is intrinsically part of the model file and can be applied if needed?

I'm asking so naively since even the example given in the ffmpeg documentation enables the transform, but I wasn't clear about what that'd do.

**Comment by kylophone** [comment]
Yeah. Good point. I can update the FFmpeg docs.

**Comment by kylophone** [comment]
I'll leave this issue open until it's fixed.

**Comment by li-zhi** [comment]
For the default model, score_transform should be disabled. The default model should generate a score value lower than the phone model.

**Comment by kylophone** [comment]
http://ffmpeg.org/pipermail/ffmpeg-devel/2018-October/235444.html

**Comment by slhck** [comment]
Looks good to me!

The only thing I'd add is removing the confusing example:

> Example with options:

>     ffmpeg -i main.mpg -i ref.mpg -lavfi libvmaf="psnr=1:enable-transform=1" -f null -

I don't see why the above would need `enable_transform` if the default model is used.

**Comment by kylophone** [comment]
Could change, but probably OK to keep (just as an example), but I'll let @li-zhi weigh in.

**Comment by li-zhi** [comment]
I agree that we could use an example that are more likely to be used, for example:
```
ffmpeg -i main.mpg -i ref.mpg -lavfi libvmaf="psnr=1:log_fmt=json" -f null -
```

**Comment by kylophone** [comment]
OK

**Comment by slhck** [comment]
Yep, I prefer this one as well. Thanks for your efforts.

**Comment by kylophone** [comment]
Almost forgot about this. Pushed to ffmpeg upstream.

https://git.videolan.org/?p=ffmpeg.git;a=blobdiff;f=doc/filters.texi;h=41fbbc53294c6772ded4afe20099bdb226c3b3b6;hp=d2d9788d8fd77345dc0f55aad07406c0cf2e57a2;hb=fd2d6f376d84f1cf1a1fc2daf0560b72a8203901;hpb=4361293fcf59edb56879c36edcd25f0a91e0edf8
