### ISSUE TITLE
High "motion" affecting score

### ISSUE THREAD

**Issue by fraser-hemp** [Netflix/vmaf#24]
I have been testing a short video which is a series of still images with medium motion between them (unfortunately I cannot provide it due to copyright) and I noticed perhaps motion is weighted too highly? This is the output of VMAF for the video:
```
Frame 0: VMAF_feature_adm2_score:0.983355, VMAF_feature_motion_score:0.000000, VMAF_feature_vif_scale0_score:0.797342, VMAF_feature_vif_scale1_score:0.972974, VMAF_feature_vif_scale2_score:0.987024, VMAF_feature_vif_scale3_score:0.992817, VMAF_score:93.100445
Frame 1: VMAF_feature_adm2_score:0.985505, VMAF_feature_motion_score:37.661541, VMAF_feature_vif_scale0_score:0.797752, VMAF_feature_vif_scale1_score:0.972760, VMAF_feature_vif_scale2_score:0.986680, VMAF_feature_vif_scale3_score:0.992413, VMAF_score:100.000000
Frame 2: VMAF_feature_adm2_score:0.976141, VMAF_feature_motion_score:40.074627, VMAF_feature_vif_scale0_score:0.708371, VMAF_feature_vif_scale1_score:0.945214, VMAF_feature_vif_scale2_score:0.972793, VMAF_feature_vif_scale3_score:0.984663, VMAF_score:100.000000
Frame 3: VMAF_feature_adm2_score:0.974181, VMAF_feature_motion_score:42.222538, VMAF_feature_vif_scale0_score:0.672937, VMAF_feature_vif_scale1_score:0.947456, VMAF_feature_vif_scale2_score:0.975278, VMAF_feature_vif_scale3_score:0.985465, VMAF_score:100.000000
Frame 4: VMAF_feature_adm2_score:0.978275, VMAF_feature_motion_score:39.471184, VMAF_feature_vif_scale0_score:0.713338, VMAF_feature_vif_scale1_score:0.947480, VMAF_feature_vif_scale2_score:0.973790, VMAF_feature_vif_scale3_score:0.983780, VMAF_score:100.000000
Frame 5: VMAF_feature_adm2_score:0.976263, VMAF_feature_motion_score:40.529591, VMAF_feature_vif_scale0_score:0.692000, VMAF_feature_vif_scale1_score:0.956538, VMAF_feature_vif_scale2_score:0.980027, VMAF_feature_vif_scale3_score:0.989142, VMAF_score:100.000000
Frame 6: VMAF_feature_adm2_score:0.972154, VMAF_feature_motion_score:35.454933, VMAF_feature_vif_scale0_score:0.688905, VMAF_feature_vif_scale1_score:0.943008, VMAF_feature_vif_scale2_score:0.972188, VMAF_feature_vif_scale3_score:0.984484, VMAF_score:100.000000
Frame 7: VMAF_feature_adm2_score:0.972674, VMAF_feature_motion_score:40.848309, VMAF_feature_vif_scale0_score:0.679250, VMAF_feature_vif_scale1_score:0.950740, VMAF_feature_vif_scale2_score:0.976935, VMAF_feature_vif_scale3_score:0.987387, VMAF_score:100.000000
Frame 8: VMAF_feature_adm2_score:0.969504, VMAF_feature_motion_score:38.406681, VMAF_feature_vif_scale0_score:0.642949, VMAF_feature_vif_scale1_score:0.931827, VMAF_feature_vif_scale2_score:0.967498, VMAF_feature_vif_scale3_score:0.982788, VMAF_score:100.000000
Aggregate: VMAF_feature_adm2_score:0.976450, VMAF_feature_motion_score:34.963267, VMAF_feature_vif_scale0_score:0.710316, VMAF_feature_vif_scale1_score:0.952000, VMAF_feature_vif_scale2_score:0.976913, VMAF_feature_vif_scale3_score:0.986993, VMAF_score:99.233383
```

As you can see the first frame with 0 motion has a more accurate score (93), but the following frames which have a motion score of above 30 (I noticed the README mentioned a normal range is 20) are score as 100? The other elementary metrics are very similar to each other. I'm not sure of the model, but could the 100 scores be due to the high motion? I have inspected the frames and I believe they should be closer to the high 80's, low 90s.

**Comment by li-zhi** [comment]
@fraser-hemp: the first frame has motion 0 is because it does not have a previous frame to calculate the motion. We plan to change this in the next version by making the motion calculation depend on either the previous frame or the next frame.

Other than this, it looks like you are getting very high VMAF scores which get clipped at 100. You may want to consider doing the calculation on a up-sampled reference/distorted video pair. Please refer to the FAQ for more information: https://github.com/Netflix/vmaf/blob/master/FAQ.md

**Comment by li-zhi** [comment]
@fraser-hemp I believe it is both: the source size is very small, and the motion is high. Do you also have the distorted clip to share?

**Comment by yuhjay** [comment]
@fraser-hemp The motion score here is based on an assumption that the frames are relatively continuous. If neighboring frames are too different, we may want to treat it as a scene cut. I would focus on the single frame score after a scene cut.

**Comment by fraser-hemp** [comment]
@li-zhi here is the dst (yuv, same res): https://drive.google.com/open?id=0B_mWxBuwYcSgX2dqdnduYmdTLUk

**Comment by fraser-hemp** [comment]
@li-zhi In your training dataset, did you have any videos with motion > 40?

**Comment by fraser-hemp** [comment]
@li-zhi I believe it was due to an error in my command line arguments, as I am now getting more appropriate values on these videos. Feel free to close this issue :)

**Comment by li-zhi** [comment]
No problem:)
