### ISSUE TITLE
Reference is distorted video or special effect video

### ISSUE THREAD

**Issue by liuxj901103** [Netflix/vmaf#241]
Hi, I have trained my VMAF model with my reference videos which are distorted videos and special effect videos. AS a result, both the SRCC and PCC are very low. I wonder if the statistic characteristics of distorted videos and special effect videos couldn't follow a GSM distribution.And if  the distrubution of reference video matter more than chosing some better features.Thanks.

**Comment by li-zhi** [comment]
Hi could you give more details about the special effect video?

**Comment by christosbampis** [comment]
If the video is not of high quality (regardless if it is the reference or the distorted video), then it will not obey the GSM model as closely as a pristine video sequence. However, I am not sure I understand your question. As Zhi suggested, giving us more details would be helpful.

**Comment by liuxj901103** [comment]
Thankyou for your apply. My most referenc videos are distorted with blocking artifacts more or less. A special effect video is shown as below.
![image](https://user-images.githubusercontent.com/40554507/47472982-406b9180-d843-11e8-8d57-c1cad71c945d.png)
 In the extreme,a reference video is as the figure shows below.
![image](https://user-images.githubusercontent.com/40554507/47472276-ad315c80-d840-11e8-8c58-945b6068b7e0.png)

**Comment by christosbampis** [comment]
Thank you for providing these sample frames. In both cases, these videos are of low quality. You can still apply VMAF but you may not get intuitive/meaningful results. It is an open area of research to extend a FR metric, like VMAF, to the NR case.

**Comment by liuxj901103** [comment]
I didn't mean NR case. I just wonder if the distorted videos can be trained with vmaf, or get a meaningful model.

**Comment by christosbampis** [comment]
If you mean whether you can train a VMAF model using pairs of videos, where the source is also distorted, you could. If the model will be meaningful or not, it depends on what you want your model to capture: is it compression/scaling distortions? is it the source distortions? or is it both? Generally, I would prefer to have good quality source videos when training a full reference model.
