### ISSUE TITLE
help: macOS, libvmaf and CVPixelBuffer

### ISSUE THREAD

**Issue by adhamhf** [Netflix/vmaf#243]
Hi,

I'm trying to use libvmaf with a CVPixelBuffer.  I'm not use video, I'm using individual images.  I read in my reference and test image into CVPixelBuffers.  I then override read_frame to get the pixel buffer from user_data.  I get the data from the buffers and assign it to ref_data and main_data.  this also seems create, but...  I always get 1 for ssim and msssim.  the vmaf score is always 97.42.  I'm really lost as to why this happens and would welcome any suggestions.

I've tried iterating over the luma portion of the CVPixelBuffer and make sure its a float from 0 to 1 by dividing the pixel by 255 but that has not helped.  Should the data that read_frame is providing be floats from 0 to 1 or 0 to 255?  Is this documented anywhere?

Using vImage instead of CVPixelBuffer I've tired vImageConvert_Planar8toPlanarF using 0.0 to 1.0 and 0.0 to 255.0, still get exact matches.  weird.

**Comment by adhamhf** [comment]
@li-zhi could you help me understand what format the pixel data needs to be in?

**Comment by li-zhi** [comment]
Sorry the delayed response. The standard pixel formats that libvmaf can take are: yuv420p, yuv422p, yuv444p, yuv420p10le, yuv422p10le and yuv44410le.

**Comment by adhamhf** [comment]
@li-zhi sorry.  I asked the question poorly.   Is the pixel data expected to be float between 0 and 1 or something else?   I think I need the convert the individual pixel values from uint8 to something else...

**Comment by li-zhi** [comment]
No, it must not be float. For example, for `yuv420p`, you will expect your data to be `6 bytes per 4 pixels, reordered`. Refer to: https://en.wikipedia.org/wiki/YUV

**Comment by adhamhf** [comment]
thanks, for that clarification.  The symptom I'm seeing is that all the metrics come out to a perfect match,  ssim is 1.0,  ms_ssim is 1.0 and all the vif_scales.  I think I'm getting my data in to YUV 422 planar format, but those results are wrong because I'm comparing very different images. 

Do you think this symptom could be caused by the pixel format being wrong, or something else?

**Comment by adhamhf** [comment]
closing, here's the solution:

```
int read_frame(float *ref_data, float *main_data, float *temp_data, int stride, void *user_data)  {

    struct vifCVData* new_value = (struct vifCVData*)user_data;
    if(new_value->count == 1 ) {
        return 2;
    }

    // created with [CIContext render: toCVPixelBuffer:]  using kCVPixelFormatType_420YpCbCr8BiPlanarFullRange pixelFormatType
    CVPixelBufferRef ref = new_value->refBuffer;
    CVPixelBufferRef test = new_value->testBuffer;

    size_t width = CVPixelBufferGetWidthOfPlane(ref,0);
    size_t height = CVPixelBufferGetHeightOfPlane(ref,0);
    uint8_t *ptrA = CVPixelBufferGetBaseAddressOfPlane(ref,0);
    uint8_t *ptrB = CVPixelBufferGetBaseAddressOfPlane(test,0);

    for( int i = 0; i < width * height; i++) {
        ref_data[i] = (float)ptrA[i];
        main_data[i] = (float)ptrB[i];
    }
    new_value->count += 1;
    return 0;
}
```
