### ISSUE TITLE
vmaf compute with x265 integrated libvmaf segment fault error

### ISSUE THREAD

**Issue by coolfat** [Netflix/vmaf#247]
The command is follows:
./x265 --input src.yuv --fps 25.0 --input-res 720x1280 --csv csv.log --crf 18.0 --recon rec.yuv -o dst-src.265

Env: linux system
gcc version: gcc.4.8.2

I check the backtrance in gdb:
0x00007ffff6c1e3f7 in raise () from /opt/compiler/gcc-4.8.2/lib/libc.so.6
(gdb) bt
0 0x00007ffff6c1e3f7 in raise () from /opt/compiler/gcc-4.8.2/lib/libc.so.6
1 0x00007ffff6c1f7d8 in abort () from /opt/compiler/gcc-4.8.2/lib/libc.so.6
2 0x00007ffff6c5c554 in __libc_message () from /opt/compiler/gcc-4.8.2/lib/libc.so.6
3 0x00007ffff6c61dbe in malloc_printerr () from /opt/compiler/gcc-4.8.2/lib/libc.so.6
4 0x00007ffff6c64a72 in _int_realloc () from /opt/compiler/gcc-4.8.2/lib/libc.so.6
5 0x00007ffff6c65929 in realloc () from /opt/compiler/gcc-4.8.2/lib/libc.so.6
6 0x000000000062cb91 in readline (input=0x7fffe1f4b1f0)

at /home/scmbuild/workspaces_cluster.debug/baidu.bce-multimedia.mct-ffmpeg-new__GCC_4.8.2.20181101.115208/baidu/bce-multimedia/mct-third64/vmaf/vmaf-1.3.9/wrapper/src/svm.cpp:343
7 svm_load_model (model_file_name=<optimized out>)

at /home/scmbuild/workspaces_cluster.debug/baidu.bce-multimedia.mct-ffmpeg-new__GCC_4.8.2.20181101.115208/baidu/bce-multimedia/mct-third64/vmaf/vmaf-1.3.9/wrapper/src/svm.cpp:536

8 0x0000000000577d6f in LibsvmNusvrTrainTestModel::_read_and_assert_svm_model (this=this@entry=0x7fffe1f4cd80, libsvm_model_path=<optimized out>)

at /home/scmbuild/workspaces_cluster.debug/baidu.bce-multimedia.mct-ffmpeg-new__GCC_4.8.2.20181101.115208/baidu/bce-multimedia/mct-third64/vmaf/vmaf-1.3.9/wrapper/src/vmaf.cpp:155

what is the problem?

**Comment by li-zhi** [comment]
Did you point to the right model file, for example: `model/vmaf_v0.6.1.pkl`?

**Comment by coolfat** [comment]
> Did you point to the right model file, for example: `model/vmaf_v0.6.1.pkl`?

Yes, the model file is correct.
I have resolved the problem. 
I use a mutex_lock when x265 call compute_vmaf() api.
![Uploading 图片.png…]()

Thanks.

**Comment by uthay45** [comment]
Hii Your image is no showing can you please repost it properly or can you please tell me clearly How did you solved ?
