### ISSUE TITLE
Reference resolution different from distorted resolution

### ISSUE THREAD

**Issue by chinesealex210** [Netflix/vmaf#248]
Hi,

Suppose I have a 3840x2160 reference video and a 1920x1080 distorted video.
When I use ffmpeg2vmaf, I can scale the distorted video's resolution to 3840x2160 by specify quality_width and quality_height:

./ffmpeg2vmaf quality_width quality_height reference_path distorted_path \
  [--model model_path] [--out-fmt out_fmt]

But it seems that ffmpeg's libvmaf does not support it, libvmaf requires width and height of input videos must be same.

Is there any option that can solve this problem? Or is there any ffmpeg option that can pipe the upscaled distorted video directly to libvmaf without generating new upscaled files?

I switch from ffmpeg2vmaf to ffmpeg's libvmaf because it provides speedup by using multi-threading, it would be a pity that I have to upscale videos by myself, which consumes a lot of time.

Thank you

**Comment by slhck** [comment]
You can scale the video with ffmpeg:

    ffmpeg -i main.mpg -i ref.mpg -filter_complex "[0:v]scale=3840:2160[main];[main][1:v]libvmaf" -f null -

This scales the first input video `0:v` and forwards it to VMAF with the label `main`, where it's compared against the second input video `1:v`.

See the [Filtering Guide](https://trac.ffmpeg.org/wiki/FilteringGuide) for more examples of complex filters.

**Comment by chinesealex210** [comment]
Thank you so much, it works!

**Comment by kylophone** [comment]
Thanks.

**Comment by li-zhi** [comment]
@slhck Useful tip! Could you add it to the FAQ page as well?

**Comment by singhkays** [comment]
@slhck This is fantastic! However, I'm also trying to specify the model file path and it's not working. Here's the command I'm using from ffmpeg filters page https://ffmpeg.org/ffmpeg-filters.html#libvmaf
```
./ffmpeg -i main.mp4 -i ref.mp4  -lavfi libvmaf="model_path=/home/kay/vmaf/model/vmaf_v0.6.1.pkl:log_fmt=json" -f null -
```
With this modification, I tried 
```
./ffmpeg -i main.mp4 -i ref.mp4 -filter_complex "[0:v]scale=1920x800:flags=bicubic[main];[main][1:v]libvmaf" -lavfi libvmaf="model_path=/home/kay/vmaf/model/vmaf_v0.6.1.pkl:log_fmt=json" -f null -
```

but got the below error
`Cannot find a matching stream for unlabeled input pad 0 on filter Parsed_libvmaf_0`

Any ideas?

**Comment by slhck** [comment]
Use only one instance of `-filter_complex` or `-lavfi` (they both refer to the same thing), then pass the options to the filters.

```
ffmpeg -i main.mpg -i ref.mpg -filter_complex \
"[0:v]scale=1920:1080:flags=bicubic[main]; \
[main][1:v]libvmaf=model_path=/home/kay/vmaf/model/vmaf_v0.6.1.pkl:log_fmt=json" \
-f null -
```

**Comment by singhkays** [comment]
@slhck Thank you! this works now

**Comment by pranaybaldev1** [comment]
@slhck Thank you. One thing I noticed is that:
1. Your command gives a higher VMAF score (difference of 2 or 3) as compared to scaling two videos, saving them locally and comparing. Any reason for this?
2. Is there any way to get the metadata of the scaled video in your command?

**Comment by slhck** [comment]
Please show the commands that you used, and and their output. Otherwise it's hard to troubleshoot.

What do you mean by metadata? What do you want to do?

**Comment by pranaybaldev1** [comment]
1. For scaling: 
ffmpeg -i url_hevc_vid_distorted -filter_complex scale=480x864 temp.hevc 
ffmpeg -i url_vid_source -filter_complex scale=480x864 s_temp.mp4
For vmaf:
ffmpeg -i temp.hevc -i s_temp.mp4 -filter_complex "libvmaf" -f null -

This would give me a score of 82.010596.

ffmpeg -i url_hevc_vid_distorted -i url_vid_source -filter_complex "[0:v]scale=480:864[main];[1:v]scale=480:864[temp];[main][temp] libvmaf" -f null -

This would give me a score of 85.037268.
I can share the video links if this is not sufficient.

2. I am writing a python script and I want bitrate, width, height. I'm using your command but I can't find a way to get the bitrate etc of the scaled video.

**Comment by slhck** [comment]
When you run your second command (`ffmpeg -i url_vid_source -filter_complex scale=480x864 s_temp.mp4 `), you are telling ffmpeg to re-encode your source video using libx264 to H.264. That means you'll introduce additional lossy compression to your source. You don't want that. If you need to wrap your source into a container (`s_temp.mp4`), add `-c:v copy` to your command. But ideally, go with the third command you've posted.

Having the bitrate of the scaled video does not make much sense. If you want the bitrate of the original, distored video, before scaling, you have various options, including calling `ffprobe` with `json` output format, and parsing the output with Python.

**Comment by pranaybaldev1** [comment]
Thank you, @slhck. 
On a side note, I read https://slhck.info/video/2017/02/24/crf-guide.html. Thank you. Big fan.

**Comment by kb1181** [comment]
> Use only one instance of `-filter_complex` or `-lavfi` (they both refer to the same thing), then pass the options to the filters.
> 
> ```
> ffmpeg -i main.mpg -i ref.mpg -filter_complex \
> "[0:v]scale=1920:1080:flags=bicubic[main]; \
> [main][1:v]libvmaf=model_path=/home/kay/vmaf/model/vmaf_v0.6.1.pkl:log_fmt=json" \
> -f null -
> ```

why I use command 'ffmpeg -i main.mp4 -i main2.mp4 -filter_complex "[0:v]scale=1920:864:flags=bicubic[main];[main][1:v]libvmaf=model_path=model/vmaf_v0.6.1.pkl:log_fmt=json" -f null -' , it's still report

Parsed_libvmaf_1 @ 000002c02126a6c0] Width and height of input videos must be same.
[Parsed_libvmaf_1 @ 000002c02126a6c0] Failed to configure input pad on Parsed_libvmaf_1

**Comment by nilfm99** [comment]
Hi @kb1181, 

VMAF expects both videos to be the same resolution. What you did is scale the distorted video up to 1920x1080, and that should work if the reference is also 1920x1080. It looks like it isn't, so you have some options:
1. Find out the resolution of the reference, and replace `1920:1080` in your command with it, so that quality is computed at that resolution.
2. Scale both reference and distorted to 1920x1080 and use that as your "quality resolution". Let me know if you need some help crafting the command for that.

**Comment by slhck** [comment]
@kb1181  Specifically, it helps always showing the complete, uncut command line output from ffmpeg. Otherwise people have to guess what the underlying issue is.

I hope it's fine to link to this here — I made a wrapper for ffmpeg's built-in quality-related filters:

https://github.com/slhck/ffmpeg-quality-metrics

You can use this to calculate VMAF and won't have to worry about manually creating the filtering commands. It takes care of resizing the distorted video to the reference size.
