### ISSUE TITLE
SUREAL for RedHat

### ISSUE THREAD

**Issue by engrzeeshan** [Netflix/vmaf#254]
I want to use VMAF on Red Hat 7.5. I'm having following error while installing sureal:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-kc5rgnpb/sureal/
Please suggest a solution.

**Comment by li-zhi** [comment]
Could you provide the complete error message dump?

**Comment by engrzeeshan** [comment]
[root@localhost bin]# pip install sureal
Collecting sureal
  Using cached https://files.pythonhosted.org/packages/02/4d/be56600d9a5a68f89e8ba7bfa85111428264046d6cf99ff3b0c39b56fda9/sureal-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/root/anaconda3/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-boy84rpf/sureal/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-boy84rpf/sureal/

**Comment by li-zhi** [comment]
Looks like you are using Python 3. Sureal works with Python 2 at this moment, and it might be the cause.

**Comment by engrzeeshan** [comment]
Can I calculate VMAF score without using SUREAL library?

**Comment by slhck** [comment]
SUREAL is not needed for VMAF, but VMAF also needs Python 2.

There are ongoing efforts to make both compatible with Python 3.

**Comment by slhck** [comment]
Sureal [should now be compatible](https://github.com/Netflix/sureal/commit/765735ac8cd7a77baf1814ab3fa525a8ab36147e) with Python 3. Testing would be appreciated.
