### ISSUE TITLE
vmafossexec -- logic error

### ISSUE THREAD

**Issue by engrzeeshan** [Netflix/vmaf#259]
I'm trying to run vmafossexec on Red Hat 7.5 to compute VMAF between source video Johnny_1280x720_60_orig.yuv and decoded video Johnny_1280x720_60_dec.yuv. I received an error "Caught logic_error: array: attempting to access element:18446744073709551613 in array of length:0". following is dump from terminal:

[root@localhost wrapper]# ./vmafossexec yuv420p 1280 720 /home/zeeshan/Data/YUV_Videos/HD/Johnny_1280x720_60_orig.yuv /home/zeeshan/Data/YUV_Videos/HD/Johnny_1280x720_60_dec.yuv /home/zeeshan/Data/VMAF/vmaf-master/model/vmaf_v0.6.1.pkl.model --log vmaf_output.xml --psnr --ssim --ms-ssim --thread 0 --subsample 5
Start calculating VMAF score...
Caught logic_error: array: attempting to access element:18446744073709551613 in array of length:0
[root@localhost wrapper]#

**Comment by li-zhi** [comment]
Please use /home/zeeshan/Data/VMAF/vmaf-master/model/vmaf_v0.6.1.pkl instead of /home/zeeshan/Data/VMAF/vmaf-master/model/vmaf_v0.6.1.pkl.model.

**Comment by engrzeeshan** [comment]
[root@localhost wrapper]# ./vmafossexec yuv420p 1280 720 /home/zeeshan/Data/YUV_Videos/HD/Johnny_1280x720_60_orig.yuv /home/zeeshan/Data/YUV_Videos/HD/Johnny_1280x720_60_dec.yuv /home/zeeshan/Data/VMAF/vmaf-master/model/vmaf_v0.6.1.pkl --log vmaf_output.xml --psnr --ssim --ms-ssim --thread 0 --subsample 5
Start calculating VMAF score...
Input model at /home/zeeshan/Data/VMAF/vmaf-master/model/vmaf_v0.6.1.pkl cannot be read successfully.
Caught VmafException: Error loading model (.pkl): Trouble reading the file:/home/zeeshan/Data/VMAF/vmaf-master/model/vmaf_v0.6.1.pkl

**Comment by engrzeeshan** [comment]
Now facing vmaException error. please guide

**Comment by li-zhi** [comment]
The following command line works for me:
```
./vmafossexec yuv420p 576 324 ../python/test/resource/yuv/src01_hrc00_576x324.yuv ../python/test/resource/yuv/src01_hrc01_576x324.yuv ../model/vmaf_v0.6.1.pkl --log ../vmaf_output.xml --psnr --ssim --ms-ssim --thread 0 --subsample 5
```
Can you try if it works? We can debug from there.
