### ISSUE TITLE
vmaf score of 1080p is almost the same as  the score of 540p

### ISSUE THREAD

**Issue by annci62** [Netflix/vmaf#274]
I tried to use nflxall_vmafv3a.pkl to get vmaf score of 1080p and 540p, and found the vmaf score of 1080p for some videos is almost the same as  the score of 540p when fixqp is 5. When calculating  the score of 540p, 540p is upsampled to 1080p. 
Shouldn't I use one model when calculating 1080p scare and 540p scare?

**Comment by li-zhi** [comment]
Have you tried to use the default mode `model/vmaf_v0.6.1.pkl`, which is recommended for general purpose use?

**Comment by annci62** [comment]
Thank li-zhi， I will try it.

**Comment by annci62** [comment]
@li-zhi, I have download BigBuckBunny_85_1080_3800.yuv from the address you provide， but don't know which pkl and which version of vmaf source code to get the vmaf of 85?

**Comment by christosbampis** [comment]
Hi @annci62 , you can use model/vmaf_v0.6.1.pkl and the latest source code. Not sure what you mean by vmaf of 85 though.

**Comment by annci62** [comment]
@li-zhi ,Thank you very much
