### ISSUE TITLE
Low quality video scores are higher

### ISSUE THREAD

**Issue by Muyip** [Netflix/vmaf#281]
I use ffmpeg's different scaling algorithms, one is "sinc" and the other is "lanczos". 
1. Scaling a 1280x720 video to 386x216；
2. Scaling the 386x216 video to 1280x720 using the corresponding algorithm. 
Now I get two videos with loss, and finally use vmafossexec.exe to compare the two lost videos with the 1280x720 video without loss. I got two scores, and I think the video scores using"sinc" scaling should be lower because some areas of the video have small squares visible to the naked eye. But these two scores are different from what I expected. 
Below are screenshots of some video and vmaf logs:

one frame in video scaled with "sinc":
![scaled_with_sinc](https://user-images.githubusercontent.com/17662241/50290195-df101980-04a5-11e9-8962-f78afc1fa211.png)
vmaf log of this frame:
![score_of_sinc](https://user-images.githubusercontent.com/17662241/50290214-ec2d0880-04a5-11e9-93a6-f965243bc689.png)

one frame in video scaled with "lanczos":
![scale_with_lanczos](https://user-images.githubusercontent.com/17662241/50290244-00710580-04a6-11e9-8e08-ce98f9d27650.png)
vmaf log of this frame:
![score_of_lanczos](https://user-images.githubusercontent.com/17662241/50290252-0961d700-04a6-11e9-9024-8ad0a8494805.png)

**Comment by mht13** [comment]
My understanding is that the reference video has to be a 1920x1080, while you are using a 1280x720. Still, I would have thought that even though you wouldn't have correlation with MOS, the scores would still reflect which one has higher quality. The other thing is that there is some CI (5% by default I think), while the difference in scores that point out is about 3. Happy to hear what people have to say.

**Comment by li-zhi** [comment]
This is a very interesting example (sorry for missing it out earlier). sinc function is known as ideal for anti-aliasing but produces ringing artifacts. The produced elementary scores are pointing to different directions: ADM predicts that sinc is doing better than lanczos, but VIF (same camp as SSIM) the other way around. I guess in this particular case, VIF wins, yet the current VMAF model is more dominated by ADM.

Is it possible to share the samples? This would be a great example for fine tuning of VMAF.

**Comment by common1994** [comment]
[sample_1280x720.zip](https://github.com/Netflix/vmaf/files/2779072/sample_1280x720.zip)

Ok, Thank you for your reply. The sample_1280x720.zip file contains a 60-frame unscaled original image. The following command is used to obtain an image that has been scaled using different scaling algorithms, and then vmaf is used to evaluate the two scaled images.

1. ffmpeg -pix_fmt yuv420p -s 1280x720 -i sample_1280x720.yuv -pix_fmt yuv420p -s 386x216 -sws_flags lanczos sample_down_lanczos_386x216.yuv
2. ffmpeg -pix_fmt yuv420p -s 1280x720 -i sample_1280x720.yuv -pix_fmt yuv420p -s 386x216 -sws_flags sinc sample_down_sinc_386x216.yuv
3. ffmpeg -pix_fmt yuv420p -s 386x216 -i sample_down_lanczos_386x216.yuv -pix_fmt yuv420p -s 1280x720 -sws_flags lanczos scaled_lanczos_1280x720.yuv
4. ffmpeg -pix_fmt yuv420p -s 386x216 -i sample_down_sinc_386x216.yuv -pix_fmt yuv420p -s 1280x720 -sws_flags sinc scaled_sinc_1280x720.yuv
5. vmafossexec.exe yuv420p 1280 720 sample_1280x720.yuv scaled_lanczos_1280x720.yuv model/vmaf_v0.6.1.pkl --log vmaf_lanczos.log --thread 0 --subsample 1
6. vmafossexec.exe yuv420p 1280 720 sample_1280x720.yuv scaled_sinc_1280x720.yuv model/vmaf_v0.6.1.pkl --log vmaf_sinc.log --thread 0 --subsample 1

**Comment by nilfm** [comment]
Closing this issue as part of a clean-up as it has been open for a long time and is probably not relevant now. Please feel free to reopen if needed.
