### ISSUE TITLE
Can vmaf wrapper support compare 2 images

### ISSUE THREAD

**Issue by fishjam** [Netflix/vmaf#286]
Is there any method in vamf wrapper that can directly compare 2 images, the method is similar to compute_psnr or compute_ssim
```
int compute_psnr(const float *ref, const float *dis, int w, int h, int ref_stride, int dis_stride, double *score, double peak, double psnr_max);
int compute_ssim(const float *ref, const float *cmp, int w, int h,
        int ref_stride, int cmp_stride, double *score,
        double *l_score, double *c_score, double *s_score);
```
Maybe the interface is similar as : 
  - int compute_vmaf(const float *ref, const float *cmp, ...., double *score...);

So I can extract and compare speical frame from reference video and distorted video.

**Comment by fishjam** [comment]
After do more research, vmaf need  prior and next frame for compute_motion, it seems that vmaf can not support compute score  frame by frame. 
But if programer can get [Result](https://github.com/Netflix/vmaf/blob/master/wrapper/src/vmaf.h#L158) in there code, it's a huge help.

**Comment by li-zhi** [comment]
VMAF can indeed be run on two images. In this case, compute_motion will return 0 value. The implication is that it will treat the single image as a static video  shot.

To run, you will need to property convert the images into YUV format. The most convenient way to do this is through FFmpeg + libvmaf as a filter. See below for how libvmaf works with FFmpeg:
https://ffmpeg.org/ffmpeg-filters.html#libvmaf

**Comment by slhck** [comment]
If you want to compare two videos, you should not compare them frame-by-frame. Otherwise you'll ignore the motion difference feature entirely, giving you an invalid prediction.

If the videos have an offset, you have to buffer the two streams while ingesting them, find the correct temporal registration, and *then* feed the synchronized streams into VMAF.

**Comment by fishjam** [comment]
Is there same issue when we use --subsample in vmafossexec?

**Comment by li-zhi** [comment]
`--subsample` is not the same as subsampling frames before passing them to VMAF. `--subsample` goes through all the frames but will skip unnecessary computation related to intermediate frames.

**Comment by fishjam** [comment]
OK, I got it.
Then there is a bug in motion compute logical.  Ref [compute_motion in combo](
  https://github.com/Netflix/vmaf/blob/master/wrapper/src/combo.c#L410) .
And I think we can accept the motion invalid prediction in our scenario, It's not a serious problem.
Thank you anyway.  :)

**Comment by li-zhi** [comment]
@fishjam could you be more specific on the bug you are referring to?

**Comment by fishjam** [comment]
According the function name, compute_motion will compute the motion score according prev_blur_buf , blur_buf and next_blur_buf, If it "goes through all the frames" to compute all frame's motion score, it could be in the range of ***if (frm_idx % n_subsample == 0)***.

Examples: If user set n_subsample to 100, then compute_motion only compute the 0, 1, 99, 100, 101, 199,200,201 ... frames. 
Is it true ?

**Comment by li-zhi** [comment]
That's interesting. I can't recall out of my head how it was implemented, but I do have a test case for checking skipping frames:
https://github.com/Netflix/vmaf/blob/master/python/test/vmafossexec_test.py#L607

**Comment by fishjam** [comment]
After refactor libvmaf.h, programer can compare 2 images and get the results, then this requirements can be closed.
