### ISSUE TITLE
make - compile error cannot find -lptools

### ISSUE THREAD

**Issue by KuntzeM** [Netflix/vmaf#29]
Hi,
if I want to compile this script with make, I get an error:

> /usr/bin/ld: cannot find -lptools 
> collect2: error: ld returned 1 exit status
> Makefile:116: recipe for target 'vmafossexec' failed
> make[1]: *** [vmafossexec] Error 1

Which libary is missing on my linux machine?

Thank your for your help!

regards 
Mathias

**Comment by KuntzeM** [comment]
edit:
now I found the lib ptools.
if the make command want to compile it, then I get the follow error message:

> Makefile:67: :: cannot open shared object file: No such file or directory
> Makefile:67: *** :: failed to load.  Stop.

Makefile:67 is:
> load : $(COM_OBJS) load.o 
> $(CC) $(CCFLAGS) $(COM_OBJS) load.o -o load

**Comment by li-zhi** [comment]
Hi Mathias, which Linux distribution and version are you using?

**Comment by KuntzeM** [comment]
I'm using Fedora version 24.

**Comment by li-zhi** [comment]
@KuntzeM Please pull master and try again. It should now work on Fedora.

**Comment by KuntzeM** [comment]
thank you it works!
