### ISSUE TITLE
Why don‘t all pkl files in /model use ssim？

### ISSUE THREAD

**Issue by annci62** [Netflix/vmaf#292]
I don't understand why all pkl files in /mode don‘t use ssim as one of elements to get vmaf score?Because some papers show ssim is better than vif when assessing video quality in video compression.

**Comment by slhck** [comment]
Some papers may show that SSIM is better than VIF, others show the opposite. It depends on how you do the evaluation. Note that neither VIF(P) nor SSIM are video quality algorithms anyway—they compare single pictures! In that sense they are both equally valid as underlying features. As to why VIF was chosen over SSIM: there may have been more than technical reasons for doing so.

Note that I can't speak for the original authors, just leaving my two cents here.

**Comment by annci62** [comment]
@slhck I understand, thank you very much

**Comment by christosbampis** [comment]
To add to the above answer, SSIM and VIF share many similarities. If, however, there is a feature that can provably improve VMAF, let us know :)
