### ISSUE TITLE
Training dataset for generic VMAF model

### ISSUE THREAD

**Issue by MukeshA1** [Netflix/vmaf#294]
Hi,
I have a question regarding the training dataset used for the generic 4k VMAF model.  Are there any videos in the training dataset whose contents are MS word documents, PPTs , desktop images etc ? I am just wondering whether existing VMAF model can be used directly for evaluating video quality for videos having predominantly word docs, PPTs etc content.
Please let me know.

Thanks

**Comment by li-zhi** [comment]
@MukeshA1 We have never tested how VMAF works on screen content. The original VMAF is trained with animation titles as a subset of the the training content, which might be similar to screen content. Another factor to consider is, screen content are viewed with a much closer distance than the original VMAF's assumption (3H). A good way to try is to run a small-scale subjective test to validate VMAF's performance.

**Comment by MukeshA1** [comment]
@li-zhi - Thanks for your input.  If we have to retrain the model for screen content, how many videos would be good enough for training?
Thanks!

**Comment by MukeshA1** [comment]
Thanks li-zhi!
