### ISSUE TITLE
build failures with mingw-w64 cross compile

### ISSUE THREAD

**Issue by rdp** [Netflix/vmaf#296]
Attempting to cross compile from linux for windows using "mingw-w64" I ran into various issues:

https://github.com/rdp/ffmpeg-windows-build-helpers/blob/master/patches/libvmaf.various.patch

Is -msse4.1 "required"?

Winsock2.h is apparently not capitalized that way, so fails in a case sensitive file system, and the "i64" suffix apparently only works with MSVC.  It did build and link though, thanks!

Plus some fixes in there for cross compiling from os x.

**Comment by rdp** [comment]
also .pc file doesn't set prefix right...

**Comment by vtorri** [comment]
with the latest release, no compilation problem with msys2 + mingw-w64, pc file is correctly written, winsock2.h is correctly capitalized

there are though a **lot** of warnings with mingw-w64

**Comment by 1480c1** [comment]
the warnings can be viewed from https://ci.appveyor.com/project/li-zhi/vmaf/build/job/b55saafmrhwojk83

a lot of them are related to the opencontainers part
