### ISSUE TITLE
easy to fix: vmafossexec returns 'variable used without being initialized' error on windows 10

### ISSUE THREAD

**Issue by kjerbi** [Netflix/vmaf#301]
Hi,
there is a small problem appearing when I execute vmafossexec on windows 10 after compiling the current state of the master branch. The "offset_flag" variable is used without being initialized.
In wrapper/source/combo.c line 102 I just changed bool offset_flag; into bool offset_flag = false; and that solved the problem.

That would be nice to avoid debugging for everyone.

Thank you so much

Regards,
Khaled

**Comment by kylophone** [comment]
Great, Thanks. Can you send this a PR?
