### ISSUE TITLE
Deleted releases?

### ISSUE THREAD

**Issue by slhck** [Netflix/vmaf#303]
The release 1.13.11 seems to have been deleted, which causes build errors for those wanting to install `libvmaf` through Homebrew.

Please consider not deleting releases, even if outdated, as links to those release versions are considered permanent.

In the meantime, I've bumped the version in the formula (see https://github.com/Homebrew/homebrew-core/pull/36885).

**Comment by li-zhi** [comment]
Didn't realized this. Will take note for next time. 

The release 1.3.11 was published for only a very small period of time before superseded by 1.3.13 (added the latest VS build files). Did it trigger any automated events?

**Comment by slhck** [comment]
I don't think so, but someone bumped the formula on Homebrew via https://github.com/Homebrew/homebrew-core/commit/5712fa94141f4bf665770160071c11a41bfb1846

**Comment by li-zhi** [comment]
Got it. Thanks for the help!
