### ISSUE TITLE
Resolve warnings in Visual Studio builds

### ISSUE THREAD

**Issue by EwoutH** [Netflix/vmaf#312]
Building with Visual Studio succeeds, but results in a command line of over 17 thousand lines with the string `warning C` appearing 6881 times.

See for example [this AppVeyor run](https://ci.appveyor.com/project/EwoutH/vmaf/builds/22459230) (with [Netflix-vmaf-log.txt](https://github.com/Netflix/vmaf/files/2876520/Netflix-vmaf-log.txt)).

**Comment by Navilor** [comment]
> 
> 
> Building with Visual Studio succeeds, but results in a command line of over 17 thousand lines with the string `warning C` appearing 6881 times.
> 
> See for example [this AppVeyor run](https://ci.appveyor.com/project/EwoutH/vmaf/builds/22459230) (with [Netflix-vmaf-log.txt](https://github.com/Netflix/vmaf/files/2876520/Netflix-vmaf-log.txt)).

ptools is a dependency for vmaf which I had to figure out the hard way.

Compile ptools before compiling vmaf. You will still get a ton of errors, but after figuring that out I was able to compile vmaf with a ton of errors. When I ran vmafossexec.exe against two examples the comparison was about 20. Using vmaf inside of MSU VQMT I got a score of 92.139.

**Comment by nilfm** [comment]
Closing this old issue as part of a clean-up. We did fix some warnings a while ago in #1004.
