### ISSUE TITLE
Erroneous results with video game footage

### ISSUE THREAD

**Issue by FireCulex** [Netflix/vmaf#321]
If I take 10 10 second clips of game #1 at 1080p60, atleast 3 will will score below 80 while the rest will score 90+ at 1080p60. Even at 250mbps the 3 would not score higher then 78. Hardware encoding with Quicksync 32 ICQ.

Today I was recording an Xbox Game

```
culex@ubuntu:/mnt/hgfs/testing$ ffmpeg -i clip1.m4v -i clip1.avi -lavfi libvmaf="psnr=1:ssim=1:ms_ssim=1" -f null -

VMAF score  = 3.869796
PSNR score = 24.926430
SSIM score = 0.880202
MS-SSIM score  = 0.890978
[libvmaf @ 0x56132ce1ac80] VMAF score: 3.869796

culex@ubuntu:/mnt/hgfs/testing$ ffmpeg -i clip3.m4v -i clip3.avi -lavfi libvmaf="psnr=1:ssim=1:ms_ssim=1" -f null -

VMAF score  = 0.683414
PSNR score = 23.111038
SSIM score = 0.786090
MS-SSIM score = 0.787885
[libvmaf @ 0x556ea187c4c0] VMAF score: 0.683414

ffmpeg -i clip2.m4v -i clip2.avi -lavfi libvmaf="psnr=1:ssim=1:ms_ssim=1" -f null -

VMAF score = 92.217242
PSNR score = 43.362736
SSIM score = 0.992338
MS-SSIM score = 0.991838
[libvmaf @ 0x5624d76a29c0] VMAF score: 92.217242
```

My theory is it has to do with motion blur in video games.

**Comment by Agamemnus-uA** [comment]
Hey mate, can you tell us how you record from the xBox? Are you able to make the originals of clip 1 and 3 available somehow? I have been testing dozens and dozens of game captures and never seen anything like that, but all mine are captured straight from the PC and onto the PC. Do the encoded versions look strange at all?  Are you able to convert them to yuv420p, check that they still look OK, and try it again on those versions? Your FFMPEG might be decoding them wrong.

**Comment by FireCulex** [comment]
Hey, small internet! You can find the clips [here](https://www.dropbox.com/sh/2m8n1d5rdyydtmx/AACpg3BYEBdo41d0iPvLQmMAa?dl=0)
I'm recording via Avermedia C985 capture card. OBS is set to NV12 is YV12 and both set to 709 partial. According to MediaInfo they are captured as YUV420.
I've been training a new model. I'm kind of bad with scales and more of a Pass or Fail kind of guy.

**Comment by FireCulex** [comment]
I think something is actually breaking with handbrake because I dont get the same results with ffmpeg.
