### ISSUE TITLE
Linuxbrew model path not working

### ISSUE THREAD

**Issue by slhck** [Netflix/vmaf#324]
VMAF is available as a [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/libvmaf.rb), which is installed into:

    /home/linuxbrew/.linuxbrew/Cellar/libvmaf

under Linuxbrew, or

    /usr/local/Cellar/libvmaf

under macOS.

When running ffmpeg with libvmaf compiled, it looks for the default model file in:

    /usr/local/share/model/vmaf_v0.6.1.pkl

This works fine for macOS, as there's a symlink:

    /usr/local/share/model -> ../Cellar/libvmaf/1.3.13/share/model

But under Linuxbrew, it doesn't exist:

```
ls -l /usr/local/share/
drwxr-xr-x 2 root root 4096 Apr 12 08:25 ca-certificates
drwxr-xr-x 2 root root 4096 Mar  7 21:00 man
```

So with Linuxbrew and ffmpeg compiled with libvmaf, ffmpeg dies with:

```
Caught VmafException: Error loading model (.pkl): Trouble reading the file:/usr/local/share/model/vmaf_v0.6.1.pkl
```

The Homebrew formula's `test` method shows how to override this when calling ffmpeg, using the private variable `share` that is available while installing the formula, but this is not accessible to the user at runtime.

I'll have to look at why that is.

The issue can be reproduced with [this Dockerfile](https://github.com/slhck/ffmpeg-quality-metrics/blob/master/Dockerfile).

**Comment by slhck** [comment]
Opened an issue here: https://github.com/Homebrew/linuxbrew-core/issues/12531

**Comment by slhck** [comment]
Closed in favor of https://github.com/Homebrew/linuxbrew-core/issues/12531.

As a workaround, use:

```
$(brew --prefix libvmaf)/share/model/vmaf_v0.6.1.pkl
```

**Comment by slhck** [comment]
Reopened since Linuxbrew won't install to `/usr/locla/share/` but some other path. The `libvmaf.c` ffmpeg code should be updated to not hardcode the path to the model location, but perhaps be patched during installation via Homebrew.

**Comment by slhck** [comment]
@kylophone With the API/model format changes, do you see a better way to address this in a platform-independent way? It'd be nice if end users wouldn't have to specify the exact model path or remember where the models are saved.

**Comment by 1480c1** [comment]
One thing I could think of would be to add a configure option to ffmpeg and others for distributors to set a default path or manually sed it like https://github.com/m-ab-s/media-autobuild_suite/pull/1508/files or alternativly, set it to relative to the executable [pathtools.c](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-pathtools/pathtools.c)

**Comment by nilfm** [comment]
Closing this as part of a clean-up. It seems it was solved some time ago. Please feel free to re-open if needed.
