### ISSUE TITLE
Run VMAF with Luma only YUV (4:0:0)

### ISSUE THREAD

**Issue by XiaYi59** [Netflix/vmaf#330]
Hi everyone, 

I was looking at the vmafossexec.exe and found that the input format supported for yuv are the following : yuv420p, yuv422p, yuv444p, yuv420p10le, yuv422p10le, yuv444p10le.

Unfortunately, I have some distorded videos with luma only (format 400) but it does not seem to be incorporated, even if the VMAF score is performed on the luminance only. Is there any way to perform the VMAF score (and other incorporated metrics such as PSNR, SSIM, etc) for this format?

Thank you in advance!

**Comment by slhck** [comment]
If you run it through ffmpeg you could use a filter `format=yuv420p`.

```
ffmpeg -i main.avi -i ref.avi -filter_complex \
"[0:v]format=yuv420p[main];[1:v]format=yuv420p[ref];[main][ref]libvmaf" -f null -
```

**Comment by XiaYi59** [comment]
Thanks for your reply, however I don't quite understand what the filter does (I search on the internet but did not find any answer...). 
I mean since the input file is luminance only, what does the filter do for the chroma? (fill it with random values, fill it with null values???) 
How can I be sure that it does not false the results of VMAF or others metrics?

**Comment by slhck** [comment]
The `format` filter changes the pixel format. The Cb/Cr should be all set to 128 if I'm not mistaken. It seems though that the Y values may be changed:

```
ffmpeg -f lavfi -i yuvtestsrc -frames:v 1 -filter:v format=gray,format=yuv420p,extractplanes=y,showinfo -f null /dev/null 2>&1 | grep checksum

ffmpeg -f lavfi -i yuvtestsrc -frames:v 1 -filter:v format=gray,extractplanes=y,showinfo -f null /dev/null 2>&1 | grep checksum
```

Returns:

```
[Parsed_showinfo_3 @ 0x7fa611000d40] n:   0 pts:      0 pts_time:0       pos:       -1 fmt:gray sar:1/1 s:320x240 i:P iskey:1 type:I checksum:6EFCA00B plane_checksum:[6EFCA00B] mean:[128] stdev:[41.4]
[Parsed_showinfo_2 @ 0x7f7f25f38c40] n:   0 pts:      0 pts_time:0       pos:       -1 fmt:gray sar:1/1 s:320x240 i:P iskey:1 type:I checksum:98811098 plane_checksum:[98811098] mean:[130] stdev:[48.3
```

Will have to investigate…

**Comment by slhck** [comment]
Seems you have to set the `-dst_range` option to `1` which forces full range as output for the format conversion:

```
ffmpeg -f lavfi -i yuvtestsrc -frames:v 1 -filter:v format=gray,extractplanes=y,showinfo -f null /dev/null 2>&1 | grep checksum

ffmpeg -f lavfi -i yuvtestsrc -frames:v 1 -filter:v format=gray,format=yuv420p,extractplanes=y,showinfo -dst_range 1 -f null /dev/null 2>&1 | grep checksum
```

Now returns the same checksum:

```
[Parsed_showinfo_2 @ 0x7f9a71c02640] n:   0 pts:      0 pts_time:0       pos:       -1 fmt:gray sar:1/1 s:320x240 i:P iskey:1 type:I checksum:98811098 plane_checksum:[98811098] mean:[130] stdev:[48.3]
[Parsed_showinfo_3 @ 0x7f8793f00d40] n:   0 pts:      0 pts_time:0       pos:       -1 fmt:gray sar:1/1 s:320x240 i:P iskey:1 type:I checksum:98811098 plane_checksum:[98811098] mean:[130] stdev:[48.3]
```

**Comment by XiaYi59** [comment]
Hi! Thank you very much for your fast reply, I think it should be ok now :D
