### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by slhck** [Netflix/vmaf#331]
[Python 2 will be EOLd in 2020](https://legacy.python.org/dev/peps/pep-0373/) and we can expect Python 2 not to be available and maintained anymore soon after that. It would be important to convert this project to Python 3 and drop support for Python 2 in the long run.

This issue should summarize steps required and identify the possible bottlenecks or where most work is needed. I would propose to use this issue and close https://github.com/Netflix/vmaf/issues/233 in favor of this thread.

I've converted SUREAL to Python 3 successfully, but with VMAF there are more open TODOs that go beyond just running `2to3`. In particular, `scanf.py` is something that should be removed entirely.

A first step would be creating a new branch and running `2to3`, then running the unit tests until everything passes again. We can collect any open problems in this thread, then.

What are your thoughts? Are there any resources from others who might be able to help?

**Comment by li-zhi** [comment]
Thanks for giving this some thought. I agree that python3 migration should be given high priority at this moment. 

One question is: do we envision that we directly migrate to python3 and drop support for python2, or, like what you did for SUREAL, it simultaneously supports 2 and 3 for a while?

I'll created a branch out of master called `feature/python3-migration`. Let's start experimenting with this branch.
https://github.com/Netflix/vmaf/tree/feature/python3-migration

**Comment by christosbampis** [comment]
I definitely agree with this. In my opinion, we can have both for a while, and then stop supporting python 2, when we feel that the python 3 version has matured enough. We could also make a disclaimer asking people to avoid using python 2 version in the meantime.

**Comment by slhck** [comment]
Thanks for your support!

Assuming there are no special cases in the codebase, I assume it will be possible to write code that will be compatible with *both* Python 3 and 2, as there are backports of common new functions available. 

Completely switching to Python 3 would allow some more features, which are not necessary though (since this project anyway runs with Python 2). Also, it'd mean you'd lose some users who, I guess, will continue running Python 2 for a while and have their scripts set up to run VMAF. As far as I can tell, not many projects have yet dropped Python 2 support.

**Comment by zsimic** [comment]
I can give this a go.
I think supporting 2 and 3 at the same time (at first) is the way to go.

Then later announce dropping of support for python2 starting at the next version bump (so ppl stuck on python2 can require `vmaf<1.5` for example.

Then, new python3 features can be used for versions >= 1.5 (for example).

I'll give it a go using this approach:
- introduce `tox.ini`, make tests pass via `tox`, exercise only python2 first
- then add python3 to the tox run, iterate until tests pass both with python2 and 3
- bump version to 1.4, announce that 1.4 supports both python2 and 3
- later down the road, when we want to drop support for python2, announce that vmaf v1.5 for example will drop python2 support

**Comment by slhck** [comment]
That sounds great! Note that there isn't even a Python package for VMAF yet that could be installed via `pip`, so that'd be another thing that could be done while doing the migration.

**Comment by zsimic** [comment]
Publishing to pypi would be great, but for that, all of the C code (like in `libsvm/python` would have to be properly described as `Extensions()` in `setup.py`, not a trivial thing to do (will probably need re-thinking how `libsvm` is used from vmaf, can't be a `sys.path` thing)

**Comment by NagabhushanSN95** [comment]
@zsimic just asking, can't you use SVM from scikit-learn package? It is also based on libsvm.

**Comment by li-zhi** [comment]
@NagabhushanSN95 This is possible.

**Comment by slhck** [comment]
I will close this now, seeing that Python 3 is supported. The PyPI issue is a separate one.

**Comment by 1480c1** [comment]
@slhck or @li-zhi can one of you guys close this? The fact that this is open made me think that vmaf does not support python3 yet
