### ISSUE TITLE
What do adm2 & motion stand for?

### ISSUE THREAD

**Issue by lazybing** [Netflix/vmaf#341]
Is the VMAF score only depends on six features,including adm2, motion2, vif_scale0, vif_scale1, vif_scale2 and vif_scale3, but not depends on psnr, ssim or ms_ssim?

I know VIF  stands for Visual Information Fidenlity. What does the adm stand for? I searched all the source code, but I did not find it. and what about adm2 and motion2?

**Comment by slhck** [comment]
See also: https://github.com/Netflix/vmaf/issues/125

**Comment by lazybing** [comment]
> See also: #125

Thanks, it really helped me. I close it.
