### ISSUE TITLE
vif_scale=nan and vmaf=nan on random frame

### ISSUE THREAD

**Issue by Xaymar** [Netflix/vmaf#345]
Occasionally the libvmaf filter in ffmpeg would store `nan` as the vif_scale0 and vmaf info in the JSON output, resulting in files that can't be parsed by most JSON parsers. This seems to not be related to the encoder, and the encoded file actually has all frames that should be compared.

It purely seems to be related to cases where VMAF expects the quality to be different from what it is, and just returns nan instead. No matter how how often i regenerate the input file, the same issue happens and the json output is corrupted as nan is not a valid float.

I have built ffmpeg according to the [guide](https://github.com/Netflix/vmaf/blob/master/resource/doc/libvmaf.md#use-libvmaf-with-ffmpeg) using ffmpeg tag 4.1.3 and vmaf tag 1.3.14. 

* Original File: https://cdn.xaymar.com/samples/games/apex_legends_001.mov
* Encoded File: https://cdn.xaymar.com/samples/encoded/%24bf%243%24rc%24cbr_hq%242p%241%24brm%242%24saq%240%24taq%240%24rcla%2432%24wp%240.mp4
* ffmpeg encode command: `-s 1280x720 -r60/1 -src_range pc -dst_range tv -colorrange tv -c:v h264_nvenc -bf 3 -rc cbr_hq -2pass 1 -b_ref_mode 2 -spatial-aq 0 -temporal-aq 0 -rc-lookahead 32 -weighted_pred 0 -b:v 3500k -bufsize 7000k`
* ffmpeg compare command: `ffmpeg -loglevel error -hide_banner -i $1 -i $2 -filter_complex "[1:v]scale=${input_size}:flags=bicubic[main];[main][0:v]libvmaf=log_path=${file_base}.json:log_fmt=json:psnr=true:ssim=true:ms_ssim=true:n_threads=10" -f null -`

**Comment by Xaymar** [comment]
I've finally been able to run all files through libvmaf after several weeks of computing results, and there's around 100 malformed json files now. The bug seems completely unrelated to anything, but it is a predictable bug which means I can reproduce it with the exact same file and configuration every time.

What does vmaf use to generate json files? As far as I'm aware, [the JSON specification does not consider Infinity or NaN to be valid JSON numbers](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf). So NaN and +-Infinity must either be written as a string, or written as null.

### Steps to final encode.
1. Decompress the video and store it as raw YUV with nothing else changed: `ffmpeg -i "${source_dir}/${source_file}" -an -c:v rawvideo -pix_fmt yuv444p "${cache}/${source_file}"` (source_file = apex_legends_001.mov, source_range = 0, dest_range = 0)
2. Encode using libx264 or h264_nvenc: `ffmpeg -i "${cache}/${source_file}.mov" -an -c:v libx264 -sws_flags bicubic -pix_fmt nv12 -s 1920x1080 -r 60/1 -src_range ${source_range} -dst_range ${dest_range} -b:v 3500k -maxrate 3500k -bufsize 7000k -g 120 -preset veryfast -psy 1 "${dest_file}"`
3. Compare to original file: `ffmpeg -i "${source_dir}/${source_file}" -i "${dest_file}" -filter_complex "[1:v]scale=${input_size}:flags=bicubic[main];[main][0:v]libvmaf=log_path=${dest_file_basename_noext}.json:log_fmt=json:psnr=true:ssim=true:ms_ssim=true:n_threads=10" -f null -` (`input_x = $(ffprobe -v error -hide_banner -select_streams v:0 -i "$1" -of default=noprint_wrapps=1:nokey=1 -show_entries stream=x)`)

**Comment by li-zhi** [comment]
@Xaymar We might have encountered the same issue and subsequently fixed it. Would you please try the same videos using the v1.5.3 release to see if the issue still persists?

**Comment by Xaymar** [comment]
I'll have to rebuild for windows, but yeah I can try once I have that working again.

**Comment by Xaymar** [comment]
@li-zhi I have retried with a new build of libvmaf, and the issue no longer seems to occur. I'll create a new issue if I run into it again, since the original bug seems to have been fixed.

**Comment by li-zhi** [comment]
Great. Thanks for reporting this.
