### ISSUE TITLE
vmafossexec.exe in Windows is only processing a few frames

### ISSUE THREAD

**Issue by alandamore** [Netflix/vmaf#348]
Using a short (17.28 seconds, 432 frames) clip, original from a digital camera 1920x1080, compressed to x265 with handbrake, comparing the files, VMAF is exiting very quickly and only processing 14 frames.
![image](https://user-images.githubusercontent.com/31634149/62301809-2b2a3000-b471-11e9-81c1-3286b09c2f4b.png)
also then gives a very low VMAF score (approx 17)

If I instead use an FFMpeg compile for windows that includes vmaf, that correctly processes all frames on the same files, takes about a minute, and gives an expected high VMAF score ~98 or 99 for higher bitrate encodes.

Tried with vmafossexec.exe from last week and also just tried yesterday's latest build from https://ci.appveyor.com/project/li-zhi/vmaf/build/artifacts (taking the vmaf-win-x64.zip file with everything in it and running from the "release" directory)

Typical command line is as follows (same with or without the "--subsample 1"). Both clips are yuv420p (reported by Mediainfo):

vmafossexec.exe yuv420p 1920 1080 ref-P1140760.MP4 hb-abr-8000-fast-turbo1p.mp4 ..\..\model\vmaf_v0.6.1.pkl --psnr --ssim --ms-ssim --log distorted.csv --subsample 1

If I then try a longer clip (36.48 seconds), it then processes 30 frames before exiting, i.e. proportionally more. It's as if it's processing about a 30th of the frames...

**Comment by HolyWu** [comment]
vmafossexec only supports raw yuv input. So far it cannot demux/decode any other format yet.

**Comment by alandamore** [comment]
Doh, I'm an idiot, was passing it the same files (.mp4) as were passed to FFmpeg. Converting to YUV and all looks good (ffmpeg -i myfile.mp4 -pix_fmt yuv420p -vsync 0 myfile.yuv) so from that point of view this "Issue" can be closed.

What I wasn't expecting is a different VMAF score calculated by ffmpeg compared to vmafossexec (the PSNR, SSIM, MS-SSIM scores are identical though). I calculated VMAF using ffmpeg on both the .mp4 and the .yuv and fortunately they matched, but were about 0.5% higher than the VMAF from vmafossexec on the .yuv file.

So this can be closed... do I need to raise that as a separate ticket or is a difference expected?

**Comment by feyzaozcan** [comment]
> Doh, ben bir aptalım, FFmpeg'e iletilenlerle aynı dosyaları (.mp4) iletiyordu. YUV'ye dönüştürme ve her şey iyi görünüyor (ffmpeg -i myfile.mp4 -pix_fmt yuv420p -vsync 0 myfile.yuv) bu açıdan bu "Sorun" kapatılabilir.
> 
> Beklemediğim şey, vmafossexec ile karşılaştırıldığında ffmpeg tarafından hesaplanan farklı bir VMAF puanıdır (PSNR, SSIM, MS-SSIM puanları yine de aynıdır). VMAF'yi hem .mp4 hem de .yuv üzerinde ffmpeg kullanarak hesapladım ve neyse ki eşleştiler, ancak .yuv dosyasında vmafossexec'in VMAF'sinden yaklaşık% 0,5 daha yüksekti.
> 
> Yani bu kapatılabilir ... Bunu ayrı bir bilet olarak yükseltmem gerekiyor mu yoksa bir fark mı bekleniyor?

hi, could you help me ? could you send me file in this link (  https://ci.appveyor.com/project/li-zhi/vmaf/build/artifacts). Link is not open now. If you have files, can you send me  please? i will so grateful. So necessary this file. Thank you. MAİL : feyzaozcan95@outlook.com
