### ISSUE TITLE
Only a small amount of frame scores are reported

### ISSUE THREAD

**Issue by mrebersv** [Netflix/vmaf#35]
Whenever I do a ./run_vmaf on an original source and transcoded output, I only get a small subset of frames reported.  For example, using a video trailer and a transcoded version with 4496 frames each (verified with ffprobe) at the same geometry and framerate, only 34 frames are reported from the run_vmaf command.

Does VMAF simply sample spots of a video or should this not be happening?

**Comment by li-zhi** [comment]
This should not be happening. All per-frame scores should be reported. I suspect that you are inputing the encoded video rather than the raw YUVs (since you mentioned ffprobe). Is it the case?

**Comment by mrebersv** [comment]
I am supplying full transport streams.  Should this not be the case?  And if not, any idea why it can still get 33 frames in before it quits?

**Comment by li-zhi** [comment]
Then it is compressed. You need to first decode the transport streams into YUV files, before passing them to VMAF. Refer to http://stackoverflow.com/questions/20609760/convert-h264-video-to-raw-yuv-format

**Comment by mrebersv** [comment]
Thank you.  Sorry about erroneously reporting an issue.  You can consider this closed, though any idea why it still got through 33 frames?

**Comment by li-zhi** [comment]
Because the VMAF executable will just treat the input files as raw YUVs (there is no header for YUV, everything is just raw pixels). It reads 33 'frames' until the end of file. The reported scores, of course, are just garbage.

**Comment by mrebersv** [comment]
Thanks for the help!  Sorry to bug you.

**Comment by li-zhi** [comment]
Don't worry about it:)
