### ISSUE TITLE
filtering makes reconstruction video get 100 vmaf scores ??? 

### ISSUE THREAD

**Issue by jayhiter** [Netflix/vmaf#358]
i used **temporal non local means filter** to preprocess a reference video sequence of HEVC of class D, **BasketballPass_416x240_50.yuv**. and after encoding in x264 , the reconstruction video **BasketballPass_tnlm_416x240_50_crf22_rec.yuv**  gets **100** scores, far better than **BasketballPass_416x240_50_crf22_rec.yuv**,the reconstruction video without filter, which only gets **94** scores, while the PSNR and SSIM scores didnt reveal the preprocessed video is better. 

I dont know why. Why would a encoded reconstrucion video get 100 scores? ? Why this non local means filter has such magic ?  I guess there is something unstable in VMAF. 
![微信图片_20190902195231](https://user-images.githubusercontent.com/10448277/64113570-431d0880-cdbd-11e9-9ac4-1dc250d60194.png)

the detail information files:
[BasketballPass_416x240_50_crf22_rec.txt](https://github.com/Netflix/vmaf/files/3565970/BasketballPass_416x240_50_crf22_rec.txt)
[BasketballPass_416x240_50_tnlm_crf22_rec.txt](https://github.com/Netflix/vmaf/files/3565971/BasketballPass_416x240_50_tnlm_crf22_rec.txt)

video file 
BasketballPass_416x240_50.yuv
BasketballPass_tnlm_416x240_50_crf22_rec.yuv
BasketballPass_416x240_50_crf22_rec.yuv

**Comment by JohnhqWang** [comment]
I am not quite sure about your encoding pipeline, let me try to clarify it:

You have 2 encoding pipelines:

1. ref.yuv -> (H.264 crf 22) -> ref_crf22.yuv
2. ref.yuv -> (tnlm) -> ref_tnlm.yuv -> (H.264 crf 22) -> ref_tnlm_crf22.yuv

Then you found that VMAF(ref.yuv, ref_crf22.yuv) = 94 and **VMAF(ref.yuv, ref_tnlm_crf22.yuv) = 100**.

If you calculate the VMAF score of (ref_tnlm.yuv, ref_tnlm_crf22.yuv), you might get a more reasonable score, i.e. around 95 or so.

Please not that most Full-Reference VQA metrics are signal integrity measurement. The encoding pipeline should not include any pre-processing of ref or post-processing of coded clip. VQA should be used between input and output of the codec.

**Comment by jayhiter** [comment]
@JohnhqWang thank you very much for your clear clarification!  You are totally right about encoding pipelines, I now understand maybe VMAF is not adapted for any pre-processing or post-processing in codec, but I am still confused  why would 100 scores happened between two different videos **VMAF(ref.yuv, ref_tnlm_crf22.yuv) = 100** ?

**Comment by slhck** [comment]
VMAF has been trained on original video degraded by lossy compression with no other processing steps being tested. This means that the features used (particularly related to changes in spatial detail) and their weighting may not correctly predict a loss of quality when using filters that have not been part of the original training dataset—it may in fact overpredict the result, clipping at a score of 100.

**Comment by JohnhqWang** [comment]
> @JohnhqWang thank you very much for your clear clarification! You are totally right about encoding pipelines, I now understand maybe VMAF is not adapted for any pre-processing or post-processing in codec, but I am still confused why would 100 scores happened between two different videos **VMAF(ref.yuv, ref_tnlm_crf22.yuv) = 100** ?

This kind of task is beyond the scope of VMAF and the predicted score really does not matter. Since VMAF uses SVM to predict the quality, it is not easy to diagnose in the feature space why **VMAF(ref.yuv, ref_tnlm_crf22.yuv) = 100** happens.

**Comment by jayhiter** [comment]
> > @JohnhqWang thank you very much for your clear clarification! You are totally right about encoding pipelines, I now understand maybe VMAF is not adapted for any pre-processing or post-processing in codec, but I am still confused why would 100 scores happened between two different videos **VMAF(ref.yuv, ref_tnlm_crf22.yuv) = 100** ?
> 
> This kind of task is beyond the scope of VMAF and the predicted score really does not matter. Since VMAF uses SVM to predict the quality, it is not easy to diagnose in the feature space why **VMAF(ref.yuv, ref_tnlm_crf22.yuv) = 100** happens.

Your explanation makes sense, and maybe VMAF should be more general like PSNR or SSIM.

**Comment by jayhiter** [comment]
> VMAF has been trained on original video degraded by lossy compression with no other processing steps being tested. This means that the features used (particularly related to changes in spatial detail) and their weighting may not correctly predict a loss of quality when using filters that have not been part of the original training dataset—it may in fact overpredict the result, clipping at a score of 100.

I guess you are right, pre processing is not included in training process and not used in training dataset, thus filter doesnt applied to this situation. Maybe VMAF just indirectly uses changes in spatial detail as one of its features while the filter changes the spatial detail and makes them get excessively high score, resulting in the result clipped at a score=100, I consider maybe this is a shortcoming of  VMAF.

**Comment by slhck** [comment]
True. It's a shortcoming you'll find in any signal-based model, since you can't test every possible filter subjectively. There's a tradeoff in how precise you can model the most common processing operations, which is for the most part "pure" lossy video compression (i.e. running a video through an encoder with its default options). Even there you can be lucky if you can perform enough subjective tests to include different encoder settings, bitrates, resolutions, etc.

**Comment by jayhiter** [comment]
> True. It's a shortcoming you'll find in any signal-based model, since you can't test every possible filter subjectively. There's a tradeoff in how precise you can model the most common processing operations, which is for the most part "pure" lossy video compression (i.e. running a video through an encoder with its default options). Even there you can be lucky if you can perform enough subjective tests to include different encoder settings, bitrates, resolutions, etc.

Does it mean that VMAF only applied to video compression process, like VMAF(ref.yuv,ref_rec.yuv)?  If I do other video process operations on a video and without using encoder then it is not suitable to use VMAF?

**Comment by slhck** [comment]
You'd have to look at what types of degradations were used when developing VMAF. These define the valid application scope of the model. For example, degradations may include packet loss (i.e. slice recovery artifacts), downscaling, lossy compression, ...

You can find some sample datasets here: https://github.com/Netflix/vmaf/blob/master/resource/doc/datasets.md – for example, Netflix public dataset includes video compressed at different bitrates and resolutions. The VQEG HD3 dataset included encoding with H.264 and MPEG-2 with different packet loss rates:

![image](https://user-images.githubusercontent.com/582444/64341634-10efee80-cfe9-11e9-993c-4979cc43c4a0.png)

(Table from the [VQEG HDTV Phase 1 report](https://www.its.bldrdoc.gov/vqeg/projects/hdtv/hdtv.aspx))

But I'm sure that other (non-public) datasets were trained to build the classifiers, correct, @li-zhi?

I think it would be worthwhile to publish a "model scope" for VMAF that more clearly defines:

- for which application areas the model was trained and validated
- for which it *may* be suitable as judged by the developers
- for which it is definitely not suitable

This is common practice for ITU-T standardized video quality assessment algorithms, see for example Tables 1 through 3 in [ITU-T Rec. P.1203](https://www.itu.int/rec/T-REC-P.1203-201710-I/en).

**Comment by jayhiter** [comment]
@slhck Oh I see, thank u so much!  It would be beneficial to publish a "model scope" for VMAF!

**Comment by li-zhi** [comment]
Agreed with what @JohnhqWang @slhck have said. VMAF was developed intended for compression and scaling artifacts (since they are the two typical artifacts in a HTTP adaptive streaming encoding pipeline). And from feedback we have received, VMAF usually breaks under image enhancement process. The interesting case here is that VMAF score gets boosted instead of dropping. This could be an artifacts of SVM fitting.

@jayhiter I wasn't able to find a link to your videos. We recently created a page to report VMAF bad cases and to upload sample videos. Would you mind upload your videos here:
https://docs.google.com/forms/d/e/1FAIpQLSdJntNoBuucMSiYoK3SDWoY1QN0yiFAi5LyEXuOyXEWJbQBtQ/viewform?usp=sf_link
(It is Google Drive so you may need VPN from China. If there is another means, please let me know.)

**Comment by jayhiter** [comment]
@li-zhi  OK I have uploaded my case into the vmaf bad case report ( use VPN of course haha). I hope it will be helpful to VMAF.

**Comment by li-zhi** [comment]
Many thanks @jayhiter

**Comment by iamzxw** [comment]
@jayhiter 
Hi, I have a question about **temporal non local means filter** ,  which tools did you used for implement temporal non local means?  like, cv2.fastNlMeansDenoisingMulti() or the others?

thanks^_^
