### ISSUE TITLE
run_testing VMAF ( I am doing something wrong?)

### ISSUE THREAD

**Issue by Fernando-Ar** [Netflix/vmaf#363]
I have this problem, when i use run_testing. 

python2 run_testing VMAF ~/vmaf/Dataset-Testing_MOS_original.py ~/vmaf/workspace/model/model-3.pkl --cache-result --parallelize

Stats calculation failed, using default stats calculation. Error cause: 
type object 'VmafQualityRunner' has no attribute 'get_bagging_score_key'
/home/fernando/vmaf/python/src/vmaf/core/perf_metric.py:616: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  a_b = lstsq(Y_mtx, x_vec)[0]

Stats on testing data: (SRCC: 0.558, PCC: 0.510, RMSE: 27.133)

**Comment by li-zhi** [comment]
Is `model-3.pkl` a custom model trained with bootstrapping enabled?

**Comment by Fernando-Ar** [comment]
No. im not use bootstrapping enable. 

python2 ./run_vmaf_training ~/vmaf/Dataset-Training_Mos_Original.py ~/vmaf/resource/feature_param/vmaf_feature_Stem.py ~/vmaf/resource/model_param/libstem_v2_Gamma_0_33_c1.py ~/vmaf/workspace/model/model-3.pkl --cache-result --parallelize

But if I use de original model_param and feature_param i had the same problem and error.

**Comment by Fernando-Ar** [comment]
I installed the ubuntu operating system again. Python2 with libraries and VMAF.
But, the error persists.

**Comment by li-zhi** [comment]
@Fernando-Ar It looks like what you encountered was not an error, since you did get the final results:
```
Stats on testing data: (SRCC: 0.558, PCC: 0.510, RMSE: 27.133)
```
It was a warning, but the message hasn't been very clear (and it needs to be improved). Check out:
https://github.com/Netflix/vmaf/blob/master/python/src/vmaf/routine.py#L301
