### ISSUE TITLE
Implement library logging function, vmaf_log()

### ISSUE THREAD

**Issue by kylophone** [Netflix/vmaf#365]
There is a need for a proper log function complete with log levels. Also, the lib should log to stderr by default (not stdout!) since this may be integrated with apps that might want to have piped output. All calls to `printf()` and `fprintf()` should be replaced with this logging function. This is a relatively easy task, see `av_log()` in ffmpeg for inspiration.

**Comment by rishacha** [comment]
Hi, is this open? Can I try and raise a PR?

**Comment by kylophone** [comment]
Yes, please do.

**Comment by rishacha** [comment]
Sorry, I took a bit of time. Was caught up. 

**Proposed changes**

1. Implement changes based on the following functions taken from `log.h -- AVUTIL_LOG_H`
  1. Log level
  2. Printf compatible string formatting

Taken from `log.h` in FFMpeg
  ```c
/**
 * Send the specified message to the log if the level is less than or equal
 * to the current av_log_level. By default, all logging messages are sent to
 * stderr. This behavior can be altered by setting a different logging callback
 * function.
 * @see av_log_set_callback
 *
 * @param avcl A pointer to an arbitrary struct of which the first field is a
 *        pointer to an AVClass struct or NULL if general log.
 * @param level The importance level of the message expressed using a @ref
 *        lavu_log_constants "Logging Constant".
 * @param fmt The format string (printf-compatible) that specifies how
 *        subsequent arguments are converted to output.
 */
void av_log(void *avcl, int level, const char *fmt, ...) av_printf_format(3, 4);

// av_printf_format
#    define av_printf_format(fmtpos, attrpos) __attribute__((__format__(__printf__, fmtpos, attrpos)))
  ```

Will start by creating a function like this `void vmaf_log(void *vmaf_class, int level, const char *fmt, ...)`

Does this align with what you need @kylophone ?

**Comment by rishacha** [comment]
Another point is - `CONTRIBUTING.md` is not updated and I haven't discovered where I can place the log module files. Please let me know if I can place it under `libvmaf/src` at the same level as `debug.h`. Thank you.

**Comment by kylophone** [comment]
Yes. `libvmaf/src/log.c` and `libvmaf/src/log.h` is the place for this. See my recent PRs for an integration example, and also try to follow the coding style seen there. If you still have questions please feel free to ask. Thanks for your help!

**Comment by kylophone** [comment]
> ```c
> void av_log(void *avcl, int level, const char *fmt, ...)
>  ```

My advice would be don't try to emulate the `av_log()` design exactly, especially the first param `void *avcl`. I'm imagining something more like this:

```c
void vmaf_log(enum VmafLogLevel, const char *fmt, ...)
```

**Comment by rishacha** [comment]
Got it, I'm starting work on `void vmaf_log(enum VmafLogLevel, const char *fmt, ...)`.

**Comment by kylophone** [comment]
How has this been going @rishacha?

**Comment by rishacha** [comment]
@kylophone , I'll be raising a PR by this weekend for review

**Comment by kylophone** [comment]
Great, thank you.

**Comment by kylophone** [comment]
Any news on this?

**Comment by kylophone** [comment]
Bouncing this. Anybody interested in working on this?

**Comment by himanshu007-creator** [comment]
Please close this issue
