### ISSUE TITLE
Info screen for VMAF and bitrate in the NETFLIX portal

### ISSUE THREAD

**Issue by waveletbeam** [Netflix/vmaf#376]
The info screen in the NETFLIX portal show s a VMAF value of 95 at a playing bitrate of 5360 (1920x1080). 

http://projekte.waveletbeam.com/throughput.jpg

I guess the unit is 5360kbps and its a average bitrate right?
Below there is a Throughput bitrate of 41748kbps, which is changing over time. Can you please check, if the unit kbps is correct and if this value reflects the current bitrate?
Thx

**Comment by li-zhi** [comment]
Closing this as this is not VMAF-related.
