### ISSUE TITLE
[RFC] libvmaf v2.0, new API

### ISSUE THREAD

**Issue by kylophone** [Netflix/vmaf#381]
Work is underway for a new `libvmaf` v2.0 API. This is a major breaking change, but should allow us to extend VMAF in the future without another disruptive change. Extensibility is a major issue in the current design. For an example usage of the new `libvmaf` v2.0 API please see below. If you have comments or questions on this change, please leave them below. If you have a use case you feel is not supported by this API please let us know now.

```c
#include <stdio.h>

#include <libvmaf/libvmaf.h>

int main(int argc, char *argv[])
{
    int err = 0;

    /* initialize vmaf context, one or many may be alloc'd at once */
    VmafContext *vmaf;
    VmafConfiguration cfg;
    vmaf_default_configuration(&cfg);

    err = vmaf_init(&vmaf, cfg);
    if (err) {
        fprintf(stderr, "vmaf_init() failed\n");
        return err;
    }

    /* one or many vmaf models */
    VmafModel model_a;
    err = vmaf_model_get_by_name(&model_a, "vmaf_model_a",
                                 VMAF_MODEL_ENABLE_CLIP);
    if (err) {
        fprintf(stderr, "vmaf_get_model_by_name() failed\n");
        return err;
    }
    err = vmaf_use_features_from_model(vmaf, model_a);

    VmafModel model_b;
    err = vmaf_model_get_by_name(&model_b, "vmaf_model_b",
                                 VMAF_MODEL_ENABLE_TRANSFORM);
    if (err) {
        fprintf(stderr, "vmaf_get_model_by_name() failed\n");
        return err;
    }
    err = vmaf_use_features_from_model(vmaf, model_b);

    /* one or many additional features */
    err  = vmaf_use_feature(vmaf, "psnr_y");
    err |= vmaf_use_feature(vmaf, "psnr_cb");
    err |= vmaf_use_feature(vmaf, "psnr_cr");
    err |= vmaf_use_feature(vmaf, "ssim");
    if (err) {
        fprintf(stderr, "vmaf_extract_additional_feature() failed\n");
        return err;
    }

    /* read each pair of pictures in a loop */
    for (unsigned i = 0; i < 100; i++) {
        VmafPicture *ref, *dist;
        err  = vmaf_picture_alloc(ref);
        err |= vmaf_picture_alloc(dist);

        // user fills in pixel data here

        err = vmaf_read_pictures(vmaf, &ref, &dist);
        if (err) {
            fprintf(stderr, "vmaf_read_frame() failed\n");
            return err;
        }
    }

    /* read pooled scores for each model */
    VmafScore score;
    vmaf_score_pooled(vmaf, model_a, VMAF_POOL_MEAN, &score);
    fprintf(stderr, "Model_A, MEAN: %f\n", score.score);
    vmaf_score_pooled(vmaf, model_a, VMAF_POOL_HARMONIC_MEAN, &score);
    fprintf(stderr, "Model_A, HARMONIC: %f\n", score.score);
    vmaf_score_pooled(vmaf, model_b, VMAF_POOL_MEAN, &score);
    fprintf(stderr, "Model_B, MEAN: %f\n", score.score);
    vmaf_score_pooled(vmaf, model_b, VMAF_POOL_HARMONIC_MEAN, &score);
    fprintf(stderr, "Model_B, HARMONIC: %f\n", score.score);

    /* close vmaf context, cleans up all associated memory */
    return vmaf_close(vmaf);
}
```

**Comment by christosbampis** [comment]
One possible suggestion is to pass in to vmaf_model_get_by_name a model configuration, since there can be a model with different options, e.g., vmaf_model_get_by_name(.,.,model_cfg_a).

**Comment by kylophone** [comment]
> One possible suggestion is to pass in to vmaf_model_get_by_name a model configuration, since there can be a model with different options, e.g., vmaf_model_get_by_name(.,.,model_cfg_a).

Yep, this is already supported via the flags parameter.

```
#ifndef __VMAF_MODEL_H__
#define __VMAF_MODEL_H__

#include "libvmaf/libvmaf.h"

enum VmafModelFlags {
    VMAF_MODEL_ENABLE_CLIP = (1 << 0),
    VMAF_MODEL_ENABLE_TRANSFORM = (1 << 1),
};

int vmaf_model_get_by_name(VmafModel *model, char *name, enum VmafModelFlags flags);

#endif /* __VMAF_MODEL_H__ */
```

**Comment by kylophone** [comment]
I should also add. When the new API is published, I will also upstream these changes to `vf_libvmaf.c` in ffmpeg. I'm aware of a few other API users (x265, gstreamer, ...). If you use `libvmaf` somewhere else, please drop a line.

**Comment by colbyn** [comment]
I’ve got a question if you don’t mind. 

I've been using VMAF in one of my projects that I call Imager ([imager-io/imager](https://github.com/imager-io/imager)). More generally, I also maintain a Rust port called [vmaf-sys](https://crates.io/crates/vmaf-sys).  

Anyway at runtime I've noticed that `libvmaf` seems to have issues when multiple instances are running on separate threads within a single process.

I’m not sure why, but it seems to be significantly more likely to segfault, unless there's some mutex locking mechanism in place or whatnot (e.g. as I've done [here](https://github.com/imager-io/imager/blob/913ba964766f7a05a606f0864eaaa899f207093e/imager/src/tool/vmaf.rs#L166)). 

Will the new API allow for simultaneous execution by multiple threads? 

Anyway I was just wondering since I've been using this for images, which typically entail lots of short lived `compute_vmaf` calls.

**Comment by kylophone** [comment]
> I've been using VMAF in one of my projects that I call Imager ([imager-io/imager](https://github.com/imager-io/imager)). More generally, I also maintain a Rust port called [vmaf-sys](https://crates.io/crates/vmaf-sys).

Cool. I'd be interested to work with you when this new API is merged.

> 
> Anyway at runtime I've noticed that `libvmaf` seems to have issues when multiple instances are running on separate threads within a single process.
> 
> I’m not sure why, but it seems to be significantly more likely to segfault, unless there's some mutex locking mechanism in place or whatnot (e.g. as I've done [here](https://github.com/imager-io/imager/blob/913ba964766f7a05a606f0864eaaa899f207093e/imager/src/tool/vmaf.rs#L166)).
> 
> Will the new API allow for simultaneous execution by multiple threads?

Yes. I just created an issue to track this (#393). Looks like most of the globals in this lib are used to store look up tables inside the individual feature extractors. Multi thread two images with mismatching dimensions and things go boom. That's quite bad, but you can expect this to be fixed for the next release.

> 
> Anyway I was just wondering since I've been using this for images, which typically entail lots of short lived `compute_vmaf` calls.
> 
> Update:
> 
> Oh and secondly, regarding `compute_vmaf` (or the new equivalent) could there be support for simply passing in a **model as a string** over **file paths**?

Yes. There will probably be a helper function that looks something like this: `vmaf_get_model_from_path(VmafModel *model, const char *path)`

> 
> The reason is to keep everything self contained and easy for lib consumers. Specially, I’ve been embedding the model file contents into the compiled executable binary (e.g. as I've done [here](https://github.com/colbyn/vmaf-sys/blob/bf06adb72d26a5682186b30049d39cb5e015dce7/src/extras.rs#L27)). This way I don’t need to marshal things into a temporary file.

**Comment by colbyn** [comment]
@kylophone interesting and thanks for the reply. 

Regarding 
> Yes. I just created an issue to track this (#393). Looks like most of the globals in this lib are used to store look up tables inside the individual feature extractors. Multi thread two images with mismatching dimensions and things go boom. That's quite bad, but you can expect this to be fixed for the next release.

Wow, I didn't think this would happen so soon. I'll be looking forward to the next release. 🙂



Regarding:
> Yes. There will probably be a helper function that looks something like this:
> ```C
> vmaf_get_model_from_path(VmafModel *model, const char *path);
> ```

My apologies if I was ambiguous with regards to "passing in a model as a string over file paths". I was thinking more like:
```C
load_from_memory(VmafModel *model, const uint8_t* contents);
```
Where `contents` is the actual file contents of e.g. [model/vmaf_4k_v0.6.1.pkl](https://github.com/Netflix/vmaf/blob/91b093a146ee4e3c02ad96177038547fc387a1c0/model/vmaf_4k_v0.6.1.pkl).

For instance FFmpeg hardcodes a default file path of `/usr/local/share/model/vmaf_v0.6.1.pkl` [here](https://github.com/FFmpeg/FFmpeg/blob/e835a9d30263ce16e2621d79ff1be9afd5274a60/libavfilter/vf_libvmaf.c#L75). Loading from memory would allow for the model to be baked into the binary, and then passed to vmaf as a string.
