### ISSUE TITLE
libvmaf speedup

### ISSUE THREAD

**Issue by kylophone** [Netflix/vmaf#382]
A speedup for libvmaf of at least x2 is targeted. 

Let's use this GitHub issue to track the performance of the `vmafossexec` executable. 

I'm testing on my MacBook using the 500 frame 1080p sequence `ducks_take_off_1080p50.y4m`. This sequence is available [here](https://media.xiph.org/video/derf/). The following shows the basic use of this tool from the command line, as well as usage with a few extra feature extractors. 

Using the basic command line, the speed is about **~23.6 fps.**
```
time ./build/install/usr/local/bin/vmafossexec yuv420p 1920 1080 ducks.yuv ducks.yuv ../model/vmaf_v0.6.1.pkl
./build/install/usr/local/bin/vmafossexec yuv420p 1920 1080 ducks.yuv    134.51s user 15.36s system 708% cpu 21.166 total
```

As you can see, without specifying a thread count with the `--thread` flag, it runs be default (on my machine) with 708% cpu.

When we add the `--thread 1` flag the speed is about **~6.57 fps.**
```
time ./build/install/usr/local/bin/vmafossexec yuv420p 1920 1080 ducks.yuv ducks.yuv ../model/vmaf_v0.6.1.pkl --thread 1                                                                                    
./build/install/usr/local/bin/vmafossexec yuv420p 1920 1080 ducks.yuv    1  67.30s user 9.09s system 99% cpu 1:16.69 total 
```

When we add the `--ssim` flag the speed is about **~5.70 fps.**
```
time ./build/install/usr/local/bin/vmafossexec yuv420p 1920 1080 ducks.yuv ducks.yuv ../model/vmaf_v0.6.1.pkl --thread 1 --ssim                                                                             
./build/install/usr/local/bin/vmafossexec yuv420p 1920 1080 ducks.yuv    1   78.07s user 9.44s system 99% cpu 1:27.65 total
```

When we add the `--ms-ssim` flag the speed is about **~1.36 fps.**
```
time ./build/install/usr/local/bin/vmafossexec yuv420p 1920 1080 ducks.yuv ducks.yuv ../model/vmaf_v0.6.1.pkl --thread 1 --ssim --ms-ssim                                                                   
./build/install/usr/local/bin/vmafossexec yuv420p 1920 1080 ducks.yuv    1    328.13s user 37.72s system 99% cpu 6:06.54 total
```
When we add the `--psnr` flag the speed is about **~1.35 fps.**
```
time ./build/install/usr/local/bin/vmafossexec yuv420p 1920 1080 ducks.yuv ducks.yuv ../model/vmaf_v0.6.1.pkl --thread 1 --ssim --ms-ssim --psnr
./build/install/usr/local/bin/vmafossexec yuv420p 1920 1080 ducks.yuv    1     331.84s user 38.19s system 99% cpu 6:10.66 total
```

The following is the command line we are interested in testing. This is a single threaded run with all available feature extractors enabled.
```
vmafossexec yuv420p 1920 1080 ref.yuv dist.yuv ../model/vmaf_v0.6.1.pkl --thread 1 --ssim --ms-ssim --psnr
```

A flame graph was generated on MacOS using dtrace. Open this SVG in a browser, and you can click through the call stack and see where all of the time is being spent.

| Feature  | Runtime  | Approx FPS|
|---------|--------|---------|
| ADM     | 6.27%  | 20.1 |
| Motion  | 0.67%  | 201.6 |
| MS-SSIM | 70.93% | 1.9 |
| PSNR    | 0.35%  | 386.1 |
| SSIM    | 3.57%  | 37.8 |
| VIF     | 16.86% | 8.0 |

[vmafossexec.svg (1).zip](https://github.com/Netflix/vmaf/files/3795121/vmafossexec.svg.1.zip)

**Comment by flip111** [comment]
Is this the code that runs the longest of time ?? https://github.com/Netflix/vmaf/blob/master/libvmaf/src/feature/iqa/convolve.c#L88-L193  Could it be GPU accelerated perhaps?
