### ISSUE TITLE
[RFC] VMAF models, new data format

### ISSUE THREAD

**Issue by kylophone** [Netflix/vmaf#383]
VMAF models are currently published as a pickled Python dictionary. For `libvmaf`, this adds a pretty large dependency (`ptools`) which itself also requires `pthreads` for some reason. My proposal for libvmaf v2.0 API (see #381) is to pick a more lightweight data format for published VMAF models. JSON probably makes the most sense, but it could always be something else. Please leave your comments here if you have an opinion on this.

**Comment by slhck** [comment]
Definitely +1 for JSON.

**Comment by kylophone** [comment]
https://github.com/Netflix/vmaf/issues/324#issuecomment-548508736

**Comment by kylophone** [comment]
> See also: [#324 (comment)](https://github.com/Netflix/vmaf/issues/324#issuecomment-548508736)

@slhck, do you know of any other packagers that currently provide libvmaf?

**Comment by slhck** [comment]
Not that I'm aware of. Linuxbrew and Homebrew as far as I know.

**Comment by kylophone** [comment]
Just to demonstrate how large of a dependency `ptools` is: 

```
github.com/AlDanial/cloc v 1.76  T=1.06 s (202.8 files/s, 64293.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                            110           5175           3768          23013
C/C++ Header                   101           5825           8545          21701
C Shell                          2             25             31             68
XML                              1              0              0             10
make                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                           215          11025          12344          44793
-------------------------------------------------------------------------------
```

Also, it complies with 90 warnings on my machine.

**Comment by kylophone** [comment]
@christosbampis, can you please convert our currently published models to a JSON format?

- [ ] Provide a JSON schema for the new format (https://json-schema.org/)
- [ ]  Convert the currently published models to this format
- [ ] Create (or reuse) a Python dict to read the data into, provide a Python function to do this reading
- [ ] Create a C structure (`VmafModel`) to hold this data

**Comment by christosbampis** [comment]
sure, on it!

**Comment by christosbampis** [comment]
Here is a draft for the json schema:

schema = {
	"type": "object",
	"properties": {

		"svm_type": {"type": "string"},
		"kernel_type": {"type": "string"},
		"classes_num": {"type": "number"},
		"support_vector_num": {"type": "number"},

		"gamma": {"type": "number"},
		"rho": {"type":  "number"},
		"nu": {"type":  "number"},

		"normalization_type": {"type": "string"},

		"score_clip_low": {"type": "number"},
		"score_clip_high": {"type": "number"},

		"score_transform": {
			"type": "object",
			"properties": {
				"p0": {"type": "number"},
				"p1": {"type": "number"},
				"p2": {"type": "number"},
				"out_gte_in": {"type": "boolean"},
				"out_lte_in": {"type": "boolean"},
			}
		}

		"intercepts": {"type": "array", "items": {"type": "number"}},
		"slopes": {"type": "array", "items": {"type": "number"}},

		"feature_dict": {
			"type": "object",
			"properties": {
				"feature_names": {"type": "array", "items": {"type": "string"}},
			}
		},

	},
}

Let me know if you think any more fields should be added/removed etc.

**Comment by kylophone** [comment]
Can you find a way to get the data from the `.model` files in there as well?

**Comment by christosbampis** [comment]
Yeah, here is what I found inside the .model for 0.6.1:

svm_type, kernel_type, gamma, nr_class, total_sv, rho, SV

so I should probably update the schema to include the support vectors (SV) themselves as well

**Comment by kylophone** [comment]
> Note that the above schema is limited (for now) to the main usecase of SVM, nu-svr.

Do we have a use case for a different type of regression? Would it be useful to experiment with other types? If so, perhaps we should build this into the model schema somehow.

**Comment by christosbampis** [comment]
Thanks, good point! So far, afaik all of the trained models use a nu-SVR. The above schema contains a number of common parameters across different SVR types, but the second group of key-value pairs (gamma, rho, nu) might indeed change (e.g. not needed) for a different SVR.

**Comment by kylophone** [comment]
Another observation: `ptools` compiles with a bunch of undefined behaviour warnings.
