### ISSUE TITLE
Implement VmafPicture

### ISSUE THREAD

**Issue by kylophone** [Netflix/vmaf#385]
Let's use this issue to track the integration of `VmafPicture`.  `VmafPicture` is a type used in the new API, which is designed as a container for pixel data, as well as all associated metadata. Roughly, it should look something like this. If you have any feedback on the design please leave it here.

```c
#ifndef __VMAF_PICTURE_H__
#define __VMAF_PICTURE_H__

#include <stddef.h>

enum VmafPixelFormat {
    VMAF_PIX_FMT_UNKNOWN,
    VMAF_PIX_FMT_YUV420P,
    VMAF_PIX_FMT_YUV422P,
    VMAF_PIX_FMT_YUV444P,
};

typedef struct {
    enum VmafPixelFormat pix_fmt;
    unsigned w, h;
    ptrdiff_t stride[2];
    pixel *data[3];
    int bpc;
} VmafPicture;

int vmaf_picture_alloc(VmafPicture *pic, enum VmafPixelFormat pix_fmt,
                       unsigned bpc, unsigned w, unsigned h);

void vmaf_picture_unref(VmafPicture *pic);

#endif /* __VMAF_PICTURE_H__ */

```

**Comment by kylophone** [comment]
Question for @christosbampis, do we want to add other things like `.colorspace`, `.colormatrix`, etc. to `VmafPicture` ? Could these be useful down the line?

**Comment by christosbampis** [comment]
Sure, they can be useful later, e.g., for HDR where we might want to capture relevant information.

**Comment by kylophone** [comment]
#397 is merged, so closing this issue.
