### ISSUE TITLE
Errors running make installing VMAF Python Library on macOS

### ISSUE THREAD

**Issue by jayholman** [Netflix/vmaf#387]
It looks like there might be some active work on this regarding `meson`, but I wanted to note a couple errors I ran into when running `make`, it failed because it was missing both the `meson` package and `ninja` dependency. I was working off the these instructions: https://github.com/Netflix/vmaf/blob/master/resource/doc/VMAF_Python_library.md#macos and I'm currently on mac OS `10.15.1`.

I solved the issue with`ninja` by simply doing `brew install ninja`. 

`meson` is not quite as simple as `Meson requires Python 3.5.2 or greater` and you will encounter an error message attempting `pip install meson`: 
<img width="685" alt="image" src="https://user-images.githubusercontent.com/15311387/68334127-f5b46480-00a7-11ea-843f-8558cb7f9e58.png">
To avoid that error, I used `pip3 install meson`, which made it possible to complete the `make` installation.

I'm happy to open a PR with those changes added to the macOS instructions if that would be helpful, but it also seems like there is work around that `make` file going on in the most recent closed PRs.

**Comment by christosbampis** [comment]
Sure, feel free to make a PR with those changes in the documentation for mac os.

**Comment by kylophone** [comment]
Closing, should be addressed by #388.
