### ISSUE TITLE
for different scene clip, does the vamf give the same right score?

### ISSUE THREAD

**Issue by lazybing** [Netflix/vmaf#396]
Is the vmaf score suitable for all scenarios?

1. If the vmaf get the same score for different scene clip, such as cartoon/art film/nature scenery fim etc， Does they looks the same good or same bad in human visual effect?

2. For different scene clip, if we look the film the same quality, is the vmaf score the same?

**Comment by christosbampis** [comment]
Hi,
VMAF should be consistent across content types, given that it was trained with different content types. In other words, a VMAF scores same between two content types should mean similar subjective quality, i.e., similar quality perceived by a human.
