### ISSUE TITLE
vmaf.sln file is missing

### ISSUE THREAD

**Issue by PDX-Runner** [Netflix/vmaf#400]
the Visual Studio solution file vmaf.sln is missing from the root folder.

**Comment by 1480c1** [comment]
the solution file was remove when they changed to a meson system https://github.com/Netflix/vmaf/pull/384

If you already know how to use meson, you can look at https://github.com/Netflix/vmaf/tree/master/libvmaf and https://mesonbuild.com/Using-with-Visual-Studio.html to generate your sln file, else you can look at https://github.com/Netflix/vmaf/issues/311 for a cmakelist to use with VS
