### ISSUE TITLE
use partial metrics

### ISSUE THREAD

**Issue by tkkcc** [Netflix/vmaf#403]
Hi, Is there any ways for python or ffmpeg to use partial metrics, for example,  disable motion2 score?

**Comment by christosbampis** [comment]
Hi,
Do you refer to the use of a pre-trained model that excludes this feature, or you want to train a new model? It seems like you need to train a new model that does not have this feature, which is indeed possible, e.g., using https://github.com/Netflix/vmaf/blob/master/python/script/run_vmaf_training.py

**Comment by tkkcc** [comment]
Hi,
Can I make it using a pretrained model?

**Comment by tkkcc** [comment]
I find one way to discard motion part, that is repeating each frame once.

Given a video, if I repeat each frame once(123=>112233), then every two scores are same. The `motion` part is zero on the second and non-zero on the first, as it is only related to the previous frame. The `motion2` part is always zero, as it uses both the previous and the next. It seems like `motion` is discard when `motion2` is zero.

I can get same result if scoring each frame as a single-frame video.

weight v0.6.1 and ffmpeg 4.2.1
