### ISSUE TITLE
Changes in how to build libvmaf.a static library

### ISSUE THREAD

**Issue by ariffinsetya** [Netflix/vmaf#406]
Hi, is there any changes in how to build libvmaf.a, because I'm unable to build it following the guide in the readme..

**Comment by 1480c1** [comment]
```bash
git clone https://github.com/Netflix/vmaf.git
cd vmaf/libvmaf
mkdir build
cd build
meson .. --buildtype=release
ninja
```
You should be able to find `libvmaf.a` under `vmaf/libvmaf/build/src/libvmaf.a`

**Comment by 1480c1** [comment]
They recently changed to a meson build system, but a lot of the docs haven't been updated yet

**Comment by jryzkns** [comment]
I got pretty confused just now when I was trying to build vmafossexec as well, please update the documentations on these!

**Comment by ryanlmcmurray** [comment]
> ```shell
> git clone https://github.com/Netflix/vmaf.git
> cd vmaf/libvmaf
> mkdir build
> cd build
> meson .. --buildtype=release
> ninja
> ```
> 
> You should be able to find `libvmaf.a` under `vmaf/libvmaf/build/src/libvmaf.a`

Tried this, but build dir already exists:
```
$ pwd 
/home/ryan/vmaf/libvmaf 

$ ls -al build | awk '{ print $9 }'
.
..
doc
include
meson-logs
meson-private
src
test
tools
```

So I:

```
$ cd build
$ meson .. --buildtype=release
The Meson build system
Version: 0.49.2
Source dir: /home/ryan/vmaf/libvmaf
Build dir: /home/ryan/vmaf/libvmaf/build
Build type: native build
Project name: libvmaf
Project version: 1.3.16
Native C compiler: cc (gcc 7.4.0 "cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
Native C++ compiler: c++ (gcc 7.4.0 "c++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Configuring version.h using configuration
Program doxygen found: YES (/usr/bin/doxygen)
Configuring Doxyfile using configuration

test/meson.build:3:0: ERROR:  Include directory to be added is not an include directory object.

A full log can be found at /home/ryan/vmaf/libvmaf/build/meson-logs/meson-log.txt
```
How can I work around this?
Thank you!

**Comment by 1480c1** [comment]
Perhaps delete the build folder and rebuild the whole thing?

**Comment by kylophone** [comment]
@ryanlmcmurray, did you solve this? Should be as simple as below. In the meantime, I'll go and clean up all dangling documentation.

```sh
cd libvmaf
meson build --buildtype release
ninja -vC build 
ninja -vC build install
```

**Comment by ryanlmcmurray** [comment]
It didn't work for me

```
pwd /home/ryan/vmaf/libvmaf
rm -rf build
meson build --buildtype release
The Meson build system
Version: 0.49.2
Source dir: /home/ryan/vmaf/libvmaf
Build dir: /home/ryan/vmaf/libvmaf/build
Build type: native build
Project name: libvmaf
Project version: 1.3.16
Native C compiler: cc (gcc 7.4.0 "cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
Native C++ compiler: c++ (gcc 7.4.0 "c++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Configuring version.h using configuration
Program doxygen found: YES (/usr/bin/doxygen)
Configuring Doxyfile using configuration

test/meson.build:3:0: ERROR:  Include directory to be added is not an include directory object.
```

**Comment by kylophone** [comment]
Seems your version of meson has a problem with `test/meson.build`. What system are you on and which version of `meson` do you have? My guess is that it should be possible to provide a backwards compatible fix to the `build.meson` file. If you want to just update your version of `meson`, the minimum supported version (0.47) is described in the libvmaf README file.

https://github.com/Netflix/vmaf/blob/master/libvmaf/README.md

https://github.com/mesonbuild/meson/issues/6024

**Comment by ryanlmcmurray** [comment]
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```
Prior to build attempt, I did upgrade meson on the system.
```
meson -v
0.49.2
```

**Comment by 1480c1** [comment]
Have you tried running the commands in a newly cloned directory? I successfully built vmaf inside a ubuntu:18.04 docker container after installing `git build-essential python3-pip ninja-build` and running the above commands

**Comment by ryanlmcmurray** [comment]
Yes. Before attempting the recommendations earlier today, I started fresh.

**Comment by 1480c1** [comment]
Can you try applying this patch and rerunning?

```patch
From 56172df2d422e5d70a912e693aa4665b5053244d Mon Sep 17 00:00:00 2001
From: Christopher Degawa <ccom@randomderp.com>
Date: Fri, 13 Dec 2019 00:12:44 +0000
Subject: [PATCH] libvmaf/test: Remove test_inc

---
 libvmaf/test/meson.build | 8 +++-----
 1 file changed, 3 insertions(+), 5 deletions(-)

diff --git a/libvmaf/test/meson.build b/libvmaf/test/meson.build
index 6db9f3e..45dec5e 100644
--- a/libvmaf/test/meson.build
+++ b/libvmaf/test/meson.build
@@ -1,18 +1,16 @@
-test_inc = include_directories('.')
-
 test_picture = executable('test_picture',
     ['test.c', 'test_picture.c', '../src/picture.c', '../src/mem.c'],
-    include_directories : [libvmaf_inc, test_inc, '../src/'],
+    include_directories : [libvmaf_inc, '../src/'],
 )
 
 test_feature_collector = executable('test_feature_collector',
     ['test.c', 'test_feature_collector.c',],
-    include_directories : [libvmaf_inc, test_inc, '../src/feature/'],
+    include_directories : [libvmaf_inc, '../src/feature/'],
 )
 
 test_model = executable('test_model',
     ['test.c', 'test_model.c', '../src/svm.cpp', '../src/unpickle.cpp'],
-    include_directories : [libvmaf_inc, test_inc, opencontainers_include,
+    include_directories : [libvmaf_inc, opencontainers_include,
                            '../src/third_party/ptools/', '../src'],
     c_args : vmaf_cflags_common,
     cpp_args : vmaf_cflags_common,
-- 
2.20.1
```

**Comment by ryanlmcmurray** [comment]
Still getting an error
```
git diff
diff --git a/libvmaf/test/meson.build b/libvmaf/test/meson.build
index 6db9f3e..2f2f03b 100644
--- a/libvmaf/test/meson.build
+++ b/libvmaf/test/meson.build
@@ -2,17 +2,17 @@ test_inc = include_directories('.')

 test_picture = executable('test_picture',
     ['test.c', 'test_picture.c', '../src/picture.c', '../src/mem.c'],
-    include_directories : [libvmaf_inc, test_inc, '../src/'],
+    include_directories : [libvmaf_inc, '../src/'],
 )

 test_feature_collector = executable('test_feature_collector',
     ['test.c', 'test_feature_collector.c',],
-    include_directories : [libvmaf_inc, test_inc, '../src/feature/'],
+    include_directories : [libvmaf_inc, '../src/feature/'],
 )

 test_model = executable('test_model',
     ['test.c', 'test_model.c', '../src/svm.cpp', '../src/unpickle.cpp'],
-    include_directories : [libvmaf_inc, test_inc, opencontainers_include,
+    include_directories : [libvmaf_inc, opencontainers_include,
                            '../src/third_party/ptools/', '../src'],
     c_args : vmaf_cflags_common,
     cpp_args : vmaf_cflags_common,
```
```
meson build --buildtype release
The Meson build system
Version: 0.49.2
Source dir: /home/ryan/vmaf/libvmaf
Build dir: /home/ryan/vmaf/libvmaf/build
Build type: native build
Project name: libvmaf
Project version: 1.3.16
Native C compiler: cc (gcc 7.4.0 "cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
Native C++ compiler: c++ (gcc 7.4.0 "c++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Configuring version.h using configuration
Program doxygen found: YES (/usr/bin/doxygen)
Configuring Doxyfile using configuration

test/meson.build:3:0: ERROR:  Include directory to be added is not an include directory object.

A full log can be found at /home/ryan/vmaf/libvmaf/build/meson-logs/meson-log.txt
```

**Comment by 1480c1** [comment]
Make sure you are deleting the first two lines in that file or check to see if `/home/ryan/vmaf/libvmaf/build/meson-logs/meson-log.txt` has any information

**Comment by ryanlmcmurray** [comment]
I did not delete the first 2 lines yesterday. Did that today and attempted build failed.
```
cat libvmaf/test/meson.build
test_picture = executable('test_picture',
    ['test.c', 'test_picture.c', '../src/picture.c', '../src/mem.c'],
    include_directories : [libvmaf_inc, '../src/'],
)

test_feature_collector = executable('test_feature_collector',
    ['test.c', 'test_feature_collector.c',],
    include_directories : [libvmaf_inc, '../src/feature/'],
)

test_model = executable('test_model',
    ['test.c', 'test_model.c', '../src/svm.cpp', '../src/unpickle.cpp'],
    include_directories : [libvmaf_inc, opencontainers_include,
                           '../src/third_party/ptools/', '../src'],
    c_args : vmaf_cflags_common,
    cpp_args : vmaf_cflags_common,
    objects : libptools.extract_all_objects(),
    dependencies : thread_lib,
)

test('test_picture', test_picture)
test('test_feature_collector', test_feature_collector)
test('test_model', test_model)
```
```
cat libvmaf/build/meson-logs/meson-log.txt
Build started at 2019-12-13T07:03:26.981215
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.49.2
Source dir: /home/ryan/vmaf/libvmaf
Build dir: /home/ryan/vmaf/libvmaf/build
Build type: native build
Project name: libvmaf
Project version: 1.3.16
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc /home/ryan/vmaf/libvmaf/build/meson-private/sanitycheckc.c -o /home/ryan/vmaf/libvmaf/build/meson-private/sanitycheckc.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/ryan/vmaf/libvmaf/build/meson-private/sanitycheckc.exe
Native C compiler: cc (gcc 7.4.0 "cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ /home/ryan/vmaf/libvmaf/build/meson-private/sanitycheckcpp.cc -o /home/ryan/vmaf/libvmaf/build/meson-private/sanitycheckcpp.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/ryan/vmaf/libvmaf/build/meson-private/sanitycheckcpp.exe
Native C++ compiler: c++ (gcc 7.4.0 "c++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Configuring version.h using configuration
Program doxygen found: YES (/usr/bin/doxygen)
Configuring Doxyfile using configuration

test/meson.build:1:0: ERROR:  Include directory to be added is not an include directory object.
```

**Comment by kylophone** [comment]
Wondering if there is any resolution on this?

**Comment by FreddyX078** [comment]
Also wondering for a solution. 
I need a static ffmpeg build (macos) but with latest vmaf.git, it links always to the shared dylib.
When removing the dylib, ffmpeg won't find and build with vmaf.
Version 1.3.15 works fine for ffmpeg but prevents mpv from build, this works fine with latest git but same problem with shared lib.

**Comment by kylophone** [comment]
Try again. https://github.com/Netflix/vmaf/commit/d629092415ee8ec3fab8e7abde7c7d2b25b2959d Should have fixed this.

**Comment by 1480c1** [comment]
That only solves linking vmafosexec, not clang chosing the dynamic lib when linking ffmpeg

**Comment by kylophone** [comment]
> That only solves linking vmafosexec, not clang chosing the dynamic lib when linking ffmpeg

Should fix https://github.com/Netflix/vmaf/issues/406#issuecomment-573626996.

**Comment by duvrai** [comment]
> ```shell
> cd libvmaf
> meson build --buildtype release
> ninja -vC build 
> ninja -vC build install
> ```

This works nicely on Ubuntu 19.10, ffmpeg also compiled succefully with --enable-vmaf as described in [the docs](https://github.com/Netflix/vmaf/blob/master/resource/doc/libvmaf.md).

**Comment by kylophone** [comment]
OK, good. Closing this for now, feel free to ping if this is still an issue.

**Comment by elkhazin** [comment]
Hi I seem to be having the same problem on centos-release-7-4.1708.el7.centos.x86_64. I edited libvmaf/test/meson.build  and removed test_inc:

test_picture = executable('test_picture',
    ['test.c', 'test_picture.c', '../src/picture.c', '../src/mem.c'],
    include_directories : [libvmaf_inc, '../src/'],
)

test_feature_collector = executable('test_feature_collector',
    ['test.c', 'test_feature_collector.c',],
    include_directories : [libvmaf_inc, '../src/feature/'],
)

test_thread_pool = executable('test_thread_pool',
    ['test.c', 'test_thread_pool.c', '../src/thread_pool.c'],
    include_directories : [libvmaf_inc, '../src/'],
    dependencies : thread_lib,
)

test_model = executable('test_model',
    ['test.c', 'test_model.c', '../src/svm.cpp', '../src/unpickle.cpp'],
    include_directories : [libvmaf_inc, opencontainers_include,
                           '../src/third_party/ptools/', '../src'],
    c_args : vmaf_cflags_common,
    cpp_args : vmaf_cflags_common,
    objects : libptools.extract_all_objects(),
    dependencies : thread_lib,
)

test_predict = executable('test_predict',
    ['test.c', 'test_predict.c', '../src/predict.c',
     '../src/feature/feature_collector.c', '../src/model.c', '../src/svm.cpp',
     '../src/unpickle.cpp'],
    include_directories : [libvmaf_inc,  opencontainers_include,
                           '../src/third_party/ptools/', '../src'],
    c_args : vmaf_cflags_common,
    cpp_args : vmaf_cflags_common,
    objects : libptools.extract_all_objects(),
    dependencies : thread_lib,
)

test_feature_extractor = executable('test_feature_extractor',
    ['test.c', 'test_feature_extractor.c', '../src/mem.c'],
    include_directories : [libvmaf_inc,  '../src/'],
    dependencies : math_lib,
    objects : [
      convolution_and_psnr_avx_static_lib.extract_all_objects(),
      libvmaf_feature_static_lib.extract_all_objects(),
      libvmaf_rc_feature_static_lib.extract_all_objects(),
    ]
)

test('test_picture', test_picture)
test('test_feature_collector', test_feature_collector)
test('test_thread_pool', test_thread_pool)
test('test_model', test_model)
test('test_predict', test_predict)
test('test_feature_extractor', test_feature_extractor)_


I ran ' meson build --buildtype release' but got the same error as ryanlmcmurray:


[akrume@xsjakrume40x libvmaf]$ cat build/meson-logs/meson-log.txt
Build started at 2020-02-12T18:42:33.671308
Main binary: /usr/bin/python3.6
Python system: Linux
The Meson build system
Version: 0.47.2
Source dir: /wrk/xsjhdnobkup5/akrume/vmaf/libvmaf
Build dir: /wrk/xsjhdnobkup5/akrume/vmaf/libvmaf/build
Build type: native build
Project name: libvmaf
Project version: 1.3.16
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc /wrk/xsjhdnobkup5/akrume/vmaf/libvmaf/build/meson-private/sanitycheckc.c -o /wrk/xsjhdnobkup5/akrume/vmaf/libvmaf/build/meson-private/sanitycheckc.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /wrk/xsjhdnobkup5/akrume/vmaf/libvmaf/build/meson-private/sanitycheckc.exe
Native C compiler: cc (gcc 4.8.5 "cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)")
Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ /wrk/xsjhdnobkup5/akrume/vmaf/libvmaf/build/meson-private/sanitycheckcpp.cc -o /wrk/xsjhdnobkup5/akrume/vmaf/libvmaf/build/meson-private/sanitycheckcpp.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /wrk/xsjhdnobkup5/akrume/vmaf/libvmaf/build/meson-private/sanitycheckcpp.exe
Native C++ compiler: c++ (gcc 7.3.0 "c++ (GCC) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Running compile:
Working directory:  /tmp/tmpgvetza5z
Command line:  cc /tmp/tmpgvetza5z/testfile.c -pipe -D_FILE_OFFSET_BITS=64 -o /tmp/tmpgvetza5z/output.exe -O0 -Wl,--start-group -lm -Wl,--end-group -Wl,--allow-shlib-undefined

Code:
 int main(int argc, char **argv) { return 0; }
Compiler stdout:

Compiler stderr:

Library m found: YES
Configuring version.h using configuration
Program doxygen found: YES (/usr/bin/doxygen)
Configuring Doxyfile using configuration

test/meson.build:2:0: ERROR:  Include directory to be added is not an include directory object.


Does anyone have a fix that might work on centos? or maybe I'm missing something. Thanks

**Comment by 1480c1** [comment]
attempting to run in a centos:7.4.1708 docker container
```bash
docker run -it centos:7.4.1708
yum update -y
yum install python3-pip git gcc gcc-c++clang
pip3 install meson ninja
git clone https://github.com/Netflix/vmaf.git
cd vmaf/libvmaf
meson build
ninja -C build/
````
And I make it past the meson step but get stopped at ninja since it seems both gcc (`Red Hat 4.8.5-39`) and clang (`3.4.2`) in the default repo does not have `stdatomic.h` https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58016

**Comment by TheGrayFrost** [comment]
@1480c1 You can use the newer version of gcc. The CentOS defaults and rpm's are way too old. [Here](https://linuxize.com/post/how-to-install-gcc-compiler-on-centos-7/)

**Comment by kylophone** [comment]
> attempting to run in a centos:7.4.1708 docker container
> 
> ```shell
> docker run -it centos:7.4.1708
> yum update -y
> yum install python3-pip git gcc gcc-c++clang
> pip3 install meson ninja
> git clone https://github.com/Netflix/vmaf.git
> cd vmaf/libvmaf
> meson build
> ninja -C build/
> ```
> 
> And I make it past the meson step but get stopped at ninja since it seems both gcc (`Red Hat 4.8.5-39`) and clang (`3.4.2`) in the default repo does not have `stdatomic.h` https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58016

Does 31565cf45237bfa271b22f2626ad6c142ecbc9d4 fix this issue?

**Comment by 1480c1** [comment]
>> ...
> > And I make it past the meson step but get stopped at ninja since it seems both gcc (`Red Hat 4.8.5-39`) and clang (`3.4.2`) in the default repo does not have `stdatomic.h` https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58016
> 
> Does [31565cf](https://github.com/Netflix/vmaf/commit/31565cf45237bfa271b22f2626ad6c142ecbc9d4) fix this issue?

Seems to have worked

```none
[124/124] Linking target test/test_predict
[root@515334d9d57f libvmaf]# ninja -C build/ test/
ninja: Entering directory `build/'
[1/2] Running all tests.
1/6 test_picture                            OK      0.021465063095092773 s
2/6 test_feature_collector                  OK      0.00959157943725586 s
3/6 test_thread_pool                        OK      0.01644301414489746 s
4/6 test_model                              OK      0.023130178451538086 s
5/6 test_predict                            OK      0.01362919807434082 s
6/6 test_feature_extractor                  OK      0.12009644508361816 s

Ok:                 6
Expected Fail:      0
Fail:               0
Unexpected Pass:    0
Skipped:            0
Timeout:            0

Full log written to /vmaf/libvmaf/build/meson-logs/testlog.txt
[root@515334d9d57f libvmaf]#
```

**Comment by kylophone** [comment]
> Seems to have worked

Thanks!
