### ISSUE TITLE
Viewing distance for phone model

### ISSUE THREAD

**Issue by Agamemnus-uA** [Netflix/vmaf#415]
Hi, can anybody tell me how to set distance when training a model like the cell-phone model?

In the documentation for models, under the Cellular Phone Screen section, it says "Instead of fixating the viewing distance, each subject is instructed to view the video at a distance he/she feels comfortable with."

In https://github.com/Netflix/vmaf/blob/master/libvmaf/src/feature/adm_tools.h on line 275 it defines a viewing distance.

So ultimately, what I'm really asking, is how was this viewing distance set for the cell phone model training, and consequently, how would I set it for my training if I want to adopt a similar subjective testing setup of "at the distance the viewer feels comfortable with" ?

**Comment by li-zhi** [comment]
A standard viewing distance for 1080p is 3H, that is, 3x the screen height.
At this distance for phone viewing, human eyes would not be able to focus.
My recommendation is to fixate at a distance between 4x and 5x instead.

**Comment by Agamemnus-uA** [comment]
Thank you for the response. So it comes down to fixing the distance at a reasonable average? There's no such thing as setting variable distances or ranges?

Is it fair to say that if the subjective test was done on 1080p monitors in circumstances where most viewers would watch at only 1.5h to 2.0h that I should fix the distance for ADM at something like 1.75h ?

**Comment by li-zhi** [comment]
The viewing distance / screen size is a dominant factoring impact video
quality, and yes, you will have to assume a fixed distance to start with.
Yes, if most viewers watches at 1.5H to 2H, a reasonable assumption is
setting the ADM parameter at 1.75H. Unfortunately VIF doesn't have such a
parameter as it is not human visual system motivated, but rather
information theory motivated.

**Comment by Agamemnus-uA** [comment]
Fantastic. Thank you very much for your help.
