### ISSUE TITLE
Travis failure during libsvm build

### ISSUE THREAD

**Issue by kylophone** [Netflix/vmaf#416]
@1480c1 , Any idea why this is failing all of a sudden?

```
0.06s$ make -C third_party/libsvm -j lib
make: Entering directory '/home/travis/build/Netflix/vmaf/third_party/libsvm'
ccache g++-7 -w -Wconversion -O3 -fPIC -c svm.cpp
ccache: error: Failed to create directory /home/travis/.ccache/1/8: Permission denied
Makefile:26: recipe for target 'svm.o' failed
make: *** [svm.o] Error 1
make: Leaving directory '/home/travis/build/Netflix/vmaf/third_party/libsvm'
The command "make -C third_party/libsvm -j lib" exited with 2.
```

https://travis-ci.org/Netflix/vmaf/jobs/624248501#L6209

**Comment by kylophone** [comment]
This may have been transient. This one passed: https://travis-ci.org/Netflix/vmaf/jobs/624359616?utm_medium=notification&utm_source=github_status

**Comment by 1480c1** [comment]
Perhaps one of the `sudo make install` or `sudo ninja install` is messing up the cache. Maybe might need a `sudo chown` on the cache right before the libsvm build

**Comment by kylophone** [comment]
Closing. Seems to be fixed now: https://travis-ci.org/Netflix/vmaf/builds/624752254
