### ISSUE TITLE
What to do with the DLL and ffmpeg?

### ISSUE THREAD

**Issue by flip111** [Netflix/vmaf#417]
I followed the instructions on how to compile vmaf, i now have a file `libvmaf.dll`. Does anyknow know how to use this file, by for example ffmpeg? I also downloaded `ffmpeg-4.2.1-win64-static.zip` which has `ffmpeg.exe`.

**Comment by 1480c1** [comment]
You would need to recompile ffmpeg with the new dll file since your static build of ffmpeg will not care about your dll file

**Comment by slhck** [comment]
You could use this project: https://github.com/m-ab-s/media-autobuild_suite

It creates an FFmpeg build including libvmaf for you. That's usually faster than trying to manually compile, depending on your expertise.

**Comment by flip111** [comment]
@slhck that's great advice, i will try this tool

@1480c1 I thought that static build of ffmpeg was that it had all default components (statically) build into the binary ... not that it had removed the ability to load dynamic libraries ...

**Comment by 1480c1** [comment]
It usually means that the libraries and needed code are in one executable. In the case of the ffmpeg you downloaded, it probably linked a `libvmaf.lib` or `libvmaf.lib` that someone else already compiled, so your ffmpeg will not look for a `libvmaf.dll`

**Comment by 1480c1** [comment]
Technically, you can selectively link certain dependencies as static and some as dynamic(since some licenses forbid static linking in some cases), but it's not really recommended
