### ISSUE TITLE
vmaf usage

### ISSUE THREAD

**Issue by imneonizer** [Netflix/vmaf#425]
Hey, this tool is exactly what I was looking for
I have various RTSP streams / Video files lying around but it becomes really tedious to keep a check on the video quality as a human perspective.

I successfully cloned this repository, ran the unit test and checked on the provided example all runs smoothly which means now I should be able to examine video quality of any clip lying on my local storage.

But the thing is, all provided examples have used two input i.e 
1. reference_path
2. distorted_path

And the second thing is, all the input format is in YUV plus we manually need to provide the video resolution (height/width).

I just wanted to use this tool to examine the video quality but this seems really complicated and challenging.

Can you please give me a minimal step by step walkthrough to examine any video / RTSP streams.

or is it necessary to provide a ``referece_path and distorted_path`` and from where do I bring the distorted_path if only what I have a is an mp4 video file.

Thanks

**Comment by imneonizer** [comment]
I tried to convert my mp4 file (2gb) and 5min duration, to YUV format using ffmpeg now it's (111gb) this could not be the most efficient way to examine a video clip.

**Comment by slhck** [comment]
Check the ffmpeg usage examples: https://github.com/Netflix/vmaf/blob/master/resource/doc/libvmaf.md#use-libvmafa-with-ffmpeg — here you can specify reference and distorted input directly, even from other formats and without having to create YUV intermediates.

**Comment by slhck** [comment]
Oh, and note that if you only have a distorted/received MP4 file, then you cannot use VMAF. VMAF is a full reference model that requires access to the original source of the video before it was compressed/transmitted.

**Comment by imneonizer** [comment]
@slhck, thanks for the clearance now I understood what's these reference/distorted paths are.
I'll try to work accordingly.
