### ISSUE TITLE
which tool do you use to convert video into .yuv file?

### ISSUE THREAD

**Issue by hopingjuly** [Netflix/vmaf#43]
which tool do you use to convert video into .yuv file?

**Comment by li-zhi** [comment]
You can use ffmpeg:
ffmpeg -i video.mp4 -c:v rawvideo -pix_fmt yuv420p out.yuv

Hope this helps.

**Comment by hopingjuly** [comment]
thank you very much

**Comment by hopingjuly** [comment]
reference_path is often a .ts file ,but distorted_path is stream in the video system . In this scenario ,how to get .yuv file ?

**Comment by li-zhi** [comment]
ffmpeg can read .ts file as input as well.

I am not sure what format your distorted_path is. To start with, you probably need to download the stream to local disk before calling ffmpeg.

**Comment by hopingjuly** [comment]
mainly  http & rstp stream
