### ISSUE TITLE
windows vmafossexec result in very low VMAF and no SSIM PSNR output

### ISSUE THREAD

**Issue by xinyi999chen** [Netflix/vmaf#435]
By build the vmaf.sln as instructed and used yuv files provided on th cloud, I have encoutered some problem with vmafossexec in windows and hope I could get a solution. 

![image](https://user-images.githubusercontent.com/59814232/72234835-bf053980-3583-11ea-99ca-fcf390834b98.png)

it turns out that all the frames are analysed yet the aggregate SSIM and PSNR are not calculated and the vmaf score is very low. 
The two video clips are CrowdRun_03_288_375.yuv and CrowdRun_25fps.yuv

The command I used was 
vmafossexec.exe yuv420p 1920 1080 CrowdRun_25fps.yuv CrowdRun_03_288_375.yuv C:\VMAF\vmaf-master\model\vmaf_v0.6.1.pkl --psnr --ssim --log C:VMAF\videos\distort.xml

is there something I did wrong?

**Comment by nilfm** [comment]
There have been significant changes since this issue was opened, closing this as outdated but please feel free to open another one if you have issues with the current version.
