### ISSUE TITLE
SSIM Fixed-Point Feature Extractor, Validation

### ISSUE THREAD

**Issue by kylophone** [Netflix/vmaf#440]
Since #437 there are now two SSIM feature extractors included in `libvmaf_rc`.  These two feature extractors are 1. `ssim`, which was ported from `daala` with a [small patch](https://github.com/Netflix/vmaf/pull/437#issuecomment-573831518), and 2. `float_ssim` which is just a wrapper over the already existing `libvmaf` floating point SSIM implementation. The two calls we are comparing are [`calc_ssim()`](https://github.com/Netflix/vmaf/blob/master/libvmaf/src/feature/integer_ssim.c#L88) which is the fixed-point version, and [`compute_ssim()`](https://github.com/Netflix/vmaf/blob/master/libvmaf/src/feature/ssim.c#L48) which is the floating point version. 

These two calls give close results, but they are not equivalent.  I didn't put any investigative work in besides noting the differences in window size. A closer look will probably reveal there are a few small modifications that should still be made. A quick way to do this is probably just run the original Matlab code and inspect the kernel directly. In order to debug this, first see #429 for some background info and build instructions. Call `vmaf_rc` directly and use both feature extractors as demonstrated below. 

```sh
./build/tools/vmaf_rc \
    --reference ref.y4m  \
    --distorted dist.y4m  \
    --no_prediction \
    --feature ssim \
    --feature float_ssim \
    --output log.xml
```

This will result in the following output (`log.xml`), which can then be parsed and compared:

```xml
<VMAF version="RELEASE_CANDIDATE">
  <frames>
    <frame frameNum="0" ssim="0.941510" float_ssim="0.943480" />
    <frame frameNum="1" ssim="0.935621" float_ssim="0.922607" />
    <frame frameNum="2" ssim="0.934862" float_ssim="0.917944" />
    <frame frameNum="3" ssim="0.936553" float_ssim="0.921523" />
  </frames>
</VMAF>
```

**Comment by li-zhi** [comment]
Is the daala implementation already fixed point?

Why the difference seem to be much larger than we have seen before?

**Comment by kylophone** [comment]
> Is the daala implementation already fixed point?

Yes.

> Why the difference seem to be much larger than we have seen before?

Don't know. This is what we'll be debugging and tracking in this issue.
