### ISSUE TITLE
Raw YUV Input In vmaf_rc 

### ISSUE THREAD

**Issue by kylophone** [Netflix/vmaf#441]
`vmaf_rc` only supports `.y4m` input, while the original `vmafossexec` only reads raw `.yuv` inputs. The intention is that `vmaf_rc` should support both formats.

**Comment by kylophone** [comment]
A number of `vmaf_rc` cli flags will need to be added to accomplish this, `--width`, `--height`, `--bitdepth` and `--pixel_format`.

**Comment by kylophone** [comment]
Both endianness options will need to be supported for high bitdepth (10/12) raw YUVs. I suggest this is handled via the `--bitdepth` option:

- `8`
- `10` / `10le` / `10be`
- `12` / `12le` / `12be`

`10` and `12` could just be aliases for either the `le` or `be` version.

`--pixel_format` should have the following options:
- `420`
- `422`
- `444`

In any case, start with the 8 bit reader, which should be straightforward.

**Comment by li-zhi** [comment]
How would we want to decompose `rgb48le` into these options? Would you treat it as `444`, `16le`? It has one more attribute, which is `planar` vs `interleaved` (conventionally YUV is planar and RGB is interleaved).

**Comment by kylophone** [comment]
> How would we want to decompose `rgb48le` into these options? Would you treat it as `444`, `16le`? It has one more attribute, which is `planar` vs `interleaved` (conventionally YUV is planar and RGB is interleaved).

Both YUV and RGB can be represented in either way. We'd want to pack our `VmafPicture`s to hold data in whichever way is most convenient for feature extraction. My guess is that is planar in all cases. For our cli tool (`vmaf_rc`) we'd want to pick a simple input format to support (perhaps `.ppm`?).  The`libvmaf` FFmpeg libavfilter, `swscale` takes care of all of this dirty work for us. Supporting RGB is fine, add a new pixel format (`VMAF_PIXEL_FORMAT_RGB`) and hold the pixel data in the same `VmafPicture` struct.

**Comment by kylophone** [comment]
Keeping this open since HBD is still not supported.
