### ISSUE TITLE
How does the frame rate affect VMAF?

### ISSUE THREAD

**Issue by crocis** [Netflix/vmaf#446]
How much does the frame rate affect VMAF? for example, if I take a 60fps video and the same video at 30 fps obtained by removing the even frames, do I get similar VMAF scores? does VMAF have a preferred frame rate?

**Comment by christosbampis** [comment]
Hi,
i am not sure what the VMAF comparisons are in this example; is it VMAF(source@60, encode@60) or VMAF(source@60, encode@30)? In the first case, there will be 60 scores reported by VMAF and averaged to yield a single value. In the second case, the source has to be temporally decimated to yield a 30fps source video (same number of frames as the encode). The number of VMAF scores will be 30 and these 30 values will be averaged to yield a single VMAF score. Between these two cases, I am guessing it depends on the amount of compression in the two encodes (@60 and @30).

VMAF does not have a preferred frame rate; the algorithm will just calculate per-frame quality and report back per-frame and average scores. Note that high-frame rates can have a distinct effect on subjective quality, that could have to be taken into account as well.

**Comment by slhck** [comment]
I think the latter part has to be emphasized: For the same source, you won't get a better score for 60 fps video than for 30 fps video (assuming coding quality being equal), as the metric is frame rate agnostic, while subjects are likely to rate the 60 fps video as higher quality.

**Comment by XuShiSheng** [comment]
I am interested in the latter part. 
According to earlier article of Netflix tech blog, the motion feature should be difference in different frame rate (ignoring the coding artifacts). @christosbampis

**Comment by li-zhi** [comment]
Unfortunately VMAF is frame-rate agnostic. The training sample we obtained is 24fps. If you input a video of 60fps, it is going to be treated as slow motion, which which case the `motion` feature is going to generate lower scores, and thus the overall VMAF score is going to be lower (less temporal masking).

**Comment by wabiloo** [comment]
I would like to re-open this, with a follow-up question.
I have tested VMAF (with ffmpeg+libvmaf) and observed something I can't explain.

If I create a video at 50fps (eg. with `ffmpeg -f lavfi -i testsrc=duration=10:size=854x480:rate=50 
-vf "drawtext=text=%{n}:fontsize=72:r=60:x=(w-tw)/2: y=h-(2*lh):fontcolor=white:box=1:boxcolor=0x00000099" test_50fps.mp4`) and then compare it to itself with libvmaf, I get a score of 98.1, with very little variation in per-frame score

If I then create a 25fps version from it (by dropping every other frame) (`ffmpeg -i test_50fps.mp4 -filter:v fps=fps=25 test_50fps_to_25fps.mp4`) and compare it with the original 50fps (but applying the fps filter on the reference as well as part of the ffmpeg command line: `ffmpeg -i test_50fps_to_25fps.mp4 -an -vsync cfr -i test_50fps.mp4 -an -vsync cfr -lavfi "[0:v]setpts=PTS-STARTPTS[dist0];[1:v]fps=fps=25.0, setpts=PTS-STARTPTS[ref0];[dist0][ref0]libvmaf=ssim=1:psnr=1:model_path=vmaf_v0.6.1.pkl:phone_model=0:n_subsample=1:log_fmt=json:log_path=vmaf.json"`) , I get a score of 97, with quite a bit of variation in the per-frame score:

![framescores_ffmpeg_test_pattern](https://user-images.githubusercontent.com/4056263/99846868-075f9180-2b6f-11eb-902f-4cdbde6ca42b.png)

Not sure how to explain that...

**Comment by slhck** [comment]
I would recommend you to create a sample video where each frame has its number rendered into the picture, and then check which frames are really being output for comparison.
