### ISSUE TITLE
Measuring Speedup, Fixed-Point Feature Extractors

### ISSUE THREAD

**Issue by kylophone** [Netflix/vmaf#461]
We are interested in tracking the speedup for each individual feature extractor. Since `libvmaf_rc` has wrapped versions of all `libvmaf` floating-point feature extractors, we will be measuring this speedup using `vmaf_rc`. This requires two separate calls to `vmaf_rc` each time only enabling the single feature extractor we are interesting in measuring. In the following case, the new runtime is `0.72 / 2.97`, or 24.24%. You'll want to make these measurements on an unloaded system, and take the average times from several runs.

```sh
/usr/bin/time/ ./build/tools/vmaf_rc \
    --reference ref.y4m  \
    --distorted dist.y4m  \
    --feature float_ssim \
    --no_prediction

0.72 real         0.60 user         0.11 sys
```

```sh
/usr/bin/time/ ./build/tools/vmaf_rc \
    --reference ref.y4m  \
    --distorted dist.y4m  \
    --feature ssim \
    --no_prediction

2.97 real         2.90 user         0.07 sys
```

Note that these calls to `vmaf_rc` are single threaded, and give us reduction to total CPU time. We will track speedups for each feature extractor in separate issues (like [ssim](https://github.com/Netflix/vmaf/issues/440)). We will track the total speed up of `vmaf_rc` with all feature extractors enabled as well as how `libvmaf_rc` scales in multithreaded mode in separate issue(s). (#462)

Forthcoming fixed-point versions of `adm`, `vif`, and `motion` should be implemented as new `VmafFeatureExtractor`s while leaving the currently wrapped `float_adm`, `float_vif`, and `float_motion` feature extractors (and their underlying function calls) as-is. When these new feature extractors are deemed accurate and stable, the old ones will be deprecated.

**Comment by flip111** [comment]
@kylophone  may i ask what is `libvmaf_rc`? I didn't see info about it in the [header file](https://github.com/Netflix/vmaf/blob/master/libvmaf/include/libvmaf/libvmaf.rc.h)

**Comment by kylophone** [comment]
> @kylophone may i ask what is `libvmaf_rc`? I didn't see info about it in the [header file](https://github.com/Netflix/vmaf/blob/master/libvmaf/include/libvmaf/libvmaf.rc.h)

See https://github.com/Netflix/vmaf/issues/429 for details.
