### ISSUE TITLE
libvmaf does not accept different model path

### ISSUE THREAD

**Issue by flip111** [Netflix/vmaf#465]
I run this command
```
./ffmpeg.exe -i "/c/Users/flip111/Videos/51 default.mkv" -i "/c/Users/flip111/Videos/elephants_dream_1080p24.y4m" -lavfi libvmaf="model_path=C\\:/media-autobuild_suite/local64/share/model/vmaf_v0.6.1.pkl":log_path=VMAF.txt -f null -
```
Everything works fine. Then for test i move the model into the parent directory (the share folder), so `C:\media-autobuild_suite\local64\share\vmaf_v0.6.1.pkl` and adjust the path to `C\\:/media-autobuild_suite/local64/share/vmaf_v0.6.1.pkl`

Then i get an error that there is something wrong with the model. I don't know if the specific error message is interesting. Should be easy to reproduce this situation. I used https://github.com/m-ab-s/media-autobuild_suite

More info about the process i followed: https://github.com/Netflix/vmaf/issues/424

**Comment by li-zhi** [comment]
I assume this is resolved now?

**Comment by flip111** [comment]
I had the problem with path working for when i placed the model path in a specific directory. This was solved in issue #424 then i closed that issue on 15 januari. Then when i move the model to another path and adjust the according directory accordingly it no longer works, that's why i posted this new issue on 25 jan. Can you reopen please ? @li-zhi

**Comment by li-zhi** [comment]
When you moved the model file, have you also moved the companion `vmaf_v0.6.1.pkl.model` file?

**Comment by flip111** [comment]
That could have been the problem.

**Comment by nilfm** [comment]
I'm assuming this is resolved, closing the issue.
