### ISSUE TITLE
Saw some speed differences with similar videos

### ISSUE THREAD

**Issue by flip111** [Netflix/vmaf#466]
I took this video as source https://media.xiph.org/video/derf/y4m/elephants_dream_1080p24.y4m

Then encoded it with x265 setting on ultrafast. When i put quality at level 23 vmaf takes 25:12. On quality level 24 it takes 12:32 and on 21 it takes 12:48. This might be an interesting testcase to figure out why vmaf is sometimes slower. I can upload these videos somewhere if it's of any interest. If it's not helpful feel free to close this issue.

**Comment by kylophone** [comment]
Did you gather these times on an unloaded system?

**Comment by flip111** [comment]
Yes. Got the computer working on some other processes so i can't test it again, but i can upload the videos if needed.

**Comment by flip111** [comment]
I think this was because the source video file was being opened from LAN.
