### ISSUE TITLE
building static library - docs outdated

### ISSUE THREAD

**Issue by tessus** [Netflix/vmaf#476]
I build the static ffmpeg binaries for macOS, but the recent changes to vmaf's build system (and no update to https://github.com/Netflix/vmaf/blob/master/resource/doc/libvmaf.md) are quite puzzling.

It seems that 

```
meson build -Dbuildtype=release -Ddefault_library=static -Dprefix=${TARGET}
```

still builds the dynamic library, and `ninja install` also installs the dynamic lib. IMO it should only compile and install the static lib.

It's not really a showstopper, but a proper build process is always nice to have. Furthermore the above mentioned `libvmaf.md` should be updated to reflect the new build system.

**Comment by tessus** [comment]
I'm not sure why this issue was closed, since none of the build options were documented anywhere.

So how do I build a static lib only? Usually you can set a prefix with `configure`. Do I have to figure this out myself (as I already have) or are you actually improving the doc?

**Comment by kylophone** [comment]
> I'm not sure why this issue was closed, since none of the build options were documented anywhere.
> 
> So how do I build a static lib only? Usually you can set a prefix with `configure`. Do I have to figure this out myself (as I already have) or are you actually improving the doc?

```
meson setup --default-library=static --buildtype=release --prefix=$(pwd)/install build
ninja -vC build install
```

**Comment by tessus** [comment]
Thx, I got that, but it's not in https://github.com/Netflix/vmaf/blob/master/libvmaf/README.md
It should be added to the doc.

**Please note** that `--default-library=static` still builds the dynamic library as well.

**Comment by kslimani** [comment]
I confirm that shared library .so file is builded and copied in lib directory when using :

```shell
meson setup --default-library=static --buildtype=release --prefix="/my/custom/path" --libdir=lib build
ninja -vC build
```

Is there a way to build only static library ?

**Comment by dp289m** [comment]
Is there a static only build please?

**Comment by tessus** [comment]
No there isn't. 
Either the person who closed this issue didn't understand what the problem was, or they didn't care.
