### ISSUE TITLE
Windows build on Appveyor

### ISSUE THREAD

**Issue by Elypha** [Netflix/vmaf#477]
I noticed that when appveyor was introduced, a series of pre-built binaries were offered in the "artifacts" (refer to [this commit](https://github.com/Netflix/vmaf/blob/6aa2a302b54a7f2d2a7a695e45e13244b8779edf/appveyor.yml) and [this appveyor project](https://ci.appveyor.com/project/EwoutH/vmaf/build/artifacts)). However, in the [menson update](https://github.com/Netflix/vmaf/commit/82a86e040371f2ca8665d6c210e3d1d2d608a636#diff-180360612c6b8c4ed830919bbb4dd459) the codes related to publishing binaries seemed to be removed.
Could it be possible to go on providing windows binaries generated by appveyor?

**Comment by EwoutH** [comment]
Thanks for the report, working on it ([branch](https://github.com/EwoutH/vmaf/tree/patch-3))
