### ISSUE TITLE
libvmaf_rc: when supplying multiple models, naming has to be unique

### ISSUE THREAD

**Issue by christosbampis** [Netflix/vmaf#486]
In a recent libvmaf rc PR, models are now loaded using a model configuration, which allows the user to specify a name. Additional logic is needed such that we guarantee/validate that the names (either provided or auto-generated) are unique, such that the logs (XML) are populated correctly. Here are some suggestions:
1. if one model is provided with no name, auto-generate this name as "vmaf"
2. if one model is provided with a name, use that name
3. if multiple models are provided, enforce the user to give names to each one of them. In a separate place, we can also check that these are unique

**Comment by christosbampis** [comment]
+ Log an error if >1 model names are identical.
+ Ensure that model name has valid XML attribute name.

**Comment by li-zhi** [comment]
addressed by #516
