### ISSUE TITLE
Potential VMAF Hack

### ISSUE THREAD

**Issue by ltrudeau-twoorioles** [Netflix/vmaf#489]
It has come to our attention that considerable work as gone into "Gaming" or "Hacking" VMAF. In July 2019, Moscow State University and Dubna State University published a paper entitled [Hacking VMAF with Video Color and Contrast Distortion](https://www.researchgate.net/publication/337394829_Hacking_VMAF_with_Video_Color_and_Contrast_Distortion). As the authors note: 

> The proposed video contrast enhancement approach [...] may be used for cheating in the comparisons via tuning to improve this metric values.

In this paper, the author discuss the use of preprocessors like unsharp masks and histogram  equalizations to increase VMAF scores.

Recently, [an unsharp mask preprocessor as been added to libaom](https://aomedia-review.googlesource.com/c/aom/+/101508). The result presented in the commit are considerably high.

> 150f/SP1/Q
> ugc360p -38.82%
> midres  -28.58%
> hdres(99% done) -37.62%
> 
> 150f/SP1/VBR
> ugc360p -30.46%
> midres  -23.35%
> hdres(95% done) -33.14%

This tool was experimental, but now appears to be more [mainstream](https://aomedia.googlesource.com/aom/+/615dc24579d531cb3a2c9627ab25a3026f9e2b47). While we are glad to see work being done in libAOM to improve perceptual quality, we are afraid that some might inadvertently deceive themselves when assessing the perceptual quality of libaom when `--tune=vmaf` is used in conjunction with the VMAF metric.

As such, we are currently patching AWCY to build libaom with -DCONFIG_TUNE_VMAF=1 (https://github.com/xiph/awcy/issues/193) so it can analyze the impact of `--tune=vmaf`. We hope that these results can help guide decision making in order to harden VMAF against adversarial attacks.

**Comment by grill05** [comment]
> While we are glad to see work being done in libAOM to improve perceptual quality, we are afraid that some might inadvertently deceive themselves when assessing the perceptual quality of libaom when --tune=vmaf is used in conjunction with the VMAF metric.

Could you please elaborate a bit on on what you mean by this? 
In tests, using `--tune=vmaf` (instead of `--tune=psnr/ssim`) does seem to improve perceptual quality as discussed on [the reddit thread](https://www.reddit.com/r/AV1/comments/f0g3yx/libaom_adds_vmaf_tune/)

**Comment by li-zhi** [comment]
VMAF does respond positively to sharpening and contrasting operations, but currently the response may be a bit too sensitive. We look forward to addressing this issue in the next version.

**Comment by li-zhi** [comment]
We have published a memo in response to this issue:
https://docs.google.com/document/d/1dJczEhXO0MZjBSNyKmd3ARiCTdFVMNPBykH4_HMPoyY/edit#heading=h.oaikhnw46pw5
