### ISSUE TITLE
Error when launching run_testing on version 1.1.16

### ISSUE THREAD

**Issue by dumenil** [Netflix/vmaf#49]
Hello,

When we launch the run_testing script for VMAF (./run_testing VMAF dataset.py), we get the following error with new version 1.1.16:
Error: Must have one and only one subclass of QualityRunner with type VMAF, but got 2

It was working fine with the version 1.1.13.

Do you know what could be the problem ?

Thanks!

**Comment by li-zhi** [comment]
@dumenil I made some changes recently that caused this issue. Please pull the latest master branch for the fix. I've also added a few test cases to make sure this wouldn't happen in the future.

**Comment by dumenil** [comment]
thanks a lot li-zhi. it works now :)
