### ISSUE TITLE
Testing VMAF on single images

### ISSUE THREAD

**Issue by abhijay-ghildyal** [Netflix/vmaf#494]
I was testing VMAF to score individual images rather than a sequence. I convert the images to yuv420 format i.e. videos with 1 frame and calculate the scores. Although it works fine most of the time for some samples, there seems to be an issue that the VMAF score is not mean and simply gives 100 as output

For e.g.,

    {
        "executorId": "VMAF_VF0.2.4c-0.6.1",
        "asset": {
            "identifier": "cmd_6796725406884470_6796725406884470_cnn_ref_000026_256x256_vs_cnn_p0_000026_256x256_q_256x256"
        },
        "frames": [
            {
                "frameNum": 0,
                "VMAF_feature_adm2_score": 1.2260154509747,
                "VMAF_feature_motion2_score": 0.0,
                "VMAF_feature_vif_scale0_score": 0.8765117480241295,
                "VMAF_feature_vif_scale1_score": 0.901948384025274,
                "VMAF_feature_vif_scale2_score": 0.9121747786181029,
                "VMAF_feature_vif_scale3_score": 0.9424458778582252,
                "VMAF_score": 100.0
            }
        ],
        "aggregate": {
            "VMAF_feature_adm2_score": 1.2260154509747,
            "VMAF_feature_motion2_score": 0.0,
            "VMAF_feature_vif_scale0_score": 0.8765117480241295,
            "VMAF_feature_vif_scale1_score": 0.901948384025274,
            "VMAF_feature_vif_scale2_score": 0.9121747786181029,
            "VMAF_feature_vif_scale3_score": 0.9424458778582252,
            "VMAF_score": 100.0,
            "method": "mean"
        }
    }

What do you think might be the issue here?

Few more examples:

    cnn/p0/000023,ImportError
    ImportError
    ImportError
    ImportError
    ImportError
    ImportError
    {
        "executorId": "VMAF_VF0.2.4c-0.6.1",
        "asset": {
            "identifier": "cmd_5031609635382921_5031609635382921_cnn_ref_000023_256x256_vs_cnn_p0_000023_256x256_q_256x256"
        },
        "frames": [
            {
                "frameNum": 0,
                "VMAF_feature_adm2_score": 0.8893017021337105,
                "VMAF_feature_motion2_score": 0.0,
                "VMAF_feature_vif_scale0_score": 0.6367421735224548,
                "VMAF_feature_vif_scale1_score": 0.7755905430331848,
                "VMAF_feature_vif_scale2_score": 0.8417476773210772,
                "VMAF_feature_vif_scale3_score": 0.903215843434046,
                "VMAF_score": 60.30249856169861
            }
        ],
        "aggregate": {
            "VMAF_feature_adm2_score": 0.8893017021337105,
            "VMAF_feature_motion2_score": 0.0,
            "VMAF_feature_vif_scale0_score": 0.6367421735224548,
            "VMAF_feature_vif_scale1_score": 0.7755905430331848,
            "VMAF_feature_vif_scale2_score": 0.8417476773210772,
            "VMAF_feature_vif_scale3_score": 0.903215843434046,
            "VMAF_score": 60.30249856169861,
            "method": "mean"
        }
    }
    
    cnn/p0/000024,ImportError
    ImportError
    ImportError
    ImportError
    ImportError
    ImportError
    {
        "executorId": "VMAF_VF0.2.4c-0.6.1",
        "asset": {
            "identifier": "cmd_7346481549740275_7346481549740275_cnn_ref_000024_256x256_vs_cnn_p0_000024_256x256_q_256x256"
        },
        "frames": [
            {
                "frameNum": 0,
                "VMAF_feature_adm2_score": 0.9650648739546922,
                "VMAF_feature_motion2_score": 0.0,
                "VMAF_feature_vif_scale0_score": 0.6598148858092928,
                "VMAF_feature_vif_scale1_score": 0.7467480987089331,
                "VMAF_feature_vif_scale2_score": 0.7729561633374613,
                "VMAF_feature_vif_scale3_score": 0.7835770092422164,
                "VMAF_score": 65.25436365256681
            }
        ],
        "aggregate": {
            "VMAF_feature_adm2_score": 0.9650648739546922,
            "VMAF_feature_motion2_score": 0.0,
            "VMAF_feature_vif_scale0_score": 0.6598148858092928,
            "VMAF_feature_vif_scale1_score": 0.7467480987089331,
            "VMAF_feature_vif_scale2_score": 0.7729561633374613,
            "VMAF_feature_vif_scale3_score": 0.7835770092422164,
            "VMAF_score": 65.25436365256681,
            "method": "mean"
        }
    }

The code also gives me import error but still works. I will try to fix that and see if there are any changes to the result. Till then please can someone let me know why it is giving a value of 100 even though the image that I'm comparing is quite distorted.

**Comment by christosbampis** [comment]
Hi,
I am not sure where these import errors are coming from; if you can share the files along and the command line you are running, I could take a look. Regarding the VMAF of 100 (first example) there is an ADM value of 1.22 which makes me wonder about this value. Are these CNN-like generated distortions?

**Comment by abhijay-ghildyal** [comment]
Yes, it is a CNN based distortion. 

The command I'm running is as follows:

    ./run_vmaf yuv420p 256 256 <file_path>/reference_000026.yuv <file_path>/distorted_000026.yuv --out-fmt json

Here is a link to the files: [link](https://drive.google.com/drive/folders/1gHVGgUd5trWnAQ8vKkldC43kw0wzoaIh?usp=sharing)

Note: ffmpeg command used to convert png to yuv

    ffmpeg -loglevel quiet -y -i <filename>.png -pix_fmt yuv420p <filename>.yuv

Thank you. Please feel free to connect with me via email abhijay@pdx.edu
