### ISSUE TITLE
The well-trained models of SpatioTemporal VMAF and Ensemble VMAF - release?

### ISSUE THREAD

**Issue by Sissuire** [Netflix/vmaf#497]
Here it is. I just read the newly published literature `SpatioTemporal Feature Integration and Model Fusion for Full Reference Video Quality Assessment, Christos G. Bampis, Zhi Li and Alan C. Bovik, IEEE TCSVT, 2018`.
 
I had checked the source files of ST-RRED, SpEED, or ST-MAD, but not found the corresponding models for ST-VMAF and E-VMAF. That is, I can only extract features with these sources but fail to predict the final video quality as the literature says.

Do the models have been released? waiting for a demo as usage in consideration of its quite promising performance.

**Comment by christosbampis** [comment]
Hi,
we have not published the ST-VMAF model yet; for E-VMAF you can rely on the python class EnsembleVmafQualityRunner to get a feeling of how to apply the models on a new test video. One would have to train two models separately and then plug them in to the aforementioned class.
