### ISSUE TITLE
Windows Build Files

### ISSUE THREAD

**Issue by MichaelDenczek** [Netflix/vmaf#502]
The Visual Studio solution and project files are missing from the repo.

**Comment by 1480c1** [comment]
https://github.com/Netflix/vmaf/issues/400

Currently msvc compilation is a bit broken due to msvc not having pthread

**Comment by MichaelDenczek** [comment]
I found version 1.3.1 of VMAF VDK and it has a Windows pthread project that builds and works.  I was hoping to upgrade from 1.3.1 to 1.3.15.  I'll attempt to use Meson to generate solution files...

**Comment by kylophone** [comment]
@MichaelDenczek, have you seen this?: https://mesonbuild.com/Using-with-Visual-Studio.html

**Comment by lrickard** [comment]
Can the README be updated to reflect the removal of the solution file and there being no recommended way to build or use this library on windows? I think "Build VMAF on Windows: follow instructions on this page." should be removed.

**Comment by kylophone** [comment]
> Can the README be updated to reflect the removal of the solution file and there being no recommended way to build or use this library on windows? I think "Build VMAF on Windows: follow instructions on this page." should be removed.

Yes, this needs to be updated.

> To respond to @kylophone for MichailDenczek, I tried the Meson route on windows and I was not able to get libvmaf to built because of pthreads. I think the Meson half went fine. I tried a couple things like pthread replacements and even mingw with no luck. Has anyone gotten this to work on windows recently?

Windows build is supported with  mingw32/64. Visual Studio build will be fixed once `ptools` is deprecated.

**Comment by MichaelDenczek** [comment]
If you get the latest **release**, it does build on Windows.

**Comment by pan-22** [comment]
> If you get the latest **release**, it does build on Windows.
I downloaded the latest vmaf-master and tried to compile it under windows following instructions below:
`meson setup libvmaf/build libvmaf --buildtype release && \
	ninja -vC libvmaf/build install`
I ran the command on "x86 native tools command prompt for VS 2017", and error occurs as "pthread.h : no such file or directory". So I installed the pthread lib but still have the same problem.
I am not sure if I didn't install the "pthread" correctly. Could anyone help? Thanks a lot.

**Comment by 1480c1** [comment]
He said release, not commit, check under the release tab

**Comment by pan-22** [comment]
@1480c1 Thanks a lot! 
I found the version 1.5.1. Would the results of VMAF scores of this version be different fromthe mater commit's version?

**Comment by 1480c1** [comment]
Theoretically, they should not since most of the changes were done to the python scripts, vmaf's new API release candidate, and build system, it would be better to ask @kylophone that though

**Comment by pan-22** [comment]
I downloaded the release version vmaf1.5.1 and tried to compile vmafossexec in "x86 native tools command prompt for VS 2017" with the command:
`meson setup libvmaf/build libvmaf --buildtype release &&  ninja -vC libvmaf/build install`
But it still can't work and returns error:
`ninja: build stopped :subcommand failed`.
Can this version be compiled under Windows? Or did I use the wrong way to compile it？

**Comment by ChaosShu** [comment]
> I downloaded the release version vmaf1.5.1 and tried to compile vmafossexec in "x86 native tools command prompt for VS 2017" with the command:
> `meson setup libvmaf/build libvmaf --buildtype release && ninja -vC libvmaf/build install`
> But it still can't work and returns error:
> `ninja: build stopped :subcommand failed`.
> Can this version be compiled under Windows? Or did I use the wrong way to compile it？

I have the same problem.
My operation(Release Version 1.5.2):
```
meson build --buildtype release
ninja -vC build

```
then error:
`ninja: build stopped: subcommand failed.`

**Comment by HolyWu** [comment]
Building with GCC under MSYS2/MinGW works fine. But building with MSVC is not well supported at the moment due to aforementioned reason.

**Comment by ChaosShu** [comment]
By downloading release version 1.3.4，I can generate vmafossexec.exe directly.

**Comment by HolyWu** [comment]
Because `pthreads-win32` were no longer bundled since release v1.5, and that's a dependency of `ptools`. Just use v1.3.15 in the meantime if you really need a MSVC-compiled VMAF library.

**Comment by ChaosShu** [comment]
THANKS！ It helps me very much~
