### ISSUE TITLE
Question regarding Temporal Pooling

### ISSUE THREAD

**Issue by ruben-ar14-mons** [Netflix/vmaf#517]
While the 'run_vmaf.py' offers different temporal pooling options, none are offered in the CLI of vmafossexec (v.1.3.15). So which of the different methods is used by vmafossexec (per default)?

**Comment by li-zhi** [comment]
`vmafossexec` does offer a few pooling options:
```
pool_method:
        mean (default)
        harmonic_mean
        min
```
If additional pooling methods would be needed, it shouldn't be too
difficult to operate on the per-frame scores parsed from the output log
files.

**Comment by ruben-ar14-mons** [comment]
I dug through the code and found the same methods, but couldn 't find or read out which one was the default ... thanks for clarifying that, it helps a lot

Add. 1: in my bachelors thesis i worked with the default one, but for proper description of testing and experimentation setup i needed that tiny bit of information

> If additional pooling methods would be needed, it shouldn't be too
difficult to operate on the per-frame scores parsed from the output log
files.

Add. 2: i wrote a nice little script to parse final scores of VMAF, (MS-)SSIM, "VMAF-PSNR" and the mean decoding energy (and even some more interesting metrics) for different QPs into a .json "dataset" - it would be easy to adopt it for that purpose.
