### ISSUE TITLE
Still Image Support

### ISSUE THREAD

**Issue by indolering** [Netflix/vmaf#522]
It would be nice if there was native support for still images.

**Comment by li-zhi** [comment]
Using FFmpg+libvmaf will allow you to directly work with still images:
https://github.com/Netflix/vmaf/blob/master/resource/doc/ffmpeg.md

**Comment by JonathanRayner** [comment]
But this documentation doesn't say how to use ffmpeg with libvmaf.

The closest example is how to input .yuv files. But to do this it specifies framerates, whose usage is unclear for a new user.
