### ISSUE TITLE
why read_frame discard the lowest 2 bits before extracting feature when reading yuv420p10le frame？

### ISSUE THREAD

**Issue by XuShiSheng** [Netflix/vmaf#525]
Hi, I would like to know why read_frame handle 10bit picture in this way. Wouldn't it result in a loss of accuracy?

**Comment by li-zhi** [comment]
For yuv420ple input, the operation used in current VMAF implmentation is to first converting values to floating point, and normalize its value to the [0, 255.75] range. This is different from simply discarding the last 2 bits.

**Comment by XuShiSheng** [comment]
oops, my mistake
