### ISSUE TITLE
Which encoders were used to train the default model?

### ISSUE THREAD

**Issue by Nakid26** [Netflix/vmaf#526]
Can anybody tell me what encoders were used on the distortions used to train model vmaf_v0.6.1.pkl? x264? x265? libvpx-vp9? h264_nvenc?

I'm interested in testing how different models trained on distortions from different encoders correlate to subjective scores. That is, if 5 different encoders were used, and a model is trained on 3 of them, how will it perform on 4 and 5? If the next iteration of the model is trained on 4 of them, how will that perform on the 5th? It would be handy to know which encoders were used in the default model for comparative purposes. Ultimately, I want to develop some kind of evidence of how well a model can be expected to perform on codecs that it hasn't seen before vs a model that has.

**Comment by li-zhi** [comment]
vmaf_v0.6.1.pkl is trained using x264 to generate the encoding artifacts. It uses lanczos for pre-encoding downsampling, and bicubic for post-encoding upsampling.

**Comment by Agamemnus-uA** [comment]
Thank you, that's very useful to know.
