### ISSUE TITLE
Different results from ffmpeg+libvmaf and docker version

### ISSUE THREAD

**Issue by vojtila** [Netflix/vmaf#527]
Hi,

I am getting quite different results from ffmpeg (installed with home-brew on MAC) and docker version of VMAF. What seems to be a problem?
FFMPEG:
Command:
ffmpeg -pix_fmt yuv420p10le -s 480x270 -i sparks_ref_480x270.yuv42010le.yuv -pix_fmt yuv420p10le -s 480x270  -i sparks_dis_480x270.yuv42010le.yuv  -lavfi libvmaf="model_path=vmaf_v0.6.1.pkl:log_path=log_sparks.json:log_fmt=json" -f null /dev/null

Output:
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.4)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2-with-options_1 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --disable-libjack --disable-indev=jack --enable-opencl --enable-videotoolbox --disable-htmlpages --enable-libvmaf --enable-version3
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[rawvideo @ 0x7fbbf7807800] Estimating duration from bitrate, this may be inaccurate
Input #0, rawvideo, from 'sparks_ref_480x270.yuv42010le.yuv':
  Duration: 00:00:00.20, start: 0.000000, bitrate: 77760 kb/s
    Stream #0:0: Video: rawvideo (Y3[11][10] / 0xA0B3359), yuv420p10le, 480x270, 77760 kb/s, 25 tbr, 25 tbn, 25 tbc
[rawvideo @ 0x7fbbf8000000] Estimating duration from bitrate, this may be inaccurate
Input #1, rawvideo, from 'sparks_dis_480x270.yuv42010le.yuv':
  Duration: 00:00:00.20, start: 0.000000, bitrate: 77760 kb/s
    Stream #1:0: Video: rawvideo (Y3[11][10] / 0xA0B3359), yuv420p10le, 480x270, 77760 kb/s, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 (rawvideo) -> libvmaf:main
  Stream #1:0 (rawvideo) -> libvmaf:reference
  libvmaf -> Stream #0:0 (wrapped_avframe)
Press [q] to stop, [?] for help
Start calculating VMAF score...
Output #0, null, to '/dev/null':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: wrapped_avframe, yuv420p10le, 480x270, q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc (default)
    Metadata:
      encoder         : Lavc58.54.100 wrapped_avframe
frame=    5 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.20 bitrate=N/A speed=18.4x    
video:3kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Exec FPS: 156.280138
VMAF score = 98.824354

{
  "version":"1.3.15",
  "params":{
    "model":"",
    "scaledWidth":480,
    "scaledHeight":270,
    "subsample":1,
    "num_bootstrap_models":0,
    "bootstrap_model_list_str":""
  },
  "metrics":[
    "adm2",
    "adm_scale0",
    "adm_scale1",
    "adm_scale2",
    "adm_scale3",
    "motion",
    "motion2",
    "vif",
    "vif_scale0",
    "vif_scale1",
    "vif_scale2",
    "vif_scale3",
    "vmaf"
  ],
  "frames":[
    {
      "frameNum":0,
      "metrics":{
        "adm2":0.9984499999999999,
        "adm_scale0":0.98836,
        "adm_scale1":0.99518,
        "adm_scale2":0.9995000000000001,
        "adm_scale3":1.00013,
        "motion":0.0,
        "motion2":0.0,
        "vif":0.8056,
        "vif_scale0":0.75453,
        "vif_scale1":0.97697,
        "vif_scale2":0.9907,
        "vif_scale3":0.99538,
        "vmaf":96.2158
      }
    },
    {
      "frameNum":1,
      "metrics":{
        "adm2":0.997,
        "adm_scale0":0.98582,
        "adm_scale1":0.99188,
        "adm_scale2":0.99814,
        "adm_scale3":0.99939,
        "motion":3.20294,
        "motion2":2.60476,
        "vif":0.77298,
        "vif_scale0":0.71604,
        "vif_scale1":0.9624,
        "vif_scale2":0.98384,
        "vif_scale3":0.9918,
        "vmaf":98.65770999999999
      }
    },
    {
      "frameNum":2,
      "metrics":{
        "adm2":0.9978900000000001,
        "adm_scale0":0.98765,
        "adm_scale1":0.99363,
        "adm_scale2":0.9991100000000001,
        "adm_scale3":0.99978,
        "motion":2.60476,
        "motion2":2.60476,
        "vif":0.78945,
        "vif_scale0":0.73498,
        "vif_scale1":0.97119,
        "vif_scale2":0.98799,
        "vif_scale3":0.99404,
        "vmaf":99.24826
      }
    },
    {
      "frameNum":3,
      "metrics":{
        "adm2":0.99609,
        "adm_scale0":0.98459,
        "adm_scale1":0.99096,
        "adm_scale2":0.9974499999999999,
        "adm_scale3":0.99834,
        "motion":10.19666,
        "motion2":4.1732,
        "vif":0.77733,
        "vif_scale0":0.72038,
        "vif_scale1":0.96679,
        "vif_scale2":0.98606,
        "vif_scale3":0.9928399999999999,
        "vmaf":100.0
      }
    },
    {
      "frameNum":4,
      "metrics":{
        "adm2":0.99754,
        "adm_scale0":0.9881,
        "adm_scale1":0.99297,
        "adm_scale2":0.99879,
        "adm_scale3":0.99938,
        "motion":4.1732,
        "motion2":4.1732,
        "vif":0.80688,
        "vif_scale0":0.75584,
        "vif_scale1":0.97753,
        "vif_scale2":0.991,
        "vif_scale3":0.99541,
        "vmaf":100.0
      }
    }
  ],
  "VMAF score":98.82435418905308,
  "ExecFps":156.2801376477945
}

Docker VMAF:
Command:
docker run --rm -v $(pwd):/tmp vmaf   run_vmaf yuv420p10le 480 270 /tmp/sparks_ref_480x270.yuv42010le.yuv /tmp/sparks_dis_480x270.yuv42010le.yuv  --model-path vmaf_v0.6.1.pkl  --out-fmt json

Output:
ImportError
ImportError
ImportError
ImportError
ImportError
ImportError
ImportError
{
    "executorId": "VMAF_VF0.2.4c-0.6.1",
    "asset": {
        "identifier": "cmd_7809839246629594_7809839246629594_sparks_ref_480x270.yuv42010le_480x270_yuv420p10le_vs_sparks_dis_480x270.yuv42010le_480x270_yuv420p10le_q_480x270"
    },
    "frames": [
        {
            "frameNum": 0,
            "VMAF_feature_adm2_score": 0.9978987884247226,
            "VMAF_feature_motion2_score": 0.0,
            "VMAF_feature_vif_scale0_score": 0.9331476847491079,
            "VMAF_feature_vif_scale1_score": 0.9971928261643997,
            "VMAF_feature_vif_scale2_score": 0.9988025311756966,
            "VMAF_feature_vif_scale3_score": 0.9993382829369319,
            "VMAF_score": 96.82324967077572
        },
        {
            "frameNum": 1,
            "VMAF_feature_adm2_score": 0.9976791393982785,
            "VMAF_feature_motion2_score": 0.776332,
            "VMAF_feature_vif_scale0_score": 0.9116515862034077,
            "VMAF_feature_vif_scale1_score": 0.9955902632914372,
            "VMAF_feature_vif_scale2_score": 0.9981563754436723,
            "VMAF_feature_vif_scale3_score": 0.9987998725237027,
            "VMAF_score": 97.75175313863036
        },
        {
            "frameNum": 2,
            "VMAF_feature_adm2_score": 0.9977915153710375,
            "VMAF_feature_motion2_score": 0.785991,
            "VMAF_feature_vif_scale0_score": 0.9241223260111233,
            "VMAF_feature_vif_scale1_score": 0.9969470576520414,
            "VMAF_feature_vif_scale2_score": 0.9987760882148571,
            "VMAF_feature_vif_scale3_score": 0.9992546049342337,
            "VMAF_score": 97.86479310297443
        },
        {
            "frameNum": 3,
            "VMAF_feature_adm2_score": 0.9986696553642525,
            "VMAF_feature_motion2_score": 1.099759,
            "VMAF_feature_vif_scale0_score": 0.9151587180367634,
            "VMAF_feature_vif_scale1_score": 0.9965925489731359,
            "VMAF_feature_vif_scale2_score": 0.9987787322973828,
            "VMAF_feature_vif_scale3_score": 0.9994960954115581,
            "VMAF_score": 98.497414199183
        },
        {
            "frameNum": 4,
            "VMAF_feature_adm2_score": 0.9988453318075108,
            "VMAF_feature_motion2_score": 1.099759,
            "VMAF_feature_vif_scale0_score": 0.936292274189064,
            "VMAF_feature_vif_scale1_score": 0.9978632056802377,
            "VMAF_feature_vif_scale2_score": 0.9992735055458324,
            "VMAF_feature_vif_scale3_score": 0.9997220699296624,
            "VMAF_score": 98.59212278993385
        }
    ],
    "aggregate": {
        "VMAF_feature_adm2_score": 0.9981768860731602,
        "VMAF_feature_motion2_score": 0.7523681999999999,
        "VMAF_feature_vif_scale0_score": 0.9240745178378933,
        "VMAF_feature_vif_scale1_score": 0.9968371803522504,
        "VMAF_feature_vif_scale2_score": 0.9987574465354883,
        "VMAF_feature_vif_scale3_score": 0.9993221851472178,
        "VMAF_score": 97.90586658029949,
        "method": "mean"
    }
}

**Comment by christosbampis** [comment]
Hi, this appears to be a difference between how ffmpeg does the 10->8 bit conversion and how run_vmaf internally does it. Perhaps the version of ffmpeg that got installed by brew does not have the 10bit fix that was done in ffmpeg: https://github.com/FFmpeg/FFmpeg/commit/e835a9d30263ce16e2621d79ff1be9afd5274a60#diff-a5ec317d1bbe660634497cb981cda18f
Can you try out using the latest ffmpeg master and see if the difference is still there?

**Comment by lucaslefaucheur** [comment]
For Ffmpeg, the first input needs to be the distorted video, and the second video the reference video.
