### ISSUE TITLE
error while loading shared libraries: libvmaf.so

### ISSUE THREAD

**Issue by KuhlTime** [Netflix/vmaf#528]
I just found out about vmaf and wanted to give it a try. I have done everything according to [this](https://github.com/yash1994/Build-FFmpeg-with-libvmaf) guide I found, but when running `ffmpeg` I get this error message:

`ffmpeg: error while loading shared libraries: libvmaf.so: cannot open shared object file: No such file or directory`

I'm running Ubuntu 18.4

I don't see where I could have messed up. Maybe you guys know more. 
Thanks in advance.

**Comment by 1480c1** [comment]
You might need to add `/usr/local/lib` to `LD_LIBRARY_PATH`

**Comment by KuhlTime** [comment]
I have tried what you suggested, but I still get the same error message.

**Comment by 1480c1** [comment]
Did you export it?

Is there a `/usr/local/lib/libvmaf.so`?

**Comment by KuhlTime** [comment]
No there is not.

**Comment by 1480c1** [comment]
Did you run `ninja install`?

**Comment by KuhlTime** [comment]
I did run `make install`.

**Comment by 1480c1** [comment]
When you run `grep libvmaf.so libvmaf/build/meson-logs/install-log.txt`, what shows up?

**Comment by KuhlTime** [comment]
I can't find a build folder inside of `libvmaf`.

**Comment by KuhlTime** [comment]
But nevermind, I don't want to waste your time. It is not that important after all.

**Comment by KuhlTime** [comment]
Found the error. The `libvmaf.so` was under `/usr/local/lib/x86_64-linux-gnu/`. 

And the `build` folder wasn't there because I redownloaded the git repo and forgot to run `make install` again. 🤦‍♂️

Thank you so much for your time and help @1480c1
