### ISSUE TITLE
Training new model - predicted scores have small differential values

### ISSUE THREAD

**Issue by archanaveluswamy** [Netflix/vmaf#529]
Hi,

I am trying to train a new model using my own dataset that we have collected using Subjective testing, when I try and train my model using dmos scores, the predicted scores have a very small difference between them (attaching the plot it generated), for e.g. in the below plot my predicted scores range between 76.8 and 77.35 whereas my dmos ranges from ~49 to 100, Is there something I am doing wrong here.  I have set my norm_type for model param file as none (as I was getting 'Divide by zero' error when I set the norm_type to any other option). 

![1](https://user-images.githubusercontent.com/62689995/77620587-96f66700-6f32-11ea-8802-0e81c4ca9977.png)

My model file looks like this 

model_type = "LIBSVMNUSVR"
model_param_dict = {

    # ==== preprocess: normalize each feature ==== #
    'norm_type': 'none', # default: do nothing
    #'norm_type': 'clip_0to1', # rescale to within [0, 1]
    # 'norm_type': 'clip_minus1to1', # rescale to within [-1, 1]
    #'norm_type': 'normalize', # rescale to mean zero and std one

    # ==== postprocess: clip final quality score ==== #
    #'score_clip': None, # default: do nothing
    'score_clip': [0.0, 100.0], # clip to within [0, 100]

    # ==== libsvmnusvr parameters ==== #

    'gamma': 0.0, # default
    #'gamma': 0.1, # vmafv1

    #'C': 1.0, # default
    'C': 4.0, # vmafv1

    #'nu': 0.5, # default
    'nu': 0.9, # vmafv1
}

Any help is appreciated

**Comment by li-zhi** [comment]
Hi. As you are using SVM, it is sensitive to the norm_type. Usually you will need to normalize it. But  why are you getting `Divide by zero` is puzzling. Is it possible that one of your features are all 0's from your dataset (for example, if your dataset is all-images, they all get motion score of 0)?

**Comment by archanaveluswamy** [comment]
Hi,

Thanks for the reply, I tried to run again with normalising, I had the following error

RuntimeWarning: divide by zero encountered in true_divide
  self.slopes = 1.0 / sds

I have specified motion2 as one my feature in my dataset, I am passing a big YUV file which has around 300 frames, the yuv file was a concatenation of individual yuv images. When I run my training it does give me ouput of the motion score, all it gives me is a plot with SRCC, PCC, RMSE 

Let me know if you need further information

**Comment by li-zhi** [comment]
The issue is that if the dataset is all images, all motion score will be zero. The solution is to exclude the motion feature in your training prameter script, and return the hyperparameters.
