### ISSUE TITLE
Could note make

### ISSUE THREAD

**Issue by soulspark666** [Netflix/vmaf#530]
When I an trying to make it shows the following error:

```
cd third_party/libsvm && make lib
make[1]: Entering directory '/home/colab/vmaf/third_party/libsvm'
if [ "Linux" = "Darwin" ]; then \
	SHARED_LIB_FLAG="-dynamiclib -Wl,-install_name,libsvm.so.2"; \
else \
	SHARED_LIB_FLAG="-shared -Wl,-soname,libsvm.so.2"; \
fi; \
g++ ${SHARED_LIB_FLAG} svm.o -o libsvm.so.2
make[1]: Leaving directory '/home/colab/vmaf/third_party/libsvm'
mkdir -p libvmaf/build && cd libvmaf/build && \
meson .. --buildtype release && \
ninja -vC .
/bin/sh: 2: meson: not found
Makefile:2: recipe for tar
```
Trying to make on
```
Linux 280dd1e97893 4.14.137+ #1 SMP Thu Aug 8 02:47:02 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
```
I have run all commands till [Testing](https://github.com/Netflix/vmaf/blob/master/resource/doc/VMAF_Python_library.md#testing).
It might be possible that I have to change some commands since I am using it on Google Colab since my videos are present on Google Drive.

**Comment by slhck** [comment]
You don't have `meson`.

`pip3 install meson` is required, or install Meson via a different method.

Make sure, if pip succeeded, that the path is available to your current shell.

**Comment by soulspark666** [comment]
did it with the following output
```
WARNING: The directory '/home/colab/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: meson in /home/colab/.local/lib/python3.6/site-packages (0.53.2)
```

**Comment by soulspark666** [comment]
Now ```make``` shows
```
cd third_party/libsvm && make lib
make[1]: Entering directory '/home/colab/vmaf/third_party/libsvm'
if [ "Linux" = "Darwin" ]; then \
	SHARED_LIB_FLAG="-dynamiclib -Wl,-install_name,libsvm.so.2"; \
else \
	SHARED_LIB_FLAG="-shared -Wl,-soname,libsvm.so.2"; \
fi; \
g++ ${SHARED_LIB_FLAG} svm.o -o libsvm.so.2
make[1]: Leaving directory '/home/colab/vmaf/third_party/libsvm'
mkdir -p libvmaf/build && cd libvmaf/build && \
meson .. --buildtype release && \
ninja -vC .
/bin/sh: 2: meson: not found
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 127
```

**Comment by Kirstihly** [comment]
This is quite interesting. I am listing my issues here if anyone can answer this.

When I use the jupyter notebook to import everything separately, I get
ImportError
ImportError
ImportError
ImportError
ImportError
ImportError
ImportError
for the first run. But it is actually imported successfully! And it is not showing ImportError when I run the second time.

**Comment by kylophone** [comment]
Closing this since it doesn't seem to be a build issue anymore. If there is something else that you can't figure out, please create a new issue.

**Comment by Wendyan1989** [comment]
When I make, the following error comes out:

ninja: build stopped: subcommand failed.                                                                                                                                            │./libvmaf/src/feature/feature_extractor.h
make: *** [all] error 1 

How could I solve the problem?
