### ISSUE TITLE
FFMPEG compilation with libvmaf

### ISSUE THREAD

**Issue by gdavila** [Netflix/vmaf#531]
I'm triying to build ffmpeg with vmaf on Ubuntu 18.04.3 LTS. It seems that libvmaf has been rightly installed by following the instructions provide [here ](https://github.com/Netflix/vmaf/tree/master/libvmaf) but when I run `./configure --enable-libvmaf --enable-version3` I got the following error:

```sh
ERROR: libvmaf >= 1.3.9 not found using pkg-config
```
Some suggestions?

**Comment by 1480c1** [comment]
Look at ffbuild log that it tells you to look at and maybe look for any errors it raises near the end

**Comment by gdavila** [comment]
Solved. pkg-config was not rightly  installed.

**Comment by ngcthuong** [comment]
I am still getting the same error despite having pkg-config. 
How did you resolve your problem @gdavila ?

Thanks

**Comment by 1480c1** [comment]
> I am still getting the same error despite having pkg-config.
> How did you resolve your problem @gdavila ?
> 
> Thanks

Check the generated ffbuild/config.log or something. There is usually some kind of message or hint

**Comment by ngcthuong** [comment]
> Package libvmaf was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libvmaf.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libvmaf' found
> ERROR: libvmaf >= 1.3.9 not found using pkg-config

What is the reason for this? I compiled vmaf aready

**Comment by ngcthuong** [comment]
After fix few error related to libvmaf.h and libvmaf.pc, I got this error
> gcc -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -std=c11 -fomit-frame-pointer -pthread -I/usr/local/include/libvmaf -L/usr/local/lib/x86_64-linux-gnu -c -o /tmp/ffconf.Vse4yM6F/test.o /tmp/ffconf.Vse4yM6F/test.c
> gcc -Wl,--as-needed -Wl,-z,noexecstack -I/usr/local/include/libvmaf -L/usr/local/lib/x86_64-linux-gnu -o /tmp/ffconf.Vse4yM6F/test /tmp/ffconf.Vse4yM6F/test.o -lvmaf
> /usr/bin/ld: cannot find -lvmaf
> collect2: error: ld returned 1 exit status

**Comment by gdavila** [comment]
It seems a  different issue than mine. Could you check that libvmaf was rightly installed? If you follow this [steps](https://github.com/Netflix/vmaf/tree/master/libvmaf), you should be able to run [vmafossexec](https://github.com/Netflix/vmaf/blob/master/resource/doc/vmafossexec.md)

**Comment by ngcthuong** [comment]
I have `vmafossexec` in my folder as well 
![image](https://user-images.githubusercontent.com/6524339/79074599-2f664880-7ca2-11ea-824b-ca21f2c29c61.png)

**Comment by 1480c1** [comment]
Do you have a file called `/usr/local/lib/x86_64-linux-gnu/libvmaf.a` or `/usr/local/lib/x86_64-linux-gnu/libvmaf.so`?

**Comment by ngcthuong** [comment]
I have fixed this problem by re-install with sudo. But still got the other error of "no such filter: libvmaf". I will go to other issues for this problem. 

Thanks @1480c1 @gdavila
