### ISSUE TITLE
How to use Nvidia GPU to accelerate VMAF measuring?

### ISSUE THREAD

**Issue by austinac** [Netflix/vmaf#535]
I recently setup FFmpeg + libvmaf on AWS EC2 G4 instance (with Tesla T4 GPU) to do transcoding and VMAF measuring for test purpose, it's easy to use GPU to accelerate transcoding with the following params 
ffmpeg -vsync 0 -hwaccel cuvid -c:v h264_cuvid
but it seems that ffmpeg filter mode doesn't support GPU acceleration, and the params above didn't work with libvmaf filter, so I'm wondering if there is a way to use Nvidia GPU to accelerate VMAF measuring instead of CPU?

**Comment by slhck** [comment]
This is not supported by the libvmaf library. What you are describing is hardware acceleration for decoding/encoding video in ffmpeg before/after it has passed the filter chain. Someone would have to:

1. implement libvmaf with CUDA
2. implement an ffmpeg filter that uses it (cf. https://ffmpeg.org/ffmpeg-filters.html#yadif_005fcuda)

**Comment by austinac** [comment]
> This is not supported by the libvmaf library. What you are describing is hardware acceleration for decoding/encoding video in ffmpeg before/after it has passed the filter chain. Someone would have to:
> 
> 1. implement libvmaf with CUDA
> 2. implement an ffmpeg filter that uses it (cf. https://ffmpeg.org/ffmpeg-filters.html#yadif_005fcuda)
Thanks @slhck, does VMAF python library could make use of GPU?

**Comment by slhck** [comment]
The feature extraction is written in C, so the same applies to running via Python.

**Comment by yabinzhangJohn** [comment]
The processing order is hw_dec, vmaf and hw_enc, where libvmaf is not required to be implemented with CUDA. As [https://ffmpeg.org/doxygen/trunk/hw_decode_8c-example.html], you can transfer decoded content from GPU mem to CPU mem using `av_hwframe_transfer_data`, and process it with normal vmaf filter, but data transfer will sacrifice some performance.

**Comment by slhck** [comment]
@yabinzhangJohn But the actual VMAF computations would be still CPU-based. I don't think that hardware decoding will speed up the VMAF computation significantly. Also, encoding is not needed, as there is no video output that you'd want to use further.

**Comment by yabinzhangJohn** [comment]
@slhck It can server for the combination of GPU based transcoding and CPU based VMAF. With a appropriate frame skip setting, there should be some speed-up due to hardware transcoding.

**Comment by skohler99** [comment]
NVIDIA has done considerable work in this area.  Please contact me if this is still of interest (skohler@nvidia.com)

**Comment by slhck** [comment]
@skohler99 Is any of that work publicly documented or otherwise availble? Would be interesting to see.

**Comment by gedoensmax** [comment]
Hey here is the merge request for CUDA acceleration. We will also integrate with FFmpeg to keep data on the GPU after using NV decoder. https://github.com/Netflix/vmaf/pull/1080
