### ISSUE TITLE
There is  some code O(n2) algorithm complexity  in  combo.c

### ISSUE THREAD

**Issue by ib198669** [Netflix/vmaf#538]
in line 479 and 493:
while(1)
{
... ...
        for(int i = 0; i <= frm_idx; i++)
        {
            int ref_reference_count = get_blur_buf_reference_count(&thread_data->ref_buf_array, i);
            int dis_reference_count = get_blur_buf_reference_count(&thread_data->dis_buf_array, i);

            if((ref_reference_count == 0) && (dis_reference_count == 0))
            {
                release_blur_buf_slot(&thread_data->ref_buf_array, i);
                release_blur_buf_slot(&thread_data->dis_buf_array, i);
            }
        }
...
}

if we have 1000 frame,   in frame_index= 1000 , we must loop 1000*1000 to handle the buffer slot

**Comment by li-zhi** [comment]
We'll be migrating to a new VMAF API (currently called libvmaf_rc), who does not suffer from a similar inefficiency. By then combo.c will be deprecated.

**Comment by ib198669** [comment]
> We'll be migrating to a new VMAF API (currently called libvmaf_rc), who does not suffer from a similar inefficiency. By then combo.c will be deprecated.

thanks ,  it will  be great  if we can avoid this
