### ISSUE TITLE
make error: /usr/bin/ld: cannot find -lptools

### ISSUE THREAD

**Issue by kingchenchina** [Netflix/vmaf#54]
ptools folder is the project's folder, it is always there. 
error information:
/wrapper/obj/main.o /home/cqy/vmaf/wrapper/obj/pugixml.o -L/home/cqy/vmaf/wrapper/../ptools  -lm -lpthread -lptools -Wl,-rpath=/home/cqy/vmaf/wrapper/../ptools
/usr/bin/ld: cannot find -lptools
collect2: error: ld returned 1 exit status
make[1]: *** [vmafossexec] Error 1

anyone can help?

**Comment by cosmin** [comment]
What platform are you attempting to compile this on? The latest version builds for me on OS X as well as on Ubuntu 16.04 without any issues. I suspect there's something related to your build environment but it's hard to tell without more information.

**Comment by kingchenchina** [comment]
thank you, cosmin.
it should be the line ending character issue. clone the source in windows platform, and transfer it to ubuntu, it throws this error. finally, i clone the source directly in ubuntu and it works.
