### ISSUE TITLE
Regarding VMAF features aggregation

### ISSUE THREAD

**Issue by NagabhushanSN95** [Netflix/vmaf#553]
Hi,
When training VMAF SVR, the features from all frames are aggregated to get a 6 dimensional vector. nuSVR is used to regress on MOS scores.
But during testing, VMAF score is computed for each frame and the scores are averaged!

Can you please explain why this is done so?

**Comment by li-zhi** [comment]
You are right. There is a mismatch between the order of the two steps. In principle during testing, we could first aggregate the frames and apply SVM, but we found the ordering yields small discrepancy in practice. Plus, we get the nice property of one score per frame.
