### ISSUE TITLE
create dynamic link library of libvmaf

### ISSUE THREAD

**Issue by PDX-Runner** [Netflix/vmaf#557]
current libvmaf only support static link library. is it possible to create an option to build the library as dynamic link library?

**Comment by 1480c1** [comment]
I think it's something like `meson -Ddefault_library=shared <rest of options>`

**Comment by slhck** [comment]
Isn't the default a dynamically linked lib? See https://github.com/Netflix/vmaf/issues/476

**Comment by tessus** [comment]
Yes, and the problem is that one cannot build a static library alone. The dynamic lib is ALWAYS compiled and installed.
