### ISSUE TITLE
Saturating score and BD-Rate calculation

### ISSUE THREAD

**Issue by tdaede** [Netflix/vmaf#56]
Sometimes depending on content I will generate two points that hit the 99-100 score range, meaning visually lossless. This behavior is mostly fine, but problematic for generating BD-Rate because the cubic fit will have a negative slope. It's pretty frequent on AWCY on a couple of "easy" clips, see for example:

https://arewecompressedyet.com/?job=fix1_pvq_with_daala_dist_30f%402017-01-20T21%3A03%3A04.007Z&job=av1_pvq_30f_Jan12_try3%402017-01-18T09%3A14%3A59.302Z

I'd like to define a standard way to handle it. One obvious way is just to fudge the values such that they are always monotonically increasing.

**Comment by li-zhi** [comment]
@tdaede yes, forcing the curve to be monotonically non-decreasing will be a way to handle it.

But I want to get into more details about this case. I followed the link, but is there a way for me to download the videos so that I can reproduce the behavior locally?
