### ISSUE TITLE
Target videos for comparison and evaluate VMAF Score

### ISSUE THREAD

**Issue by tsinghal18** [Netflix/vmaf#566]
Regarding upscaling the encoded video to match source width and height- 
1) Do we upscale but retain other encoder settings like (bitrate frame rate etc;) same?

My understanding is bitrate needs to be retained same otherwise we will not be able to capture correct compression artifacts

**Comment by slhck** [comment]
When you upscale, you must upscale to an uncompressed and/or lossless format (e.g. raw YUV or FFV1, lossless H.264). Do not upscale and re-encode (i.e., apply lossy compression), as this will introduce compression artifacts.

See https://github.com/Netflix/vmaf/blob/master/resource/doc/ffmpeg.md for a simple example where everything is done internally via ffmpeg.
