### ISSUE TITLE
unittest failure -- FAIL: test_to_json

### ISSUE THREAD

**Issue by ethanjyx** [Netflix/vmaf#57]
Hey there, after I ran make I wanted to run unittest to verify the result, but it does not seem to be working. Here is the trace:

```
.test libsvmnusvr train and predict...
.test random forest train and predict...
.test train, save, load and predict...
.test libsvmnusvr train, save, load and predict...
.......
======================================================================
FAIL: test_to_json (result_test.ResultFormattingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jyx/code/vmaf/python/test/result_test.py", line 147, in test_to_json
    '{\n    "executorId": "SSIM_V1.0", \n    "asset": {\n        "identifier": "test_0_0_checkerboard_1920_1080_10_3_0_0_1920x1080_vs_checkerboard_1920_1080_10_3_1_0_1920x1080_q_1920x1080"\n    }, \n    "frames": [\n        {\n            "frameNum": 0, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.999983, \n            "SSIM_feature_ssim_s_score": 0.935802, \n            "SSIM_score": 0.933353\n        }, \n        {\n            "frameNum": 1, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.999983, \n            "SSIM_feature_ssim_s_score": 0.935802, \n            "SSIM_score": 0.933353\n        }, \n        {\n            "frameNum": 2, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.999983, \n            "SSIM_feature_ssim_s_score": 0.935803, \n            "SSIM_score": 0.933354\n        }\n    ], \n    "aggregate": {\n        "SSIM_feature_ssim_c_score": 0.99740399999999996, \n        "SSIM_feature_ssim_l_score": 0.99998299999999996, \n        "SSIM_feature_ssim_s_score": 0.93580233333333329, \n        "SSIM_score": 0.93335333333333337, \n        "method": "mean"\n    }\n}')
AssertionError: '{\n    "executorId": "SSIM_V1.0", \n    "asset": {\n        "identifier": "test_0_0_checkerboard_1920_1080_10_3_0_0_1920x1080_vs_checkerboard_1920_1080_10_3_1_0_1920x1080_q_1920x1080"\n    }, \n    "frames": [\n        {\n            "frameNum": 0, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.999983, \n            "SSIM_feature_ssim_s_score": 0.935802, \n            "SSIM_score": 0.933353\n        }, \n        {\n            "frameNum": 1, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.999983, \n            "SSIM_feature_ssim_s_score": 0.935802, \n            "SSIM_score": 0.933353\n        }, \n        {\n            "frameNum": 2, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.999983, \n            "SSIM_feature_ssim_s_score": 0.935803, \n            "SSIM_score": 0.933354\n        }\n    ], \n    "aggregate": {\n        "SSIM_feature_ssim_c_score": 0.997404, \n        "SSIM_feature_ssim_l_score": 0.999983, \n        "SSIM_feature_ssim_s_score": 0.9358023333333333, \n        "SSIM_score": 0.9333533333333334, \n        "method": "mean"\n    }\n}' != '{\n    "executorId": "SSIM_V1.0", \n    "asset": {\n        "identifier": "test_0_0_checkerboard_1920_1080_10_3_0_0_1920x1080_vs_checkerboard_1920_1080_10_3_1_0_1920x1080_q_1920x1080"\n    }, \n    "frames": [\n        {\n            "frameNum": 0, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.999983, \n            "SSIM_feature_ssim_s_score": 0.935802, \n            "SSIM_score": 0.933353\n        }, \n        {\n            "frameNum": 1, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.999983, \n            "SSIM_feature_ssim_s_score": 0.935802, \n            "SSIM_score": 0.933353\n        }, \n        {\n            "frameNum": 2, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.999983, \n            "SSIM_feature_ssim_s_score": 0.935803, \n            "SSIM_score": 0.933354\n        }\n    ], \n    "aggregate": {\n        "SSIM_feature_ssim_c_score": 0.99740399999999996, \n        "SSIM_feature_ssim_l_score": 0.99998299999999996, \n        "SSIM_feature_ssim_s_score": 0.93580233333333329, \n        "SSIM_score": 0.93335333333333337, \n        "method": "mean"\n    }\n}'

----------------------------------------------------------------------
Ran 234 tests in 372.974s
```

Does anyone know why?

**Comment by li-zhi** [comment]
More info please. Is this the only test that fails?

**Comment by ethanjyx** [comment]
Right all the previous ones have passed. What other info do you need? I am running on mac os with python 2.7

**Comment by li-zhi** [comment]
Ok. In this case you can probably ignore the error. If you look into the error message, it fails because there is some tiny numeric difference, e.g. 0.9358023333333333 vs. 0.93580233333333329.

**Comment by ethanjyx** [comment]
Sounds like a bug. Should use delta difference when comparing floats.

**Comment by li-zhi** [comment]
The main purpose of this test is to test the json output method. Other tests should already cover numeric results. I could think of a more atomic way to test json...

**Comment by leslie-wang** [comment]
got similar failure at 1.1.6 release at Mac OS. Below is the failure. Seems like it is better beautify error output. :-)

> .test random forest train and predict...
> .test train, save, load and predict...
> .test libsvmnusvr train, save, load and predict...
> .......
> ======================================================================
> FAIL: test_to_json (result_test.ResultFormattingTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/Users/qiwa/workspace/opensouce/video-quality/vmaf/vmaf-1.1.6/python/test/result_test.py", line 147, in test_to_json
>     '{\n    "executorId": "SSIM_V1.0", \n    "asset": {\n        "identifier": "test_0_0_checkerboard_1920_1080_10_3_0_0_1920x1080_vs_checkerboard_1920_1080_10_3_1_0_1920x1080_q_1920x1080"\n    }, \n    "frames": [\n        {\n            "frameNum": 0, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.965512, \n            "SSIM_feature_ssim_s_score": 0.935803, \n            "SSIM_score": 0.901161\n        }, \n        {\n            "frameNum": 1, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.965512, \n            "SSIM_feature_ssim_s_score": 0.935803, \n            "SSIM_score": 0.90116\n        }, \n        {\n            "frameNum": 2, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.965514, \n            "SSIM_feature_ssim_s_score": 0.935804, \n            "SSIM_score": 0.901163\n        }\n    ], \n    "aggregate": {\n        "SSIM_feature_ssim_c_score": 0.99740399999999996, \n        "SSIM_feature_ssim_l_score": 0.96551266666666669, \n        "SSIM_feature_ssim_s_score": 0.93580333333333332, \n        "SSIM_score": 0.90116133333333337, \n        "method": "mean"\n    }\n}')
> AssertionError: '{\n    "executorId": "SSIM_V1.0", \n    "asset": {\n        "identifier": "test_0_0_checkerboard_1920_1080_10_3_0_0_1920x1080_vs_checkerboard_1920_1080_10_3_1_0_1920x1080_q_1920x1080"\n    }, \n    "frames": [\n        {\n            "frameNum": 0, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.965512, \n            "SSIM_feature_ssim_s_score": 0.935803, \n            "SSIM_score": 0.901161\n        }, \n        {\n            "frameNum": 1, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.965512, \n            "SSIM_feature_ssim_s_score": 0.935803, \n            "SSIM_score": 0.90116\n        }, \n        {\n            "frameNum": 2, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.965514, \n            "SSIM_feature_ssim_s_score": 0.935804, \n            "SSIM_score": 0.901163\n        }\n    ], \n    "aggregate": {\n        "SSIM_feature_ssim_c_score": 0.997404, \n        "SSIM_feature_ssim_l_score": 0.9655126666666667, \n        "SSIM_feature_ssim_s_score": 0.9358033333333333, \n        "SSIM_score": 0.9011613333333334, \n        "method": "mean"\n    }\n}' != '{\n    "executorId": "SSIM_V1.0", \n    "asset": {\n        "identifier": "test_0_0_checkerboard_1920_1080_10_3_0_0_1920x1080_vs_checkerboard_1920_1080_10_3_1_0_1920x1080_q_1920x1080"\n    }, \n    "frames": [\n        {\n            "frameNum": 0, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.965512, \n            "SSIM_feature_ssim_s_score": 0.935803, \n            "SSIM_score": 0.901161\n        }, \n        {\n            "frameNum": 1, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.965512, \n            "SSIM_feature_ssim_s_score": 0.935803, \n            "SSIM_score": 0.90116\n        }, \n        {\n            "frameNum": 2, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.965514, \n            "SSIM_feature_ssim_s_score": 0.935804, \n            "SSIM_score": 0.901163\n        }\n    ], \n    "aggregate": {\n        "SSIM_feature_ssim_c_score": 0.99740399999999996, \n        "SSIM_feature_ssim_l_score": 0.96551266666666669, \n        "SSIM_feature_ssim_s_score": 0.93580333333333332, \n        "SSIM_score": 0.90116133333333337, \n        "method": "mean"\n    }\n}'
> 
> ----------------------------------------------------------------------
> Ran 106 tests in 310.566s
> 
> FAILED (failures=1)

**Comment by li-zhi** [comment]
@ethanjyx @leslie-wang I put some changes to the master branch, which should fix this issue. Would you like to try out to see if it works?

**Comment by leslie-wang** [comment]
I downloaded the zip file of master branch. Here is the info:

> $ ls -l
> total 117392
> drwxr-xr-x@ 34 qiwa  staff      1156 Feb 21 14:26 vmaf-master
> -rw-r--r--@  1 qiwa  staff  60101906 Feb 23 21:22 vmaf-master.zip

same result as below:

>======================================================================
>FAIL: test_to_json (result_test.ResultFormattingTest)
>----------------------------------------------------------------------
>Traceback (most recent call last):
>  File "/Users/qiwa/workspace/opensouce/video-quality/vmaf/new-vmaf-master/vmaf-master/python/test/result_test.py", line 153, in test_to_json
>    '{\n    "executorId": "SSIM_V1.0", \n    "asset": {\n        "identifier": "test_0_0_checkerboard_1920_1080_10_3_0_0_1920x1080_vs_checkerboard_1920_1080_10_3_1_0_1920x1080_q_1920x1080"\n    }, \n    "frames": [\n        {\n            "frameNum": 0, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.999983, \n            "SSIM_feature_ssim_s_score": 0.935802, \n            "SSIM_score": 0.933353\n        }, \n        {\n            "frameNum": 1, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.999983, \n            "SSIM_feature_ssim_s_score": 0.935802, \n            "SSIM_score": 0.933353\n        }, \n        {\n            "frameNum": 2, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.999983, \n            "SSIM_feature_ssim_s_score": 0.935803, \n            "SSIM_score": 0.933354\n        }\n    ], \n    "aggregate": {\n        "SSIM_feature_ssim_c_score": 0.99740399999999996, \n        "SSIM_feature_ssim_l_score": 0.99998299999999996, \n        "SSIM_feature_ssim_s_score": 0.93580233333333329, \n        "SSIM_score": 0.93335333333333337, \n        "method": "mean"\n    }\n}')
AssertionError: '{\n    "executorId": "SSIM_V1.0", \n    "asset": {\n        "identifier": "test_0_0_checkerboard_1920_1080_10_3_0_0_1920x1080_vs_checkerboard_1920_1080_10_3_1_0_1920x1080_q_1920x1080"\n    }, \n    "frames": [\n        {\n            "frameNum": 0, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.999983, \n            "SSIM_feature_ssim_s_score": 0.935802, \n            "SSIM_score": 0.933353\n        }, \n        {\n            "frameNum": 1, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.999983, \n            "SSIM_feature_ssim_s_score": 0.935802, \n            "SSIM_score": 0.933353\n        }, \n        {\n            "frameNum": 2, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.999983, \n            "SSIM_feature_ssim_s_score": 0.935803, \n            "SSIM_score": 0.933354\n        }\n    ], \n    "aggregate": {\n        "SSIM_feature_ssim_c_score": 0.997404, \n        "SSIM_feature_ssim_l_score": 0.999983, \n        "SSIM_feature_ssim_s_score": 0.9358023333333333, \n        "SSIM_score": 0.9333533333333334, \n        "method": "mean"\n    }\n}' != '{\n    "executorId": "SSIM_V1.0", \n    "asset": {\n        "identifier": "test_0_0_checkerboard_1920_1080_10_3_0_0_1920x1080_vs_checkerboard_1920_1080_10_3_1_0_1920x1080_q_1920x1080"\n    }, \n    "frames": [\n        {\n            "frameNum": 0, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.999983, \n            "SSIM_feature_ssim_s_score": 0.935802, \n            "SSIM_score": 0.933353\n        }, \n        {\n            "frameNum": 1, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.999983, \n            "SSIM_feature_ssim_s_score": 0.935802, \n            "SSIM_score": 0.933353\n        }, \n        {\n            "frameNum": 2, \n            "SSIM_feature_ssim_c_score": 0.997404, \n            "SSIM_feature_ssim_l_score": 0.999983, \n            "SSIM_feature_ssim_s_score": 0.935803, \n            "SSIM_score": 0.933354\n        }\n    ], \n    "aggregate": {\n        "SSIM_feature_ssim_c_score": 0.99740399999999996, \n        "SSIM_feature_ssim_l_score": 0.99998299999999996, \n        "SSIM_feature_ssim_s_score": 0.93580233333333329, \n        "SSIM_score": 0.93335333333333337, \n        "method": "mean"\n    }\n}'

>----------------------------------------------------------------------
>Ran 225 tests in 437.710s

>FAILED (failures=1)

**Comment by leslie-wang** [comment]
same failure result even if I clone latest master branch.

> $ git branch
> * master
