### ISSUE TITLE
libvmaf.pc: release version and provided version are unsync

### ISSUE THREAD

**Issue by Oxalin** [Netflix/vmaf#571]
Until version 1.5.1, libvmaf was providing the same version as the release version. Under 1.5.1, they are unsync, libvmaf.pc providing version 1.3.16.

Here is the content of libvmaf.pc:
prefix=/usr
libdir=${prefix}/lib
includedir=${prefix}/include

Name: libvmaf
Description: VMAF, Video Multimethod Assessment Fusion
Version: 1.3.16
Libs: -L${libdir} -lvmaf
Libs.private: -pthread
Cflags: -I${includedir}/libvmaf

**Comment by Oxalin** [comment]
Was this intended?

**Comment by Oxalin** [comment]
This should be fixed for next release version by https://github.com/Netflix/vmaf/pull/572

**Comment by kylophone** [comment]
CFixed.
