### ISSUE TITLE
VmafFeatureExtractor, provide initialization options

### ISSUE THREAD

**Issue by kylophone** [Netflix/vmaf#578]
Initialization options for `VmafFeatureExtractor`s are desired. The usecase is that some computation or extra feature may not always be required by default, but useful to enable in some cases. An example of this could be some transform of a pre-existing feature, or multi-scale feature extraction. Enabling these by default just causes noisier logs, and unneeded computation is wasteful.

**Comment by li-zhi** [comment]
@kylophone I think this one is resolved?

**Comment by kylophone** [comment]
Yes, closed.
