### ISSUE TITLE
VMAF OpenSuse installation - unittest errors

### ISSUE THREAD

**Issue by stevescia** [Netflix/vmaf#58]
Hello; i have installed VMAF on an OpenSuse server (version 13.1);  I am seeing errors when running the unittest suite as described in the Readme @ github.com/Netflix/VMAF . 

some score assertions have differences up to 4 places.  for example:
FAIL: test_all (feature_test.FeatureTestYuv422p10le)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vqeg/git/vqegjeg.git/netflix/vmaf/feature/test/feature_test.py", line 429, in test_all
    self.assertAlmostEquals(score, 6899.24648475, places=4)
AssertionError: 6899.246359479167 != 6899.24648475 within 4 places

Are errors of this type okay and safely ignored?  any information is appreciated.
Thank you very much for making this tool available!

I have attached the otput file to this posting:
[unittest.txt](https://github.com/Netflix/vmaf/files/741094/unittest.txt)

Regards,
steves

**Comment by li-zhi** [comment]
@stevescia I was able to run VMAF with all test cases passed. Let me share with you my system info:

zli@linux-sbkq:~>  cat /etc/SuSE-release
openSUSE 13.1 (x86_64)
VERSION = 13.1
CODENAME = Bottle

zli@linux-sbkq:~> uname -a

Linux linux-sbkq 3.11.6-4-desktop #1 SMP PREEMPT Wed Oct 30 18:04:56 UTC 2013 (e6d4a27) x86_64 x86_64 x86_64 GNU/Linux



zli@linux-sbkq:~/Projects/public/vmaf> python -c 'import numpy as pkg; print pkg.__version__; print pkg.__file__'

1.12.0

/usr/lib64/python2.7/site-packages/numpy/__init__.pyc

zli@linux-sbkq:~/Projects/public/vmaf> python -c 'import scipy as pkg; print pkg.__version__; print pkg.__file__'

0.17.0

/usr/lib64/python2.7/site-packages/scipy/__init__.pyc

zli@linux-sbkq:~/Projects/public/vmaf> python -c 'import matplotlib as pkg; print pkg.__version__; print pkg.__file__'

1.5.1

/usr/lib64/python2.7/site-packages/matplotlib/__init__.pyc

zli@linux-sbkq:~/Projects/public/vmaf> python -c 'import pandas as pkg; print pkg.__version__; print pkg.__file__'

0.17.1

/usr/lib64/python2.7/site-packages/pandas/__init__.pyc

zli@linux-sbkq:~/Projects/public/vmaf> python -c 'import sklearn as pkg; print pkg.__version__; print pkg.__file__'

0.18

/usr/lib64/python2.7/site-packages/sklearn/__init__.pyc

zli@linux-sbkq:~/Projects/public/vmaf> python -c 'import h5py as pkg; print pkg.__version__; print pkg.__file__'

2.6.0

/usr/lib64/python2.7/site-packages/h5py/__init__.pyc
