### ISSUE TITLE
Testing with unittest

### ISSUE THREAD

**Issue by yuanCabaal** [Netflix/vmaf#581]
Hi, so I installed vmaf on the most recent ubuntu version. Now I am trying to run the unittest to see if everything went well or something is still missing. The test goes well until it gets stuck at command line test_run_testing_vmaf_raw_dataset. Am I missing something or is it suppose to take a long time?

Btw I am using Virtualbox and I got a message that the storage was filled?

**Comment by li-zhi** [comment]
No it shouldn't get stuck at test_run_testing_vmaf_raw_dataset. Is there any error messages?

Could you run individual test case to see what is going on?

**Comment by yuanCabaal** [comment]
there were no error messages. The test stopped there and nothing happened. I am not sure if it has anything to do with it, but the disk (10GB) was suddenly filled.

Well, all the test that came before test_run_testing_vmaf_raw_dataset went smoothly.

**Comment by li-zhi** [comment]
Sorry for the late attendance of this issue. Has it been resolved?

**Comment by nilfm** [comment]
Closing this issue as part of a clean-up as it has been open for a long time and is probably not relevant now. Please feel free to reopen if needed.
