### ISSUE TITLE
ansnr ??== PSNR-HVS && ADM ??== DLM

### ISSUE THREAD

**Issue by leslie-wang** [Netflix/vmaf#60]
Is ansnr in the source code equal to PSNR-HVS referred in blog? Also is ADM equal to DLM method?

Seems like both ansnr and motion feature is not used in VmafFeatureExtractor. From blog, seems like motion should be used. right?

**Comment by li-zhi** [comment]
@leslie-wang Long answer short, ADM and DLM are terms refer to the same elementary metric. And no, ANSNR and PSNR-HVS are different. ANSNR was used in older version of VMAF but subsequently abandoned.

**Comment by leslie-wang** [comment]
thanks for the reply. it is clear for me. I'll close the issue.
