### ISSUE TITLE
Appveyor README badge does not show master branch status

### ISSUE THREAD

**Issue by kylophone** [Netflix/vmaf#606]
The badge shows the status most recent build. Builds are triggered by pushes to branches or a PR, could be something that is not even merged. This badge should show the status of the master branch.

**Comment by 1480c1** [comment]
`s#https://ci.appveyor.com/api/projects/status/68i57b8ssasttngg?svg=true#https://ci.appveyor.com/api/projects/status/68i57b8ssasttngg/branch/master?svg=true#/`

need to add `/branch/master` to the end of the url

**Comment by kylophone** [comment]
Should be addressed by a635ff6.
