### ISSUE TITLE
vmafossexec - a C++ executable Usages

### ISSUE THREAD

**Issue by CyrusJoin** [Netflix/vmaf#607]
Hi
I follow the instructions to execute the following command：

`./vmafossexec yuv420p 576 324 ../python/test/resource/yuv/src01_hrc00_576x324.yuv ../python/test/resource/yuv/src01_hrc01_576x324.yuv ../model/vmaf_v0.6.1.pkl --psnr --ssim`

output：

```
Start calculating VMAF score...
Exec FPS: 99.163044
VMAF score = 76.699271
PSNR score = 30.755064
SSIM score = 0.863227
```
And im confused what the meaning of "Exec FPS", Higher value means better video quality?
can anyone told me?

Thx

**Comment by slhck** [comment]
That's the number of frames that were calculated per second, i.e. the execution speed of VMAF.
