### ISSUE TITLE
Does custom creative work filters added in video impact vmaf calculation

### ISSUE THREAD

**Issue by tarun-discovery** [Netflix/vmaf#610]
Hi Team,

I have a video which has one of the frame like below. If you notice carefully, the imagery is having some visual effects / filters added by creative team in scenarious such as showin flashbacks.

I would like to know if source frames have these kind of visual effects, does that have impact on vmaf score output. Will VMAF system take this frame as distorted frame?

Ques 2: If I am evaluating VMAF score of a video which is of same quality level as source however source itself is having very poor visuals , will I get 100? if 100 relative score of encoded video compare to source?

![image](https://user-images.githubusercontent.com/65272004/86580659-a444d800-bf9c-11ea-8e0c-1f8d3977d4cd.png)

**Comment by li-zhi** [comment]
Re Q1: this looks like a halftoning effect. We don't know the impact if you encode on such a source. A small (expert) subjective test would probably provide some clues.

Re Q2: VMAF is not meant to be applied to source with poor quality. The reported score will likely overpredict the perceived quality.
