### ISSUE TITLE
how to sync frames while calculating vmaf score using ffmpeg

### ISSUE THREAD

**Issue by tarun-discovery** [Netflix/vmaf#611]
Hi
I have one source video and encoder version of that source. Now I need to find vmaf score. However I read that to ensure right vmaf score, it is important that both source and encoded videos are in frame sync. Can you please advise how can i do that using filters on decoded streams in ffmpeg, automatedly

I have command like below
`
ffmpeg2 -i 11sec_encoded_720p_200k.mp4 -i 11sec_original_1080p.mxf -filter_complex "[0:v]scale=1920x1080:flags=bicubic[main]; [main][1:v]libvmaf=model_path=vmaf_v0.6.1.pkl:psnr=1:ssim=1:ms_ssim=1:log_fmt=json:log_path=720p_200k.json" -report -f null -`

**Comment by slhck** [comment]
If you are sure that the number of frames is the same, have a look at these suggested documentation improvements: https://github.com/Netflix/vmaf/pull/423/files#diff-3a2a1d80df150ed8600f8261c4b994b8L56

They were not merged yet, but I think @christosbampis is working on some, or will be once the new API is released/merged into ffmpeg.

**Comment by tarun-discovery** [comment]
Hi, I tried this but it didnt improve the VMAF score. However I do see following for source vs encoded video. 
Left side image is source and right side image if for encoded video. Notice the difference between overall duration and frame count. 
Do you think this is causing low vmaf score. any remedies?
![image](https://user-images.githubusercontent.com/65272004/86802761-f49e6180-c092-11ea-9abb-72a0bedb3ea0.png)

**Comment by slhck** [comment]
If you have a different number of frames and duration, then that might affect the VMAF score – particularly if, say, the first frame is already offset and everything is shifted by one frame.

**Comment by christosbampis** [comment]
+1 I agree with @slhck, the first thing to check is if the number of frames is same. If it is same, and visual inspection does not show any obvious offset, additional ffmpeg tricks might need to be employed like the setPts referenced above.

**Comment by li-zhi** [comment]
@tarun-discovery we just upddated the page on FFmpeg usage with a few examples. See if this helps your use case:
https://github.com/Netflix/vmaf/blob/master/resource/doc/ffmpeg.md
