### ISSUE TITLE
missing stdlib.h in read_frame.c for malloc and free

### ISSUE THREAD

**Issue by vtorri** [Netflix/vmaf#612]
../tools/read_frame.c:25:1: note: include '<stdlib.h>' or provide a declaration of 'malloc'

**Comment by kylophone** [comment]
Thanks, can you send a PR?

**Comment by cosmin** [comment]
I fixed this and a few other missing includes in #641

**Comment by 1480c1** [comment]
@kylophone might want to close this issue as well

**Comment by kylophone** [comment]
> @kylophone might want to close this issue as well

Closed. Thank you.
