### ISSUE TITLE
Windows with MSYS2 + mingw-w64 support

### ISSUE THREAD

**Issue by vtorri** [Netflix/vmaf#613]
hello

in libvmaf/src/meson.build, i can see, line 11 :  '-DLINUX_',

this is passed when the compiler is not vc++, so it is passed with gcc on Windows

I don't think it is a good idea to pass macro specific for an OS for detecting features, but instead checking the feature in meson

regards

**Comment by 1480c1** [comment]
afaik, that's only used with the OpenContainers and ptools stuff, which don't work nice with msvc anyway due to pthread stuff. Those dependencies are supposedly going away in vmaf 2.0 or whatever the name will be

**Comment by vtorri** [comment]
has the development of vmaf 2 started ?

**Comment by 1480c1** [comment]
vmaf_rc is the library
https://github.com/Netflix/vmaf/blob/master/libvmaf/src/meson.build#L200

**Comment by vtorri** [comment]
why are you using both libraries in meson.build ? You force people to install both static and shared lib, while people usually want only one. And if they want both, they pass 'both' to default_library option

**Comment by 1480c1** [comment]
because both libs are preferable usually for distributing on Linux. if the packager wants, they can set the default_library option or only install specific libs manually

**Comment by vtorri** [comment]
you are wrong. I've just tried that. My script : 

```
cd libvmaf

rm -rf builddir && mkdir builddir && cd builddir
meson .. \
      --prefix=/opt/libvmaf2 \
      --libdir=lib \
      --buildtype=release \
      --strip \
      --cross-file ../cross_toolchain.txt \
      --default-library shared \
      -Denable_docs=false  \
      -Denable_tests=false

ninja install
```

and find /opt/libvmaf2 gives : 

```
$ find /opt/libvmaf2/
/opt/libvmaf2/
/opt/libvmaf2/bin
/opt/libvmaf2/bin/libvmaf-0.dll
/opt/libvmaf2/bin/vmafossexec.exe
/opt/libvmaf2/include
/opt/libvmaf2/include/libvmaf
/opt/libvmaf2/include/libvmaf/libvmaf.h
/opt/libvmaf2/include/libvmaf/version.h
/opt/libvmaf2/lib
/opt/libvmaf2/lib/libvmaf.a
/opt/libvmaf2/lib/libvmaf.dll.a
/opt/libvmaf2/lib/pkgconfig
/opt/libvmaf2/lib/pkgconfig/libvmaf.pc
etc...
```

so you are forcing people to install both static and shared lib

so you should do what I said : 

1) use libraries instead of both_libraries
2) let the user use 'both' as value for --default-library if they want to install both libraries

and i doubt that the vast majority of linux distro install both shared and static lib with the same package.

**Comment by 1480c1** [comment]
Oh, well, you can always submit a PR requesting your changes if you want

**Comment by kylophone** [comment]
We are in the process of deprecating `libvmaf` in favor of `libvmaf_rc`. Ptools will also be going away which should make Windows compilation a lot less of a hassle.

**Comment by vtorri** [comment]
@kylophone so i wait for the new libvmaf_rc code, thanks
