### ISSUE TITLE
Caught runtime_error: StatVector size is 0.

### ISSUE THREAD

**Issue by masterholdy** [Netflix/vmaf#624]
I want to Test VMAF but im always getting StatVector size is 0.
This is how i run the CMD
```
vmafossexec.exe yuv422p10le 1920 1080 reference.yuv distorted.yuv C:\ffmpeg\vmaf\model\vmaf_v0.6.1.pkl --psnr --ssim --ms-ssim --log distorted.csv
```

I also tried absolute Paths.

Im using Windows 10 Pro latest Version and i installed VMAF 
via. downloading it via AppVeyor ( https://ci.appveyor.com/project/li-zhi/vmaf ) 

All my Videos Reference Videos are Uncompressed Avi ( `yuv422p10le` )
I created every YUV File via `ffmpeg -y -i distorted.mp4 -pix_fmt yuv422p10le -vsync 0 distorted.yuv`

Im not really sure what to post to help you guys help me.

Edit://
The Link in https://github.com/Netflix/vmaf/blob/master/resource/doc/BuildForWindows.md
for the SLN File is Dead btw.
otherwise i would have tried to install it "correctly" - aswell

**Comment by 1480c1** [comment]
It seems it's tripping on `_assert_size()`

could you perhaps try different clips and use `C:/ffmpeg/vmaf/model/vmaf_v0.6.1.pkl` along with using the bare minimum?

trying to reduce the potential variable and determine if it's vmafossexec's fault or potentially a clip that trips up libvmaf.

Also, can you try giving the exact commit or link that you downloaded from appveyor?
