### ISSUE TITLE
Some frames have a VMAF score of 0 

### ISSUE THREAD

**Issue by BassThatHertz** [Netflix/vmaf#629]
I've noticed that when using libvmfaf with FFmpeg,some frames have a VMAF score of 0. I have attached a .txt file which contains the JSON output of one of the tests that I conducted.
[VMAF.txt](https://github.com/Netflix/vmaf/files/4938253/VMAF.txt)
If you search for **"vmaf":0**, you see will that there are 34 matches which means that 34 frames have a VMAF of 0. And this file is only 1 minute and 8 seconds long.

This isn't the only case. My friend has also found something similar. In fact, in his case, ~26% of the frames were shown to have a VMAF of 0. 

`ffmpeg -i "<encoded_file>" -i "<original_file>" -lavfi libvmaf=model_path=vmaf_v0.6.1.pkl:log_path=output.json:log_fmt=json -f null -`

Does anyone have an idea of what the issue may be?

I can share the original and encoded file, if that may help.

**Comment by li-zhi** [comment]
The feature scores all seem so low that it is not surprising VMAF score is 0. Can you enable the PSNR flag to get a PSNR number too? I wonder if this is a frame synchronization issue.
Check out this link for more information on using  FFmpeg with libvmaf:
https://github.com/Netflix/vmaf/blob/master/resource/doc/ffmpeg.md

**Comment by BassThatHertz** [comment]
@li-zhi Where are the feature scores in the file? And I have re-run it with PSNR enabled. Here's the file with PSNR numbers: 
[With PSNR.txt](https://github.com/Netflix/vmaf/files/4939456/With.PSNR.txt)

**Comment by li-zhi** [comment]
The same frame with 0 VMAF score also has very low PSNR score of 20:
    {
      "frameNum":194,
      "metrics":{
        "adm2":0.53833,
        "motion2":0.0,
        "psnr":20.26411,
        "vif_scale0":0.25127,
        "vif_scale1":0.34652,
        "vif_scale2":0.37569,
        "vif_scale3":0.41424,
        "vmaf":0.0
      }
    },

This should be a frame misalignment issue.

By feature scores I meant the adm and vif scores.

**Comment by BassThatHertz** [comment]
@li-zhi What is frame misalignment and does this mean that the final VMAF score is inaccurate?

**Comment by li-zhi** [comment]
Please refer to:
https://github.com/Netflix/vmaf/blob/master/resource/doc/ffmpeg.md
When libvmaf is used as a filter in FFmpeg, the time alignment is not frame-by-frame. Instead, it is based on PTS (presentation timestamp). You will have to make sure that your frame rate (`-r`) is set correctly. Perhaps you also need to invoke `setpts=PTS-STARTPTS`.

**Comment by slhck** [comment]
Could you please send a sample that exhibits these problems? I'd like to make sure that the suggested solution works in my tools.

**Comment by BassThatHertz** [comment]
@slhck Yes, visit the following link: https://drive.google.com/drive/folders/1Lhari6_BQa5D7x6zUg0pHPrpPrwV5dGJ?usp=sharing
Please keep me updated :)

**Comment by BassThatHertz** [comment]
@li-zhi I tried again and this time specified the framerate and added `setpts=PTS-STARTPTS` as you can see below:
```
		vmaf_options = {
			"model_path": "vmaf_v0.6.1.pkl",
			"log_path": json_file_path, 
			"log_fmt": "json"
		}

		vmaf_options = ":".join(f'{key}={value}' for key, value in vmaf_options.items())

		subprocess_args = [
			"ffmpeg", "-loglevel", "error", "-stats", "-i", output_file_path, "-r", "23.976",
			"-i", args.video_path, "-r", "23.976",
			"-lavfi", "[0:v]setpts=PTS-STARTPTS[dist];[1:v]setpts=PTS-STARTPTS[ref];[dist][ref]"
			f'libvmaf={vmaf_options}', "-f", "null", "-"
		]

		subprocess.run(subprocess_args)
```
But the issue persists.

@slhck The `vmaf_options = ":".join(f'{key}={value}' for key, value in vmaf_options.items())` probably looks a little familiar. I took inspiration from your code :p

**Comment by li-zhi** [comment]
The following seems to give me the correct result without VMAF 0 (tested on the first 200 frames):
```
ffmpeg -r 23.976 -i /Users/zli/Downloads/Original.mkv -r 23.976 -i /Users/zli/Downloads/Transcoded.mkv -lavfi "[0:v]select='gte(n\\,0)*gte(199\\,n)',setpts=PTS-STARTPTS[reference];[1:v]select='gte(n\\,0)*gte(199\\,n)',setpts=PTS-STARTPTS[distorted];[distorted][reference]libvmaf=log_fmt=json:log_path=/dev/stdout:model_path=/usr/local/share/model/vmaf_v0.6.1.pkl" -f null -
```

**Comment by BassThatHertz** [comment]
@li-zhi The issue was that I specified the framerate after the name of the input file. You need to specify the framerate before the input file. `setpts=PTS-STARTPTS` doesn't need to be invoked, at least not for this video, but I suppose there's no harm in adding it.

The solution for those run into the same issue: 

Specify the framerate before `-i` for each video and use `setpts=PTS-STARTPTS` (documented [here](https://github.com/Netflix/vmaf/blob/master/resource/doc/ffmpeg.md). This wasn't necessary for the video that I tested with, but it may be necessary in your case).

To get the framerate of a video with Python, you can do this with OpenCV-Python (`pip install opencv-python`) and then:
```
import cv2
cap = cv2.VideoCapture(path_of_video)
fps = cap.get(cv2.CAP_PROP_FPS)
```
This gives you a value of type `float`. If you want a string, do `str(cap.get(cv2.CAP_PROP_FPS))` instead.

**Comment by li-zhi** [comment]
Good catch. I'll add a sentence to the doc to highlight that `-r` needs to be before `-i`.

**Comment by slhck** [comment]
@BassThatHertz I haven't yet downloaded your files (only on a mobile connection here), but I wonder why you need to specify the framerate while reading with ffmpeg. Normally, that framerate is part of the container metadata and should be the same between the original and the transcoded file. It doesn't hurt to add it during the calculation of VMAF, so I'll try to add this to my script.

**Comment by slhck** [comment]
@BassThatHertz I updated the code so it fetches the FPS from dist/ref files and also sets the PTS, see https://github.com/slhck/ffmpeg-quality-metrics/ v0.5.0. Now, in case that dist/ref have differing FPS it'll show a warning. I am not sure what the best solution is in that case … forcing the user to choose a framerate manually, which will be applied to both dist/ref?

**Comment by BassThatHertz** [comment]
@slhck Hmm. Well, in almost every case, the frame rate of the transcoded video will be the same as the original, as people don't usually change the frame rate when transcoding. In the rare occasion that the frame rates differ, you _could_ force the user to choose a frame rate and then change the frame rate of dist/ref to that, but is it possible to change the frame rate without re-encoding the video? If not, I don't think it's worth it, because you'd no longer be making the same comparison. Rather you'd be comparing the quality of the encoded version of dist to the quality of the encoded version of ref.

Personally, I'd just inform the user that the frame rates differ (which you're doing in v0.5.0), but I'd also add why this is an issue, because some users may not realise that differing frame rates will mean inaccurate quality metrics. So something like:

```
print_stderr(
            f"[warning] ref, dist framerates differ: {ref_framerate}, {dist_framerate}. This will result in inaccurate quality metrics. "
        )
```

And give the user the option to abort (recommended) or continue.

**Comment by slhck** [comment]
> is it possible to change the frame rate without re-encoding the video?

While reading the video, yes. Applying `-r` before ´-i` will simply force the demuxer to generate the PTS instead of relying on the ones present in the file, yielding a different framerate, but the same number of frames.

(This is different from specifying `-r` after `-i`, which will drop or duplicate frames to achieve the chosen target rate, and output a newly encoded video file.)

I'll improve the warning. Thanks for the hint!

**Comment by BassThatHertz** [comment]
@slhck @li-zhi This is unrelated to the original issue about getting a quality of 0, but it's related to the topic of specifying `-r`. 

I did some reading and it seems like with FFmpeg, by default the input framerate is set to 25. Therefore, even if you ignore the VMAF issue I had earlier, it seems like you should always specify an input framerate when encoding a video with FFmpeg (if the video doesn't have a framerate of 25), because if you don't, the input framerate will be set to 25 which means that the output will be a little different to the original?

I did a test to see what exactly the input framerate does, by adding `-r 1` before `-i`. I noticed that this means that you only see 1 frame every second in the output file.

Now let's say you have a 30 FPS file and you encode it with FFmpeg, and you don't specify `-r 30` before `-i`. This would be the same as specifying `-r 25` before `-i`, becausethat's the default. This means that every second, you will only see 5/6 of the frames that were in the original file, correct?

In this case, I'm wondering why I've never seen it mentioned in the FFmpeg documentation that whenever you encode a video, you should specify the framerate of the video before `-i`, especially considering that most videos don't have a framerate of 25, because otherwise the output will be a little different to the original (even if you may not notice that).

Am I misunderstanding something?

**Comment by slhck** [comment]
> by default the input framerate is set to 25

Only when working with containers that do not specify a framerate, i.e. `rawvideo` or raw YUV files.

> it seems like you should always specify an input framerate when encoding a video with FFmpeg (if the video doesn't have a framerate of 25), because if you don't, the input framerate will be set to 25 which means that the output will be a little different to the original?

No, this is not needed. Consider this small test:

```
$ ffmpeg -f lavfi -i testsrc=r=30:d=1 file-with-30-fps.mp4
$ ffmpeg -i file-with-30-fps.mp4
...
    Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 320x240 [SAR 1:1 DAR 4:3], 59 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
```

See that it encoded a file with 30 fps, that, when reading it, still has 30 fps?

Let's encode it again:

```
$ ffmpeg -i file-with-30-fps.mp4 file-with-30-fps-2.mp4
...
    Stream #0:0(und): Video: h264 (libx264) (avc1 / 0x31637661), yuv444p, 320x240 [SAR 1:1 DAR 4:3], q=-1--1, 30 fps, 15360 tbn, 30 tbc (default)
...
```

You'll see that it still has 30 fps.

Now, let's create a raw, uncompressed file instead:

```
$ ffmpeg -f lavfi -i testsrc=r=30:d=1 file-with-30-fps.yuv
```

What happens if we read it?

```
$ ffmpeg -video_size 320x240 -i file-with-30-fps.yuv
...
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 320x240, 23040 kb/s, 25 tbr, 25 tbn, 25 tbc
...
```

Ahah, ffmpeg applies the default 25 fps, because it does not know what the original framerate was (as a raw YUV file cannot contain that information).

**Comment by slhck** [comment]
I should add that in video quality testing, working with YUV files is very common. Most probably for historical reasons, and because they can be easily parsed and read with low-level programs.
With the availability of wrappers to read containers like MP4, MKV, or even (the very old) AVI, this may not be needed, although that adds a level of complexity.

Anyway, this is why you'll see the need to specify the framerate manually so often.

**Comment by BassThatHertz** [comment]
@slhck
> Only when working with containers that do not specify a framerate

I feel like I may me misunderstanding what you mean by this. Don't all containers not specify a framerate? Because why would a container specify a framerate? Shouldn't that just be dependent on the framerate of the video stream that is going to be put in the container? For example, MP4 videos can be 24/30/60 FPS etc. If the MPEG-4 container specified the framerate, then all MP4 videos would have the same framerate, but that's not the case.

**Comment by slhck** [comment]
> if someone says that a container "specifies the framerate", they just mean that the framerate is in the metadata, not that the container determined what the framerate should be. Correct?

Yes. The container holds metadata about which framerate the video stream(s) was/were coded with. Sometimes that information is also part of the elementary video stream itself.

However, for raw video streams (i.e., multiple YUV frames simply concatentated into a `.yuv` file), there is no such framerate information.

> With the VMAF issue, it was required to specify the framerate even though the videos are H.264 and not something like raw YUV. I wonder why.

Most likely the encoder dropped or duplicated one or more frames while encoding.
