### ISSUE TITLE
New libvmaf_rc API should not take a FILE* argument

### ISSUE THREAD

**Issue by dwbuiten** [Netflix/vmaf#632]
The new vmaf_rc API being introduced contains:

```C
int vmaf_write_output(VmafContext *vmaf, FILE *logfile, enum VmafOutputFormat fmt);
```

Unfortunately, `FILE *` in APIs is not safe/portable, since, for example, the application linking libvmaf_rc and the library itself may use different libc implementations, especially on Windows where it is common for an application and its libraries to use different MSVCRT versions. `FILE *` compatability between libc is not guaranteed by the C or C++ standards (their internals can differ).

It should either be a `const char *` file path, or a write callback like `size_t (*write_callback)(void *opaque, uint8_t *buf, size_t buf_size)`.

**Comment by kylophone** [comment]
Fixed by #633. Thanks for the report.
