### ISSUE TITLE
Building the Windows

### ISSUE THREAD

**Issue by archanaveluswamy** [Netflix/vmaf#636]
Hi,

Has anyone successfully built the latest version on windows? As the sln has been removed and building has changed to meson, it will be helpful if anyone knows how t build on Windows.

Thanks

**Comment by 1480c1** [comment]
You can try using msys2 and mingw-w64 as show in https://github.com/Netflix/vmaf/blob/master/appveyor.yml

**Comment by kylophone** [comment]
Yes, MSYS2 works for now. When the old libvmaf is deprecated (soon) Windows building should be a lot more straightforward.

**Comment by archanaveluswamy** [comment]
Thanks for the replies, I am able to build it now with mingw64

**Comment by lzz8246** [comment]
Hi, could you please tell me how to build it with mingw64? Still not work on my side.

**Comment by archanaveluswamy** [comment]
I copied the following commands to a batch file and ran the batch file
----------------------------------------------------------------------------------------------------------------------------------------------
compiler: msvc2019
arch: x64
MSYSTEM: MINGW64
CC: ccache x86_64-w64-mingw32-gcc
CXX: ccache x86_64-w64-mingw32-g++


set "PATH=C:\msys64\mingw64\bin;C:\msys64\mingw32\bin;C:\msys64\usr\bin;%PATH%"
set MSYS2_PATH_TYPE=inherit

pacman -Syyuu --ask=20 --noconfirm --noprogressbar --needed
pacman -Sy --ask=20 --noconfirm --noprogressbar --needed mingw-w64-x86_64-ninja mingw-w64-x86_64-meson

if "%compiler%"=="msvc2015" ( call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %arch% )
if "%compiler%"=="msvc2017" ( call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %arch% )
if "%compiler%"=="msvc2019" ( call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %arch% )

echo Building on %arch% with %compiler%
set "CFLAGS=-static %CFLAGS%"
set "CXXFLAGS=-static %CXXFLAGS%"
cd libvmaf
meson setup --backend=ninja --default-library=static --buildtype=release --prefix="%CD%/install" build
ninja -vC build install
----------------------------------------------------------------------------------------------------------------------------------------------

I have meson, ninja installed already

**Comment by lzz8246** [comment]
Got it with a lot thanks.
