### ISSUE TITLE
different training model parameter data

### ISSUE THREAD

**Issue by leslie-wang** [Netflix/vmaf#64]
I'm using Netflix public data and using below commands to train model parameters
> `./run_vmaf_training resource/dataset/NFLX_dataset_public.py resource/feature_param/vmaf_feature_v3.py resource/model_param/libsvmnusvr_v3.py workspace/model/test_model.pkl --parallelize`

But I got different parameter by comparing with all files under resource/model. Also if I use new trained model and got different scores by running
> `./run_vmaf yuv420p 576 324 resource/yuv/src01_hrc00_576x324.yuv resource/yuv/src01_hrc01_576x324.yuv --model workspace/model/test_model.pkl`

This should be understandable because of different trained parameters. So can we list out which dataset are used to training each model files under resource/model?

**Comment by li-zhi** [comment]
Unfortunately we cannot share the dataset used to train these models since
they contain video clips that are copyright protected.
