### ISSUE TITLE
appveyor: Maximum allowed artifact storage size of 50000 Mb will be exceeded.

### ISSUE THREAD

**Issue by kylophone** [Netflix/vmaf#642]
Our appveyor is out of artifact storage as of https://ci.appveyor.com/project/li-zhi/vmaf/builds/34577819. This has happened to me a few times in other repos. It is a real bummer, tbh. Last time this happened to me the solution was to open a ticket at appveyor asking for more storage. Not really a permanent solution, because it will happen again at some point in the future. So unless someone knows better (@1480c1, maybe you've encountered this again more recently than I have?), I guess there are two solutions:

- Open an appveyor ticket and ask for more storage. @li-zhi, this was registered under your personal account, looks like.

-  Move all Windows CI to Github Actions, discontinue use of appveyor.

My preference is for the latter, replacing appveyor.

**Comment by 1480c1** [comment]
I've had this before in SVT-AV1 indeed, and my personal preference is to just move all CI to GitHub Actions other than the multi arch ones like arm.

I can try to work on this in my free time, but no guarantees just yet

**Comment by kylophone** [comment]
> I've had this before in SVT-AV1 indeed, and my personal preference is to just move all CI to GitHub Actions other than the multi arch ones like arm.
> 
> I can try to work on this in my free time, but no guarantees just yet

Thanks, that's what I thought. OK. If I get to it before you, I'll be sure to let you know.

**Comment by 1480c1** [comment]
@kylophone if I make it so that the windows job in GitHub Actions also build FFmpeg, do you want me to make it so it also uploads the static windows binary with vmaf?

**Comment by kylophone** [comment]
> @kylophone if I make it so that the windows job in GitHub Actions also build FFmpeg, do you want me to make it so it also uploads the static windows binary with vmaf per build and also upload on releases?

Static FFmpeg? Probably not. Static vmaf binary? Good idea.
