### ISSUE TITLE
I used ffmpeg decode a video to a queue of AVFrame , and then how can i used vmaf ?

### ISSUE THREAD

**Issue by matsunatsu** [Netflix/vmaf#653]
if i can use vmaf_read_pictures(),but how can i initialize VmafPicture

**Comment by kylophone** [comment]
Use `vmaf_picture_alloc()`: https://github.com/Netflix/vmaf/blob/master/libvmaf/include/libvmaf/picture.h#L42-L43. For an example usage, see `vmaf.c`. Once allocated, you will need to copy your pixel data from your `AVFrame` into the `VmafPicture`.

Also, please note that `libvmaf_rc` is still a release candidate library. It will be uplifted in the next version, but it's still good for you to be aware of that.
