### ISSUE TITLE
vmaf python version is out of sync of project version

### ISSUE THREAD

**Issue by dvrogozh** [Netflix/vmaf#654]
https://github.com/Netflix/vmaf/blob/9ad79192dbb29e3249744acb8231962cccc23f78/python/vmaf/__init__.py#L6

vmaf python module is still being versioned as 1.5.1 (this went to latest 1.5.2 release).

Couple of things to consider:
1. Parse libvmaf meson.build to extract version for python module?
2. Integrate python module build into meson build and generate `__init__.py`?

**Comment by dvrogozh** [comment]
Since meson version gets slightly better traction (it seems), maybe custom build step can be added to verify that python version matches and build/configuration would fail otherwise? And if only python version will be changed, then this would be caught by CI pretty instantaneously as meson configuration/build failure.

**Comment by kylophone** [comment]
> Since meson version gets slightly better traction (it seems), maybe custom build step can be added to verify that python version matches and build/configuration would fail otherwise? And if only python version will be changed, then this would be caught by CI pretty instantaneously as meson configuration/build failure.

Yes, this is a good idea. It would keep this from happening again.

**Comment by li-zhi** [comment]
Agreed. Let's invest time for proper solutions. For now I'll write an instruction for the steps to make a new release (including bump version numbers, update CHANGELOG etc). In the middle term VMAF is to be packaged and published in PyPi.

**Comment by li-zhi** [comment]
This is now fixed by #655.
