### ISSUE TITLE
psnr along with vmaf score is different with using psnr command

### ISSUE THREAD

**Issue by FelixYue** [Netflix/vmaf#659]
command 1: ffmpeg -i AirShow_Dis01.mp4 -i AirShow_Ori.mp4 -filter_complex libvmaf="psnr=1:log_fmt="csv":log_path=psnr.csv" -f null –
psnr score:42.3156(average)

command 2: ffmpeg -i AirShow_Dis01.mp4 -i AirShow_Ori.mp4 -filter_complex psnr="stats_file=psnr1.csv" -f null -
psnr score:41.9575(average)

Why are the PSNR scores calculated by the two commands different?Which one is correct?
[score.zip](https://github.com/Netflix/vmaf/files/5135102/score.zip)

**Comment by li-zhi** [comment]
The PSNR reported by libvmaf is the PSNR value for the Y channel only. It matches closely with the psnr_y reported in your second command.
