### ISSUE TITLE
Q: FFmpeg + libvmaf_rc

### ISSUE THREAD

**Issue by gdavila** [Netflix/vmaf#661]
I'm not familiar with the details FFmpeg uses to work with  libvmaf library so  my questions: **Is there any way to compile FFmpeg with libvmaf_rc instead of  libvmaf?**  Particullary, I'm interested to test the new `vmaf_v0.6.1neg.pkl` ( HD model that takes into account gain enhacement issues) using ffmpeg.

**Comment by slhck** [comment]
It is my understanding that you do not need `libvmaf_rc` to use another model. Simply point to the other model file via the respective ffmpeg `libvmaf` filter options.

**Comment by gdavila** [comment]
I understood in the same way too, but I am not sure.  On the [docs](https://docs.google.com/document/d/1dJczEhXO0MZjBSNyKmd3ARiCTdFVMNPBykH4_HMPoyY) I notice that the elementary metrics of VMAF (VIF and DLM) could change for some conditions. I dont know if the provided model works well for the old way to compute that metrics or not.

**Comment by li-zhi** [comment]
unfortunately libvmaf_rc doesn't work with FFmpeg yet. This will be supported when we make libvmaf_rc official (and dropping the "rc"). This should happen in a month or so.

@kylophone

**Comment by gdavila** [comment]
@li-zhi just to be sure, `vmaf_v0.6.1neg.pkl` is supported with `libvmaf`?

**Comment by li-zhi** [comment]
Hi @gdavila, no, vmaf_v0.6.1neg.pkl is not supported in the FFmpeg+libvmaf as of today. The only way to invoke it is through vmaf_rc.
