### ISSUE TITLE
Different Resolutions for ref & distorted... again

### ISSUE THREAD

**Issue by EposVox** [Netflix/vmaf#667]
Hi! This is similar to #248 
I'm trying to compare across resolutions, but no matter what I do I get
`[Parsed_libvmaf_1 @ 000001aafa60ee80] libvmaf encountered an error, check log for details
Error while filtering: Invalid argument
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #1:0`

I've tried every bit from every post I can find about it, with encoded sources and raw yuv sources, and keep getting stuck here.

Here's my current draft command:
`for /R %%A in (*.mp4) do (   
    echo Processing %%A   
	ffmpeg -i %%A -i E:\compare2\source\Shooters.mov -filter_complex "[0:v]scale=1920:1080:flags=bicubic[main];[main][1:v]libvmaf=:psnr=1:ssim=1:log_path=E:\compare2\%%A_log.txt" -f null -
	echo Processed %%A
)
echo done - check for errors
pause`

What am I missing? Basically every post gives this more or less verbatim. Chopping off everything after libvmaf doesn't change anything. Playing with quotation locations doesn't help either.

Reference file is ProRes - but I also have the YUV extract (just have to fight "Picture size 0x0 is invalid" errors, which the size-specifying commands don't play nice when specifying 2 inputs w/ ffmpeg). Distorted files are H264, but again also have YUV extracts.

Windows 10 x64.

**Comment by 1480c1** [comment]
First guess is because you are on windows, you need to add `model_path`, which tricky to do on windows because ffmpeg uses `:` as option separators, but windows also uses it as part of the drive path

**Comment by slhck** [comment]
`libvmaf=:psnr=1` is a syntax error. Remove the `:` before `psnr`. To troubleshoot, please try with one command first, no loop, and include the full, uncut ffmpeg command line output.

**Comment by EposVox** [comment]
This command:
`ffmpeg -i Shooters-NVENC_6M_720p.mp4 -i E:\compare2\source\Shooters.mov -filter_complex "[0:v]scale=1920:1080:flags=bicubic[main];[main][1:v]libvmaf=model_path=vmaf_v0.6.1.pkl:psnr=1:ssim=1:log_path=E:\compare2\test_log.txt" -f null -`
Gets this error:
![7Ir7jZl 1](https://user-images.githubusercontent.com/18689681/93738442-c8837e80-fbb3-11ea-8e0a-016cfd20163f.png)

Removing the log part makes it work, however. I feel silly, I was so obsessed with figuring out the scaling issue, I missed a typo. Facedesk.
Anyway, what needs done/moved to make logging work? As the command line output only gives me VMAF when PSNR and SSIM are turned on, I assume the CSV would give me that as well.

**Comment by 1480c1** [comment]
You should probably use / instead of \ for the log path, and also try using relative paths instead since you will need to worry about a lot of escaping issues if you want to use the full path with a : in it

**Comment by 1480c1** [comment]
If trying to use yuv files, the normal constraints apply with trying to read any raw bytes (need to specify video info) https://stackoverflow.com/questions/15778774/using-ffmpeg-to-losslessly-convert-yuv-to-another-format-for-editing-in-adobe-pr `ffmpeg -f rawvideo -vcodec rawvideo -s 1920x1080 -r 25 -pix_fmt yuv420p -i inputfile.yuv ...` i think you need this info before both -i s so ffmpeg knows what's it's passing to libvmaf

**Comment by 1480c1** [comment]
For more info on using full paths with model_path https://github.com/Netflix/vmaf/issues/413#issuecomment-568328774

**Comment by EposVox** [comment]
Thanks!
