### ISSUE TITLE
VMAF score of some distorted files from CSIQ Video Quality Database

### ISSUE THREAD

**Issue by paulwgw88** [Netflix/vmaf#673]
Thanks for the release of VMAF. Recently I have been using it to test some distorted samples of CSIQ Video Quality Database, and comparing the result of VMAF with the subject MOS given by the database, and I found some interesting results. 
Take **BasketballDrive_832x480_dst_04.yuv** (which has some packet loss in the bitstream) as an example, the VMAF score is 99.42580561984659 while the subject MOS is only around 56. After analyzing the VMAF score of each frame of the distorted yuv, I found that there are some frames, which have small broken tiles that may cause the degeneration of the subject score, still have VMAF scores close to 100, but the PSNR is pretty low compare to other normal frames.
My question is that whether this case can be avoided after I train a new model including this case, or this case is unavoidable because of the limitation of VMAF itself. 
Looking forward to your reply. Thanks again.

broken frame:
    "frameNum":46,
      "metrics":{
        "adm2":0.98982,
        "motion2":8.363630000000001,
        "ms_ssim":0.98294,
        **"psnr":31.33784,**
        "ssim":0.98239,
        "vif_scale0":0.78612,
        "vif_scale1":0.95527,
        "vif_scale2":0.96455,
        "vif_scale3":0.96801,
        **"vmaf":100.0**
      }

normal frame:
    "frameNum":39,
      "metrics":{
        "adm2":0.98921,
        "motion2":7.76571,
        "ms_ssim":0.9878,
        **"psnr":36.69851,**
        "ssim":0.98603,
        "vif_scale0":0.7985,
        "vif_scale1":0.9567600000000001,
        "vif_scale2":0.96631,
        "vif_scale3":0.97128,
        **"vmaf":100.0**
      }

P.S.  I ran my test by FFmpeg commands with libvmaf built from the latest release version: 1.5.3, using the default model vmaf_v0.6.1.pkl

**Comment by li-zhi** [comment]
@paulwgw88 thanks for reporting. Would be great if you can submit the specific videos that exhibit this behavior in the following link:
https://github.com/Netflix/vmaf#report-of-vmaf-bad-cases

In the mean time, have you tried the VMAF NEG model on this video? More details here:
https://docs.google.com/document/d/1dJczEhXO0MZjBSNyKmd3ARiCTdFVMNPBykH4_HMPoyY/edit#heading=h.oaikhnw46pw5

**Comment by paulwgw88** [comment]
> @paulwgw88 thanks for reporting. Would be great if you can submit the specific videos that exhibit this behavior in the following link:
> https://github.com/Netflix/vmaf#report-of-vmaf-bad-cases
> 
> In the mean time, have you tried the VMAF NEG model on this video? More details here:
> https://docs.google.com/document/d/1dJczEhXO0MZjBSNyKmd3ARiCTdFVMNPBykH4_HMPoyY/edit#heading=h.oaikhnw46pw5

@li-zhi thanks for your reply. I have submitted the distorted and reference videos. And also I have tried the vmaf_v0.6.1neg.pkl, the result is pretty much the same as the one using the default model vmaf_v0.6.1.pkl.

**Comment by li-zhi** [comment]
Thanks for uploading. Let me look into the videos.
