### ISSUE TITLE
Inconsistent results when using segmented video

### ISSUE THREAD

**Issue by dpasqualin** [Netflix/vmaf#674]
I generated a log file containing the per frame vmaf/psnr/ssim, then I segmented both the reference and distorted videos into 10s segments. GOP is 25, framerate 25, so each segment has 250 frames. Than I tried to calculate vmaf/psnr/ssim over each segment. Values for psnr and ssim always match with original, which makes be believe that the frames are correctly aligned, but for vmaf the first frame (and only the first) of each segment has a lower value if compared to the original measurement in the non segmented video. Any idea on why this happens?

Command used to segment the video.
```bash
ffmpeg -fflags +genpts -i <video>.mp4 -c:v copy -an -dn -sn -bsf:v hevc_mp4toannexb -segment_time 10 -reset_timestamps 1 -f segment -y segment_%010d.mp4
```

Command used to calculate vmaf (I ran over each segment, than concatenate the csv files).
```bash
ffmpeg -i <reference_segment_X>.mp4 -i <distorted_segment_X>.mp4 -lavfi "[0:v]setpts=PTS-STARTPTS[reference]; [1:v]scale=1280:720:flags=bicubic,setpts=PTS-STARTPTS[distorted]; [distorted][reference]libvmaf=log_fmt=csv:log_path=metrics.csv:psnr=true:ssim=true:model_path=/usr/share/model/vmaf_v0.6.1.pkl" -f null -
```

Example of differences:
![example](https://user-images.githubusercontent.com/68142/94937896-7a824b00-04d0-11eb-97d9-bb37a04fb1b6.png)

**Comment by li-zhi** [comment]
Have you looked at per-frame scores? I would expect that 9 of the 250 frames (the first frame of each segment) to have VMAF slightly lower since the motion score is 0. But overall 89.6910 vs. 84.9489 is too much a difference. What about the features scores such as vif_scale0?

**Comment by dpasqualin** [comment]
Hi @li-zhi, thank you for your answer. Sorry if I wasn't very clear, I'm looking at the per-frame score, but in the example I filtered out the values where the segmented and not-segmented videos match. The segments have 250 frames, and they don't match only in the first frame of each segment. Is that expected?

About the other features, they are always the same, only VMAF is different. Here an example.
![diff](https://user-images.githubusercontent.com/68142/94998166-0d45e700-05b0-11eb-92d7-cdb40bb8b937.png)

**Comment by li-zhi** [comment]
Got it. So the difference of `89.6910 vs. 84.9489` is on a single frame. This is expected. The first frame of the segment doesn't have a previous frame to refer to to calculate the `motion` score, so it reports `motion=0`. The VMAF score is expected to positively correlate with the motion score. That is why the value is lower in the segmented case.
