### ISSUE TITLE
libvmaf build fails on macOS Catalina

### ISSUE THREAD

**Issue by xanadu6291** [Netflix/vmaf#675]
libvmaf build fails on macOS Catalina.  I run  the following command to build libvmaf:

cd ${SRC}
curl -LO https://github.com/Netflix/vmaf/archive/v1.5.3.tar.gz
cd ${CMPL}
tar xf ${SRC}/v1.5.3.tar.gz
cd vmaf-1.5.3/libvmaf
meson setup --prefix=${TARGET} --default-library=static --buildtype=release build
ninja -vC build
ninja -vC build test
ninja -vC build install

This is because some function are declared implicit. 
Attached patch fixes this build error...
[libvmaf_implicit_fix.zip](https://github.com/Netflix/vmaf/files/5323049/libvmaf_implicit_fix.zip)

**Comment by li-zhi** [comment]
@xanadu6291 would you mind sending a PR?

**Comment by xanadu6291** [comment]
@li-zhi I just send pull request which covers this issue.

https://github.com/Netflix/vmaf/pull/676
