### ISSUE TITLE
Can the new model be used by FFmpeg with libvmaf?

### ISSUE THREAD

**Issue by paulwgw88** [Netflix/vmaf#680]
I have tried to train a new model using the steps in the following page:
_https://github.com/Netflix/vmaf/blob/master/resource/doc/VMAF_Python_library.md#advanced-usage_

After I obtain the new model, I try to test it with FFmpeg, vmafossexec and ./python/vmaf/script/run_vmaf.py. It seems that only 
 run_vmaf.py can use this model. Both FFmpeg and vmafossexec will generate the following error:
**Caught VmafException: Error loading model (.pkl): Unknown token**

My question is that whether the model trained by run_vmaf_training.py can only be used with run_vmaf.py. Is this a bug or limitation.
Looking forward to your reply.
Thanks

**Comment by li-zhi** [comment]
This is an issue with python3. The ptools library can only process python2
pickle files. A temporary solution is to convert the py3 pickle file to py2
compatible. We are looking for a long term solution - possibly retire the
ptools library.

Please keep this issue open.

**Comment by paulwgw88** [comment]
> pickle files. A temporary solution is to convert the py3 pickle file to py2

@li-zhi , thanks for your kindly reply. I will try the temporary solution to avoid this issue for now. 
Looking forward to your long term solution.

**Comment by paulwgw88** [comment]
@li-zhi I have tried to change the pickle protocol to 0/1/2 in train_test_model.py, but none of the model file was readable by ptools. I am wondering how did the default model vmaf_v0.6.1.pkl be generated.
Thanks.

**Comment by li-zhi** [comment]
Try this in python2.x:
```
with open(output_vmaf_model_path, 'wb') as output_file:
    pickle.dump(vmaf_model, output_file, protocol=1)
```

**Comment by paulwgw88** [comment]
> Try this in python2.x:
> 
> ```
> with open(output_vmaf_model_path, 'wb') as output_file:
>     pickle.dump(vmaf_model, output_file, protocol=1)
> ```

Still can not work. I just wrote a simple script as follows and ran it in python2.7.18 to perform the conversion. The src.pkl is generated by run_vmaf_training.py. When using the default protocol (seems to be 4) in train_test_model.py, the src.pkl was not able to be loaded by pickle of python2. Then I change the protocol to 2 in train_test_model.py, the src.pkl could be loaded by pickle of python2. However, the dst.pkl generated by the following script with protocol 1 was still not readable by ptools, showing the following error:
**Caught VmafException: Error loading model (.pkl): Don't know how to handle X**


**convert.py:**
import pickle as pkl
with open('./src.pkl','rb') as rFd:
    data = pkl.load(rFd)
    pkl.dump(data, open('./dst.pkl','wb'), protocol=1)

**Comment by li-zhi** [comment]
Ok. If you could wait for 3 more weeks, we'll be migrating away from the ptools library and instead using json as the model file format.
