### ISSUE TITLE
Why my VMAF_score is 0?

### ISSUE THREAD

**Issue by zhuxiaol** [Netflix/vmaf#686]
Why my VMAF_score is 0?

{rame: 0/0
"executorId": "VMAF_VF0.2.4c-0.6.1",
"asset": {
"identifier": "cmd_9658997764371198_9658997764371198_13_real_teapot_376x224_376x224_vs_13_arcore_teapot_376x224_q_376x224"
},
"frames": [
{
"frameNum": 0,
"VMAF_feature_adm2_score": 0.541459791730362,
"VMAF_feature_motion2_score": 0.0,
"VMAF_feature_vif_scale0_score": 0.16038680879058081,
"VMAF_feature_vif_scale1_score": 0.28488235071996626,
"VMAF_feature_vif_scale2_score": 0.3145256747290411,
"VMAF_feature_vif_scale3_score": 0.33458374222480275,
"VMAF_score": 0.0
}
],
"aggregate": {
"VMAF_feature_adm2_score": 0.541459791730362,
"VMAF_feature_motion2_score": 0.0,
"VMAF_feature_vif_scale0_score": 0.16038680879058081,
"VMAF_feature_vif_scale1_score": 0.28488235071996626,
"VMAF_feature_vif_scale2_score": 0.3145256747290411,
"VMAF_feature_vif_scale3_score": 0.33458374222480275,
"VMAF_score": 0.0,
"method": "mean"
}
}

**Comment by li-zhi** [comment]
The most common culprit in this situation is that your reference/distortedd frames are not aligned. Can you report the PSNR value received? What is your command?

**Comment by BassThatHertz** [comment]
I also got VMAF scores of 0 in the past and I posted [this issue](https://github.com/Netflix/vmaf/issues/629).
Try specifying the framerate before `-i` with `-r <framerate>` and synchronize the PTS with `setpts=PTS-STARTPTS`. See the example [here](https://github.com/Netflix/vmaf/blob/master/resource/doc/ffmpeg.md#using-vmaf-with-ffmpeg).

**Comment by li-zhi** [comment]
Is it a single frame? Most likely the reference/distorted frames are not aligned.

**Comment by nilfm** [comment]
Closing this issue as it hasn't been updated in years.
