### ISSUE TITLE
Build with external toolchain

### ISSUE THREAD

**Issue by pvonkaenel** [Netflix/vmaf#688]
Hi,

I'm in the unfortunate position of needing to build in a company provided build environment based on Centos.  Last year I was able to get VMAF to build using our toolchain fairly easily since the build was based on make.  Now that it's migrated to Meson, I'm having a lot of difficulty.  I've added a --cross-file which specifies where the C and C++ compiler binaries exist, but when I do, it looks like some of the default compiler options no longer take effect, such as --std=c99.  Has anyone been able to get the VMAF library to build using an external toolchain?

**Comment by kylophone** [comment]
I might be able to help you, but first: What exactly do you mean by "external toolchain"?

**Comment by pvonkaenel** [comment]
Thanks for the link @kylophone , I think I'll try this approach instead of the --cross-file option.  What worries me about both approaches is there's no was to just specify a base toolchain directory, so I have to also specify the compiler lib and include directories in more env vars.  I just hope I'm not missing something which results in a mix of compiler tools.

**Comment by pvonkaenel** [comment]
I've tried using the CC and CXX environment variables, and at least now I'm using the correct compiler.  However, it's failing when using the default linker.  Using CC_LD and CXX_LD complains that I'm not specifying a supported linker.

Has anyone been able to get a noon-standard toolchain working?

Thanks

**Comment by pvonkaenel** [comment]
Here's the error I'm seeing:

     [exec] In file included from vmaf/core/adm_dwt2_cy.c:637:
     [exec] vmaf/core/../../../libvmaf/src/feature/adm_tools.c:935:60: note: expected 'const adm_dwt_band_t_d *' {aka 'const struct adm_dwt_band_t_d *'} but argument is of type 'struct __pyx_t_4vmaf_4core_11adm_dwt2_cy_adm_dwt_band_t *'
     [exec]   935 | void adm_dwt2_d(const double *src, const adm_dwt_band_t_d *dst, int **ind_y, int **ind_x, int w, int h, int src_stride, int dst_stride)
     [exec]       |                                    ~~~~~~~~~~~~~~~~~~~~~~~~^~~
     [exec] In file included from vmaf/core/../../../libvmaf/src/feature/adm_tools.c:29,
     [exec]                  from vmaf/core/adm_dwt2_cy.c:637:
     [exec] vmaf/core/adm_dwt2_cy.c: At top level:
     [exec] vmaf/core/../../../libvmaf/src/feature/adm_tools.h:344:59: warning: 'dwt_7_9_basis_function_amplitudes' is static but used in inline function 'dwt_quant_step' which is not static
     [exec]   344 |     float Q = 2.0*params->a*pow(10.0,params->k*temp*temp)/dwt_7_9_basis_function_amplitudes[lambda][theta];
     [exec]       |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     [exec] gcc -pthread -shared -Wl,-z,relro -g build/temp.linux-x86_64-3.6/vmaf/core/adm_dwt2_cy.o -L/usr/lib64 -lpython3.6m -o ./vmaf/core/adm_dwt2_cy.cpython-36m-x86_64-linux-gnu.so
     [exec] /usr/bin/ld: /opt/omneon/cross_x86_64_v9/x86_64-linux/lib64/../lib64/crti.o: unrecognized relocation (0x2a) in section `.init'
     [exec] /usr/bin/ld: final link failed: Bad value
     [exec] collect2: error: ld returned 1 exit status
     [exec] /home/vagrant/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /vagrant/src/Tools/vmaf/VMAF/python/vmaf/core/adm_dwt2_cy.pyx
     [exec]   tree = Parsing.p_module(s, pxd, full_module_name)
     [exec] /usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
     [exec]   warnings.warn(msg)
     [exec] /usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'include_package_data'
     [exec]   warnings.warn(msg)
     [exec] /usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
     [exec]   warnings.warn(msg)
     [exec] /usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'entry_points'
     [exec]   warnings.warn(msg)
     [exec] error: command 'gcc' failed with exit status 1
     [exec] make: *** [all] Error 1

**Comment by pvonkaenel** [comment]
I think I've figured it out.  I'm running the Makefile in the root directory, and it's failing on the last line in the "all" target:
	cd python && python3 setup.py build_ext --build-lib .

When I remove it, it completes.
