### ISSUE TITLE
Problem overriding nasm version

### ISSUE THREAD

**Issue by efleurant** [Netflix/vmaf#690]
Hi,

I am currently trying to configure `libvmaf` with `meson` and I'm having a hard time overriding the version of `nasm` that gets auto-detected.

In other words running meson detects the default `nasm` version installed on CentOS, but I want to be able to point to a custom and newer build of `nasm` installed in a specific directory (without having to install that version of `nasm` on the system).

This is super easy in `cmake`, but how do I go about doing that with `meson` (giving me a hard time!!!)

Thanks in advance!

**Comment by 1480c1** [comment]
https://github.com/Netflix/vmaf/blob/master/libvmaf/src/meson.build#L40 seems it just looks for `nasm`, which I assume they just look in your `PATH` variable, so try prepending the path to your special `nasm` before your normal path?

**Comment by efleurant** [comment]
> https://github.com/Netflix/vmaf/blob/master/libvmaf/src/meson.build#L40 seems it just looks for `nasm`, which I assume they just look in your `PATH` variable, so try prepending the path to your special `nasm` before your normal path?

That worked like a charm, thanks!
