### ISSUE TITLE
I can't find Vmaf Relase and x64 file.  Could you please help me ?

### ISSUE THREAD

**Issue by erkans1** [Netflix/vmaf#694]
**First of all, I want you to know that I am very newbie.
 
I cannot find the x64 folder and exe files in the relases files you recommend for Windows.
 
After finding the exe files, my job seems easy but I can't find it.
 
Can you please help from the very beginning? This is very important for me.**

**Comment by 1480c1** [comment]
For windows, you could go here https://github.com/Netflix/vmaf/runs/1334416168?check_suite_focus=true and click on the artifacts on the top right and try to see if the binary you download is good enough for you, if not there's this place https://github.com/Netflix/vmaf/releases/tag/v1.5.3

**Comment by erkans1** [comment]
thank you for your help.  I did it as you specified but  there are another problem. 
![WhatsApp Image 2020-11-03 at 08 42 53](https://user-images.githubusercontent.com/73784828/97953620-26f66c00-1db2-11eb-8a02-840636b0732a.jpeg)

As you see ı did it but  system does not calculate VMAF score, calculates frame like Frame 347/760. Why is this happening ?
I spent a lot of hours, days for this. Could you help me again ?

**Comment by eclipseo** [comment]
vmafossexec does not output to screen but to a file. Maybe you should add [--log log_path] [--log-fmt log_fmt]  to specify where to save the data and its format? If you want it on your screen it's --log /dev/stdout on Linux but I don't know how it works on Windows.

**Comment by nilfm** [comment]
Closing this old issue as part of a clean-up.
