### ISSUE TITLE
Interalaced Sources to calculate the vmaf score

### ISSUE THREAD

**Issue by lazybing** [Netflix/vmaf#702]
how can i use vmaf to compare the interlaced source and progressive bitstream?

I have a interlace bitstream and i convert it to progressive bitstream using ffmpeg with yadif filter.

then how can i calculate the vmaf score with the two bitstreams?

I test it with the method mentioned in this artical https://gdavila.github.io/broadcast/Vmaf/2020-03-05-Vmaf/#interalaced-sources.

the vmaf score is very low, about 50-60 score, but The video quality looks good.

**Comment by gdavila** [comment]
@lazybing  from my empirical experience, if the scores are low but upper 50/60, the deinterlacing filter you are using is not working as expected. 

Using ffmpeg, you may try:

```
ffmpeg -i <distorted> -i <reference> -lavfi "[1:v]yadif=0:-1:0[ref];[0:v][ref]libvmaf=model_path=/usr/local/share/model/VMAF_v0.6.1.pkl" -f null -
```
The above commandline assumes that reference stream is interlaced, so it is passed to the `yadif ` filter with the options  `mode:parity:deint = 0:-1:0 `. This means:

 `0`: Output one frame per each frame in the input (So if the filter input had a frame rate of 29.97i with interlaced scan mode, the yadif filter will output 29.97p in progressive mode)
 `-1`: Enable automatic detection of field parity.
 `0`: Deinterlace all frames.

BTW, I've updated the article you provide with a more comprehensive version: https://ottverse.com/vmaf-easyvmaf/

**Comment by lazybing** [comment]
tks gdavila.

You are so good.
