### ISSUE TITLE
[Question] How to implement progress method?

### ISSUE THREAD

**Issue by fu-hsi** [Netflix/vmaf#704]
Hi.
I use ffmpeg and libvmaf and the only information I get is:

`frame=  150 fps=1.8 q=-0.0 Lsize=N/A time=00:00:05.00 bitrate=N/A speed=0.0615x`

I don't want to wait for the program to finish, because it takes a long time.
I need to implement a progress method with current PSNR, SSIM and VMAF information.

How to do that in Windows?
I know, I can read xml log at the and, but this file is not updated until they are finished.

Regards.

**Comment by nilfm99** [comment]
Just found this looking at old issues, sorry we didn't pick this one up. The answer, as far as I know, is that there's no way to do that just by using the ffmpeg CLI. It would be possible to get intermediate results by calling the libvmaf C API.

Closing as inactive, please open a new issue if needed and we will respond there.
