### ISSUE TITLE
[Feature Request]: Would it be possible to embed a default model file inside libvmaf?

### ISSUE THREAD

**Issue by 1480c1** [Netflix/vmaf#709]
It would be nice to be able to embed a default model file inside the libvmaf as something like a `static char array` that libvmaf would read from instead of a file if the model_path is NULL or zero-length so it would be easier to use on systems with no good defaults for where to read from (windows).

I know on Linux, you can use `xxd -i file` to print out an `unsigned char` array composed of hexadecimal, but I am not sure what would be a good equivalent on windows and macOS

**Comment by kylophone** [comment]
Yes, this is actually a plan of mine. We will compile in a few models.

**Comment by kylophone** [comment]
#724 merged.

**Comment by 1480c1** [comment]
@kylophone how hard would it be to add something like a "keyword" to use the internal model files when passed as the `model_path` through ffmpeg and others (including aomenc) until proper support has been added on their side? Something like `libvmaf=model_path="NULL"` or similar to use the default model instead of looking for a file called `NULL`?

**Comment by kylophone** [comment]
I would rather approach this from the `libaom` side. They were already linking our release candidate library, so they'll have to rewrite a portion of that code anyway. I can reach out to them and report back here. Obviously the main advantage to using the built-in models is the fact that everything is self contained and nothing auxiliary is required. The way we approached this in `vmaf` was to just always default to `v0.6.1` whenever `--model` was not passed.

**Comment by 1480c1** [comment]
I see, thanks
