### ISSUE TITLE
What are the options to print ms-ssim values when running `run_vmaf`?

### ISSUE THREAD

**Issue by ethanjyx** [Netflix/vmaf#73]
I heard we can print ms-ssim values while running `run_vmaf`, is it true? How can I enable it?  Did not find documentation when running `./run_vmaf --help`.

```
$ ./run_vmaf --help
usage: run_vmaf fmt width height ref_path dis_path [--model model_path] [--out-fmt out_fmt]

fmt:
	yuv420p
	yuv422p
	yuv444p
	yuv420p10le
	yuv422p10le
	yuv444p10le

out_fmt:
	text (default)
	xml
	json
```

**Comment by li-zhi** [comment]
Try wrapper/vmafossexec

**Comment by ethanjyx** [comment]
Thank you Zhi. However, after giving a try, I am getting an error message below: 
```
Start calculating VMAF score...
Input model at --phone-model cannot be read successfully.
Error: Error loading model (.pkl): Trouble reading the file:--phone-model
```

Here is my command:
`./vmafossexec yuv420p 768 512 ~/Documents/vp9_encode/raw/grouplove265_6k_768x512.yuv ~/Documents/vp9_encode/libvpx_samples/grouplove265_6k_768x512.mp4crf28.yuv --phone-model --ms-ssim`
Am I using this right?

**Comment by li-zhi** [comment]
You would need to add path to the model file, as in:
```
./vmafossexec yuv420p 768 512 ~/Documents/vp9_encode/raw/grouplove265_6k_768x512.yuv ~/Documents/vp9_encode/libvpx_samples/grouplove265_6k_768x512.mp4crf28.yuv ../model/vmaf_v0.6.1.pkl --phone-model --ms-ssim
```
