### ISSUE TITLE
Ambiguous dates in the change log and "News" section of readme

### ISSUE THREAD

**Issue by varnav** [Netflix/vmaf#746]
Example:

> (12/3/20) We are releasing libvmaf v2.0.0. It has a new fixed-point and SIMD-optimized implementation that achieves 2x speed 
> up compared to the previous floating-point version. It also has a new API that is more flexible and extensible.

It is unclear if this is 12th of March (around 6 billion people in the world are used to this format) or 3rd of December (mm/dd/yyyy format used in just one country).

Best format for this would be `2020-03-12`, or, if you want to stay with US-styled endianness but eliminate ambiguity  - `March 12, 2020`

**Comment by li-zhi** [comment]
Good point. Thanks!

**Comment by 1480c1** [comment]
If going the unambiguous route, I personally would prefer 3 Dec 2020 since it eliminates one of the number groups and feels less ambiguous, although it uses more characters and might be harder to parse if expecting just numbers and symbols

**Comment by slhck** [comment]
This has already been fixed in https://github.com/Netflix/vmaf/commit/42c380c5ceb281be3e8728e77cb87a764ce60c62

**Comment by li-zhi** [comment]
I'll close this for now. Let's stick to one format going forward, which is yyyy-mm-dd.
