### ISSUE TITLE
[Question] Per Channel Scores?

### ISSUE THREAD

**Issue by DarrenR96** [Netflix/vmaf#754]
VMAF outputs per frame scores and then an aggregated clip score, but is there anyway to allow for a per channel score? E.g. if the frame is YUV format, is there a Y, U and V score that could be used before it is aggregated to give the frame score?

**Comment by kylophone** [comment]
At the moment VMAF features are defined on the Y channel only. While one could calculate the same metrics on the other channels, it is not meaningful. There are other auxiliary metrics in libvmaf which are well-defined when it comes to chroma (i.e. `psnr_cb`, `psnr_cr`) which are part of the output logs.
