### ISSUE TITLE
vmaf_4k_v0.6.1.json not working

### ISSUE THREAD

**Issue by Killua-Zolldyck** [Netflix/vmaf#759]
Hi there,

Starting with the release of v2.0.0 built into ffmpeg (using Media Autobuild Suite), I always get an error message when I try to use vmaf_4k_v0.6.1.json:

problem loading feature extractors from model file: [...]vmaf_4k_v0.6.1.json

Using vmaf_v0.6.1.json (no 4K) is working fine, but not really what I want to use.

Any help appriciated.

Best regards and stay healthy!

**Comment by 1480c1** [comment]
can you print the full command line you used, also does the same error show up with other model files?

**Comment by Killua-Zolldyck** [comment]
Here comes the requested information:

command line:
ffmpeg -i "vidfile1.mkv" -i "vidfile2.mkv" -lavfi libvmaf="model_path=C\\:/mypath/model/vmaf_4k_v0.6.1.json" -f null -

I've tested all json files inside model folder and subfolders and the only 2 working are vmaf_v0.6.1.json and vmaf_v0.6.1neg.json. All other fail.

**Comment by 1480c1** [comment]
can you try with relative paths and also make sure you follow https://github.com/Netflix/vmaf/blob/master/resource/doc/ffmpeg.md#note-about-the-model-path-on-windows ?

**Comment by Killua-Zolldyck** [comment]
Just tried the following command line with json file in the same folder:

ffmpeg -i "vidfile1.mkv" -i "vidfile2.mkv" -lavfi libvmaf="model_path=vmaf_4k_v0.6.1.json" -f null -

Still getting "problem loading feature extractors from model file". Be aware that is another error message than eg having a wrong path or filename which is resulting in "problem loading model file".

**Comment by gdavila** [comment]
Hi,

I found a bug on `vmaf` executable that also could be related with this issue . I'm running the next command:

```
vmaf  --reference src01_hrc00_576x324.yuv --distorted src01_hrc01_576x324.yuv  --width 576 --height 324 --pixel_format 420 --bitdepth 8  --model version=<model_version>
```

The previous command works just for `vmaf_v0.6.1` and `vmaf_v0.6.1neg` models. For the rest of the models I get the error message `problem loading model`

The same happens using `ffmpeg`. **The only valid `model_paths` are `vmaf_v0.6.1.json` and `vmaf_v0.6.1neg.json`**. For the rest of models located on the model folder I get the error` problem loading feature extractors from model file`, i,e:

```
ffmpeg -video_size 576x324 -r 24 -pixel_format yuv420p -i src01_hrc00_576x324.yuv     -video_size 576x324 -r 24 -pixel_format yuv420p -i src01_hrc01_576x324.yuv     -lavfi "[0:v]setpts=PTS-STARTPTS[reference]; \
            [1:v]setpts=PTS-STARTPTS[distorted]; \
            [distorted][reference]libvmaf=log_fmt=xml:log_path=/dev/stdout:model_path=vmaf-2.0.0/model/vmaf_4k_v0.6.1.json"  \
           -f null -
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --enable-libvmaf --enable-version3 --disable-shared
 [omited output]
[LIBVMAF] `compute_vmaf()` is deprecated and will be removed in a future libvmaf version
problem loading feature extractors from model file: vmaf-2.0.0/model/vmaf_4k_v0.6.1.json
[Parsed_libvmaf_2 @ 0x564065b2b400] libvmaf encountered an error, check log for details
Error while filtering: Invalid argument
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #1:0
Conversion failed!
```

**Comment by xiaokeZuo** [comment]
Hi,

I met the same problem in Ubuntu 18.04 and only vmaf_v0.6.1.json and vmaf_v0.6.1neg.json can be used.

**Comment by li-zhi** [comment]
vmaf_4k_v0.6.1.json has not been updated to use fixed-point features. I just committed to change to fix this in #759. Please try the latest master branch.

**Comment by gdavila** [comment]
Thanks!

It was solved for `vmaf_4k_v0.6.1.json`

However, I am confused about the proper use of model files, i.e., when should I use `vmaf_float_v0.6.1.json` instead of `vmaf_v0.6.1.json`? If I try to run vmaf by using ` vmaf_float_v0.6.1.json` got the same previous error message: `problem loading model file`

**Comment by li-zhi** [comment]
```
However, I am confused about the proper use of model files, i.e., when
should I use vmaf_float_v0.6.1.json instead of vmaf_v0.6.1.json? If I try
to run vmaf by using vmaf_float_v0.6.1.json got the same previous error
message: problem loading model file
```
This is probably something to do with ffmpeg hasn't been updated with
working with the latest API. You are still using the old API and by default
it is coupled with the fixed point features. This should be fixed once the
ffmpeg is updated.

**Comment by Killua-Zolldyck** [comment]
Just built a new version of ffmpeg and vmaf_4k_v0.6.1.json is working fine now. Thank you!

**Comment by kylophone** [comment]
> However, I am confused about the proper use of model files, i.e., when should I use `vmaf_float_v0.6.1.json` instead of `vmaf_v0.6.1.json`? If I try to run vmaf by using ` vmaf_float_v0.6.1.json` got the same previous error message: `problem loading model file`

Hi @gdavila,

You can pretty much consider the `vmaf_float_*.json` versions of all the models deprecated. We rewrote the elementary feature extractors to use fixed-point data types and we have provided new models trained on those new feature extractors, and renamed the original models with the `_float_`. Numerically, the results are extremely close. We haven't removed the old "float" feature extractors from the codebase just in case someone wanted to validate results. These feature extractors are available, but they are not compiled-in by default, add `-Denable_float=true` to your meson command to compile them into your libvmaf build. As for that error message, it's very cryptic. As soon as I merge https://github.com/Netflix/vmaf/pull/767/commits/53f3eb1cad8eefe78d41de89ee58f1555f0ae2ff it should become more obvious exactly why things are failing.

Thanks,
Kyle

**Comment by uthay45** [comment]
> Hi there,
> 
> Starting with the release of v2.0.0 built into ffmpeg (using Media Autobuild Suite), I always get an error message when I try to use vmaf_4k_v0.6.1.json:
> 
> problem loading feature extractors from model file: [...]vmaf_4k_v0.6.1.json
> 
> Using vmaf_v0.6.1.json (no 4K) is working fine, but not really what I want to use.
> 
> Any help appriciated.
> 
> Best regards and stay healthy!

Hii actually i have a problem with **vmaf_v0.6.1.json** itself it showing segmentation fault error.

[mcw@localhost linux]$ ./x265 --input /mnt/Cajon/testsequences/BasketballDrive_3840x2160_50.yuv --input-res 3840x2160 --fps 50 --recon recon.yuv -o out.hevc --csv out.csv
yuv  [info]: 3840x2160 fps 50000/1000 i420p8 frames 0 - 500 of 501
yuv  [info]: reconstructed images 3840x2160 fps 50000/1000 i420
raw  [info]: output file: out.hevc
x265 [info]: HEVC encoder version 3.5+119-e112940
x265 [info]: build info [Linux][GCC 12.2.0][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [info]: Main 10 profile, Level-5.1 (Main tier)
x265 [info]: Thread pool 0 using 44 threads on numa nodes 0
x265 [info]: Thread pool 1 using 44 threads on numa nodes 1
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 6 / wpp(34 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : hex / 57 / 2 / 3
x265 [info]: Keyframe min / max / scenecut / bias  : 25 / 250 / 40 / 5.00
x265 [info]: Lookahead / bframes / badapt        : 20 / 4 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
x265 [info]: References / ref-limit  cu / depth  : 3 / off / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 2 / 1.0 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-28.0 / 0.60
x265 [info]: tools: rd=3 psy-rd=2.00 early-skip rskip mode=1 signhide tmvp
x265 [info]: tools: b-intra strong-intra-smoothing lslices=8 deblock sao
libvmaf INFO `compute_vmaf()` is deprecated and will be removed in a future libvmaf version
Segmentation fault (core dumped)
