### ISSUE TITLE
 test_model FAIL: problem during vmaf_model_load_from_path

### ISSUE THREAD

**Issue by gdavila** [Netflix/vmaf#760]
I'am runing the following commands under libvmaf directory. I'm using a docker image with `ubuntu:20.04`
```
	meson build --buildtype release && \
	ninja -vC build && \
	ninja -vC build test && \
	ninja -vC build install && \
```

However,  I got the next error message:
```

1/9 test_picture OK 0.02s
2/9 test_feature_collector OK 0.02s
3/9 test_thread_pool OK 0.02s
5/9 test_predict OK 0.01s
6/9 test_feature_extractor OK 0.07s
7/9 test_dict OK 0.01s
8/9 test_cpu OK 0.02s
9/9 test_ref OK 0.02s
The output from the failed tests:
4/9 test_model FAIL 0.01s (exit status 1)
--- command ---
13:11:37 /tmp/workdir/vmaf-master/libvmaf/build/test/test_model
--- stderr ---
test_json_model: [31mfail[0m[31m, problem during vmaf_model_load_from_path
```

Any clue about this issue?

**Comment by kylophone** [comment]
Yeah, try running from the `./build` directory. I believe the test paths are relative to this directory. Should probably find a way to fix this...

**Comment by gdavila** [comment]
I'm not familiar with ninja and meson, so a couple of questions:

1. How can I run the test from the ./build directory? I got the following error 
```
root@765a9ebca060:/tmp/workdir/vmaf-master/libvmaf/build# ninja -vC  test
ninja: Entering directory `test'
ninja: error: loading 'build.ninja': No such file or directory
```

2. How can I check if I'm using the built-i models? I just used the default parameters:
```
	meson build --buildtype release && \
	ninja -vC build && \
```

**Comment by 1480c1** [comment]
just run `ninja -v test`

**Comment by kylophone** [comment]
What I meant is that tests are just binaries that you can run directly: `./build/test/test_model`

**Comment by gdavila** [comment]
Thanks,

I got the same error.
```
root@765a9ebca060:/tmp/workdir/vmaf-master/libvmaf# ./build/test/test_model
test_json_model: fail, problem during vmaf_read_json_model
1 tests run, 1 failed
```

Do you know if this is just an issue of the test module or it could have impact on vmaf also?

**Comment by kylophone** [comment]
The failure is here: https://github.com/Netflix/vmaf/blob/master/libvmaf/test/test_model.c#L70-L71

Since these tests pass on CI, it is likely a difference in your environment. Probably having to do with the relative path. What OS are you on?

**Comment by gdavila** [comment]
I'm using `ubuntu 20.04`  in a docker image.

If you are familiar with docker, you can try it out by using [this dockerfile](https://gist.githubusercontent.com/gdavila/dc629f60890bdfd80a3afeb23372da5e/raw/d300da7425b74e95a40d12291d610d09e1d8a2de/Dockerfile-vmaf-test):

```
docker build -t vmaf-build-test https://gist.githubusercontent.com/gdavila/dc629f60890bdfd80a3afeb23372da5e/raw/d300da7425b74e95a40d12291d610d09e1d8a2de/Dockerfile-vmaf-test
```

**Comment by gdavila** [comment]
I solved this issue by installing xxd package: `apt-get install xxd`. I dont know if this package was not needed on previous VMAF versions or it was removed on updated ubuntu distribtions.
