### ISSUE TITLE
NEG does not appear to have the same effect on models 0.6.1 and 0.6.3

### ISSUE THREAD

**Issue by ltrudeau-twoorioles** [Netflix/vmaf#765]
It has come to our attention that the effect of applying NEG on model 0.6.1 differs from the effect of applying NEG on model 0.6.3.

While the "normal" versions of models 0.6.1 and 0.6.3 performed very similarly to each other (i.e. the difference is often within 0.5% BDRate-VMAF of each other). The NEG versions of models 0.6.1 and 0.6.3 can differ up to 8% BDRate-VMAF-NEG.

For model 0.6.1 NEG, we used the built-in model `--model=version=vmaf_v0.6.1neg`. For 0.6.3 NEG, we used the built-in model `vmaf_b_v0.6.3` with the following extra parameters `--feature vif=vif_enhn_gain_limit=1.0 --feature adm=adm_enhn_gain_limit=1.0`.

We expected that NEG would have a similar effect on both of these models, but it does not appear to be the case. We are curious as to whether this is intentional or not and would love to find out more about this.

**Comment by li-zhi** [comment]
This is interesting. vmaf_b_v0.6.3 is a model retrained on the same dataset used to train vmaf_v0.6.1, after some small feature fixes. Plus, it is a bootstrapping model that gives confidence intervals. I wouldn't expect such large deviation.

To triage the problem: have you tried to use the enhn_gain_limit parameters combined with vmaf_v0.6.1 model and see if it produces the same result as vmaf_v0.6.1neg?

**Comment by ltrudeau-twoorioles** [comment]
Sorry for the false alarm, this appears to be a parsing problem with one of my scripts.
