### ISSUE TITLE
Why libvmaf2.0 is slower than v1.3.14

### ISSUE THREAD

**Issue by dark-light24** [Netflix/vmaf#771]
I compare libvmaf2.0 and v1.3.14 with same parameters, but libvmaf2.0 is slower and fps is not correct. 
Are my configuration or parameters are not correct?
And I redirect stdout and stderr to file ( >vmaf.log 2>&1), but result file is empty. How can I fix it ? 
Thanks very much.

libvmaf 2.0 test:
 time vmaf -w 1280 -h 720 -b 8 -p 420 -r /Users/linke01/yuv_input/vidyo1_1280x720_60.yuv -d test_1280x720.yuv -m version=vmaf_v0.6.1 --threads 4
VMAF version 2.0.0
600 frames ⠉⠙ 6.11 FPS
vmaf_v0.6.1: 89.145320

real	0m27.607s
user	1m37.711s
sys	0m1.096s

v1.3.14:
time ~/vmaf/wrapper/vmafossexec yuv420p 1280 720 /Users/linke01/yuv_input/vidyo1_1280x720_60.yuv test_1280x720.yuv  ~/vmaf/model/vmaf_v0.6.1.pkl --thread 4
Start calculating VMAF score...
Exec FPS: 32.873996
VMAF score = 89.175719

real	0m18.274s
user	0m56.917s
sys	0m4.321s

**Comment by malakudi** [comment]
Check https://github.com/Netflix/vmaf/issues/770

**Comment by dark-light24** [comment]
> Check #770

they are both threads=4，other parameters are same too.

**Comment by kylophone** [comment]
I cannot reproduce your issue. I ran the same versions with the same resolution input and parameters and got the following. The new version is both "wall-clock" faster and uses less CPU time. Are you running on x86, and have you compiled with the AVX2/AVX-512 SIMD?

`vmafossexec` v1.3.14
```sh
Start calculating VMAF score...
Exec FPS: 44.441161
VMAF score = 97.428043
real        13.51
user        50.08
sys          3.10
 252268544  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
     61242  page reclaims
       104  page faults
         0  swaps
         0  block input operations
         0  block output operations
         0  messages sent
         0  messages received
         0  signals received
        13  voluntary context switches
     29519  involuntary context switches
```
`vmaf` v2.0.0
```sh
VMAF version 9f5ecc65
600 frames ⠉⠙ 17.80 FPS
vmaf_v0.6.1: 97.428043
real         8.63
user        32.91
sys          1.01
 198070272  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
     47600  page reclaims
         0  page faults
         0  swaps
         0  block input operations
         0  block output operations
         0  messages sent
         0  messages received
         0  signals received
         0  voluntary context switches
    105973  involuntary context switches
```

**Comment by dark-light24** [comment]
After I download the latest code, the speed is similar as yours.  (One thread test,  AVX2,  user time is similar as yours):

time /Users/linke01/Downloads/vmaf-master_2/libvmaf/build/tools/vmaf  --reference /Users/linke01/yuv_input/vidyo1_1280x720_60.yuv --distorted test_1280x720.yuv --width 1280 --height 720 --pixel_format 420 --bitdepth 8 --model version=vmaf_v0.6.1 --threads 1
VMAF version 2.0.0
600 frames ⠉⠙ 17.54 FPS
vmaf_v0.6.1: 89.145320

real	0m34.473s
user	0m33.360s
sys	0m0.945s

But when I download the release version v2.0.0:  Source code(zip) or macos-10.15-vmaf.zip
The speed is the same as before ( enable_asm=true, enable_avx512=false, my cpu just supports avx2):

time /Users/linke01/Downloads/vmaf-2.0.0/libvmaf/build/tools/vmaf  --reference /Users/linke01/yuv_input/vidyo1_1280x720_60.yuv --distorted test_1280x720.yuv --width 1280 --height 720 --pixel_format 420 --bitdepth 8 --model version=vmaf_v0.6.1 --threads 1
VMAF version 2.0.0
600 frames ⠉⠙ 7.43 FPS
vmaf_v0.6.1: 89.145320

real	1m22.070s
user	1m19.948s
sys	0m1.091s

So I just need to update the code to the latest. Thanks.
