### ISSUE TITLE
Cflags's in libvmaf.pc not in sync with how headers are looked up in the meson config

### ISSUE THREAD

**Issue by ekacnet** [Netflix/vmaf#772]
The generated libvmaf.pc contains this stanza for includes: `Cflags: -I${includedir}/libvmaf` but meson config uses `libvmaf_inc = include_directories(['include'])`.
When using the information from the pkgconfig file headers should be included without prefixing them with `libvmaf` like it's the case in ffmpeg, but when using the information from the meson config they should be prefixed with `libvmaf` as it's the case in `libvmaf/tools/main.cpp` or `libvmaf/tools/cli_parse.c`

**Comment by kylophone** [comment]
My take on this is the `libvmaf` "prefix directory", _i.e._ `libvmaf/libvmaf.h` is correct. The un-namespaced way things were being done previously was just bad practice. We should clean up the internal use of the headers of, course. Externally this is just one of the differences in the major version bump. For the FFmpeg filter specifically, I will be sending a new version to `ffmpeg-devel` quite soon which will take this into account. Any other thoughts or questions, let me know.

**Comment by ekacnet** [comment]
@kylophone It's not the internal use of the headers that you need to fix, I think they are correct (they use the prefix). It's the way the include path is expose to things using the pkgconfig like ffmpeg for instance.

**Comment by kylophone** [comment]
> @kylophone It's not the internal use of the headers that you need to fix, I think they are correct (they use the prefix). It's the way the include path is expose to things using the pkgconfig like ffmpeg for instance.

Yeah, I got you. This is a change that happened with `v2.0.0`. The rationale should hopefully make sense. From v2.0.0 onward, users of this lib will need to use `#include "libvmaf/libvmaf.h"`. This was a major release, and we've tried to maintain a certain amount of backward compatibility (like `compute_vmaf.h`). But since this was fundamentally broken we decided to use the major version bump to fix it.

```
prefix=/usr/local
libdir=${prefix}/lib
includedir=${prefix}/include

Name: libvmaf
Description: VMAF, Video Multimethod Assessment Fusion
Version: 2.0.0
Libs: -L${libdir} -lvmaf
Libs.private: -lm
Cflags: -I${includedir}/libvmaf
```
