### ISSUE TITLE
CI: Travis tests are not running 

### ISSUE THREAD

**Issue by kylophone** [Netflix/vmaf#774]
> Owner Netflix does not have enough credits.

This was a silent failure for 12 days. I guess this means that it's time to move to Github Actions completely. Most of the work is already redundant, the two outstanding things I can think of are as follows:

- Python `tox` tests. This should be moved to Github Actions immediately.
- ARM builds, this needs to stay of Travis until Github supports ARM runners. Hopefully with MacOS M1, maybe they'll have something like that soon. Based on this comment: https://github.com/actions/virtual-environments/issues/2187#issuecomment-737339211, it will probably take some time.

**Comment by kylophone** [comment]
> * Python `tox` tests. This should be moved to Github Actions immediately.

I am actively work on this right now.

**Comment by 1480c1** [comment]
For the arm builds, it would probably be best to add a cross compilation job for now

**Comment by kylophone** [comment]
> For the arm builds, it would probably be best to add a cross compilation job for now, that is what I'm working towards in svt-av1

Good idea. Really the only reason we have this is to avoid cross-platform breakage.

**Comment by kylophone** [comment]
#775 merged, tox tests are now running on Github actions. There is still an issue with the MacOS tox tests, and it seems to have something to do with Python version.
