### ISSUE TITLE
Range for VMAF_score 

### ISSUE THREAD

**Issue by khavishbhundoo** [Netflix/vmaf#78]
> "aggregate": {
>         "VMAF_feature_adm2_score": 0.93458780728708746,
>         "VMAF_feature_motion2_score": 3.8953518541666665,
>         "VMAF_feature_vif_scale0_score": 0.36342081156994926,
>         "VMAF_feature_vif_scale1_score": 0.76664738784617292,
>         "VMAF_feature_vif_scale2_score": 0.86285338927816291,
>         "VMAF_feature_vif_scale3_score": 0.91597186913930484,
>         "VMAF_score": 76.699271272486044,
>         "method": "mean"
>     }

What is the range for VMAF_score ? .I am particularly interested to know the  best , average and worst range

**Comment by li-zhi** [comment]
VMAF score ranges from 0 to 100, with 100 being the best quality.

**Comment by khavishbhundoo** [comment]
At what quality is the perceived quality loss  unnoticeable ?

**Comment by li-zhi** [comment]
It really depends on many things. The default VMAF model assumes a 1080 display and a viewing distance of 3x display height.

**Comment by khavishbhundoo** [comment]
Still you must have a rough idea....like for jpeg you can see that after 95
there is no visual quality gain.

**Comment by li-zhi** [comment]
A rule of thumb I would use is any score >= 90 is deemed good quality. A caveat is on which resolution to compute the scores. See the first question in the FAQ:
https://github.com/Netflix/vmaf/blob/master/FAQ.md
