### ISSUE TITLE
Can I use VMAF to measure the improvement of video quality?

### ISSUE THREAD

**Issue by ExplodedJelly** [Netflix/vmaf#783]
Hi~I am using some SDK to improve the video quality. If I have an origin video A, and improved video B and C from SDK. Can I use B and C as reference video, and A as distorted video? If the A-B's VMAF score is lower than A-C's, does it mean B's quality is better than A?
Thanks.

**Comment by li-zhi** [comment]
Not entirely sure if I understand the problem statement. I guess you meant "If the A-B's VMAF score is lower than A-C's, does it mean B's quality is better than *C*?"

Typically swapping reference and distorted videos would yield unanticipated consequences. Why not stick to using A as the reference, and B/C as the "distorted" (or "processed")?

**Comment by ExplodedJelly** [comment]
Thanks for your reply. The reason why I swapping the reference and distorted video is that I want know how much the B and C improved compare to A. If I use the A as reference and B/C as the distorted, the score will be always 100 (cause the B and C are improved from A).

**Comment by slhck** [comment]
If you're applying artificial enhancements to pristine videos and expect *increased* (subjective) visual quality as output, VMAF is not suitable for this use case. Instead, you should use VMAF to judge how much videos *degrade* by applying typical lossy video compression and/or spatial downscaling, possibly with some visual enhancements like unsharp masking. The reason for this is that the entire model wasn't trained to predict videos that are better than the original.

(NB: I'm not a VMAF developer, just a user.)

**Comment by ExplodedJelly** [comment]
@slhck @li-zhi Thanks a lot! I still want to know what can I do to measure the gain from the SDK, is the new neg mode can measure it?

**Comment by li-zhi** [comment]
I don't think the NEG mode is intended for your use case.

To be on the safe side, the major use case of VMAF is still for compresison and scaling artifacts, not enhancement, although the VMAF formulation preserves properties to capture enhancement.

That being said, I would suggest the following: the reason you see the scores are both at 100.0 is because of the clipping at 100.0 right before the VMAF score is output. using the `disable_clip` flag could disable the clipping. (search "disable_clip" in [this](https://docs.google.com/document/d/1dJczEhXO0MZjBSNyKmd3ARiCTdFVMNPBykH4_HMPoyY/edit#) doc). Let me know what scores you got, and I'll see if the prediction makes sense.

**Comment by HunterAP23** [comment]
If you have three videos: source video A and two distorted videos B and C, your best method of comparing B and C against one another is to test B vs A and C vs A, and compare those results.

The NEG mode is supposed to only used for seeing the effect of compression on the distorted videos compared to the source. It does not include enhancements like the default model does. This doesn't mean that using the NEG model will do what you're looking for.

The general idea is that re-encoding a video will always introduce some generational quality loss - at this moment there is nothing you can do to magically restore that lost quality into the re-encoded video. Applying some post-processing can help mitigate the quality loss, but it will never surpass the source. IF it does surpass the source, then it wouldn't be considered the similar enough to the source to compare anymore - it's just too modified to be comparable.

**Comment by nilfm** [comment]
Closing this issue as part of a clean-up. I believe the question was answered, but feel free to re-open this or a new issue for further questions.
