### ISSUE TITLE
psnr=1 does not work when using libvmaf v2.0.0

### ISSUE THREAD

**Issue by BassThatHertz** [Netflix/vmaf#787]
I made a command-line program, Video Quality Metrics, that uses libvmaf: https://github.com/BassThatHertz/video-quality-metrics

Supplying `psnr=1` used to work in an older version of libvmaf, but since upgrading to libvmaf v2.0.0, that no longer works as I get a `problem loading feature extractor: psnr` error:
```
problem loading feature extractor: psnr[Parsed_libvmaf_2 @ 0000022fb50da0c0] libvmaf encountered an error, check log for details
Error while filtering: Invalid argument
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #1:0
```
Here is the command that my program is trying to run:

`
ffmpeg -loglevel warning -stats -y -r 24000/1001 -i (1.mkv)/Presets comparison at CRF 23\ultrafast.mkv -r 24000/1001 -i (1.mkv)\1-20 (ClipLength-IntervalSeconds).mkv -lavfi [0:v]setpts=PTS-STARTPTS[dist];[1:v]setpts=PTS-STARTPTS[ref];[dist][ref]libvmaf=log_fmt=json:log_path=(1.mkv)/Presets comparison at CRF 23/Raw JSON Data/ultrafast.json:model_path=vmaf_models/vmaf_v0.6.1.json:phone_model=0:psnr=1:ssim=0 -f null -
`

How do you enable PSNR when using libvmaf v2.0.0?

**Comment by luigi311** [comment]
I get the same error message
```bash
ibvmaf INFO `compute_vmaf()` is deprecated and will be removed in a future libvmaf version
libvmaf ERROR problem loading feature extractor: psnr
[Parsed_libvmaf_0 @ 0x5642d2249900] libvmaf encountered an error, check log for details
Error while filtering: Invalid argument
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #1:0
```

**Comment by hassan-c** [comment]
From playing around with things, it seems that libvmaf must be built with the `enable_float` flag set to `true`, i.e.

`meson build --buildtype release -Denable_float=true`

And then the rest of the steps in the [libvmaf README](https://github.com/Netflix/vmaf/blob/master/libvmaf/README.md) can be followed. I do believe this flag should be enabled by default though.

**Comment by BassThatHertz** [comment]
> I get the same error message with
> 
> ```shell
> ffmpeg -hide_banner -r 60 -i output/x264/baseline_crf50/baseline_crf50.mkv -r 60 -i Llamigos.mkv -filter_complex "libvmaf=psnr=1:ssim=1:ms_ssim=1:log_path=test.json:log_fmt=json:n_threads=12" -f null -
> ```
> 
> ```shell
> ibvmaf INFO `compute_vmaf()` is deprecated and will be removed in a future libvmaf version
> libvmaf ERROR problem loading feature extractor: psnr
> [Parsed_libvmaf_0 @ 0x5642d2249900] libvmaf encountered an error, check log for details
> Error while filtering: Invalid argument
> Failed to inject frame into filter network: Invalid argument
> Error while processing the decoded data for stream #1:0
> ```

You have also confirmed `psnr=1` doesn't work after upgrading to libvmaf v2.0.0. I'm a little surprised that @li-zhi or @kylophone, the top contributors to VMAF who have surely seen this issue, haven't commented.

Because of this issue, users of my [Video Quality Metrics](https://github.com/BassThatHertz/video-quality-metrics) command line program can no longer opt to have the PSNR calculated in addition to VMAF.

**Comment by kylophone** [comment]
> You have also confirmed `psnr=1` doesn't work after upgrading to libvmaf v2.0.0. I'm a little surprised that @li-zhi or @kylophone, the top contributors to VMAF who have surely seen this issue, haven't commented.

Hi, sorry must have gotten lost over the holidays. 

> From playing around with things, it seems that libvmaf must be built with the `enable_float` flag set to `true`, i.e.
> 
> `meson build --buildtype release -Denable_float=true`
> 
> And then the rest of the steps in the [libvmaf README](https://github.com/Netflix/vmaf/blob/master/libvmaf/README.md) can be followed. I do believe this flag should be enabled by default though.

This is true, setting this that will make it work. `-Denable_float` is false by default because the floating point versions of the feature extractors are in the processing of being deprecated. So the solution to your problem can be one of the following.

* Compile with `-Denable_float=true`
* We update the `compute_vmaf()` wrapper to use the integer version of PSNR. This is probably the best solution because there is no numerical difference between the two.

https://github.com/Netflix/vmaf/blob/master/libvmaf/src/compute_vmaf.c#L185

**Comment by HunterAP23** [comment]
I was running into this issue as well, but thought something was broken with some recent FFmpeg builds I was using.
I'm curious how enabling SSIM works fine, but not PSNR. That section of code linked above shows that `float_ssim` also has a check similar to `float_psnr` but it doesn't throw an error.

**Comment by hassan-c** [comment]
> I was running into this issue as well, but thought something was broken with some recent FFmpeg builds I was using.
> I'm curious how enabling SSIM works fine, but not PSNR. That section of code linked above shows that `float_ssim` also has a check similar to `float_psnr` but it doesn't throw an error.

https://github.com/Netflix/vmaf/blob/2e1b24d8344c8e8dbb770699ac5beae8b11463d4/libvmaf/src/feature/feature_extractor.c#L46-L64

I believe this snippet of code should explain that. When libvmaf is compiled with the `enable_float` flag, then `VMAF_FLOAT_FEATURES` is 1.

**Comment by HunterAP23** [comment]
So I'm digging around to see if I can find a fix for this issue, and I believe I've found a possible fix aside from compiling with `-Denable_float=true`.

Although I'd like some input if there is anything else people think may need changing - I've already made a fork of this repo and will apply the below changes, but will happily accept any recommendations & suggestions for other changes that would need to be done.

First, we change the lines found here regarding any float values into integer ones (IE: `float_psnr` should become `integer_psnr`). Only issue is that there is no integer version of `float_ms_ssim` but there is one for `float_ssim`.
https://github.com/Netflix/vmaf/blob/2e1b24d8344c8e8dbb770699ac5beae8b11463d4/libvmaf/src/feature/alias.c#L101-L114

https://github.com/Netflix/vmaf/blob/2e1b24d8344c8e8dbb770699ac5beae8b11463d4/libvmaf/src/compute_vmaf.c#L184-L191

https://github.com/Netflix/vmaf/blob/2e1b24d8344c8e8dbb770699ac5beae8b11463d4/python/test/vmafexec_test.py#L34-L44

Second, we would simply remove any mention of `float_psnr` in these files:
https://github.com/Netflix/vmaf/blob/2e1b24d8344c8e8dbb770699ac5beae8b11463d4/python/vmaf/__init__.py#L235-L239

https://github.com/Netflix/vmaf/blob/2e1b24d8344c8e8dbb770699ac5beae8b11463d4/python/vmaf/core/quality_runner.py#L1163-L1181

https://github.com/Netflix/vmaf/blob/2e1b24d8344c8e8dbb770699ac5beae8b11463d4/python/vmaf/core/quality_runner.py#L1225-L1229

https://github.com/Netflix/vmaf/blob/2e1b24d8344c8e8dbb770699ac5beae8b11463d4/python/vmaf/core/feature_extractor.py#L542-L544

https://github.com/Netflix/vmaf/blob/2e1b24d8344c8e8dbb770699ac5beae8b11463d4/python/vmaf/core/feature_extractor.py#L560

**Comment by kylophone** [comment]
@HunterAP23, there is no fork necessary for this. Can you please check if #806 solves your issue?
