### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by juanpef** [Netflix/vmaf#79]
I cannot make the project on Ubuntu (gcc (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4).

I get always the same error:

make[1]: Entering directory `/home/ubuntu/vmaf/ptools'
g++ -pthread -Wall -Wextra -fpic -O -fno-strict-aliasing -DLINUX_ -DOC_NEW_STYLE_INCLUDES -Wno-deprecated -I./opencontainers_1_8_4/include -pthread -D_REENTRANT m2pythontools.o valpython.o midassocket.o valprotocol2.o m2ser.o m2streamdataenc.o m2convertrep.o timeconv.o -shared -o libptools.so
make[1]: Leaving directory `/home/ubuntu/vmaf/ptools'
make[1]: Entering directory `/home/ubuntu/vmaf/feature'
cc  -c -o /home/ubuntu/vmaf/feature/obj/adm_tools.o -std=c99 -g -O3 -fPIC -w -Wextra -pedantic   /home/ubuntu/vmaf/feature/src/adm_tools.c
In file included from /usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:31:0,
                 from /home/ubuntu/vmaf/feature/src/adm_tools.c:32:
/home/ubuntu/vmaf/feature/src/adm_tools.c: In function ârcp_sâ:
/usr/lib/gcc/i686-linux-gnu/4.9/include/xmmintrin.h:902:1: error: inlining failed in call to always_inline â_mm_load_ss.isra.0â: target specific option mismatch
 _mm_load_ss (float const *__P)
 ^
/home/ubuntu/vmaf/feature/src/adm_tools.c:36:16: error: called from here
     float xi = _mm_cvtss_f32(_mm_rcp_ss(_mm_load_ss(&x)));
                ^
In file included from /usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:31:0,
                 from /home/ubuntu/vmaf/feature/src/adm_tools.c:32:
/usr/lib/gcc/i686-linux-gnu/4.9/include/xmmintrin.h:155:1: error: inlining failed in call to always_inline â_mm_rcp_ssâ: target specific option mismatch
 _mm_rcp_ss (__m128 __A)
 ^
/home/ubuntu/vmaf/feature/src/adm_tools.c:36:16: error: called from here
     float xi = _mm_cvtss_f32(_mm_rcp_ss(_mm_load_ss(&x)));
                ^
In file included from /usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:31:0,
                 from /home/ubuntu/vmaf/feature/src/adm_tools.c:32:
/usr/lib/gcc/i686-linux-gnu/4.9/include/xmmintrin.h:964:1: error: inlining failed in call to always_inline â_mm_cvtss_f32â: target specific option mismatch
 _mm_cvtss_f32 (__m128 __A)
 ^
/home/ubuntu/vmaf/feature/src/adm_tools.c:36:11: error: called from here
     float xi = _mm_cvtss_f32(_mm_rcp_ss(_mm_load_ss(&x)));
           ^
make[1]: *** [/home/ubuntu/vmaf/feature/obj/adm_tools.o] Error 1
make[1]: Leaving directory `/home/ubuntu/vmaf/feature'
make[1]: Entering directory `/home/ubuntu/vmaf/libsvm'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/ubuntu/vmaf/libsvm'
make[1]: Entering directory `/home/ubuntu/vmaf/wrapper'
cc -c -o /home/ubuntu/vmaf/wrapper/obj/adm_tools.o -std=c99 -g -O3 -fPIC -w -Wextra -pedantic   /home/ubuntu/vmaf/wrapper/../feature/src/adm_tools.c
In file included from /usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:31:0,
                 from /home/ubuntu/vmaf/wrapper/../feature/src/adm_tools.c:32:
/home/ubuntu/vmaf/wrapper/../feature/src/adm_tools.c: In function ârcp_sâ:
/usr/lib/gcc/i686-linux-gnu/4.9/include/xmmintrin.h:902:1: error: inlining failed in call to always_inline â_mm_load_ss.isra.0â: target specific option mismatch
 _mm_load_ss (float const *__P)
 ^
/home/ubuntu/vmaf/wrapper/../feature/src/adm_tools.c:36:16: error: called from here
     float xi = _mm_cvtss_f32(_mm_rcp_ss(_mm_load_ss(&x)));
                ^
In file included from /usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:31:0,
                 from /home/ubuntu/vmaf/wrapper/../feature/src/adm_tools.c:32:
/usr/lib/gcc/i686-linux-gnu/4.9/include/xmmintrin.h:155:1: error: inlining failed in call to always_inline â_mm_rcp_ssâ: target specific option mismatch
 _mm_rcp_ss (__m128 __A)
 ^
/home/ubuntu/vmaf/wrapper/../feature/src/adm_tools.c:36:16: error: called from here
     float xi = _mm_cvtss_f32(_mm_rcp_ss(_mm_load_ss(&x)));
                ^
In file included from /usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:31:0,
                 from /home/ubuntu/vmaf/wrapper/../feature/src/adm_tools.c:32:
/usr/lib/gcc/i686-linux-gnu/4.9/include/xmmintrin.h:964:1: error: inlining failed in call to always_inline â_mm_cvtss_f32â: target specific option mismatch
 _mm_cvtss_f32 (__m128 __A)
 ^
/home/ubuntu/vmaf/wrapper/../feature/src/adm_tools.c:36:11: error: called from here
     float xi = _mm_cvtss_f32(_mm_rcp_ss(_mm_load_ss(&x)));
           ^
make[1]: *** [/home/ubuntu/vmaf/wrapper/obj/adm_tools.o] Error 1
make[1]: Leaving directory `/home/ubuntu/vmaf/wrapper'
cd libsvm; make lib; cd ..;
make[1]: Entering directory `/home/ubuntu/vmaf/libsvm'
if [ "Linux" = "Darwin" ]; then \
                SHARED_LIB_FLAG="-dynamiclib -Wl,-install_name,libsvm.so.2"; \
        else \
                SHARED_LIB_FLAG="-shared -Wl,-soname,libsvm.so.2"; \
        fi; \
        g++ ${SHARED_LIB_FLAG} svm.o -o libsvm.so.2
make[1]: Leaving directory `/home/ubuntu/vmaf/libsvm'

Thanks

**Comment by li-zhi** [comment]
It seems there are some character conversion issues, for example:
error: inlining failed in call to always_inline â_mm_cvtss_f32â: target
specific option mismatch
_mm_cvtss_f32 (__m128 __A)

**Comment by juanpef** [comment]
Thanks. I found the solution here:

http://stackoverflow.com/questions/43128698/inlining-failed-in-call-to-always-inline-mm-mullo-epi32-target-specific-opti

**Comment by rdp** [comment]
what was the solution?
