### ISSUE TITLE
Exeption import error

### ISSUE THREAD

**Issue by juanpef** [Netflix/vmaf#80]
Hi,
I get an import error when run ./run_vmaf:

Traceback (most recent call last):
  File "./run_vmaf", line 8, in <module>
    from vmaf.config import VmafConfig
ImportError: No module named vmaf.config

What could be the problem?

Thanks

**Comment by juanpef** [comment]
The problem was with the python/src subdirectory to the environment variable PYTHONPATH

**Comment by chuaweijie** [comment]
@juanpef , I'm having the same problem. I've checked the PYTHONPATH variable with echo $PYTHONPATH and it shows the correct path. 

Is it possible for you to elaborate on what is the problem and how did you solve it? Your help is highly appreciated.

**Comment by badpx** [comment]
@chuaweijie , may be you can try the absolute file path.

**Comment by chuaweijie** [comment]
@badpx thanks for the reply. I'm not using this anymore. I'm sure your reply will help others. ^^ 
Cheers.
