### ISSUE TITLE
Ninja build for vmaf compilation in linux

### ISSUE THREAD

**Issue by shrinidhi-venkatakrishnan** [Netflix/vmaf#819]
whrn i try to run this cmd line from inside the vmaf-master folder 
ninja -vC libvmaf/build install
it seems to crash everytime i tried using -j and running with different number of threads as well

Did anyone else face this problem?
When I ran it the final time before the crash it exited with an error that sub-command not found

**Comment by kylophone** [comment]
Could you please copy/paste your terminal output? Might help with the debugging.

**Comment by shrinidhi-venkatakrishnan** [comment]
Hi, thank you for getting back. I upgraded all the packages and it seems to be working fine now
