### ISSUE TITLE
Question regarding temporal features

### ISSUE THREAD

**Issue by arnisgustins** [Netflix/vmaf#820]
If I understand correctly, VMAF takes into consideration features from adjacent frames, right? For example, motion.
This means that it is important to fully preserve all frames and the FPS (speed) of reference video. As this explanation https://github.com/Netflix/vmaf/issues/446#issuecomment-703005622 suggests, even a frame rate change without any changes in content will influence the "motion" feature which will influence final the VMAF score.

Would it be possible to simply ignore any temporal features and just use frame-to-frame comparison similar to SSIM and PSNR?

**More about what I am trying to do.**
I am trying to use VMAF included in FFmpeg to evaluate e2e RTC videos where some content might be lost. Our source video contains markers that allow us to recreate the degraded video with frames form reference video to make them comparable. Because there might be missing parts, fps drops, freezes and other network related issues that will alter the frame order, I am concerned about the VMAF score stability as it will significantly influence such features as motion that I am not particularly interested in.

**Comment by li-zhi** [comment]
This is possible. Actually, there is a hidden option called `motion_force_zero` which does just this. The VMAF model will take `motion` feature value 0 as input.

What does this mean? when motion score is 0 the VMAF model will treat each frame as a still image, ignoring temporal masking. The temporal masking effect of human visual system tends hide coding artifacts from being perceived by human eyes. Disabling temporal masking will result in lower quality score. In other words, your estimated quality is more conservative than reality.

**Comment by arnisgustins** [comment]
Nice, would like to try this option.
Is there a way to enable it through FFmpeg?

**Comment by li-zhi** [comment]
Here is one example:
```
libvmaf/build/tools/vmaf --reference python/test/resource/yuv/src01_hrc00_576x324.yuv --distorted python/test/resource/yuv/src01_hrc01_576x324.yuv --width 576 --height 324 --pixel_format 420 --bitdepth 8 --output /dev/stdout --model name=vmaf:path=model/vmaf_v0.6.1.json:motion.motion_force_zero=true
```
Unfortunately, this has not been supported in FFmpeg yet.

**Comment by cosmin** [comment]
@li-zhi is it possible to create a modified `.json` model file with this option similar to the way the enhancement gain parameters are passed in the NEG model file?

Would adding `motion_force_zero` to the `feature_opts_dicts` in the model file work when passing the model to libvmaf? If I'm looking at this correctly it looks like the options may be sorted by name (for example in `vmaf_0.6.1neg.json` the second dictionary is empty and I'm assuming that's the one that `motion_force_zero` would belong to).

**Comment by kylophone** [comment]
> Would adding `motion_force_zero` to the `feature_opts_dicts` in the model file work when passing the model to libvmaf? If I'm looking at this correctly it looks like the options may be sorted by name (for example in `vmaf_0.6.1neg.json` the second dictionary is empty and I'm assuming that's the one that `motion_force_zero` would belong to).

Yes. See https://github.com/Netflix/vmaf/blob/master/model/vmaf_float_v0.6.1neg.json#L34-L50 for the NEG example. Just add `"motion_force_zero": true` to the appropriate feature_opts_dicts index. The order is implicit, and derived from the order found in the `feature_names` array.

**Comment by arnisgustins** [comment]
Thank you for the replies, got what I wanted 👍
