### ISSUE TITLE
Questions about the models

### ISSUE THREAD

**Issue by RenYang-home** [Netflix/vmaf#821]
When I am using VMAF with FFMpeg and input libvmaf="model_path=./model/vmaf_v0.6.1.json", there occurs an error:

Caught VmafException: Error loading model (.pkl): Unknown token

If changing "vmaf_v0.6.1.json" to "vmaf_float_v0.6.1.pkl", it works. Also in FFMpeg document (https://ffmpeg.org/ffmpeg-filters.html#libvmaf), it says to use pkl. 

But there's no vmaf_v0.6.1.pkl in ./models, is "vmaf_v0.6.1.json" equivalent to "vmaf_float_v0.6.1.pkl"? 

What do "_float", "_b", "_rb", etc, mean? 

Is there any information regarding the meaning of file names and their corresponding suitable scenarios to be used?

Thanks a lot!

**Comment by li-zhi** [comment]
The FFmpeg filters page is not up-to-date. Please use .json moving forward. Thanks.

**Comment by RenYang-home** [comment]
Thanks for the reply. The problem is that using .json leads to an error "Caught VmafException: Error loading model (.pkl): Unknown token", but using .pkl is workable, but there seems a bug when using vmaf_float_v0.6.1.pkl: input two same images but vmaf is not 100 (if using vmaf_4k_v0.6.1.pkl, it is 100). Is this a bug? What FFMpeg version do you use for .json?

Thanks a lot.

**Comment by cosmin** [comment]
> Caught VmafException: Error loading model (.pkl):

This looks like the library may be trying to load a JSON model but parsing it as a `pkl` file (which is a Python pickle serialization format). If you're feeding it JSON then in theory it should load it as such. Can you double check that the `libvmaf` version that ffmpeg is built against is up to date and supports JSON models?

**Comment by li-zhi** [comment]
Sorry for misreading the question the first time. Cosmin's reply should be the right solution. You should use a libvmaf release with version 2.0.0 or later.

**Comment by RenYang-home** [comment]
Thanks for the reply. I solved the problem.
