### ISSUE TITLE
Error when building by ninja

### ISSUE THREAD

**Issue by RenYang-home** [Netflix/vmaf#822]
I got an error when building libvmaf using ninja. The log of error information is at https://data.vision.ee.ethz.ch/reyang/ErrorLog.txt (too long to paste it here). My tools are ninja 1.10.0, gcc 6.3.0, meson 0.56.2, Python 3.8.5, nasm  2.15.05

Could you please take a look and give some help? Thanks a lot for your help.

**Comment by 1480c1** [comment]
seems an error is that it's using `/usr/bin/gcc-6` instead of `/usr/bin/g++-6` for linking, so it doesn't link the c++ library, not sure how to solve that with meson

**Comment by kylophone** [comment]
Do you have a C++ compiler installed? Currently we have a third party dependency `libsvm` which requires C++.

**Comment by RenYang-home** [comment]
> Do you have a C++ compiler installed? Currently we have a third party dependency `libsvm` which requires C++.

Yes, I changed to C++ by 
export CXX=/usr/bin/g++-6
and solved the bug.

Thanks!
