### ISSUE TITLE
Documentation for distorted dataset

### ISSUE THREAD

**Issue by kfeng19** [Netflix/vmaf#824]
Is it possible to add some documentation [here](https://github.com/Netflix/vmaf/blob/master/resource/doc/datasets.md) for the distorted video samples in the NFLX public dataset? E.g. the meaning of each number in the filename _BirdsInCage_85_720_1050.yuv_ and how each distorted video is different.

**Comment by li-zhi** [comment]
Updated with requested information:
https://github.com/Netflix/vmaf/blob/master/resource/doc/datasets.md
