### ISSUE TITLE
vmaf crashes with yuv420p10 akiyo encoded sample from ffmpeg

### ISSUE THREAD

**Issue by richardpl** [Netflix/vmaf#825]
Also it fails to process 8bit akiyo encoded sample as generated by ffmpeg.
Looks like y4m parser is buggy.

**Comment by kylophone** [comment]
Can you send your y4m header? y4ms are parsed with the daala code, so it would be interesting if this was indeed broken.

**Comment by richardpl** [comment]
YUV4MPEG2 W352 H288 F30000:1001 Ip A128:117 C420jpeg XYSCSS=420JPEG XCOLORRANGE=LIMITED

**Comment by 1480c1** [comment]
as a note, adding `-color_range 0` to the ffmpeg command line will "fix" the issue, but the issue stems from https://github.com/Netflix/vmaf/blob/e23732666b24792fee70afbb830b2f1805db30d6/libvmaf/tools/y4m_input.c#L565 as it is the same issue that is mentioned in https://trac.ffmpeg.org/ticket/8958

**Comment by 1480c1** [comment]
The commits that aom has to fix it
https://github.com/m-ab-s/aom/commit/dfcb5ff4dd7df0c3aa65da1d1b6e697c87292481#diff-4a0f487671ec05415220fed2b5c1d6c93f41591861c5cae3d0d4001ff50a5200
https://github.com/m-ab-s/aom/commit/06023aeaff79e6215c69f3b93b9c740f022ee1c4#diff-4a0f487671ec05415220fed2b5c1d6c93f41591861c5cae3d0d4001ff50a5200
https://github.com/m-ab-s/aom/commit/cff8ac586150c23fc10712be601af422c41fa8a7#diff-4a0f487671ec05415220fed2b5c1d6c93f41591861c5cae3d0d4001ff50a5200

**Comment by kylophone** [comment]
> as a note, adding `-color_range 0` to the ffmpeg command line will "fix" the issue, but the issue stems from
> 
> https://github.com/Netflix/vmaf/blob/e23732666b24792fee70afbb830b2f1805db30d6/libvmaf/tools/y4m_input.c#L565
> 
> as it is the same issue that is mentioned in https://trac.ffmpeg.org/ticket/8958

Nice find, thank you. I guess a quick fix from the `vmaf` side is to just use a bigger buffer. This code is from `daala`, so if they haven't already fixed it there, we should send them the patch too.

**Comment by 1480c1** [comment]
I have mentioned it to unlord in #daala, you might want to ask him if he is working on it or not to prevent duplicate efforts

**Comment by kylophone** [comment]
OK, I'll check #daala.
