### ISSUE TITLE
Build vmaf without avx2 support

### ISSUE THREAD

**Issue by gosalak** [Netflix/vmaf#831]
Hi, Can I ask if libvmaf can be built without avx2 support. Despite many changes I tried in meson.build and meson_options.txt, it always ended up using avx2 related functions? Is there a way to compile vmaf without avx2 support. Thanks.

**Comment by kylophone** [comment]
Did you try `-Denable_asm=false`?

**Comment by gosalak** [comment]
It is working fine now. Thanks a lot.
