### ISSUE TITLE
How to get aggregate metrics for ffmpeg with vmaf v2.1.1?

### ISSUE THREAD

**Issue by Frankziyi** [Netflix/vmaf#832]
For version 2.1.1, the ffmpeg should calculate the vmaf with funciton compute_vmaf(). It seems that the function won't give out the aggregate metrics. 
When I calculate the vmaf with subsample on, the vmaf is different with pool metrics vmaf mean value. Is there any solution?

`[libvmaf @ 0x1dec6c0] VMAF score: 93.308420`
`<metric name="vmaf" min="86.553743" max="100.000000" mean="92.119881" harmonic_mean="92.047273" />`

**Comment by li-zhi** [comment]
This one got overlooked and is too old. Close for now. If the problem persists, please re-open the issue.
