### ISSUE TITLE
PSNR

### ISSUE THREAD

**Issue by hailangWu-Aval** [Netflix/vmaf#840]
i using vmaf through ffmpeg to test two mp4 format video in windows, but get different result with ffmpeg depedently, can anybody give some tips

order ffmpeg with vmaf:
 os.system('ffmpeg -i "{}"  -i "{}" -lavfi libvmaf=model_path="{}":log_path="./{}_log.xml":psnr=1:ssim=1 -f null - '.format(video_path1, video_path2, model_path, "s"))

order ffmpeg:
ffmpeg.exe -i  video_path1 -i  video_path2 -lavfi psnr="stats_file=./psnr.log" -f null -

**Comment by richardpl** [comment]
what are  results?

**Comment by gdavila** [comment]
@hailangWu-Aval Please, load a sample of the log files with psnr computations.
