### ISSUE TITLE
Score the same video, execute it multiple times, and get different scores。

### ISSUE THREAD

**Issue by sherry1993** [Netflix/vmaf#841]
When the video is not converted into a yuv file, the score is obtained directly through the VMAF command, and the same score is scored, and the score obtained is different.
When both the original video and the comparison video are converted into yuv files, score the two yuv files and run the VMAF scoring command multiple times to obtain the same score.
1、Run multiple times, the scoring value is different.
`ffmpeg \
    -r 24 -i Seeking_30_480_1050.mp4 \
    -r 24 -i Seeking_10_288_375.mp4 \
    -lavfi "[0:v]setpts=PTS-STARTPTS[reference]; \
            [1:v]scale=720:480:flags=bicubic,setpts=PTS-STARTPTS[distorted]; \
            [distorted][reference]libvmaf=log_fmt=xml:log_path=/dev/stdout:model_path={your_vmaf_dir}/model/vmaf_v0.6.1.pkl" \
    -f null -`
Seeking_30_480_1050.mp4：https://github.com/Netflix/vmaf_resource/blob/master/python/test/resource/mp4/Seeking_30_480_1050.mp4
Seeking_10_288_375.mp4
https://github.com/Netflix/vmaf_resource/blob/master/python/test/resource/mp4/Seeking_10_288_375.mp4
[libvmaf @ 0x7fcfe780d840] VMAF score: 30.421254
[libvmaf @ 0x7feadaf0b640] VMAF score: 11.170481
Record of the process of executing the command：
[1_1.txt](https://github.com/Netflix/vmaf/files/6134428/1_1.txt)
[1_2.txt](https://github.com/Netflix/vmaf/files/6134429/1_2.txt)

2、Run multiple times, the scoring value is same.
`ffmpeg -video_size 576x324 -r 24 -pixel_format yuv420p -i src01_hrc00_576x324.yuv \
    -video_size 576x324 -r 24 -pixel_format yuv420p -i src01_hrc01_576x324.yuv \
    -lavfi "[0:v]setpts=PTS-STARTPTS[reference]; \
            [1:v]setpts=PTS-STARTPTS[distorted]; \
            [distorted][reference]libvmaf=log_fmt=xml:log_path=/dev/stdout:model_path={your_vmaf_dir}/model/vmaf_v0.6.1.json" \
    -f null -`
src01_hrc00_576x324.yuv：
https://github.com/Netflix/vmaf_resource/blob/master/python/test/resource/yuv/src01_hrc00_576x324.yuv
src01_hrc01_576x324.yuv：
https://github.com/Netflix/vmaf_resource/blob/master/python/test/resource/yuv/src01_hrc01_576x324.yuv
[libvmaf @ 0x7f964b605500] VMAF score: 76.684256

**Comment by kylophone** [comment]
This looks like an FFmpeg issue. Can you remove libvmaf and check the differences in
 the resulting decoded and scaled videos?

**Comment by nilfm** [comment]
Closing this issue as it hasn't been updated in two years.
