### ISSUE TITLE
compilation errors for libvmaf/tools and libvmaf/test

### ISSUE THREAD

**Issue by wangwei1237** [Netflix/vmaf#847]
**The compilation error information as following:** 

FAILED: tools/vmafossexec 
c++  -o tools/vmafossexec tools/vmafossexec.p/main.cpp.o tools/vmafossexec.p/read_frame.c.o -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error src/libvmaf.a -lm
ld: warning: ignoring file src/libvmaf.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture x86_64:
  "_compute_vmaf", referenced from:
      _main in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[135/141] c++  -o tools/vmaf tools/vmaf.p/vmaf.c.o tools/vmaf.p/cli_parse.c.o tools/vmaf.p/y4m_input.c.o tools/vmaf.p/vidinput.c.o tools/vmaf.p/yuv_input.c.o -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error src/libvmaf.a -lm
FAILED: tools/vmaf 
c++  -o tools/vmaf tools/vmaf.p/vmaf.c.o tools/vmaf.p/cli_parse.c.o tools/vmaf.p/y4m_input.c.o tools/vmaf.p/vidinput.c.o tools/vmaf.p/yuv_input.c.o -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error src/libvmaf.a -lm
ld: warning: ignoring file src/libvmaf.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture x86_64:
  "_vmaf_close", referenced from:
      _main in vmaf.c.o
  "_vmaf_feature_dictionary_set", referenced from:
      _cli_parse in cli_parse.c.o
      _parse_feature_config in cli_parse.c.o
  "_vmaf_init", referenced from:
      _main in vmaf.c.o
  "_vmaf_model_collection_destroy", referenced from:
      _main in vmaf.c.o
  "_vmaf_model_collection_feature_overload", referenced from:
      _main in vmaf.c.o
  "_vmaf_model_collection_load", referenced from:
      _main in vmaf.c.o
  "_vmaf_model_collection_load_from_path", referenced from:
      _main in vmaf.c.o
  "_vmaf_model_destroy", referenced from:
      _main in vmaf.c.o
  "_vmaf_model_feature_overload", referenced from:
      _main in vmaf.c.o
  "_vmaf_model_load", referenced from:
      _main in vmaf.c.o
  "_vmaf_model_load_from_path", referenced from:
      _main in vmaf.c.o
  "_vmaf_picture_alloc", referenced from:
      _fetch_picture in vmaf.c.o
  "_vmaf_read_pictures", referenced from:
      _main in vmaf.c.o
  "_vmaf_score_pooled", referenced from:
      _main in vmaf.c.o
  "_vmaf_score_pooled_model_collection", referenced from:
      _main in vmaf.c.o
  "_vmaf_use_feature", referenced from:
      _main in vmaf.c.o
  "_vmaf_use_features_from_model", referenced from:
      _main in vmaf.c.o
  "_vmaf_use_features_from_model_collection", referenced from:
      _main in vmaf.c.o
  "_vmaf_version", referenced from:
      _main in vmaf.c.o
      _cli_parse in cli_parse.c.o
  "_vmaf_write_output", referenced from:
      _main in vmaf.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[136/141] c++  -o test/test_context test/test_context.p/test.c.o test/test_context.p/test_context.c.o -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error src/libvmaf.a -lm
FAILED: test/test_context 
c++  -o test/test_context test/test_context.p/test.c.o test/test_context.p/test_context.c.o -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error src/libvmaf.a -lm
ld: warning: ignoring file src/libvmaf.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture x86_64:
  "_vmaf_close", referenced from:
      _run_tests in test_context.c.o
  "_vmaf_feature_score_at_index", referenced from:
      _run_tests in test_context.c.o
  "_vmaf_feature_score_pooled", referenced from:
      _run_tests in test_context.c.o
  "_vmaf_import_feature_score", referenced from:
      _run_tests in test_context.c.o
  "_vmaf_init", referenced from:
      _run_tests in test_context.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[137/141] c++  -o test/test_feature_collector test/test_feature_collector.p/test.c.o test/test_feature_collector.p/test_feature_collector.c.o test/test_feature_collector.p/.._src_log.c.o -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error src/libvmaf.a -lm
FAILED: test/test_feature_collector 
c++  -o test/test_feature_collector test/test_feature_collector.p/test.c.o test/test_feature_collector.p/test_feature_collector.c.o test/test_feature_collector.p/.._src_log.c.o -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error src/libvmaf.a -lm
ld: warning: ignoring file src/libvmaf.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture x86_64:
  "_vmaf_feature_name", referenced from:
      _vmaf_feature_collector_append_templated in test_feature_collector.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[138/141] c++ -Itest/test_model.p -Itest -I../test -Iinclude -I../include -Isrc -I../src -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++11 -O3 -pedantic -DOC_NEW_STYLE_INCLUDES -MD -MQ test/test_model.p/.._src_svm.cpp.o -MF test/test_model.p/.._src_svm.cpp.o.d -o test/test_model.p/.._src_svm.cpp.o -c ../src/svm.cpp
[139/141] c++ -Itest/test_predict.p -Itest -I../test -Iinclude -I../include -Isrc -I../src -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++11 -O3 -pedantic -DOC_NEW_STYLE_INCLUDES -MD -MQ test/test_predict.p/.._src_svm.cpp.o -MF test/test_predict.p/.._src_svm.cpp.o.d -o test/test_predict.p/.._src_svm.cpp.o -c ../src/svm.cpp
ninja: build stopped: subcommand failed.

**I checked the build script, and updated the link_with script as following:**
```
vmaf = executable(
    ...
    link_with : libvmaf,
    ...
)
```
And then, I found that I can successfully compile this library. But I don't know why? Is there some bugs in the build script when link with static library?

**Comment by kylophone** [comment]
What was your `meson` command?

**Comment by wangwei1237** [comment]
> What was your `meson` command?

```
$ meson build --buildtype releas
```

```
$ meson -v
0.55.3
```

**Comment by nilfm99** [comment]
Closing as inactive, please reopen if you are still having this issue.
