### ISSUE TITLE
How can i get niqe brisque metric with vmaf command-line tool?

### ISSUE THREAD

**Issue by ceiliafeng** [Netflix/vmaf#856]
I want get niqe brisque metrics of the video , i see vmaf has the two metrics feature extractor, if i want get the value of niqe and brisque, what can i do ??

**Comment by li-zhi** [comment]
NIQE and BRISQUE are Python implementation. You can follow the example here to run them:
https://github.com/Netflix/vmaf/blob/master/python/test/noref_feature_extractor_test.py#L66
