### ISSUE TITLE
Live/Interlaced sources

### ISSUE THREAD

**Issue by alano17** [Netflix/vmaf#86]
Hi guys,

I've been playing a bit with the software and I have few questions about it.

The first one, reading the your article, you made a comparison for live sources but I don't see exactly the way you can do it, as you need the sources frame aligned and also yuv files. (unless you record the live streams).

The second question is: mostly all the sources (live and VOD) are interlaced, and in the OTT world all the streams are progressive. What is the behavior of vmaf when compares these two files? Are you de-interlacing them previously the comparison?

If all the previous steps have to be done, must it be done by hand or is there an automated way already?

Thanks,

**Comment by li-zhi** [comment]
VMAF hasn't been tested on interlaced source so we don't know for sure. But my hunch is that if you apply it to the fields (reference and distorted pairs for each field) prior to interlacing, it should give you a reasonable estimation.
