### ISSUE TITLE
PSNR error on ffmpeg with libvmaf 2.0

### ISSUE THREAD

**Issue by gdavila** [Netflix/vmaf#862]
It seems the  merge #806 should solve the issue to get psnr values (#787) but as far I can test it wont work. Am I missing something?
Tested on `macOS`, `libvmaf v2.1.1`, `ffmpeg v4.4` installed via homebrew.
```
ffmpeg -y -hide_banner -stats -loglevel verbose -i "bbb_sunflower_8.mp4" -i "bbb_sample_60s.mp4" -map 0:v -map 1:v -lavfi "[0:v][1:v]libvmaf=log_fmt=json:model_path=/usr/local/share/model/vmaf_v0.6.1.json:phone_model=0:n_subsample=1:log_path=bbb_sunflower_8_vmaf.json:n_threads=8:psnr=1" -f null -


...
...

libvmaf ERROR problem loading feature extractor: psnrbitrate=N/A speed=0.271x    
[Parsed_libvmaf_0 @ 0x7fbb70e3f480] libvmaf encountered an error, check log for details
Error while filtering: Invalid argument
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #1:0
[AVIOContext @ 0x7fbb70e05d40] Statistics: 356260 bytes read, 2 seeks
[AVIOContext @ 0x7fbb70e068c0] Statistics: 609338 bytes read, 2 seeks
Conversion failed!
```

**Comment by HunterAP23** [comment]
Can you instead try a nightly version of ffmpeg found [on the official site's download page for Mac systems](https://evermeet.cx/ffmpeg/)? You're going to want to grab the ffmpeg build on the left that has the commit hash in the name of the 7z file.
Then when you call ffmpeg, use the explicit path to wherever you extracted the 7z file and see if the error persists.
