### ISSUE TITLE
How to train a new model on a dataset that has videos of different resolutions?

### ISSUE THREAD

**Issue by SuperCrystal** [Netflix/vmaf#869]
I noted that in the dataset.py the width and height of the videos are defined, but what if the videos are across different resolutions when we want to train a new model? :)

**Comment by li-zhi** [comment]
Usually we train one VMAF model for a particular resolution and a viewing distance assumption. How diverse are your resolutions? Could you train one model per resolution?

**Comment by SuperCrystal** [comment]
Thanks a lot for your reply! The problem is that we have videos of both 720 x 1280 and 1280 x 720 in our dataset, so I'm wondering whether we can train a model across different resolutions.

**Comment by li-zhi** [comment]
This is an interesting case. Ignoring the possible different sensitivity of horizontal and vertical directional filtering (VMAF ignores anyway), the easiest solution is to rotate the vertical video to horizonal.
