### ISSUE TITLE
per-frame motion scores are the same for different distorted videos

### ISSUE THREAD

**Issue by aukejw** [Netflix/vmaf#872]
Hi,

I'm observing that for a given reference video, two different distorted videos have exactly the same per-frame `motion` and `motion2` scores. If I flip the inputs by passing the distorted videos as the `--reference` and the target as `--distorted`, these scores are different.

Are motion scores computed on target videos? This seems surprising to me, hence the question.

VMAF v2.1.1, commit 8ba4a4b8.

Thanks.

**Comment by li-zhi** [comment]
The motion / motion2 are computed on the reference video only, hence your
observation. They serve as an estimate of the amount of temporal
information in the original source.

**Comment by aukejw** [comment]
I misunderstood from the tech blog then, I thought the motion score would be a proxy for temporal consistency of the _distorted_ video. 

Thanks for the quick response.
