### ISSUE TITLE
Can we change back to the original motion-score without adaption to scene changes?

### ISSUE THREAD

**Issue by SuperCrystal** [Netflix/vmaf#876]
Since our videos have already been pre-processed by scene-cut algorithms, and the feature of motion2 seems to give bad results sometimes. Can this be disabled? Thx a lot :)

**Comment by cosmin** [comment]
You should replace `motion2` with motion in the VMAF model which will force the use of the original model without the scene change compensation.

**Comment by li-zhi** [comment]
+1. Direct editing the model file should work.
