### ISSUE TITLE
"motion" feature error when vmaf_neg test

### ISSUE THREAD

**Issue by dark-light24** [Netflix/vmaf#892]
error message(vmaf.log):
libvmaf WARNING feature "VMAF_integer_feature_motion2_score" cannot be overwritten at index 898
libvmaf WARNING problem with feature extractor "motion" at index 899
problem generating pooled VMAF score

command line:
~/vmaf-master20210715/vmaf-master/libvmaf/build/tools/vmaf --reference ~/video/yuv_input/City_1280x720_30.yuv --distorted ./City_test.yuv  --width 1280 --height 720 --pixel_format 420 --bitdepth 8 --model version=vmaf_v0.6.1neg --threads 8 -o out_vmaf.log > vmaf.log 2>&1

It happens by accident when a large number test for vmaf_neg. The probability of occurrence is very very low, and can't reproduce by running the same command line.
Is it a multithreading problem?

**Comment by li-zhi** [comment]
Could be. Without being able to reproducing the issue, it may not be easily fix. Closing for now. Please come back to this thread if you encounter it again.
