### ISSUE TITLE
Statistics VMAF with VMAF on the ffmpeg

### ISSUE THREAD

**Issue by tingfengl** [Netflix/vmaf#895]
when I move vmaf_v0.6.0.pkl and vmaf_v0.6.0.pkl.model to bin directory the same as ffmpeg.exe, but ffmpeg something wrong when I ffmpeg command, error log show: libvmaf encountered an error.  Anyone what happen on this issue ? I will appreciate for your help !

My ffmpeg  command is: ./ffmpeg.exe -s 1280*720 -i filter_0_1280x720.yuv -s 1280*720 -i filter_1_1280x720.yuv -lavfi libvmaf="model_path=vmaf_v0.6.1.pkl:log_path=VMAF.txt" -report -f null -

The error log as below:

fmpeg started on 2021-08-12 at 10:50:23
Report written to "ffmpeg-20210812-105023.log"
Log level: 48
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200726
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rawvideo @ 000002e32ecc0180] Estimating duration from bitrate, this may be inaccurate
Input #0, rawvideo, from 'filter_0_1280x720.yuv':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 276480 kb/s
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720, 276480 kb/s, 25 tbr, 25 tbn, 25 tbc
[rawvideo @ 000002e32ecc2240] Estimating duration from bitrate, this may be inaccurate
Input #1, rawvideo, from 'filter_1_1280x720.yuv':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 276480 kb/s
    Stream #1:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720, 276480 kb/s, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 (rawvideo) -> libvmaf:main
  Stream #1:0 (rawvideo) -> libvmaf:reference
  libvmaf -> Stream #0:0 (wrapped_avframe)
Press [q] to stop, [?] for help
[Parsed_libvmaf_0 @ 000002e32d197a40] libvmaf encountered an error, check log for details
Error while filtering: Invalid argument
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #1:0
Conversion failed!
Input model at vmaf_v0.6.1.pkl cannot be read successfully.
Caught VmafException: Error loading model (.pkl): Trouble reading the file:vmaf_v0.6.1.pkl

**Comment by 1480c1** [comment]
libvmaf only accepts the .json model files

**Comment by tingfengl** [comment]
> libvmaf only accepts the .json model files

Thanks for your reply, I try to add vmaf_v0.6.1.json file to the directory where the ffmpeg.exe file is located, but there still occur the same error log.

**Comment by tingfengl** [comment]
> libvmaf only accepts the .json model files
I understand what you mean now, I use command:
 ./ffmpeg.exe -s 1280*720 -i filter_0_1280x720.yuv -s 1280*720 -i filter_1_1280x720.yuv -lavfi libvmaf="model_path=vmaf_v0.6.1.json:log_path=VMAF.txt" -report -f null -
instead 
 ./ffmpeg.exe -s 1280*720 -i filter_0_1280x720.yuv -s 1280*720 -i filter_1_1280x720.yuv -lavfi libvmaf="model_path=vmaf_v0.6.1.pkl:log_path=VMAF.txt" -report -f null -
I can get a vmaf score now.
