### ISSUE TITLE
Using libvmaf with ffmpeg

### ISSUE THREAD

**Issue by tingfengl** [Netflix/vmaf#896]
When I run ffmpeg command for get VMAF, but there is occur libvmaf ERROR problem loading model file: vmaf_v0.6.0.pkl. How I can fix this issue ?

ffmpeg command: ./ffmpeg.exe -s 1280*720 -i filter_0_1280x720.yuv -s 1280*720 -i filter_1_1280x720.yuv -lavfi libvmaf="model_path="vmaf_v0.6.0.pkl":log_path=VMAF.txt" -report -f null -

command log as below, also I put ffmpeg-20210812-184722.log in here.

$ ./ffmpeg.exe -s 1280*720 -i filter_0_1280x720.yuv -s 1280*720 -i filter_1_1280x720.yuv -lavfi libvmaf="model_path="vmaf_v0.6.0.pkl":log_path=VMAF.txt" -report -f null -
ffmpeg started on 2021-08-12 at 18:47:22
Report written to "ffmpeg-20210812-184722.log"
Log level: 48

[rawvideo @ 000001abee220300] Estimating duration from bitrate, this may be inaccurate
Input #0, rawvideo, from 'filter_0_1280x720.yuv':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 276480 kb/s
  Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720, 276480 kb/s, 25 tbr, 25 tbn
[rawvideo @ 000001abee2227c0] Estimating duration from bitrate, this may be inaccurate
Input #1, rawvideo, from 'filter_1_1280x720.yuv':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 276480 kb/s
  Stream #1:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720, 276480 kb/s, 25 tbr, 25 tbn
Stream mapping:
  Stream #0:0 (rawvideo) -> libvmaf:main
  Stream #1:0 (rawvideo) -> libvmaf:reference
  libvmaf -> Stream #0:0 (wrapped_avframe)
Press [q] to stop, [?] for help
libvmaf INFO `compute_vmaf()` is deprecated and will be removed in a future libvmaf version
libvmaf WARNING could not read model from path: "vmaf_v0.6.0.pkl"
libvmaf WARNING pkl model files have been deprecated, use json
libvmaf ERROR problem loading model file: vmaf_v0.6.0.pkl
[Parsed_libvmaf_0 @ 000001abec8387c0] libvmaf encountered an error, check log for details
Error while filtering: Invalid argument
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data
 for stream #1:0
Conversion failed!

log file:
[ffmpeg-20210812-184722.log](https://github.com/Netflix/vmaf/files/6974884/ffmpeg-20210812-184722.log)

**Comment by 1480c1** [comment]
same issue as https://github.com/Netflix/vmaf/issues/895?

**Comment by tingfengl** [comment]
> same issue as #895?

Yes, but the same error occurred for different operations, I had been fixed this issue. I will close this issue and 895 issue.

**Comment by crystal-16250207** [comment]
How did you solve this problem please？

**Comment by 1480c1** [comment]
> How did you solve this problem please？

which issue? do you have the exact error line?

**Comment by crystal-16250207** [comment]
> > D:\ffmpeg\ffmpeg\bin>ffmpeg -i testdianbo1.h264 -i testdianbo2.h264 -lavfi libvmaf="model_path='D:\ffmpeg\ffmpeg\bin\vmaf_v0.6.1.json'" -f null -
> 
> Your issue seems to be closer to https://github.com/Netflix/vmaf/blob/master/resource/doc/ffmpeg.md#note-about-the-model-path-on-windows than this issue, you could try the method in there to convert your path to one that ffmpeg understands
> 
> > and I would also like to know how to calculate the VMAF value of two pictures in .bmp format？
> 
> This should be the same command, but with the two .bmp images as the sources rather than h264

Thank you very much! The problem has been solved.
