### ISSUE TITLE
Low VMAF

### ISSUE THREAD

**Issue by andini2807** [Netflix/vmaf#899]
https://user-images.githubusercontent.com/47917100/130665888-8bd7bc1f-f8ae-4dbf-a45e-597e6c946668.mp4

Hello, I have an issue trying to get the VMAF score of an 1920x1080 10 seg, 30 fps video.
I used this command for encoding:
`vvencapp -i Football.yuv -s 1920x1080 -c yuv420 -r 30 --preset medium --qp 31 --qpa 0 -ip 64 -t 4 -o Football_vvc_qp31.266`
This one for decoding:
`vvdecapp -b Football_vvc_qp31.266 -o Football_vvc.yuv`
and this one to get the VMAF:
`vmaf -r Football.yuv -d prueba.yuv -w 1920 -h 1080 -p 420 -b 8`
and I get a VMAF of 6 points. Just to check I encoded the Football_vvc.yuv file with h264 and the video had 20 seconds duration and horrible quality. What I am doing wrong? Thank you.

**Comment by RonRicoSuave** [comment]
Where is "prueba.yuv" coming from?   Is that meant to be Football_vvc.yuv?
If not, accidentally used the wrong file for comparison maybe?  :D
