### ISSUE TITLE
why the motion2 and the motion are all using the reference video? what do the values means?

### ISSUE THREAD

**Issue by Hanamaki** [Netflix/vmaf#900]
The score used ref_pic,
`uint64_t sad;
    s->sad(&s->blur[blur_idx_2], &s->blur[blur_idx_0], &sad);
    double score = s->score =
        normalize_and_scale_sad(sad, ref_pic->w[0], ref_pic->h[0]);`

And the score2 also used ref_pic:
`uint64_t sad;
    s->sad(&s->blur[blur_idx_2], &s->blur[blur_idx_0], &sad);
    double score = s->score =
        normalize_and_scale_sad(sad, ref_pic->w[0], ref_pic->h[0]);`

May I get some explanation ,papers or informations? Thank you.

**Comment by li-zhi** [comment]
The rationale behind is that VMAF uses motion2 to assess the motion complexity of the original video, and make adjustment on the VMAF score based on it, to minic the temporal masking effect of human visual system. If the feature is evaluated based on the distorted video, it could be that compression reduces the complexity of the scores.

**Comment by ycho** [comment]
The reason why motion is used is understandable, to measure 'temporal masking effect'. 
Could you also help us understand why it considers two scores then choose smaller score please (unanswered part in original question), are they meant to include the motion score of previous frame as well, I guess? https://github.com/Netflix/vmaf/blob/master/libvmaf/src/feature/float_motion.c#L189. 
Thanks!

**Comment by slhck** [comment]
This is to alleviate issues with artificially high motion values caused by scene cuts.
