### ISSUE TITLE
Distorted results

### ISSUE THREAD

**Issue by imaster0** [Netflix/vmaf#902]
Hi, I measured the VMAF score for the attached video and the result seems weird.

*VMAF v2.1.1*
[Video](https://drive.google.com/file/d/10Zt9M1pDg_9uXuRkXbvy33wgOgZCRR5M/view?usp=sharing)

Used commands:

```
ffmpeg -i video_test.mp4 -c:v libx264 -preset slow -crf 0 -c:a copy video_test_crf_0.mp4
```

```
ffmpeg \
-i video_test.mp4 \
-i video_test_crf_0.mp4 \
-lavfi "[0:v]setpts=PTS-STARTPTS[reference]; \
        [1:v]setpts=PTS-STARTPTS[distorted]; \
[distorted][reference]libvmaf=log_fmt=csv:ssim=1:psnr=1:log_path=crf0_result.csv:model_path=../vmaf-2.1.1/model/vmaf_v0.6.1.json" -f null -
```

Result:
![output](https://user-images.githubusercontent.com/19633921/132169175-aa514a5d-2c6e-4cd7-a8a4-1d0aab954e36.png)

I wonder why the value of 100 on the chart comes out so regularly. Can anyone explain this?

**Comment by li-zhi** [comment]
My hypothesis is that you have every two adjacent frames being identical. Is this true?

**Comment by imaster0** [comment]
@li-zhi Every frame is identical, this appears also when using the same video as reference and distorted.
