### ISSUE TITLE
What's the difference between different modules?

### ISSUE THREAD

**Issue by huangfuxc** [Netflix/vmaf#907]
What's the difference between different modules? 0.6.1 vs 0.6.2 vs 0.6.3  is the newer version has better performance or they are trained using different datasets and applied for different cases?

**Comment by li-zhi** [comment]
There aren't material difference comparing 0.6.2 and 0.6.3 to 0.6.1. 0.6.2 and 0.6.3 were retrained later on the same dataset with the same hyperparameters, but based on the elementary features that have been slightly improved. 0.6.2 and 0.6.3 also comes with a way to compute the prediction confidence interval based on bootstrapping.
