### ISSUE TITLE
VMAF Running Time

### ISSUE THREAD

**Issue by HossamAmer12** [Netflix/vmaf#91]
Hello Everyone,

I am using 'run_vmaf' to compare an original video with a distorted video, yet it is really taking long time in the order of minutes.  Is that normal? Is there something that I am missing?

This is my Python code for the vmaf call:

`  sp.call(
      (path_to_vmaf_tool + ' ' + pix_fmt + ' ' + width + ' ' + ' ' + height +
       ' ' + original_video + ' ' + encoded_video + ' --out-fmt text > ' +
       output_path + 'vmaf.txt'),
      shell=True)`

Thanks!
Hossam

**Comment by li-zhi** [comment]
The run time depends on the video resolution, frame rate and duration. Can
you give more specifics?

**Comment by HossamAmer12** [comment]
My video resolution is 1080p. Let's assume that I am running 10 frames.

**Comment by li-zhi** [comment]
10 frames at 1080p for several minutes doesn't make sense. looks fishy.

**Comment by HossamAmer12** [comment]
Yeah it does not make sense to me too

Any clue?

**Comment by li-zhi** [comment]
Any chance you can share the video and its reference?

**Comment by HossamAmer12** [comment]
Please pick any HD video from this list [https://media.xiph.org/video/derf/], and you will most likely face this problem.

If it is really necessary, I will share my videos. :)

**Comment by HossamAmer12** [comment]
Please note that I have already shared videos with you.

**Comment by li-zhi** [comment]
I tried on
`time ./ffmpeg2vmaf 1920 1080 ~/Downloads/riverbed_1080p25.y4m ~/Downloads/riverbed_1080p25.y4m`

and it gives:
```
...
Frame 249: VMAF_feature_adm2_score:1.000000, VMAF_feature_motion2_score:17.773630, VMAF_feature_vif_scale0_score:1.000000, VMAF_feature_vif_scale1_score:1.000000, VMAF_feature_vif_scale2_score:1.000000, VMAF_feature_vif_scale3_score:1.000000, VMAF_score:100.000000
Aggregate (mean): VMAF_feature_adm2_score:1.000000, VMAF_feature_motion2_score:16.469404, VMAF_feature_vif_scale0_score:1.000000, VMAF_feature_vif_scale1_score:1.000000, VMAF_feature_vif_scale2_score:1.000000, VMAF_feature_vif_scale3_score:1.000000, VMAF_score:99.989712

real	2m17.994s
user	2m6.724s
sys	0m11.647s
```

**Comment by HossamAmer12** [comment]
Why do you use ffmpeg2vmaf? Why don't you use run_vmaf script?

**Comment by li-zhi** [comment]
run_vmaf only takes YUV formats (type ./run_vmaf to get help message), where as y4m is YUV wrapped with header information, and can be decoded by ffmpeg.

**Comment by HossamAmer12** [comment]
Can you please try run_vmaf?

**Comment by li-zhi** [comment]
Do you have a pair of YUV files for me to try?

**Comment by HossamAmer12** [comment]
Any pair of the HD YUVs from the Xiph page can work for this test.

**Comment by li-zhi** [comment]
Can you point me to a specific one to try? Some links seem broken

**Comment by HossamAmer12** [comment]
Please find the link:
https://media.xiph.org/video/derf/y4m/tractor_1080p25.y4m

**Comment by li-zhi** [comment]
@HossamAmer12 Oh that's a .y4m file, which is not YUV. You cannot use run_vmaf command with that file. Only ffmpeg2vmaf will work on that file.

**Comment by HossamAmer12** [comment]
I use the YUV version of this file and the running time is long.

Can you please use the YUV and let me know your running time?

**Comment by HossamAmer12** [comment]
Hi Zhi,

Can you please use the YUV version instead?

Thanks!
Hossam

**Comment by li-zhi** [comment]
@HossamAmer12 I am on vacation until Wednesday. Let me get back to you after I am back.

**Comment by li-zhi** [comment]
@HossamAmer12 I decoded the .y4m file to YUV, and ran using ` time ./run_vmaf yuv420p 1920 1080 ~/Downloads/tractor_1080p25.yuv ~/Downloads/tractor_1080p25.yuv`. 690 frames took about 6 minutes:
```
real	6m6.219s
user	5m39.770s
sys	0m23.817s
```

**Comment by HossamAmer12** [comment]
Ok -- Thank you Zhi! :)

**Comment by zshenker** [comment]
@li-zhi Running on my late 2016 Macbook Pro, with a 1080p source I am seeing similar numbers to your tests above of around `1.7-2.1`fps.

I am looking to run VMAF over a larger library of content, would you have any recommendations on any way to increase the speed of VMAF or if there any way to run in a parallel/distributed way?

**Comment by li-zhi** [comment]
@zshenker If you have multiple videos to process, you can run VMAF in parallel (up to the number of cores). The best way is to create a dataset file (see https://github.com/Netflix/vmaf#create-a-dataset) and use command ./run_testing (see https://github.com/Netflix/vmaf#validate-a-dataset).
