### ISSUE TITLE
is ms-ssim calculated on Y channel or YUV channel?

### ISSUE THREAD

**Issue by leoyu800** [Netflix/vmaf#918]
Since the ms-ssim index only gives an total result , I wonder if ms-ssim only calculated on Y channel or on both YUV channels?

The log is like this:
frame frameNum="0" psnr_y="41.020081" psnr_cb="49.185869" psnr_cr="48.091883" integer_motion2="0.000000" integer_motion="0.000000" float_ssim="0.998963" integer_adm2="0.973663" integer_adm_scale0="0.935512" integer_adm_scale1="0.944083" integer_adm_scale2="0.981678" integer_adm_scale3="0.994638" integer_vif_scale0="0.411728" integer_vif_scale1="0.967495" integer_vif_scale2="0.987014" integer_vif_scale3="0.993444" float_ms_ssim="0.988163" vmaf="95.201686"

**Comment by leoyu800** [comment]
i suppose it's only calculated on Y channel.

**Comment by li-zhi** [comment]
Yes. I confirm MS-SSIM is only calculated on the Y channel.
