### ISSUE TITLE
Use an external thread pool

### ISSUE THREAD

**Issue by foosoftsrlold** [Netflix/vmaf#919]
In a project, we're doing parallel vmaf estimation, i.e. encode at different resolutions / rates, decode, and compute VMAF wrf the original video for small video fragments (say... a fragment transcoder server)

Currently, for each fragment / level we create a libvmaf instance, and this is somewhat unefficient due to the following reasons:

* duplicated computations on reference
* too many thread context switches

Tackling the first point would require an API such as compare (reference, distorted[], count).
The second point (which would become irrelevant should the first point be fixed) could be solved by using a shared long-lived thread pool.
I believe that the minimum effort solution for VMAF is adding a thread pool factory parameter.

Is there a chance the first problem will be solved sooner or later?
And what about the second?

**Comment by foosoftsrl** [comment]
The pull request has been closed... may be next time
