### ISSUE TITLE
How to use this for Windows ?

### ISSUE THREAD

**Issue by phanluchoaofficial20** [Netflix/vmaf#922]

**Comment by halikular** [comment]
If you haven't figured out yet, you can use VMAF natively on Windows with [this guide](https://blog.otterbro.com/how-to-vmaf-ffmpeg/), or through [WSL](https://docs.microsoft.com/en-us/windows/wsl/install) with [this guide](https://ottverse.com/vmaf-ffmpeg-ubuntu-compilation-installation-usage-guide/).

**Comment by phanluchoaofficial20** [comment]
thanks

Vào Th 2, 8 thg 11, 2021 lúc 11:31 Adam Blomberg ***@***.***>
đã viết:

**Comment by li-zhi** [comment]
Useful guides. Thanks.
