### ISSUE TITLE
CLI seems to read Y4M files in the wrong colorspace

### ISSUE THREAD

**Issue by bbasics** [Netflix/vmaf#923]
Y4M is supposed to be in the YCbCr BT.601 format. 
It seems that there is something wrong with the color spaces with the CLI. The result act like it was transferred to RGB using the YUV to RGB conversion somewhere instead of the YCbCr to RGB conversion.
`vmaf -r ref.y4m -d dist.y4m`
In my case, both files are in 4:2:0.

When I use the C API, I feed vmaf with a YUV image and I get a different result. However If I act like the input is in YUV format, which is not, the result is identical to the CLI.

**Comment by li-zhi** [comment]
I think Y4M is simply YUV with header. YUV is simply a pixel format and it does not inform anything about color space (you can put YCbCr, ICtCp, etc... into YUV). In the CLI, there is no fancy conversion to/from RGB. VMAF relies on ffmpeg to do this. Check out this section: https://github.com/Netflix/vmaf/blob/master/resource/doc/ffmpeg.md

**Comment by bbasics** [comment]
Thanks for your answer!
According to https://wiki.multimedia.cx/index.php/YUV4MPEG2 , it specify the Y4M format should be in YCbCr, and based on my experience this online samples it seems to be the case.
As there is nothing to specify the colorspace in the Y4M header, having multiple colorspace would make the y4m format quite unusable except for internal project maybe.
I don't know what's going on inside the vmaf code, and maybe it is related to how ffmpeg work, but it feels like there is a bug somewhere, and in 4:2:0 format it can change the result quite a bit.

Just to put my situation in context, we are trying to develop a new kind of codec using deep learning (kompil.io). We use pytorch for the DL framework. I manage to interface the C API to read directly on pytorch tensors and avoid any usage of the hard disk and speed things by a lot. I wanted to check if my implementation give the same result as the `vmaf` native CLI.

**Comment by li-zhi** [comment]
One thing for sure is that if you invoke the `vmaf` native CLI, no ffmpeg is involved.
