### ISSUE TITLE
How to deal with DMOS score when it higher than 100?

### ISSUE THREAD

**Issue by huangfuxc** [Netflix/vmaf#928]
@li-zhi  I saw in your public dataset, some DMOS score is higher than 100, does it means that the distorted video has better quality than the source video? Maybe for some sequence, it is difficult to find the distortion in encoded streams but it seems strange that the distorted video quality is higher than the original video.

So How do we deal with DMOS scores?  Keep its original data, or treat all more than 100 as 100?

**Comment by huangfuxc** [comment]
A similar question is for the same sequence if the high bitrate or low QP encoded stream has lower DMOS/MOS scores than low bitrate or high QP encoded stream, how to deal with these scores?

**Comment by li-zhi** [comment]
For DMOS, the reference is fixated at 100, and sometimes due to measurement noise, the distorted video can get a score higher than 100. 

How do you intend to use the DMOS and the dataset? as part of training? I think it is fine to train w.r.t. to the dataset. In the final trained model, you could clip the score at 100.

**Comment by huangfuxc** [comment]
> For DMOS, the reference is fixated at 100, and sometimes due to measurement noise, the distorted video can get a score higher than 100.
> 
> How do you intend to use the DMOS and the dataset? as part of training? I think it is fine to train w.r.t. to the dataset. In the final trained model, you could clip the score at 100.

Thanks for your reply. Yes, I want to use this dataset for training. And for another question, is it also noise if one high bitrate stream has a lower subjective score than a low bitrate stream? Both streams are encoded from the same sequence.

**Comment by li-zhi** [comment]
This is also possible. Depending on the question asked and a subject's personal preference, a lower-bitrate encode could be voted as higher quality.
