### ISSUE TITLE
Models installation directory

### ISSUE THREAD

**Issue by dbermond** [Netflix/vmaf#93]
Models are being installed in `$(PREFIX)/share` directory after running `make install`.

This type of files are usually installed in `$(PREFIX)/share/<name>` directory.
Shouldn't it be installed in something else like `$(PREFIX)/share/vmaf` or `$(PREFIX)/share/model`?

https://github.com/Netflix/vmaf/blob/7821b0aa607e8afc74dfb75fc964858e47cd8000/wrapper/Makefile#L152

https://github.com/Netflix/vmaf/blob/7821b0aa607e8afc74dfb75fc964858e47cd8000/wrapper/Makefile#L159

**Comment by li-zhi** [comment]
@ashk43712 @rbultje

**Comment by ashk43712** [comment]
@dbermond , the vmaf/model directory is copied to $(PREFIX)/share/ . So model files reside under $(PREFIX)/share/model/ .

**Comment by dbermond** [comment]
@ashk43712 

Thank you for the reply.

I'm getting models installed in `$(PREFIX)/share` when running `make install`.

But now I could figure out why: creation of the  `$(PREFIX)/share` directory is **missed** from `wrapper/Makefile`.

Other directories (`include` and `lib`) are being previously created with `mkdir` and installation works fine with them. But regarding `share`, the `cp` command is creating a `share` directory with the model contents inside it because it does not exist previously.

Including this in line 150 of `wrapper/Makefile` will fix it:
`mkdir -p $(DESTDIR)$(PREFIX)/share`

**Comment by ashk43712** [comment]
@dbermond, you are right.
Thanks for figuring that out.
@li-zhi can you please include this one line in your next commit.
Thanks

**Comment by dbermond** [comment]
@ashk43712 
Thank you for confirming this.

If you wish I can open a pull request to fix it.

**Comment by li-zhi** [comment]
No problem. Will do.

**Comment by li-zhi** [comment]
Updated.

**Comment by dbermond** [comment]
Fixed by commit d733c3ca35db14d2ca29b79bd095ff60f9368bec.
Thank you for fixing this.

Closing this issue.
