### ISSUE TITLE
How to generate CAMBI heat maps?

### ISSUE THREAD

**Issue by ltrudeau-twoorioles** [Netflix/vmaf#936]
Is it possible to dump the CAMBI confidence data using the VMAF executable as is done in the tech blog?

![image](https://user-images.githubusercontent.com/41166672/141352686-8b085c3f-4213-4df0-8992-978b3bd6704f.png)
 
With this data, heat maps can easily be generated using either Matlab or Matplotlib (_in a Jupyter notebook_).

**Comment by kylophone** [comment]
cc @jsole, @nilfm, @mafonsoN

Do you already have a buffer like this inside the feature extractor? If so, it might be good to add an option to dump the buffer to disk. Maybe use [PGM](http://netpbm.sourceforge.net/doc/pgm.html)?

**Comment by ltrudeau-twoorioles** [comment]
Looks like the data is in the `c_values` buffer see https://github.com/Netflix/vmaf/blob/master/libvmaf/src/feature/cambi.c#L272

**Comment by nilfm** [comment]
I agree it's a good idea to add a flag to dump this to disk. I would think using PFM is better so the rescaling is simpler. From what I've seen, the values in PFM need to be between 0 and 1 so we could divide by the maximum theoretical c_value for a pixel. This value, according to my calculations, can be computed as `max(diff_weights) * window_size^2 / 4`, and for the current default parameters is a bit under 4000.

Interested in what others have to say, it's probably worth trying and then tuning the normalization parameter if it seems too large.

**Comment by kylophone** [comment]
> I agree it's a good idea to add a flag to dump this to disk. I would think using PFM is better so the rescaling is simpler. From what I've seen, the values in PFM need to be between 0 and 1 so we could divide by the maximum theoretical c_value for a pixel. This value, according to my calculations, can be computed as `max(diff_weights) * window_size^2 / 4`, and for the current default parameters is a bit under 4000.
> 
> Interested in what others have to say, it's probably worth trying and then tuning the normalization parameter if it seems too large.

Try it out, hopefully not too much work. As for putting an `fopen` and `fwrite` inside of a feature extractor, it might be worth having all of this behind some `#ifdef`s.

**Comment by nilfm** [comment]
Hi @ltrudeau-twoorioles, the branch [feature/nilfm-cambi-heatmaps](https://github.com/Netflix/vmaf/tree/feature/nilfm-cambi-heatmaps) implements this feature, pending some testing and checking cross-platform compatibility. You can try it and see if it works for your purposes by adding the flag `cambi_heatmaps=some_path` to CAMBI. Some considerations:
* The path `some_path` has to point to an already-existing directory.
* This will generate one `.pfm` file for each frame and scale. We might want to change this to generate a single `.yuv` file per scale, which would be an easy change and allow us to see the temporal variation of bands, but it isn't implemented as of now.
* The `.pfm` images might be vertically flipped depending on which reader you are using. I am not sure why different readers seem to behave differently in this regard.
* Having the `heatmaps_path` flag active slows the program down by about 2x in my experience. If the flag isn't used, by default it doesn't write anything to disk.

Here is (a screenshot of) one of the maps generated by this:

<img width="1673" alt="Screenshot 2021-11-19 at 19 33 39" src="https://user-images.githubusercontent.com/35379309/142673838-0e40db6f-849f-4129-83d5-7ce597f54975.png">

Please let me know if you have any questions/suggestions, and contributions are welcome! :)

**Comment by ltrudeau-twoorioles** [comment]
That's some great work @nilfm, thanks for the branch! Works great for me on MacOS. I opened the `.pfm` with Preview and it wasn't flipped.

![dinner 184 001](https://user-images.githubusercontent.com/41166672/142900873-360681cc-9619-48f1-b1c5-0e9653ebea1c.png)
Scale 0:
![cambi_heatmap_frame_0_scale_0](https://user-images.githubusercontent.com/41166672/142901032-f2834083-9a9e-4ba9-8547-73f578c158de.png)

The hope is that this map would help better understand how different parts of the frame contribute to the overall CAMBI score. For example, banding in dark vs brighter regions or how CAMBI react to film grain.

**Comment by kylophone** [comment]
@nilfm, are you going to make a PR for this?

**Comment by nilfm** [comment]
@kylophone, I made the changes to output a 16-bit YUV400 (grayscale) video for each scale instead of separate frames, and I'll put the PR up now. I think it helps visualize the temporal movement of the bands, and it should be easy to take a single frame from it if necessary. We can discuss futher on the PR, and we can always not push this last commit if we want the old behaviour instead.

**Comment by kylophone** [comment]
Closed, since #947 is now merged.
