### ISSUE TITLE
Lower precision in VIF filtering might make more efficient AVX2 code possible 

### ISSUE THREAD

**Issue by foosoftsrlold** [Netflix/vmaf#946]
After first stage, filtered samples are stored at 16-bit precision.
If they were stored at 15 bit resolution, it would be possible to reduce significantly multiplications, as smoothing filters are symmetric.
If they were stored at 12 bit resolution, and taps were 8 bit (i.e. sum up to 256) most filtering code would fit in 32 bit
I think that the precision loss would be more than acceptable, and VMAF at more than 12 bit is not a reasonable use case in my opinion.
What do you think?

**Comment by li-zhi** [comment]
@foosoftsrl your understanding is mostly correct. In practice video sources come in with 12-bit or less. We use 16-bit mostly for future proof. Do you think there is much to be gained if we use 12-bit? By 12-bit, you mean for the filtered samples only?

**Comment by foosoftsrl** [comment]
Hi li-zhi, 
thanks for your attention.

Using 15 bit for intermediates can be a good saving... the VIF filtering might be...  say 20% faster.
Using 12 bit for intermediates and 8-bit tap will definitely make VIF filtering twice as fast or around that.
But overall gain will be definitely less... especially for 8-bit inputs, for which vertical filtering is not performed with 64 bit accumulators

Even if input comes in at 16 bit, lowering the pixel depth at 12 bits will make no harm. I mean... VMAF is about people, and people do not notice 1/65536 luminance difference :)
I mean... if the residual is such that 1/65536 luminance difference is relevant, we're at 99.99999 VMAF. No one wants to stream that

**Comment by igv** [comment]
Isn't 16bit is used not for precision of luminance but to store variances of 8bit input (max 255^2)?
And for 10/12bit input - 24bit is required. Using 12bit for intermediates means converting anything at input to 6bit. (I don't know how hbd is handled in VMAF though)

**Comment by foosoftsrl** [comment]
Hi all,
thanks Igv for waking me up.

@li-zhi, I was only thinking about vertical filtering, so there's a piece missing, you're right.

Top performance would be, for VIF computation bpp > 8 or >1st stage
- input to vertical filtering 12 bit, so that with 8 bit taps, the accumulator fits in 32 bit for refsq / dissq / refdis
-- right now input to vertical filtering is 16 bit, except for 1st stage > 8 bit
- output of vertical filtering is scaled to fit in 24 bits
-- right now input to horizontal filtering fits in 32 bit 
- horizontal filtering output might be 32 bits, as it is now, but lowering precision might help VIF formula computation in case of conversion to SIMD (did not think much about it)


Hope it makes sense.
Luca

**Comment by igv** [comment]
By "1st stage" you mean processing of fine scale (scale 0)? In that case why would downscaled image have higher bit depth than input?

**Comment by igv** [comment]
Also, it would be more efficient to first create all scales and then process them in parallel.

**Comment by igv** [comment]
This is what I think is the optimal integer VIF implementation:    

- 8bit input converted to 10bit, don't increase precision further (only to store variances)

- eps = 1

- same bit depth of all scale levels    

- optionally decrease sigma_nsq for coarse scales

Pretty straightforward, small accuracy loss, only scores on average are 10-20% higher.

Sample:
```
import sys
from PIL import Image
import numpy as np
from scipy.ndimage import gaussian_filter

def vif(file1, file2):

    img1 = Image.open(file1).convert('RGB')
    img2 = Image.open(file2).convert('RGB')

    width, height = img1.size
    img1 = np.frombuffer(img1.tobytes(), dtype=np.uint8).reshape(height, width, 3)
    img2 = np.frombuffer(img2.tobytes(), dtype=np.uint8).reshape(height, width, 3)

    L1 = ((0.299 * img1[:,:,0] + 0.587 * img1[:,:,1] + 0.114 * img1[:,:,2]) * 4).astype(np.uint16)
    L2 = ((0.299 * img2[:,:,0] + 0.587 * img2[:,:,1] + 0.114 * img2[:,:,2]) * 4).astype(np.uint16)

    bd_mul = 16              # 2**((bit_depth-8)*2)
    sigma_nsq = 2 * bd_mul
    eps = 1

    num = 0.0
    den = 0.0
    for scale in range(1, 5):

        N = 2**(4-scale+1) + 1
        sd, t = N/3.0, 1.4  # kernel radius = round(sd * truncate)

        if scale > 1:
            L1 = gaussian_filter(L1, 1.08, truncate=1.5)[::2, ::2]
            L2 = gaussian_filter(L2, 1.08, truncate=1.5)[::2, ::2]

        mu1 = gaussian_filter(L1, sd, truncate=t)
        mu2 = gaussian_filter(L2, sd, truncate=t)

        mu1_sq = mu1.astype(np.uint32) * mu1.astype(np.uint32)
        mu2_sq = mu2.astype(np.uint32) * mu2.astype(np.uint32)
        mu1_mu2 = mu1.astype(np.uint32) * mu2.astype(np.uint32)
        L1_sq = L1.astype(np.uint32) * L1.astype(np.uint32)
        L2_sq = L2.astype(np.uint32) * L2.astype(np.uint32)
        L1_L2 = L1.astype(np.uint32) * L2.astype(np.uint32)

        sigma1_sq = gaussian_filter(L1_sq, sd, truncate=t) - mu1_sq
        sigma2_sq = gaussian_filter(L2_sq, sd, truncate=t) - mu2_sq
        sigma12 = gaussian_filter(L1_L2, sd, truncate=t) - mu1_mu2

        sigma1_sq[sigma1_sq<eps] = eps
        sigma2_sq[sigma2_sq<eps] = eps
        sigma12[sigma12<eps] = eps

        g = sigma12 / sigma1_sq
        sv_sq = sigma2_sq - g * sigma12

        g[sigma1_sq<sigma_nsq] = 1
        sv_sq[sigma1_sq<sigma_nsq] *= 4./255.**2
        sv_sq[sv_sq<0] = 0

        num += np.sum(np.log2(1 + g * g * sigma1_sq / (sv_sq + sigma_nsq)))
        den += np.sum(np.log2(1 + sigma1_sq / sigma_nsq))

    vifp = num/den

    return vifp

def main():
    for arg in sys.argv[2:]:
        score = vif(sys.argv[1], arg)
        print(str(score) + "\t" + arg)

if __name__ == '__main__':
    main()

```

**Comment by igv** [comment]
Oops, used the wrong type for covariance...

**Comment by igv** [comment]
Looks like 10bit integer version is much better at accounting for banding artifacts because of lower precision.

**Comment by li-zhi** [comment]
@igv we thought about this, but the existing VMAF's incapability of detecting banding is more at the algorithmic level than data representation. We are working on integrating CAMBI (Netflix's banding detector) into VMAF, which should improve its banding sensitivity.
