### ISSUE TITLE
Unexplained frame values with AV1

### ISSUE THREAD

**Issue by wabiloo** [Netflix/vmaf#951]
Hi,

I've been trying to make sense of some results I'm getting when comparing 2 files:
- a reference in H264 (10Mbps 25fps 1920x1080)
- an output (out of a set) generated by encoding the reference with AV1 (1.5 Mbps 25fps 1920x1080).

I'm getting really odd results with a lot of frames showing a VMAF of 0.
I know this usually indicates an issue of frame alignment, however I cannot see that issue when analysing the files

- Both files have the same number of frames
- Both have the same constant frame rate
- Both appear to be in sync (when doing a sync'd playback with `ffplay` or `mpv`) and visually good

The two files are here:
- Reference: https://test-bm-output-2.s3.amazonaws.com/svat_test_cases/AV1-1/MI201109210084_mpeg-4_hd_high_1080p25_10mbits.mp4
- Distorted https://test-bm-output-2.s3.amazonaws.com/svat_test_cases/AV1-1/out-av1_3.mp4

I have tried all sorts of combinations of `-r 25`, `-vsync`, `setpts=PTS-STARTPTS`, `fps=fps=25`, `framerate=25`, but nothing pushed the score beyond VMAF 26.896766 which is abnormally low.

```
ffmpeg -y -hide_banner -loglevel info \
  -r 25 -i "MI201109210084_mpeg-4_hd_high_1080p25_10mbits.mp4" -an \
  -r 25 -i "out-av1_3.mp4" -an \
  -lavfi "[0:v]setpts=PTS-STARTPTS[reference0];[1:v]scale=1920:1080:flags=bicubic,setpts=PTS-STARTPTS[distorted0];[distorted0][reference0]libvmaf=ssim=1:psnr=1:model_path=model/vmaf_v0.6.1.json:phone_model=0:n_subsample=1:log_fmt=json:log_path=out-av1_3.mp4.vmaf.3.json" \
  -f null -
```

A vmaf-per-frame graph shows the issue quite clearly, but I really can't figure out where this issue comes from...
![out-av1_3 mp4 vmaf 3 json](https://user-images.githubusercontent.com/4056263/144243820-1047a212-0fcd-42a6-955d-1b791cea9a07.png)

I would appreciate some feedback on this.

Thanks in advance

**Comment by kylophone** [comment]
As a troubleshooting step, try decoding your reference and distorted to y4m first. My guess is that this is probably some sort of decoding problem.
