### ISSUE TITLE
Does anyone run successfully on windows?

### ISSUE THREAD

**Issue by selina21** [Netflix/vmaf#963]

**Comment by 1480c1** [comment]
I have compiled and ran vmaf.exe and ffmpeg+libvmaf2 with libvmaf1 api and ffmpeg+libvmaf2 with libvmaf2 api, could you elaborate more on if you are experiencing an issue with it?

**Comment by kylophone** [comment]
Also, we have a CI job to make sure Windows builds are not broken.

**Comment by selina21** [comment]
Is the video file available, or is it to find it by myself?

**Comment by selina21** [comment]
![image](https://user-images.githubusercontent.com/57252718/145930394-eac8e2e3-be2c-4a2e-ab06-e1f25a59ef5c.png)
I have some problems when using msys2, after creating the directory

**Comment by 1480c1** [comment]
> Is the video file available, or is it to find it by myself?

Not sure I understand this at all

**Comment by 1480c1** [comment]
> ![image](https://user-images.githubusercontent.com/57252718/145930394-eac8e2e3-be2c-4a2e-ab06-e1f25a59ef5c.png) I have some problems when using msys2, after creating the directory

There is not much context to this, what is the output of the terminal?

**Comment by selina21** [comment]
![0f8df8c420bbc670982fa3875987051](https://user-images.githubusercontent.com/57252718/145947066-119f441e-ca4e-46e9-8401-65ed7f00b53e.png)
I have downloaded meson, but there is a problem

**Comment by 1480c1** [comment]
It doesn't seem like you actually have meson, what did you do to install meson?

**Comment by selina21** [comment]
![image](https://user-images.githubusercontent.com/57252718/145948950-32333489-424f-466d-8826-b69f7ee396e5.png)
This is it

**Comment by selina21** [comment]
![image](https://user-images.githubusercontent.com/57252718/145949571-6b921714-c017-4a2c-a3c7-70e618b384f6.png)
this is it

**Comment by 1480c1** [comment]
That doesn't install meson, you need to run the command in step 2, but since you are using the 32-bit subsystem

```bash
pacman -S --noconfirm --needed $MINGW_PACKAGE_PREFIX-nasm $MINGW_PACKAGE_PREFIX-gcc $MINGW_PACKAGE_PREFIX-meson $MINGW_PACKAGE_PREFIX-ninja
```

**Comment by selina21** [comment]
Ok, i‘ll try now

**Comment by selina21** [comment]
![image](https://user-images.githubusercontent.com/57252718/145952237-d9667006-64d1-4b77-8077-cb079c8b67b0.png)
new question......

**Comment by 1480c1** [comment]
You should not use the msys subsystem, you should use either the mingw64 or mingw32 subsystem

**Comment by selina21** [comment]
![image](https://user-images.githubusercontent.com/57252718/145953854-4cd71c03-265b-4b05-86e5-43b30346f9ed.png)

**Comment by selina21** [comment]
may I have your contact?

**Comment by 1480c1** [comment]
> may I have your contact?

I would prefer not, I get too much spam already, plus I'm not sure if that will help anything.



> ![image](https://user-images.githubusercontent.com/57252718/145953854-4cd71c03-265b-4b05-86e5-43b30346f9ed.png)

Did you properly download vmaf? `/e/A/download/vmaf-master/libvmaf/meson.build` should exist. You can use the zip file at https://github.com/Netflix/vmaf/archive/refs/heads/master.zip and unzip it

**Comment by selina21** [comment]
I have compiled it, but libgcc_s_dw2-1.dll cannot be found when I run it




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Netflix/vmaf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月15日(星期三) 凌晨2:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Netflix/vmaf] Does anyone run successfully on windows? (Issue #963)





  
may I have your contact?
  
I would prefer not, I get too much spam already, plus I'm not sure if that will help anything.
  

  
Did you properly download vmaf? /e/A/download/vmaf-master/libvmaf/meson.build should exist. You can use the zip file at https://github.com/Netflix/vmaf/archive/refs/heads/master.zip and unzip it
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1480c1** [comment]
you might want to either

1. only run it in the same terminal you compiled it in
2. add the `$MINGW_PREFIX/bin` folder to your environment's PATH
3. statically compile vmaf


1 would be the easiest for both you and me, 2 might be feasible if you search online "how to add a folder to my PATH" and get the path by running in the same terminal `cygpath -m "$MINGW_PREFIX/bin"` and use that folder path, 3 would require adding to the LDFLAGS environment variable during meson setup and compilation with `-static-libgcc -static-libstdc++`

**Comment by li-zhi** [comment]
Closing this thread for now... @1480c1 thanks for helping out.

**Comment by godka** [comment]
Just download the standalone version if you only wanna 'run' VMAF rather than compile it.

https://github.com/Netflix/vmaf/releases/download/v2.3.0/vmaf.exe
