### ISSUE TITLE
[Question] Why is the vmaf score calculated by using vmaf.exe directly different from the vmaf score calculated by ffmpeg.exe?

### ISSUE THREAD

**Issue by klob** [Netflix/vmaf#966]
Bellow is my cmd
vmaf
```
vmaf  --width 500 --height 450 --pixel_format 420 -b 8 --r origin.yuv --d noroi.yuv --json --o vmafroiexenew.log --thread 16 --model version=vmaf_v0.6.1:vif.vif_enhn_gain_limit=1.0
```

```
    "vmaf": {
      "min": 29.813728,
      "max": 73.875363,
      "mean": 57.653273,
      "harmonic_mean": 56.604650
    }
```

ffmpeg
```
bin\ffmpeg.exe -s 500x450 -i origin.yuv  -pix_fmt yuv420p -c:v rawvideo -s 500x450 -i noroi.yuv  -pix_fmt yuv420p -c:v rawvideo -lavfi libvmaf="model_path=vmaf/vmaf_v0.6.1.json:log_fmt=json:log_path=vmafroiffmpeg.log:n_threads=16" -report -f null 
```

    "vmaf": {
      "min": 35.760099,
      "max": 82.503418,
      "mean": 68.545269,
      "harmonic_mean": 67.850527
    }

I can provide all the content I use if needed

**Comment by li-zhi** [comment]
Can you try vooya player on the input videos to see what number you get? https://www.offminor.de/

vooya has VMAF calculation built in.

**Comment by klob** [comment]
https://egame-hdr-1251275578.cos.ap-guangzhou.myqcloud.com/vmaf/noroi.mp4

**Comment by klob** [comment]
Can you do that for me? Bellow is the video.
before
https://egame-hdr-1251275578.cos.ap-guangzhou.myqcloud.com/vmaf/origin.mp4
after
https://egame-hdr-1251275578.cos.ap-guangzhou.myqcloud.com/vmaf/noroi.mp4

**Comment by li-zhi** [comment]
@klob I am afraid we won't have time for debugging your specific issue.
