### ISSUE TITLE
vif method

### ISSUE THREAD

**Issue by zuo-chao** [Netflix/vmaf#970]
Now I compared two pictures with vmaf, found the score of vif is low, other scores is ok, I want to know the core code of vif, but cannot find it, could you tell me where is it? Thanks.

**Comment by kylophone** [comment]
> Now I compared two pictures with vmaf, found the score of vif is low, other scores is ok, I want to know the core code of vif, but cannot find it, could you tell me where is it? Thanks.

https://github.com/Netflix/vmaf/blob/master/libvmaf/src/feature/integer_vif.c
