### ISSUE TITLE
 undefined reference to `vmaf_cpu_cpuid

### ISSUE THREAD

**Issue by thompon** [Netflix/vmaf#971]
Hi,

I am trying to build libvmaf for Windows, using msys2.

I get this error several times:

**undefined reference to `vmaf_cpu_cpuid'**

This function is called in _src\x86\cpu.c_ but it does not exist in the code (I have checked in all files).

Could someone fix this? How can you compile the source code with such a missing function?

Thanks in advance.

**Comment by 1480c1** [comment]
The function comes from https://github.com/Netflix/vmaf/blob/e23732666b24792fee70afbb830b2f1805db30d6/libvmaf/src/x86/cpuid.asm#L30

Can you check to make sure you have nasm or yasm installed?

**Comment by thompon** [comment]
Thank you for your reply.

I have both nasm and yasm installed.

But for some reasons, meson does not compile the asm files (I took the last version of the source code: v2.3.0).

**Comment by 1480c1** [comment]
Can you provide all of the steps you have taken to reproduce your issue?

**Comment by 1480c1** [comment]
Perhaps you have your subsystems mixed? the `x86_64-pc-msys` part is implying you are compiling for msys2's MSYS base, you might be looking for the MINGW64 or one of the other *64 build environments

**Comment by thompon** [comment]
Thank you again for your help.

I have done as indicated here: **https://github.com/Netflix/vmaf/blob/master/resource/doc/windows.md**

It means I have done that:

_pacman -S --noconfirm --needed mingw-w64-x86_64-nasm mingw-w64-x86_64-gcc mingw-w64-x86_64-meson mingw-w64-x86_64-ninja_
_meson setup libvmaf libvmaf/build --buildtype release --default-library static --prefix C:/vmaf-install_
_meson install -C libvmaf/build_

In order to avoid compilation errors:
- in vmaf-master\libvmaf\meson.build,I had to replace _'c_std=c11'_ by _'c_std=gnu11'_
- in vmaf-master\libvmaf\src\svm.cpp, I had to implement the function _char* strdup (const char* s)_
- in vmaf-master\libvmaf\src\feature\ciede.c, I had to define _M_PI_

But now I am facing linking errors

**Comment by thompon** [comment]
Thank you VERY MUCH because that was the cause of the problem. I don't know how I have not seen that by myself. Sorry for the inconvenience.

Now compilation works fine.

But I cannot find any _libvmaf.lib_ file (that's the file I am looking for because I want to include it in a C++ program in Visual Studio).

There is a file _libvmaf.a_ in C:\vmaf-install\lib but it's a small file (467 KB) whereas the _libvmaf.lib_ I compiled several months ago from version 1.3.14 had a file size of 15714 KB so I am expecting a bigger file. I have even tried to rename it to _libvmaf.lib_ but Visual Studio says it's an "invalid or damaged" lib file.

Do you have any idea?

**Comment by 1480c1** [comment]
Oh, what you compiled was a static library, but for mingw-w64 toolchains specifically, not one that you can easily import into Visual Studio due to many reasons including incompatible C runtime library (mingw-w64 uses msvcrt while individual Visual Studios get packaged with their own dlls that you have to link against).

I personally have never tried compiling for MSVC as I don't have MSVC installed on any of my machines, but you could try the instructions mentioned in https://mesonbuild.com/Using-with-Visual-Studio.html however, I am not sure if you would have meson available inside your PATH by default, so it's possible even if you open the development console, you wouldn't be able to run `meson`. You could try inside the msvc development command line
```batch
rem or wherever your msys2 is installed to
set "PATH=%PATH%;C:\msys64\mingw64\bin"
cd %VMAF_REPO%
meson setup --backend vs visualstdio
```
and I  think that should get you a visual studio solution project

**Comment by thompon** [comment]
Thanks again for your help.

Unfortunately I have an error.

I type this:

_meson setup libvmaf libvmaf/build --reconfigure --backend vs --buildtype release --default-library static --prefix C:/vmaf-install_

It gives me some warnings:

_Regenerating configuration from scratch: Build directory has been generated with Meson version 0.59.2, which is incompatible with the current version 0.61.0.
The Meson build system
Version: 0.61.0
Source dir: C:\VMAF230\vmaf-master\libvmaf
Build dir: C:\VMAF230\vmaf-master\libvmaf\build
Build type: native build
Project name: libvmaf
Project version: 2.3.0
C compiler for the host machine: cl (msvc 19.29.30136 "Compilateur d'optimisation Microsoft (R) C/C++ version�19.29.30136 pour x86")
C linker for the host machine: link link 14.29.30136.0
C++ compiler for the host machine: cl (msvc 19.29.30136 "Compilateur d'optimisation Microsoft (R) C/C++ version�19.29.30136 pour x86")
C++ linker for the host machine: link link 14.29.30136.0
Auto detected Visual Studio backend: vs2019
Host machine cpu family: x86
Host machine cpu: x86
Check usable header "stdatomic.h" : NO
Configuring version.h using configuration
Program nasm found: YES (C:\Program Files\Meson\nasm.EXE)
WARNING: You should add the boolean check kwarg to the run_command call.
         It currently defaults to false,
         but it will default to true in future releases of meson.
         See also: https://github.com/mesonbuild/meson/issues/9300
Configuring config.asm using configuration
Program xxd found: NO
Configuring config.h using configuration
WARNING: extract_all_objects called without setting recursive
keyword argument. Meson currently defaults to
non-recursive to maintain backward compatibility but
the default will be changed in the future.

Run-time dependency threads found: YES
Library m found: NO
WARNING: extract_all_objects called without setting recursive
keyword argument. Meson currently defaults to
non-recursive to maintain backward compatibility but
the default will be changed in the future.

WARNING: extract_all_objects called without setting recursive
keyword argument. Meson currently defaults to
non-recursive to maintain backward compatibility but
the default will be changed in the future.

Checking for function "strsep" : NO
Program doxygen found: NO
WARNING: extract_all_objects called without setting recursive
keyword argument. Meson currently defaults to
non-recursive to maintain backward compatibility but
the default will be changed in the future.

WARNING: extract_all_objects called without setting recursive
keyword argument. Meson currently defaults to
non-recursive to maintain backward compatibility but
the default will be changed in the future.

WARNING: extract_all_objects called without setting recursive
keyword argument. Meson currently defaults to
non-recursive to maintain backward compatibility but
the default will be changed in the future.

Build targets in project: 21

libvmaf 2.3.0

  User defined options
    backend        : vs
    buildtype      : release
    default_library: static
    prefix         : C:/vmaf-install

WARNING: msvc does not support C++11; attempting best effort; setting the standard to C++14_

So far it's only warnings but when I type:

_vmaf-master>meson install -C libvmaf/build_

I get this error:

_Only ninja backend is supported to rebuild the project before installation.
Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 146, in run
  File "mesonbuild\minstall.py", line 808, in run
  File "mesonbuild\minstall.py", line 586, in do_install
  File "mesonbuild\minstall.py", line 715, in install_targets
RuntimeError: File 'src\\libvmaf.a' could not be found

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!_

**Comment by 1480c1** [comment]
You might need to remove the `libvmaf/build` folder before you run meson since it's going to be conflicting with ninja that you previously used

**Comment by 1480c1** [comment]
I realized, you have your builddir and sourcedir wrong, it should be  `meson libvmaf/build libvmaf` and not the other way around

**Comment by thompon** [comment]
I have tried to swap the 2 arguments:

_meson setup libvmaf libvmaf/build --reconfigure --backend vs --buildtype release --default-library static --prefix C:/vmaf-install_

But it gives the same issue when I run _meson install -C libvmaf/build_ :

_Only ninja backend is supported to rebuild the project before installation.
Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 146, in run
  File "mesonbuild\minstall.py", line 808, in run
  File "mesonbuild\minstall.py", line 586, in do_install
  File "mesonbuild\minstall.py", line 715, in install_targets
RuntimeError: File 'src\\libvmaf.a' could not be found

ERROR: Unhandled python exception

This is a Meson bug and should be reported!_

I have noticed that meson created a solution file (*.sln) for Visual Studio in libvmaf/build. The file is called libvmaf.sln

Unfortunately, when I load in Visual Studio 2019 (I have VS2010, 2015, 2017 and 2019 - I chose 2019 because VS2019 supports c++11).

I think it would be better if I started a new thread about "How to build libvmaf for MS Visual Studio". Do you agree?
