### ISSUE TITLE
FFmpeg and cambi

### ISSUE THREAD

**Issue by DonTequila** [Netflix/vmaf#975]
Hi,

I couldn't find instructions how to use CAMBI in the vmaf filter for FFmpeg. Is this implemented yet?

Thanks!

**Comment by kylophone** [comment]
As soon as this ffmpeg patch is merged, calculating cambi (and other metrics) from the libvmaf avfilter will be supported. ETA sometime this week hopefully. 

http://ffmpeg.org/pipermail/ffmpeg-devel/2022-January/291606.html

**Comment by DonTequila** [comment]
Ah, got it. Thanks and great work!
