### ISSUE TITLE
CAMBI full-ref with ffmpeg

### ISSUE THREAD

**Issue by wabiloo** [Netflix/vmaf#985]
Hi, is there any way (or plan) to specify full-ref when calculating CAMBI scores with ffmpeg?

**Comment by nilfm** [comment]
Hi, this is already possible although the syntax is a bit weird. After following the documentation [here](https://ffmpeg.org/ffmpeg-filters.html#libvmaf), you have to escape a semicolon with a double-backslash to specify command-line options for CAMBI. Here's an example where 3 options are specified, which computes full-ref CAMBI: 

```
ffmpeg -video_size 1920x1080 -r 24 -pixel_format yuv420p -i source_1920x1080_yuv420p.yuv \
    -video_size 1920x1080 -r 24 -pixel_format yuv420p -i source_1920x1080_yuv420p.yuv \
    -lavfi libvmaf='feature=name=cambi\\:full_ref=true\\:enc_width=1920\\:enc_height=1080:log_fmt=json:log_path=/dev/stdout' \
    -f null -
```

I'll try to get that documentation updated with an example similar to this.

**Comment by wabiloo** [comment]
What version of ffmpeg is that?  I've found (as per #986) that I could not use this new type of filter string with `feature=` when using the latest ffmpeg...

**Comment by slhck** [comment]
This is a bit of a weird filter string syntax 😄

I guess it makes sense when breaking it up into the parts that apply to ffmpeg and those that apply to libvmaf's `feature` option.

```bash
libvmaf= # ffmpeg filter name
  feature= # libvmaf filter option "feature"
    name=cambi\\:
    full_ref=true\\:
    enc_width=1920\\:
    enc_height=1080
    # ^---- all of this is one value passed to the "feature" option of the "libvmaf" filter
  log_fmt=json: # libvmaf filter option "log_fmt" set to "json"
  log_path=/dev/stdout # libvmaf filter option "log_path" set to "stdout"
```

**Comment by nilfm** [comment]
@wabiloo I had the same problem that you had using ffmpeg 5.0 (installed via brew). I got this error:
```
[Parsed_libvmaf_0 @ 0x7ffed5c37540] Option 'feature' not found
[AVFilterGraph @ 0x7ffed5c373c0] Error initializing filter 'libvmaf' with args 'feature=name=cambi\:full_ref=true\:enc_width=1920\:enc_height=1080:log_fmt=json:log_path=/dev/stdout'
Error initializing complex filters.
Option not found
```

What I did was clone the FFmpeg [github repo](https://github.com/FFmpeg/FFmpeg/tree/master) and follow the instructions [here](https://github.com/Netflix/vmaf/blob/29d510a8a52a3e1e27f1ac271380ec5cc4c70075/resource/doc/ffmpeg.md) to install it. 

The change that enables the new syntax seems to come from [this commit](https://github.com/FFmpeg/FFmpeg/commit/3d29724c008d8f27fecf85757152789b074e8ef9) dated Jan 23rd, while the [5.0 release](https://github.com/FFmpeg/FFmpeg/releases/tag/n5.0) dates January 14th. I think this may be causing your discrepancy.

**Comment by slhck** [comment]
By the way, you can use https://github.com/homebrew-ffmpeg/homebrew-ffmpeg with the HEAD option to build the latest ffmpeg under macOS without manual compilation steps.

**Comment by wabiloo** [comment]
Thanks @nilfm and @slhck.
In my case I (also) need to build it to run on Ubuntu, so no such easy step there unfortunately...

@slhck I see you're a maintainer of that homebrew tap. If using --HEAD, will that also apply to the libvmaf component (and other libraries)?

**Comment by slhck** [comment]
No, unfortunately it doesn't pass that on. (Or luckily? It might be very unstable.) You would have to manually install the latest version.
Homebrew also works under Linux.

**Comment by kylophone** [comment]
> This is a bit of a weird filter string syntax 😄
> 
> I guess it makes sense when breaking it up into the parts that apply to ffmpeg and those that apply to libvmaf's `feature` option.
> 
> ```shell
> libvmaf= # ffmpeg filter name
>   feature= # libvmaf filter option "feature"
>     name=cambi\\:
>     full_ref=true\\:
>     enc_width=1920\\:
>     enc_height=1080
>     # ^---- all of this is one value passed to the "feature" option of the "libvmaf" filter


Yes, the syntax is a bit ... unfortunate. But it does support multi-model/multi-feature execution with parameter overrides.

**Comment by slhck** [comment]
I think it would help to improve the documentation with regard to the following aspects:

- Explain that the option values for `feature` and `model` actually resemble ffmpeg's own filter syntax, which means that `:` has to be escaped.
- Explain for which version of libvmaf the ffmpeg options work (i.e., which ones are not backwards-compatible), or require libvmaf to be at least 2.x for current ffmpeg.
- Explicitly list which parameters can be passed to the model and feature option, or link to a reference describing those parameters. Right now it only says "a number of parameters". The page that I created [here](https://github.com/Netflix/vmaf/blob/master/resource/doc/metrics.md) could be used for listing the parameters in a central location — having them in each individual page like [here](https://github.com/Netflix/vmaf/blob/master/resource/doc/cambi.md#options) makes it hard to discover IMO.
- In particular, reading the current documentation, it's unclear why the model has a parameter "path" and "version" — are they the same? Does "version" implicitly select a model at a particular preconfigured path?
- Mention the default log format
- Mention the default frame subsampling interval

I can help with this but I'd have to look a bit more into the implementation.

**Comment by wabiloo** [comment]
Among all this could also be clearer guidance on setting `n_threads`, since there was a significant change between vmaf 1.x and 2.x in that regard

**Comment by wabiloo** [comment]
> What I did was clone the FFmpeg [github repo](https://github.com/FFmpeg/FFmpeg/tree/master) and follow the instructions [here](https://github.com/Netflix/vmaf/blob/29d510a8a52a3e1e27f1ac271380ec5cc4c70075/resource/doc/ffmpeg.md) to install it.

I have tried this, but am now getting a new error:
```
libvmaf WARNING no such built-in model: "vmaf_v0.6.1"
[Parsed_libvmaf_3 @ 0x564fee7387c0] could not load libvmaf model with version: vmaf_v0.6.1
```

I get that whether or not I set the `model=` flag in the filter string:

```
ffmpeg -r "24000/1001" -i "/data/reference.mkv" -an -r "24000/1001" -i "/data/distorted.mp4" -an -lavfi '[0:v]setpts=PTS-STARTPTS[reference0];[1:v]scale=1280:720:flags=bicubic,setpts=PTS-STARTPTS[distorted0];[distorted0][reference0]libvmaf=feature=name=psnr:n_subsample=1:n_threads=8:log_fmt=json:log_path=/data/AWOLNATION_muxed_10s_416w-145000_P1.mp4.vmaf.json' -f null -
```

I even compiled libvmaf with `-Dbuilt_in_models=true` to make sure (even though it's the default)

**Comment by li-zhi** [comment]
We’ll need to update the ffmpeg.md page on Netflix/vmaf, besides the
ffmpeg/ffmpeg-filters.html.

**Comment by slhck** [comment]
The features page is now up-to-date.

@wabiloo I have an experimental branch of my ffmpeg wrapper here: https://github.com/slhck/ffmpeg-quality-metrics/tree/vmaf-2.0

It runs fine with a new FFmpeg and libvmaf build, except for the open issue #1075. You can specify all feature names and options you want in a way that's easier to read than a pure ffmpeg CLI call.

For instance:

```bash
python3 \
  -m ffmpeg_quality_metrics \
  test/dist-854x480.mkv \
  test/ref-1280x720.mkv \
  -m vmaf \
  --vmaf-model-params enable_transform=true enable_conf_interval=true \
  --vmaf-features cambi:full_ref=true
```
