### ISSUE TITLE
ffmpeg 5.0 + libvmaf 2.3.0- usage questions and issues

### ISSUE THREAD

**Issue by wabiloo** [Netflix/vmaf#986]
Hi,

I'm trying to migrate my ffmpeg command line to use the built-in models and the new way of stating features (as described in https://ffmpeg.org/ffmpeg-filters.html#libvmaf).

I'm however struggling to find the right expression, and am continuously getting errors:

```
[Parsed_libvmaf_3 @ 0x7ffebe7113c0] Option 'model' not found
[AVFilterGraph @ 0x7ffebe7101c0] Error initializing filter 'libvmaf' with args 'model=version=vmaf_v0.6.1:name=vmaf|version=vmaf_v0.6.1neg:name=vmaf_neg:feature=name=vmaf|name=psnr:phone_model=0:n_subsample=1:log_fmt=json:log_path=output.json'
Error initializing complex filters.
Option not found
```

My command is:
```
ffmpeg -y -hide_banner -loglevel info -r "24000/1001" -i "reference.mkv" -an -r "24000/1001" -i "distorted.mp4" -an -lavfi "[0:v]setpts=PTS-STARTPTS[reference0];[1:v]scale=1280:720:flags=bicubic,setpts=PTS-STARTPTS[distorted0];[distorted0][reference0]libvmaf=model=version=vmaf_v0.6.1\\:name=vmaf|version=vmaf_v0.6.1neg\\:name=vmaf_neg:feature=name=vmaf|name=psnr:phone_model=0:n_subsample=1:log_fmt=json:log_path=output.json" -f null -
```

I'm using the evermeet.cx release on my Mac: https://evermeet.cx/ffmpeg/ffmpeg-5.0.7z

Am I missing something obvious, or is the syntax not quite correct?

**Comment by wabiloo** [comment]
According to evermeet.cx, that release contains vmaf `20220109-e768a2be 2.3.0-72`.
I tried https://evermeet.cx/ffmpeg/ffmpeg-105453-gcc5eb2e662.7z which contains `20220127-df6b6696 2.3.0-94`, and this one seemed to work. That seems like a bit of a major change without a release in between...

**Comment by wabiloo** [comment]
Finally got it...  So for future readers (including myself):

```
ffmpeg -y -hide_banner -loglevel info -r "24000/1001" -i "reference.mkv" -an -r "24000/1001" -i "distorted.mp4" -an -lavfi "[0:v]setpts=PTS-STARTPTS[reference0];[1:v]scale=1280:720:flags=bicubic,setpts=PTS-STARTPTS[distorted0];[distorted0][reference0]libvmaf=model=version=vmaf_v0.6.1\\\\:name=vmaf|version=vmaf_v0.6.1neg\\\\:name=vmaf_neg:feature=name=psnr|name=cambi:enable_transform=false:n_subsample=1:n_threads=8:log_fmt=json:log_path=output.json" -f null -
```

**Comment by wabiloo** [comment]
Is there any clarity as to when this new libvmaf instruction string will make it into a v2.4.0 release?

**Comment by wabiloo** [comment]
@kylophone @li-zhi would you rather that I distil those questions and issues into individual tickets in Github?

**Comment by kylophone** [comment]
> @kylophone @li-zhi would you rather that I distil those questions and issues into individual tickets in Github?

Yes, why don't we make a separate issue and workshop the changes we want to add to the upstream ffmpeg filter documentation. That way it's all fixed, and then we can just send one patch. @slhck had a lot of good suggestions in his comment here: https://github.com/Netflix/vmaf/issues/985#issuecomment-1033509319.

**Comment by wabiloo** [comment]
Opened #987, #988 and #989 to replace this thread, so will now close it.
