### ISSUE TITLE
Phone model in 1.x vs enable_transform in 2.x

### ISSUE THREAD

**Issue by wabiloo** [Netflix/vmaf#987]
With ffmpeg + libvmaf 1.x, there was a `phone_model` parameter.
With ffmpeg + libvmaf 2.x (2.3.0 tested), we now get a warning such as:

`[libvmaf @ 0x7fcffb611b80] The "phone_model" option is deprecated: use model='enable_transform=true'.`

This seems odd, as enable_transform did already exist before.
In addition, the documentation at https://ffmpeg.org/ffmpeg-filters.html#libvmaf seems to show a clash between the 2:

```
enable_transform - Deprecated, use model=’enable_transform=true’.
phone_model - Deprecated, use model=’enable_transform=true’.
```

Tested by compiling latest versions of ffmpeg and libvmaf (in `master` branch for both)

**Comment by PavanNemala** [comment]
Hi,

How can we use phone_model option in ffmpeg command.
