### ISSUE TITLE
ssim and ms_ssim not supported?

### ISSUE THREAD

**Issue by wabiloo** [Netflix/vmaf#988]
When using the latest version of ffmpeg (5.0) and libvmaf (2.3.0), both compiled from the `master` branch in git, I get an error if trying to request features `ssim` and/or `ms_ssim`:

```
ffmpeg -i "/data/reference.mkv" -an -i "/data/distorted.mp4" -an -lavfi '[0:v]setpts=PTS-STARTPTS[reference0];[1:v]setpts=PTS-STARTPTS[distorted0];[distorted0][reference0]libvmaf=model=path=/usr/local/share/model/vmaf_v0.6.1.json\\:name=vmaf:feature=name=psnr|name=ms_ssim:n_subsample=1:n_threads=8:log_fmt=json:log_path=/data/output.json' -f null -
```

returns 
```
[Parsed_libvmaf_3 @ 0x55a24c80f840] problem during vmaf_use_feature: ms_ssim
[AVFilterGraph @ 0x55a24c809a80] Error initializing filter 'libvmaf' with args 'model=path=/usr/local/share/model/vmaf_v0.6.1.json\:name=vmaf:feature=name=psnr|name=ms_ssim:n_subsample=1:n_threads=8:log_fmt=json:log_path=/data/output.json'
```

However the documentation at https://ffmpeg.org/ffmpeg-filters.html#libvmaf seems to indicate it should still be supported

**Comment by kylophone** [comment]
Ah, this is a typo in the ffmpeg filter docs. The feature names should actually be `float_ssim` and `float_ms_ssim`.

**Comment by wabiloo** [comment]
> Ah, this is a typo in the ffmpeg filter docs. The feature names should actually be `float_ssim` and `float_ms_ssim`.

Just checking then... will that feature work even if the VMAF models used are not the old "float" ones?  By which I mean compilation that does NOT use `-Denable_float=true`

**Comment by kylophone** [comment]
> > Ah, this is a typo in the ffmpeg filter docs. The feature names should actually be `float_ssim` and `float_ms_ssim`.
> 
> Just checking then... will that feature work even if the VMAF models used are not the old "float" ones? By which I mean compilation that does NOT use `-Denable_float=true`

Yes, those two metrics are compiled in always. There was talk about integerizing these metrics as well, but it has not happened yet.

**Comment by slhck** [comment]
> Ah, this is a typo in the ffmpeg filter docs. The feature names should actually be `float_ssim` and `float_ms_ssim`.

It seems the ffmpeg docs are not yet updated to reflect this. Would it be possible for you to push a change there?
