### ISSUE TITLE
"could not load libvmaf model" with built-in models

### ISSUE THREAD

**Issue by wabiloo** [Netflix/vmaf#989]
When trying to use built-in models, I get an error.
I've compiled the latest ffmpeg (5.0) and libvmaf (2.3.0) from the git `master` branches.
I'm following the documentation at https://ffmpeg.org/ffmpeg-filters.html#libvmaf to define what model to use.

```ffmpeg -i "/data/reference.mkv" -an -i "/data/distorted.mp4" -an -lavfi '[0:v]setpts=PTS-STARTPTS[reference0];[1:v]setpts=PTS-STARTPTS[distorted0];[distorted0][reference0]libvmaf=model=version=vmaf_v0.6.1\\:name=vmaf:n_subsample=1:n_threads=8:log_fmt=json:log_path=/data/output.json' -f null -```

returns:

```
libvmaf WARNING no such built-in model: "vmaf_v0.6.1"
[Parsed_libvmaf_3 @ 0x564fee7387c0] could not load libvmaf model with version: vmaf_v0.6.1
[AVFilterGraph @ 0x562d23c22180] Error initializing filter 'libvmaf' with args 'model=version=vmaf_v0.6.1\:name=vmaf:n_subsample=1:n_threads=8:log_fmt=json:log_path=/data/output.json'
```
I checked the meson config file, and even forced the flag when compiling:

```
curl -sL https://github.com/Netflix/vmaf/tarball/master -o vmaf.tgz
tar -xz --strip-components=1 -f vmaf.tgz
meson build --buildtype release -Denable_avx512=true -Dbuilt_in_models=true
ninja -vC build
ninja -vC build install
```

Note: Using `libvmaf=model=path=...` with the full path does work

**Comment by wabiloo** [comment]
That was it!  I was missing `xxd`. Thanks for that @1480c1!
Might be worth adding to the pre-requisites/compilation documentation at https://github.com/Netflix/vmaf/tree/master/libvmaf

**Comment by slhck** [comment]
Added a PR that mentions this requirement.

I think it would be good to keep issues like this open until they are addressed in the documentation.
