### ISSUE TITLE
Can't access Netflix Public Dataset

### ISSUE THREAD

**Issue by scribblemaniac** [Netflix/vmaf#993]
I can't access the "Netflix Public Dataset" [linked](https://drive.google.com/folderview?id=0B3YWNICYMBIweGdJbERlUG9zc0k&usp=sharing) in `resource/doc/datasets.md`. Instead am directed to a page that is asking me to request access to the google drive folder. If you could change the access permissions for this to be public or update the link that would be appreciated.

**Comment by li-zhi** [comment]
If you send the access request, I should be able to grant it to you.

**Comment by nilfm** [comment]
Thanks for raising this point, I updated the documentation to explicitly say users should request access to the dataset.

**Comment by scribblemaniac** [comment]
Thanks. Sorry for not following up. I believe the VQEG collection ended up being good enough for my needs. I am however still glad to see the documentation for this updated.
